api/api_test.go, libnetwork_test.go
* TestwriteJSON and TestontainerInvalidLeave were never executed due to the typos. Recent govet found them.
* TestWriteJSON was failing due to the comparison between string and []byte. Also, it didn't considered that json.Encode a
ppends LF.
* TestContainerInvalidLeave was faling due to a typo
=> Fix test failures

agent.go, cluster/provider.go, cmd/dnet/dnet.go, networkdb/cluster.go, networkdb/networkdb.go
If user provided a non-zero listen address, honor that and bind only to
that address. Right now it is not honored and we always bind to all ip
addresses in the host.
This requires an equivalent change in docker.
=> Honor user provided listen address for gossip

drivers/overlay/filter.go
When plumbing overlay filter rules serialize this to make sure that
multiple sandbox join or leave is not causing erroneous behavior while
moving the RETURN rule in the predefined chains.
=> Serialize overlay filter plumbing

networkdb/cluster.go
=> Allow the memberlist shutdown even if networkdb leave fails

networkdb/cluster.go
=> Cherry-picking : Allow the memberlist shutdown even if networkdb leave fails

networkdb/cluster.go, networkdb/delegate.go, networkdb/networkdb.go
Since the node name randomization fix, we need to make sure that we
purge the old node with the same prefix and same IP from the nodes
database if it still present. This causes unnecessary reconnect
attempts.
Also added a change to avoid unnecessary update of local lamport time
and only do it of we are ready to do a push pull on a join. Join should
happen only when the node is bootstrapped or when trying to reconnect
with a failed node.
=> Purge stale nodes with same prefix and IP

networkdb/cluster.go, networkdb/delegate.go, networkdb/networkdb.go
Since the node name randomization fix, we need to make sure that we
purge the old node with the same prefix and same IP from the nodes
database if it still present. This causes unnecessary reconnect
attempts.
Also added a change to avoid unnecessary update of local lamport time
and only do it of we are ready to do a push pull on a join. Join should
happen only when the node is bootstrapped or when trying to reconnect
with a failed node.
=> Cherry-pick: Purge stale nodes with same prefix and IP

agent.go, networkdb/cluster.go
When a gossip join failure happens do not return early in the call chain because a join failure is most likely transient and the retry logic built in the networkdb is going to retry and succeed. Returning early makes the initialization of ingress network/sandbox to not happen which causes a problem even after the gossip join on retry is successful.
=> Avoid returning early on agent join failures

agent.go, networkdb/cluster.go
When a gossip join failure happens do not return early in the call chain
because a join failure is most likely transient and the retry logic
built in the networkdb is going to retry and succeed. Returning early
makes the initialization of ingress network/sandbox to not happen which
causes a problem even after the gossip join on retry is successful.
=> Cherry-picking to v0.8 : Avoid returning early on agent join failures

networkdb/cluster.go, networkdb/delegate.go
Once the bulksync ack channel is closed remove it from the ack table
right away. There is no reason to keep it in the ack table and later
delete it in the ack waiter. Ack waiter anyways has reference to the
channel on which it is waiting.
=> Do not hold ack channel in ack table after closing

networkdb/cluster.go, networkdb/delegate.go
Once the bulksync ack channel is closed remove it from the ack table
right away. There is no reason to keep it in the ack table and later
delete it in the ack waiter. Ack waiter anyways has reference to the
channel on which it is waiting.
=> Cherry Pick: Do not hold ack channel in ack table after closing

network.go
Do not add service discovery names to ingress network as this is a
routing only network and no intra-cluster discovery should happen in
that network. This fixes the ambiguity and resolving names between
services which are both publishing ports and also attached to same
another network.
Related to https://github.com/docker/docker/issues/27147
=> Do not add names to ingress network

controller.go, drivers/remote/api/api.go, drivers/remote/driver.go
Also added an API to return list of builtin network drivers
=> Add support for NetworkAllocate and NetworkFree in remote driver

circle.yml, drivers/bridge/bridge.go
- and update it to store. Otherwise after an ungraceful shutdown,
at next boot there will be in store two bridge endpoints with
same port-mapping data. When bridge driver will try to restore
the endpoints, there will be conflicts and a container with
restart policy could fail to start.
- It can be related to some of the reports in https://github.com/docker/docker/issues/20486 and in https://github.com/docker/docker/issues/25981
- Steps to reproduce:
```
$ # create two networks and run a container on the second one in lexical order
$ docker network create nwa
11d1f4bc8e5e3c06d3025fb2509869fa8f31e0b428a2185e60a649ab5ede552f
$ docker network create nwb
d84ae082627e45ea3254a86b905a20869a9ca8d910be53c046a8f955991454bc
$
$ docker run -d --name w0 --restart always -d -p 8000:8000 -p 9000:9000 …
```
=> Reset endpoint port info on connectivity revoke in bridge driver

networkdb/networkdb.go
There are multiple places which read from that slice(i.e. bulkSync).
=> networkdb: fix race in deleteNetwork

controller.go
=> fix race in serializing sandbox to string

controller.go, libnetwork_internal_test.go, network.go
This PR adds `Created()` to the `NetworkInfo` interface and `created` to the `network` structure for implementation of https://github.com/docker/docker/pull/26130/files
=> add Created to NetworkInfo

service_linux.go
Currently there is an instance of controller and service lock being
obtained in different order which causes the AB/BA deadlock. Do not ever
wrap controller lock around service lock.
=> Avoid controller/service lock AB/BA situation

ns/init_linux.go
- When docker is run inside a container, the infrastructure
needed by modprobe is not always available, causing the
xfrm module load to fail even when these modules are already
loaded or builtin in the kernel.
- In case of probe failure, before declaring the failure,
run an API check by attempting the creation of
a NETLINK_XFRM socket.
Fixes  #1439 
Related to https://github.com/docker/docker/issues/27188
=> Run API check to assert xfrm modules

sandbox.go
=> Fix map access race in populatedEndpoints

cmd/proxy/tcp_proxy.go, cmd/proxy/udp_proxy.go
This simplifies how we build it in docker/docker as no vendoring needed,
and this does program not use any logrus features.
Signed-off-by: Justin Cormack <justin.cormack@docker.com>
=> Do not use logrus for proxy

Vagrantfile
This PR updates the Vagrantfile to use a box available at atlas.hashicorp.com
```
$ vagrant up
Bringing machine 'consul-server' up with 'virtualbox' provider...
Bringing machine 'net-1' up with 'virtualbox' provider...
Bringing machine 'net-2' up with 'virtualbox' provider...
==> consul-server: Checking if box 'ubuntu/trusty64' is up to date...
==> consul-server: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> consul-server: flag to force provisioning. Provisioners marked to run always will still run.
==> net-1: Box 'ubuntu/vivid64' could not be found. Attempting to find and install...
net-1: Box Provider: virtualbox
net-1: Box Version: >= 0
The box 'ubuntu/vivid64' could not be found or
could not be accessed in the remote catalog. If this is a private …
```
=> Updated vagrant box, ubuntu/vivid64 was remove from atlas.hashicorp.com

networkdb/cluster.go, networkdb/delegate.go, networkdb/networkdb.go
Go's time.Now() uses `CLOCK_REALTIME` source. In the networkDB we use `time.Now() and Sub()` to determine the elapsed time to delete the entries. `CLOCK_REALTIME` source can be modified by the user (it can jump forward or backward) or by NTP (though NTP never moves the time back, the time can jump forward at different speed at different intervals till it catches up).
This is problematic because if the time changes significantly it can lead to premature removal of state from networkDB. For delete events this can lead to stale state in the cluster.
We should use a monotonic clock source. Surprisingly Golang doesn't expose the monotonic source in the standard library; https://github.com/golang/go/issues/12914. Hence using a work around which is still platform agnostic.
=> Use monotonic clock source to reap networkDB entries

networkdb/cluster.go, networkdb/event_delegate.go, networkdb/networkdb.go
Remove the failed nodes after a 24 hour interval to avoid unnecessary reconnect attempts.
=> Reap failed nodes after 24 hours

controller.go
NetworkDrivers were still using v1 to Get plugins. Fix that.
Signed-off-by: Anusha Ragunathan <anusha@docker.com>
=> Update loadDriver to use pluginv2.

endpoint.go
There is no guarantees that the ep and extEp are using the same driver.
If they are not using the same drivers, the driver for ep will not know
about the networks of extEp and fails the RevokeExternalConnectivity
call.
Signed-off-by: Shayan Pooya <shayan@liveve.org>
=> Handle containers with different network drivers

drivers/bridge/bridge.go, drivers/ipvlan/ipvlan_network.go, drivers/macvlan/macvlan_network.go, drivers/overlay/ov_network.go
Signed-off-by: Lei Jitang <leijitang@huawei.com>
On driver deleting network, we should also remove the endpoints belong to it if
there are endpoints remain, or else the endpoints in the store would never been removed.
ping @aboch
=> Remove driver endpoints on network deleting

cmd/dnet/dnet.go, drivers/bridge/bridge_test.go, drivers/bridge/interface.go, drivers/bridge/interface_test.go, drivers/bridge/setup_ipv4.go, drivers/bridge/setup_verify.go, netutils/utils_freebsd.go, netutils/utils_linux.go, netutils/utils_solaris.go, netutils/utils_test.go, netutils/utils_windows.go
This fix tries to address the issue raised in:
https://github.com/docker/docker/issues/26341
where multiple addresses in a bridge may cause `--fixed-cidr` to not have the correct addresses.
The issue is that `netutils.ElectInterfaceAddresses(bridgeName)` only returns the first IPv4 address.
This fix changes `ElectInterfaceAddresses()` and `addresses()` so that all IPv4 addresses are returned. This will allow the possibility of selectively choose the address needed.
This fix is related to docker PR:
https://github.com/docker/docker/pull/26659
Signed-off-by: Yong Tang <yong.tang.github@outlook.com>
=> Fix issue for `--fixed-cidr` when bridge has multiple addresses

endpoint.go, osl/interface_linux.go, osl/options_linux.go, osl/sandbox.go, sandbox.go, service_linux.go
Related to [docker #25497](https://github.com/docker/docker/issues/25497)
Being able to ping the service vip is useful for quick debugging. Currently only the vip of the service the task belongs to is programmed as a secondary IP on the interface.
This PR enables ping to vip of all services that are attached to a given network by programming the service's vip as a secondary IP.
Signed-off-by: Santhosh Manohar santhosh@docker.com
=> Enable ping for service vip address

agent.go
- This fixes a panic in memberlist.Leave() because called
after memberlist.shutdown = false
It happens because of two interlocking calls to NetworkDB.clusterLeave()
It is easily reproducible with two back-to-back calls
to docker swarm init && docker swarm leave --force
While the first clusterLeave() is waiting for sendNodeEvent(NodeEventTypeLeave)
to timeout (5 sec) a second clusterLeave() is called. The second clusterLeave()
will end up invoking memberlist.Leave() after the previous call already did
the same, therefore after memberlist.shutdown was set false.
- The fix is to have agentClose() acquire the agent instance and reset the
agent pointer right away under lock. Then execute the closing/leave functions
on the agent instance.
This is exposed by running recent docker-py integration …
=> Allow concurrent calls to agentClose

error.go
1. Modify it's to its.
2. The information of error should be begin with low-case letter and keep the same style in this file.
Signed-off-by: yuexiao-wang wang.yuexiao@zte.com.cn
=> Fix some typos about error

config/config.go, config/config_test.go, controller.go, error.go, network.go
fixes https://github.com/docker/docker/issues/27449
I think currently docker network name validation is not so strict.
This PR tries to make it more strictly like container or volume name validation.
Signed-off-by: allencloud allen.sun@daocloud.io
=> validate network and endpoint name more strictly

drivers/bridge/setup_ip_tables.go
Related to https://github.com/docker/docker/issues/26724
```
$ docker network create --opt com.docker.network.bridge.enable_icc=false --internal nicc
a13d820de6c06810fa2797853faba7793bdf135f097c137fddd9c188b67ba1b3
$ 
$ docker run -d --name c1 --network nicc busybox top
fcbb2b8db5a54f64f99c68856a18a626e9fa00af4f3ce63aa1ff8cb875520d3b
$ docker run -d --name c2 --network nicc busybox top
89307983319a362170fb0922ad92444f7f3572b343699151e805d81beabccc7c
$ docker exec c1 ping -c 2 c2
^C
$ sudo iptables -nvL FORWARD
Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
pkts bytes target     prot opt in     out     source               destination         
2   168 DOCKER-ISOLATION  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
0     0 DOCKER     all  --  *      docker0  0.0.0.0/0 …
```
=> Respect icc option for internal networks

network_windows.go
This fixes docker daemon showing incorrect message on startup:
time="2016-11-01T14:46:22.385577300-07:00" level=error msg="Resolver Setup/Start failed for container none, \"json: cannot unmarshal array into Go value of type hcsshim.HNSNetwork\""
Signed-off-by: msabansal <sabansal@microsoft.com>
=> Fixing incorrect resovler error message shown on daemon startup

endpoint.go, libnetwork_test.go, networkdb/networkdb.go, sandbox.go
This change [was added earlier](https://github.com/docker/libnetwork/pull/1416) but reverted since the docker changes weren't ready.
In this version there are some minor changes to address the comments raised in the docker/docker review, https://github.com/docker/docker/pull/27279
Signed-off-by: Santhosh Manohar santhosh@docker.com
=> Add sandbox API for task insertion to service LB and service discovery

networkdb/cluster.go, networkdb/networkdb.go
remove unused mConfig in network. Here is my reason:
1. it is unused;
2. we can get this config from memberlist.Config
Just a kind of minor change, feel free to tell me if I miss something
=> remove unused mConfig

drivers_windows.go
Without this change, specifying a remote network driver on Windows results in "could not resolve driver X in registry" error. Fixes #1539 
Signed-off-by: Michal Kostrzewa <kostrzewa.michal@o2.pl>
=> Register remote network driver on Windows.

controller.go, networkdb/cluster.go
When I was learning networkdb in libnetwork, I found some nits in code.
When init networkdb, reapDeadNode should be executed periodically every `nodeReapPeriod`, when one loop finishes, reapTime of node should minus `nodeReapPeriod` instead of `reapPeriod`.
What I did:
1. update the reapNode interval;
2. fix a typo
=> update reapNode interval

endpoint.go, libnetwork_linux_test.go, libnetwork_test.go, osl/interface_linux.go, osl/sandbox_linux_test.go, sandbox_test.go
Related to https://github.com/docker/docker/issues/26912
```
$ docker network create -d bridge --subnet 10.10.0.0/16 nw1
223f14676fcc80685cc8f8f409540afe8d492ae4b1246ee11fc2520b1d5c68e9
$ docker network create -d macvlan --subnet 10.10.0.0/16 nw2
2a60cc4e302ec2245ffddbe17914f7c0b59f701deb1b8873e35fe4b93ab52103
$ 
$ docker run -d --name c0 --network nw1 busybox top
4493ebbc8a436407ebe009dbd386376c813e07c583ea8876dcf0a5bf05af1571
$ 
$ docker network connect nw2 c0
Error response from daemon: failed to add interface veth83adfe4 to sandbox: error setting interface "veth83adfe4" IP to 10.10.0.4/16: cannot program address 10.10.0.4/16 in sandbox interface because it conflicts with existing route {Ifindex: 42 Dst: 10.10.0.0/16 Src: 10.10.0.3 Gw: <nil> Flags: [] Table: 254}
$ 
$ docker network …
```
=> Look for overlap when programming sandbox interface

drivers/overlay/ovmanager/ovmanager.go, idm/idm.go
This will allow users to use the full spectrum of vxlan-ids
=> IDM need not be bound by default vxlan-id start index

drivers/bridge/bridge.go, drivers/bridge/setup_ip_forwarding.go, drivers/bridge/setup_ip_forwarding_test.go, iptables/iptables.go
Related to [docker #14041](https://github.com/docker/docker/issues/14041)
If docker daemon enables ip_forwarding on a host set the policy in the FORWARD chain to DROP. This blocks the vulnerability explained in the above mentioned issue. Setting the policy is done from the bridge driver to keep it consistent with the current handling for `ip_forward` flag.
Signed-off-by: Santhosh Manohar santhosh@docker.com
=> when enabling ip forwarding set the default forward policy to drop

sandbox.go
Following panic was reported by one of the docker users..
```
Nov 14 18:43:17 docker-demo9-d dockerd[1732]: panic: runtime error: invalid memory address or nil pointer dereference
Nov 14 18:43:17 docker-demo9-d dockerd[1732]: [signal 0xb code=0x1 addr=0x58 pc=0x8c1b44]
Nov 14 18:43:17 docker-demo9-d dockerd[1732]: goroutine 52749 [running]:
Nov 14 18:43:17 docker-demo9-d dockerd[1732]: panic(0x1a9cb40, 0xc82000a080)
Nov 14 18:43:17 docker-demo9-d dockerd[1732]: /usr/local/go/src/runtime/panic.go:481 +0x3e6
Nov 14 18:43:17 docker-demo9-d dockerd[1732]: github.com/docker/libnetwork.(*sandbox).execFunc(0xc82026c000, 0xc820fae450)
Nov 14 18:43:17 docker-demo9-d dockerd[1732]: /root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/libnetwork/sandbox.go:440 +0x44
Nov 14 18:43:17 …
```
=> Add a nil check before accessing sandbox.osSbox

network.go
This change supports network option `attachable` serialization. It's part of fix for 
https://github.com/docker/docker/issues/27124. 
Signed-off-by: Dong Chen <dongluo.chen@docker.com>
=> Add attachable to network structure

api/api_test.go, ipam/allocator.go, network.go
Related to https://github.com/docker/docker/issues/28055
```
$ docker network create --ipv6 nw6
Error response from daemon: could not find an available, non-overlapping IPv6 address pool among the defaults to auto assign to the network
```
=> Respect auto allocation for --ipv6

config/config.go, config/config_test.go
#1510 introduced some restrictions over the libnetwork resource names.
It was reported the restrictions are too strict, and are breaking Microsoft CI.
Unless we decide to revert back #1510, this PR modifies the constraints to allow spaces in resource names.
=> Allow spaces in network names

agent.go, endpoint.go, networkdb/networkdb.go, sandbox.go
`EnableService` and `DisableService` APIs allow a service to be accessible through Service Discovery and Load Balancer only if the image's healthcheck passes. Currently these APIs control the network plumbing as well. So if the healthcheck of an image tries to connect to other services on the same network it will not work. This PR separates the networking plumbing from the `<Enable|Disable>Service` APIs.
This will also help in the upgrade case where we want to take the service out of availability (ie: no new client connections to the service), but the existing connections should work till a grace period.
=> Separate service LB & SD from network plumbing

endpoint.go, osl/interface_linux.go, osl/options_linux.go, osl/sandbox.go, sandbox.go, service_linux.go
This PR reverts #1501 because it causes docker/docker#28358.
Instead, (thanks to @jpetazzo) we will a ICMP reply NAT rule to the Service VIP which will do exactly what #1501 tried to achieve.
If we agree on this approach, we can close https://github.com/docker/libnetwork/pull/1565.
=> Redo "Enable ping for service vip address"

resolver.go
If a container comes up and brought down quickly its possible for resolver.Stop() to get called before resolver.Start() completes. In that case `r.conn` can be nil
`s := &dns.Server{Handler: r, PacketConn: r.conn}` 
dns library code checks only if PacketConn is nil which is an interface type. Because of the missing check for interface data being nil this results in a panic.
https://github.com/miekg/dns/blob/3f1f7c8ec9ead89493df11f2c3d8bec353a2c2c0/server.go#L388
related to 
[docker #28112](https://github.com/docker/docker/issues/28112)
[docker #28465](https://github.com/docker/docker/issues/28465)
=> Serialize embedded resolver Start and Stop

endpoint_info.go, libnetwork_internal_test.go
Related to https://github.com/docker/docker/issues/28606
=> Fix bug in link-local unmarshalling

drivers/overlay/ovmanager/ovmanager.go
With the introduction of GetIDInRange function in IDM and using it in
ovmanager, the idm.New was modified to start from 1. But that causes
issues when the network is removed which results in releasing the
vxlan-id from IDM. With the offset of 1, the Release call incorrectly
releases a bit which could be in use by another network and this results
in the infamous "error creating vxlan interface: file exists" errors
when another network is created with this freed bit.
=> Create vxlan-id space from 0 instead of starting from 1

agent.go, controller.go, network.go, networkdb/cluster.go, service_common.go, service_linux.go
Related to https://github.com/docker/docker/issues/28697, https://github.com/docker/docker/issues/28845 and https://github.com/docker/docker/issues/28712, 
=> Add missing locks in agent and service code

resolver.go
#1556 Fixes a panic when sandbox.osSbox is nil. But the error message returned is not getting displayed correctly. Fixed it and also changed it to a warning so that such errors won't go unnoticed.
=> Fix incorrect debug message

iptables/iptables.go
- iptables pkg functions are coded to discard the xtables_lock error message about acquiring the lock, because all the calls are done with the wait logic. So they just need to wait. But the error message has  slightly changed between iptables 1.4.x and 1.6:
https://git.netfilter.org/iptables/tree/iptables/xshared.c?h=v1.4.21:
```
fprintf(stderr, "Another app is currently holding the xtables lock; "
"waiting for it to exit...\n");
```
https://git.netfilter.org/iptables/tree/iptables/xshared.c?h=v1.6.0:
```
fprintf(stderr, "Another app is currently holding the xtables lock; "
"waiting (%ds) for it to exit...\n", waited);
```
This lead to false positives causing docker network create to fail in presence of concurrent calls.
Related to https://github.com/docker/docker/issues/26111
To …
=> Fix xtables_lock message probe

ns/init_linux.go
- When docker is run inside a container, the infrastructure
needed by modprobe is not always available, causing the
xfrm module load to fail even when these modules are already
loaded or builtin in the kernel.
- In case of probe failure, before declaring the failure,
run an API check by attempting the creation of
a NETLINK_XFRM socket.
=> Cherry-pick for 1.12.x: Run API check to assert xfrm modules

networkdb/cluster.go
Right now, items logged by memberlist end up as a complete log line
embedded inside another log line, like the following:
Nov 22 16:34:16 hostname dockerd: time="2016-11-22T16:34:16.802103258-08:00" level=info msg="2016/11/22 16:34:16 [INFO] memberlist: Marking xyz-1d1ec2dfa053 as failed, suspect timeout reached\n"
This has two time and date stamps, and an escaped newline inside the
"msg" field of the outer log message.
To fix this, define a custom logger that only prints the message itself.
Capture this message in logWriter, strip off the log level (added
directly by memberlist), and route to the appropriate logrus method.
Relevant issue: https://github.com/docker/docker/issues/28969
=> networkdb: Properly format memberlist logs

networkdb/networkdb.go
Related to [docker #28931](https://github.com/docker/docker/issues/28931)
This happens if swarm nodes running 1.12.3 are upgraded to 1.13.0-rc2 by installing the deb (could happens with rpm as well). I couldn't replicate the issue when replacing the binaries manually and restarting the daemon. 
When the daemon restarts, the gossip cluster-id changes. This issue happens when the old name of the node gets removed from the `nDB.nodes` map but its still present in the per network node list. This change avoids the panic by having a nil check for the node in `nDB.nodes`. I am looking into why the per network list still has the node. 
=> Check for node's presence in networkDB's node map before accessing.

resolvconf/resolvconf.go, resolvconf/resolvconf_test.go
Related to [docker #28172](https://github.com/docker/docker/issues/28172)
IPv6 link local addresses can have a Zone id in the `%number` or `%interface name` format to disambiguate the right interface. Corrected the regexp to filter such addresses.
=> Correct regexp to match v6 addresses with zone ID

drivers/remote/driver.go, ipams/remote/remote.go
With Plugin-V2, plugins can get activated before remote driver is
Initialized. Those plugins fails to get registered with drvRegistry.
This fix handles that scenario.
** Reproduction steps **
1. Install network-plugin and create a network.
```
$ sudo docker plugin install tiborvass/test-docker-netplugin
Plugin "tiborvass/test-docker-netplugin" is requesting the following privileges:
- network: [host]
Do you grant the above permissions? [y/N] y
tiborvass/test-docker-netplugin
$ sudo docker network create -d tiborvass/test-docker-netplugin:latest testnet2
16262841d23a96d287c58b4569d2ba3f6205d29f7eeff5fa658f882a32e89111
```
2. Restart the daemon, make sure the plugin still exists and create another network. Without this PR, the network creation will fail.
```
{{ RESTART DAEMON }}
$ sudo …
```
=> Handle the case of registering active plugins during remote init

controller.go, driverapi/driverapi.go, drivers/bridge/bridge.go, drivers/host/host.go, drivers/ipvlan/ipvlan.go, drivers/macvlan/macvlan.go, drivers/null/null.go, drivers/overlay/overlay.go, drivers/overlay/ovmanager/ovmanager.go, drivers/remote/driver.go, drivers/solaris/bridge/bridge.go, drivers/solaris/overlay/overlay.go, drivers/solaris/overlay/ovmanager/ovmanager.go, drivers/windows/overlay/overlay_windows.go, drivers/windows/windows.go, drvregistry/drvregistry.go, drvregistry/drvregistry_test.go, ipam/allocator.go, ipamapi/contract.go, ipams/null/null.go, ipams/remote/remote.go, ipams/windowsipam/windowsipam.go, libnetwork_internal_test.go
Addresses https://github.com/docker/docker/issues/29473
drvRegistry isnt aware if a plugin is v1 or v2. Plugin-v2 provides a way
for user to disable and remove plugins. But unfortunately, there isnt
any api to advertise the removal to drvRegistry. Hence there is no way
to handle "docker plugin rm" of installed plugin. In order to support
the case of "docker plugin install x" followed by "docker plugin rm x"
followed by reinstalling of plugin "docker plugin install x",
drvRegistry must allow overriding any existing plugin with the same
name. The protection in plugin infra will prevent willful override of
existing plugin.
=> Let drvRegistry to override remote plugin

libnetwork_internal_test.go, network.go, resolver.go, sandbox.go
Related to [docker #22004](https://github.com/docker/docker/issues/22004) 
For service discovery an external DNS based mechanism can be used. Its naming scheme could be different from that of Docker's service discovery provided by embedded DNS server. In such cases A/AAAA queries will be forwarded to the external server if the name can't be resolved by the docker server. But the PTR queries will be responded to by the docker DNS server. This change provides a fix to defer the PTR queries also to external server. Embedded server looks at the A/AAAA record responses;  if the IP is present in docker domain its marked with a flag and is used to defer the PTR queries. Hence for this to work correctly there has to be a forward lookup at least once. Nevertheless, it could be useful for some apps …
=> Defer PTR queries to external servers based on A/AAAA response

network.go
Related to [docker #28836](https://github.com/docker/docker/issues/28836)
`ResolveName` returns a slice of IP addresses from the service DB. Since the callers can modify the slice (currently the resolver shuffles the entries which can be racy in case of concurrent calls) `ResolveName` should return a copy of the IP addresses.
=> ResolveName should return copy of IPs

Godeps/Godeps.json, Godeps/_workspace/src/github.com/docker/docker/pkg/plugingetter/getter.go, drivers/remote/driver.go, ipams/remote/remote.go
For more details : https://github.com/docker/docker/pull/29665 and https://github.com/docker/docker/pull/29556
=> Make use of GetAllManagedPluginsForCap to avoid loading v1-plugins

sandbox_dns_unix.go
This fixes an issue where using a fqdn as hostname
not being added to /etc/hosts.
The etchosts.Build() function was never called
with an IP-address, therefore the fqdn was not
added.
The subsequent updateHostsFile() was not updated
to support fqdn's as hostname, and not adding
the record correctly to /etc/hosts.
This patch copies the functionality to updateHostsFile()
relates to https://github.com/docker/docker/issues/29100
=> Fix fqdn as hostname not being added to /etc/hosts

controller.go, resolvconf/dns/resolvconf.go, resolver.go, sandbox.go, sandbox_dns_unix.go, sandbox_store.go
Currently the loopback address from host's resolv.conf is filtered out. If that was the only nameserver available docker adds Google DNS servers by default for the containers. This is not ideal in many cases 
- google DNS servers are not reachable
- external DNS server to be used has a white list of acceptable clients
- DNSSEC enabled local resolvers
This PR adds support handling the external resolver available at the host loopback address. If the host resolv.conf has other external resolvers after 127.0.0.x, embedded server will continue to try them after first trying to resolve using the host resolver.  The current behavior of using a resolver local to the container using `--dns 127.0.0.x` will also continue to work.
related to 
[docker …
=> Add support in embedded DNS server for host loopback resolver

sandbox.go
- when selecting sandbox's default gw
Fixes #1443 
Fixes #1141 
=> Prioritize nw endpoint which can provide both v4 and v6 connectivity

cmd/proxy/network_proxy_test.go, cmd/proxy/tcp_proxy.go
Related to docker/docker#27539
After `io.Copy(to, from)`, we should call `to.CloseWrite()`, not `to.CloseRead()`.
Without this fix, `TestTCP4ProxyHalfClose` (newly added in this commit) fails as
follows:
```
--- FAIL: TestTCP4ProxyHalfClose (0.00s)
network_proxy_test.go:135: EOF
```
In this test, the client calls `Write()`, `CloseWrite()`, then `Read()`, and the server calls `ReadAll()`, then `Write()`.
Without the fix, the client fails to `Read()` because of `EOF`.
=> proxy: fix an issue about half-closing net.TCPConn after io.Copy()

resolver.go, sandbox_dns_unix.go, sandbox_store.go
#1595 introduced a change to the sandbox state that is persisted in boltdb. This results in container start failing when upgrading from 1.12.x to 1.14-dev. This error is seen on task/container start..
````
ERRO[0283] fatal task error                              error="starting container failed: failed to update the store state of sandbox: failed to update store for object type *libnetwork.sbState: json: cannot unmarshal string into Go value of type libnetwork.extDNSEntry" module="node/agent/taskmanager" task.id=6zenzorwcsjftn5clzdg4vw9e
````
This PR adds the required reconciliation to handle the data model change between the versions. Verified that 1.12.x to 1.14-dev and also 1.14-dev to 1.12 works (downgrade not supported in swarm mode though)
Signed-off-by: Santhosh Manohar …
=> Fix the data model inconsistency that breaks upgrade to 1.14-dev

resolvconf/resolvconf.go
- the function is broken as it does not strip the
zone id from an IPv6 nameserver address, and it
returns the IPv6 address with /32
In presence of zoned ipv6 nameservers in resolv.conf, `CheckNameserverOverlaps()` will fail 
to parse the CIDR and the calling funtion `FindAvailableNetwork()` will assume that all the 
predefined address pools overlaps with some nameserver.
Because of the change in #1590 this issue is now exposed.
Related to docker/docker/issues/30295
=> Fix GetNameServerAsCIDR

service_linux.go
On service create with multiple replicas or on service scale,
multiple concurrent calls to `addLBBackend()` happens, all trying to
create the same service. One succeeds, the other ones get the file exists error,
generating this misleading log:
```
ERRO[0539] Failed to create a new service for vip 10.0.0.2 fwmark 256: file exists 
```
=> Gracefully handle redundant ipvs service create failures

agent.go, controller.go, networkdb/event_delegate.go, networkdb/watch.go
With the introduction of networkdb, the node discovery events were not
sent to the drivers. This commit generates the node discovery events and
sents it to the drivers interested in it.
=> Generating node discovery events to the drivers from networkdb

config/config.go, config/config_test.go, controller.go, error.go, network.go
Reverting the strict network name check until we find a backward compatible way of introducing this change.
Pls refer to the discussion in  https://github.com/docker/docker/issues/29829 for more details.
=> Reverting the strict network name check

ipvs/ipvs.go, ipvs/netlink.go, service_common.go, service_linux.go, service_windows.go
- The virtual and real servers creation can be initiated from different paths, and in case
of a service creation or scale to few tens of tasks, same requests from different code paths are initiated in parallel.
The current logic to decide who has to create the virtual server and when is kind on weak and it does fail when we get into the above scenario.
Because of this, a plethora of `"Failed to create real server ...` error messages floods the logs,
because it happens the real server programming is attempted before the virtual server
was programmed. 
- Also, do not error on redundant service removal and give some context to the logs to help debugging
- The fix is to not relay on software logic, rather query the kernel for the virtual server presence
Fixes #1622
Signed-off-by: Alessandro …
=> Make virtual service programming more robust

datastore/datastore.go, endpoint_info.go, store.go
getNetworksFromStore reads networks and endpoint_cnt from the kvstores.
endpoint_cnt especially is read in a for-loop for each network and that
causes a lot of stress in poorly performing KV-Stores.
This fix eases the load on the kvstore by fetching all the endpoint_cnt
in a single read and the operation is performed on it.
=> replace individual endpoint_cnt read from store with 1 bulk read

drivers/overlay/peerdb.go
Otherwise it can lead to dead lock. 
For example a dead lock on the channel send, if the walking function is `pushLocalEndpointEvent` waiting on the event channel (size 1) to be drained, while the drainer function `serfLoop` is blocked while processing an event which also locks on the `nMap.Lock()` itself.
=> Do not hold the peer map lock during the peerDBNetworkWalk

drivers/overlay/ov_network.go, drivers/overlay/ov_serf.go, osl/neigh_linux.go
When deploying classic swarm with overlay network and using `on-node-failure` reschedule policy randomly some containers might have connectivity issues with other containers in the same network.
To illustrate: One container C1 with three worker nodes W1, W2 and W3.
Container interface's mac is built from the IP address. 
Let say C1 has 10.0.0.2 and mac 02:42:0a:00:00:02. If its initially scheduled on W1 the reachability info will be distributed to other nodes will be 
`<join 10.0.0.2, 02:42:0a:00:00:02, VTEP IP of W1>`
If W1 goes through a failure and the container gets rescheduled to W2  the results events will be
`<leave 10.0.0.2, 02:42:0a:00:00:02, VTEP IP of W1>`
`<join 10.0.0.2, 02:42:0a:00:00:02, VTEP IP of W2>`
At this point if W3's daemon is restarted serf replays all the previous …
=> Ignore previous serf user events to avoid wrong fdb programming

drivers/overlay/encryption.go
- It was not using the advertise IP to construct the SPI
Related to docker/docker/issues/30727
=> Fix bug in datapath key rotation in 1-1 NAT case

drivers/overlay/overlay.go, drivers/overlay/peerdb.go
On a daemon or node restart containers with restart `always` policy can come up before the self discovery event is received by libnetwork. In such cases the peer DB entry would have been updated with `nil` VTEP IP. It has to be corrected when we get the discovery event. Otherwise if a peer restarts and then queries for this IP it will not get the right VTEP.
=> Update the local VTEP in peerdb on receiving self discovery

controller.go, drivers/bridge/setup_ip_tables.go
Related to docker/docker/issues/25393
- The per-host same iptables rule programming done by `ensureJumpRule()` 
is processed for each network create.
Concurrent networks creations sometimes exposes the non-atomicity of the
function causing the network creation to fail.
- I opted for a minimal impact fix which serializes the function executions.
=> Serialize non-atomic jump rule programming in bridge

osl/neigh_linux.go
Aquire the linux network namespace lock before adding neighbors. neighbor deletion code takes the lock correctly.
kernel's watch miss notification and the serf events are handled in two different go routines. So its possible to end up with concurrent AddNeighbor and DeleteNeighbor calls. Racy behavior here can lead to a situation where the fdb entry for the peer has been removed from the kernel but not removed from `networkNamespace.neighbors`. This can result in a permanent loss of connectivity for any container that gets that particular IP address. Such a symptom has been reported by an UCP customer.
=> Lock linux namespace structure when adding neighbors

agent.go
- Currently when a non-named container with network aliases
is connected to a swarm attachable network, its aliases are
not added to the service records.
This is not in line with what we do when connecting to
a local scope network, or to a kv-store based overlay network.
Related to docker/docker/issues/31015, docker/docker/issues/31238
=> Add anonymous container alias to service record on attachable network

drivers/bridge/setup_ip_tables.go, drivers/bridge/setup_ip_tables_test.go, iptables/iptables.go
Rules with ctstate RELATED,ESTABLISHED must be create before same rules without ctstate.
See https://github.com/docker/docker/issues/18911
=> Fix bad order of iptables filter rules

iptables/iptables.go
I saw a rare race condition during the first few calls to iptables module
where some of them would reenter initCheck() after the first call
to it already changed iptablesPath, but before the rest of the function
completed (in particular the long execs into testing for availability
of --wait flag and determining iptables version), resulting in
failure of one or more of iptables calls that did not use --wait and
were concurrent.
To fix the problem, this change gathers all one-time initialization into a
single function under a sync.Once instead of using a global variable
as a "done initializing" flag before initialization is done. sync.Once
guarantees all concurrent calls will block until the first one completes.
In addition, it turns out that GetVersion(), called from initCheck(), used …
=> Ensure iptables initialization only happens once

agent.go, driverapi/driverapi.go, drivers/bridge/bridge.go, drivers/host/host.go, drivers/ipvlan/ipvlan.go, drivers/macvlan/macvlan.go, drivers/null/null.go, drivers/overlay/joinleave.go, drivers/overlay/ov_network.go, drivers/overlay/ovmanager/ovmanager.go, drivers/remote/driver.go, drivers/solaris/bridge/bridge.go, drivers/solaris/overlay/joinleave.go, drivers/solaris/overlay/ov_network.go, drivers/solaris/overlay/ovmanager/ovmanager.go, drivers/windows/overlay/joinleave_windows.go, drivers/windows/overlay/ov_network_windows.go, drivers/windows/windows.go, drvregistry/drvregistry_test.go, libnetwork_internal_test.go, network.go, networkdb/networkdb.go, service_common.go
In swarm mode `network inspect` shows only the information about the endpoints local to the node. This is because the earlier libnetwork design for overlay relied on the KV store which is not available in the swarm mode. Lack of the cluster-wide visibility makes it difficult to verify if all nodes have a consistent state for the services.
This PR adds the support in libnetwork to add a UX option: `docker network inspect --verbose nw` which will display all the services in a network with the backend task IP and the host in which the task resides. This is a first step towards better debugging/diagnostics support for swarm mode services. It will used to provide a troubleshooting container that can fetch this `control plane` state and probe the kernel state to verify if they match.
For …
=> swarm mode network inspect should provide cluser-wide task details

drivers/overlay/encryption.go
- Cleanup security states and policies when joining the swarm
- Properly construct CIDR in policy selector, current code programs src/dst cidr like 192.168.100.126/128
Related to docker/docker/issues/30727
Signed-off-by: Alessandro Boch aboch@docker.com
=> Few changes in encryption overlay

drivers/bridge/bridge.go, drivers/bridge/bridge_store.go, netlabel/labels.go, osl/interface_linux.go, osl/namespace_linux.go
This adds support for a custom interface prefix. Can be used to address issues such as docker/docker#20067. If the label is not used the default behaviour prevails.
=> Support for com.docker.network.bridge.container_interface_prefix label

networkdb/networkdb_test.go
```
fatal error: concurrent map read and map write
goroutine 264 [running]:
runtime.throw(0x90043c, 0x21)
/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc4203d1d68 sp=0xc4203d1d48
runtime.mapaccess2_faststr(0x86df20, 0xc4203f5470, 0xc42044afc0, 0x5, 0xc4203d1e40, 0x4ed6b8)
/usr/local/go/src/runtime/hashmap_fast.go:306 +0x52b fp=0xc4203d1dc8 sp=0xc4203d1d68
github.com/docker/libnetwork/networkdb.(*NetworkDB).verifyNodeExistence(0xc42007e160, 0xc42008a240, 0xc42044afc0, 0x5, 0x1)
/go/src/github.com/docker/libnetwork/networkdb/networkdb_test.go:58 +0x6c fp=0xc4203d1e50 sp=0xc4203d1dc8
github.com/docker/libnetwork/networkdb.TestNetworkDBCRUDMediumCluster(0xc42008a240)
/go/src/github.com/docker/libnetwork/networkdb/networkdb_test.go:395 +0x991 fp=0xc4203d1f68 sp=0xc4203d1e50 …
```
=> Fix panic in networkdb test code

networkdb/broadcast.go
- When network DB enqueues a message into the memberlist broadcast queue,
memberlist checks whether the message can suppress past messages  present
in the queue by running a invalidation check. The check is implemented by the 
owner of the message, in this case network DB,  by implementing the Invalidates() method. 
With the only in clear information available in the message (table id, nw id and key),
network DB marks any two updates for the same key on the same network as redundant.
-  This means that if N endpoint updates happen in tens of millisecond window, network DB
will suppress the first N-1 updates and only propagate the last one in the cluster.
- For example this is breaking the endpoint rename use-case.
The service record delete event (associated to the old container name) is …
=> Do not invalidate table event messages

drivers/overlay/joinleave.go, drivers/overlay/ov_network.go, drivers/overlay/ov_serf.go, drivers/overlay/peerdb.go, drivers/solaris/overlay/peerdb.go, osl/neigh_linux.go, osl/sandbox.go
For all the overlay endpoints we pre-program both the neighbor and fdb entry. So typically either both are present or both are missing in which case we send a query. But in some error cases we have seen the fdb entry missing but the neighbor entry is present. Though we register for the l2miss notification from fdb it wasn't being handled in the overlay driver. Addressing it with this fix.
=> Handle kernel's l2miss notification in the overlay driver

cmd/dnet/dnet.go
Signed-off-by: Hui Kang <kangh@us.ibm.com>
=> Fix misspelling fmt verb in dnet

endpoint.go
- The rename logic has not been updated yet to work in swarm overlay networks.
This PR takes care of it.
=> Fix rename for containers on swarm network

agent.go, controller.go
- to signal when the networking cluster agent is stopped
This is needed by the daemon when it cleans up the cluster network resources on swarm leave or on graceful shutdown.  See [comment](https://github.com/docker/docker/pull/32283/files/43a938ef33640edf2d1b28a27120e65290f66284#r109971301).
=> Add AgentStopWait method

iptables/firewalld.go
Related to https://github.com/docker/docker/issues/31473
- The info it provides can be found elsewhere
The logs gets printed too often becasue of
the programming being done in the tasks
=> Remove firewalld running log

error.go
Signed-off-by: chchliang <chen.chuanliang@zte.com.cn>
- What I did
print name and id infomation when `docekr network rm` has active endpoints
- How I did it
func (aee *ActiveEndpointsError) Error() string {
return fmt.Sprintf("network %s id %s has active endpoints", aee.name, aee.id[0:12])
}
- How to verify it
`docekr network rm xxx` if network xxx has active endpoints, then print
Error response from daemon: network xxx id xxx has active endpoints
=> print name and id infomation  when  has active endpoints

controller.go
Signed-off-by: Krasi Georgiev <krasi@vip-consult.solutions>
a follow up from https://github.com/docker/docker/pull/31690
Related to  https://github.com/docker/docker/issues/31610
**- What I did**
when the docker daemon uses a non default folder as root set custom location for the sandbox files created for the ingress sandbox
**- How I did it**
added them in the ingress config struct when creating the sandbox
**- How to verify it**
dockerd -g /tmp/docker
docker swarm init
ls /tmp/docker/network/files/
ls /var/lib/docker 
should be empty
https://github.com/docker/docker/blob/master/vendor/github.com/docker/libnetwork/sandbox_dns_unix.go#L22
additionally I think I should also change 
defaultPrefix = cfg.Daemon.DataDir+"/network/files"
instead of 
defaultPrefix = …
=> ingress sandbox hosts and resolve.conf files location didn't respect the custom daemon root directory

networkdb/delegate.go, networkdb/networkdb.go
When the last task on an overlay network is shutdown, the node will leave from the network. Once a node leaves the network subsequence bulksync updates won't include the state for that network. If a bunch of tasks on a network are shutdown when there other network issues some of the gossip updates might be lost. If the network leave event does reach the peers they should cleanup the local state. Not doing so will leave the missed gossip state updates permanently in the peers' networkdb.
=> control-plane hardening: cleanup local state on peer leaving a network

sandbox.go
Related to docker/docker/issues/31414
Because the failure would not be on creating the osl sandbox
(which is done by somebody else). It would be on the programming
libnetwork does on the osl sandbox. In case of failure just report
the error. External caller will take care of removing the parent sandbox
via the cleanup on the error handling path. Otherwise the osl sandbox
will never be removed.
=> Sandbox.SetKey() should not reset the osl sandbox on failure

default_gateway.go, endpoint.go
- Currently if the join fails, the gw endpoint becomes
stale and stays connected to the gw network.
- Also fix sbJoin to do the cleanup in case
setupDefaultGW() fails
=> Remove gw endpoint on gw nw join failure

agent.go
- concurrent swarm join and daemon stop seen in
integration tests may cause agentSetup to access
a nil clusterProvider, resulting in a panic
Reported in moby/moby/issues/32673
=> agentSetup to first check if clusterProvider is nil

networkdb/broadcast.go
- Otherwise operation will unnecessarely block
for five seconds.
- This is particularly noticeable on graceful
shutdown of daemon in one node cluster.
Related to docker/docker/issues/32446
=> On clusterLeave, notify only if there are peers

agent.go, cluster/provider.go, cmd/dnet/dnet.go
During configuration in SWARM mode is now possible to pass an additional
parameter --datapath-addr <ip|interface>.
The information is going to be used to configure which is the interface
that is going to be used for the data path for global scope drivers.
Up to now the only driver really using this extra parameter is the
overlay driver.
=> Add the datapath-addr in libnetwork

networkdb/cluster.go
With the current design in libnetwork control plane events are first sent through gossip. This is through  UDP which can be lossy. To account for that there is an anti entropy phase every 30 seconds that does a full state sync.
Problem: In some deployments we have seen CPU getting pegged or memory exhaustion (till OOM kicks in) for longer periods resulting in both gossip and push/pull state sync failing. Delete events are retained in nDB for 60 seconds currently. So at the max a deleted event will remain only for two bulk-sync cycles. If few bulk-syncs fail from this node the peers will be left with stale events forever.
This can be fixed by two approaches:
1) Introduce a mechanism in every node to somehow figure out when an event is stale and delete it locally. This can be done by a mark …
=> control-plane hardening: Avoid nDB stale entries

agent.go, cluster/provider.go, cmd/dnet/dnet.go
Change in the provider interface to let the provider
return the whole list of managers.
This will allow the netwrok db to have multiple choice
to establish the first adjacencies
Relates to https://github.com/docker/libnetwork/issues/1734
=> Change GetRemoteAddr to return all managers

networkdb/cluster.go
Memberlist does a full validation of the protocol version (min, current, max)
amoung all the ndoes of the cluster.
The previous code was setting the protocol version to max version.
This makes the upgrade incompatible.
Relates to: moby/moby/issues/33091
=> Remove explicit set of memberlist protocol

agent.go, cluster/provider.go, cmd/dnet/dnet.go, config/config.go, controller.go
This change serialize the init/close of the libnetwork agent into one single code path.
On swarm init there are several things that are appening in parallel, before the
initialization of the agent was happening thorugh differents code paths depending
from timing.
This change cleans up the entire init logic letting the init happening in the goroutine
clusterAgentInit.
Moby side: https://github.com/moby/moby/pull/32906
=> Fix for swarm init/leave race condition

agent.go, controller.go, datastore/datastore.go, docs/remote.md, driverapi/driverapi.go, drivers/bridge/bridge.go, drivers/bridge/brmanager/brmanager.go, drivers/host/host.go, drivers/ipvlan/ipvlan.go, drivers/ipvlan/ivmanager/ivmanager.go, drivers/macvlan/macvlan.go, drivers/macvlan/mvmanager/mvmanager.go, drivers/overlay/overlay.go, drivers/overlay/ovmanager/ovmanager.go, drivers/remote/api/api.go, drivers/remote/driver.go, drivers/remote/driver_test.go, drivers/solaris/bridge/bridge.go, drivers/solaris/overlay/overlay.go, drivers/solaris/overlay/ovmanager/ovmanager.go, drivers/windows/overlay/overlay_windows.go, drivers/windows/windows.go, endpoint.go, libnetwork_internal_test.go, libnetwork_test.go, network.go, store.go
- It specifies whether the network driver can
provide containers connectivity across hosts.
- As of now, the data scope of the driver was
being overloaded with this notion.
- The driver scope information is still valid
and it defines whether the data allocation
of the network resources can be done globally
or only locally.
- With the scope network option, user can now
force a network as swarm scoped
regardless of the driver data scope.
- In case the network is configured as swarm scoped,
and the network driver is multihost capable,
a network DB instance will be launched for it.
Support configuration networks:
- They are configuration-only networks which
can be used to supply the configuration
when creating regular networks.
- They do not get allocated and do net get plumbed.
Drivers do …
=> ConnectivityScope capability and configuration networks

store.go
- Unless it is needed
After #1742, the `scope` field of the `network` structure is no longer tied to the network's datascope. The datastore APIs do in fact deduct the store scope for the network object from the DataScope() API.
That API itself has been changed to return the proper datastore scope in case of regular or swarm network.
The network read from store function are resetting the `network.scope` to the network's datascope. This was a long because of a long ago change to make sure a network could be removed in case the driver (remote) is no longer there, or in case a network was added with a older docker version where the scope field was not being saved to store.
Changed the code to perform the above logic only in case the `network.scope` is missing.
=> Do not reset network scope during store read

controller.go, drivers/bridge/setup_ip_tables.go, firewall_linux.go, firewall_others.go, iptables/iptables.go
Allow users to configure firewall policies in way that persists
docker operations/restarts. Docker will not delete or modify any
pre-existing rules from the DOCKER-FORWARD-TOP filter chain. This
allows the user to create in advance any rules required to further
restrict access from/to the containers.
Fixes docker/docker/issues/29184
Fixes docker/docker/issues/23987
Related to docker/docker/issues/24848
Signed-off-by: Jacob Wen <jian.w.wen@oracle.com>
=> Add a filter chain to allow persistent rules

controller.go, drivers/bridge/setup_ip_tables.go
Cherry-pick of fe741120dbacc1c720a80812de1d65811695f5d6 for 17.03.2
Related to https://github.com/moby/moby/issues/25393
=> [17.03.x] Serialize non-atomic jump rule programming in bridge

controller.go
Issue was reported by @thaJeztah in https://github.com/moby/moby/pull/32981#issuecomment-301956637
```
$ docker node ls
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.
$ ./docker network create --scope swarm bb
Error response from daemon: cannot create a swarm scoped network when swarm is not active
```
=> Do not accept swarm scope network creation if swarm is off

network.go
- This got mistakenly chaged by 596122e05edd3
- Current PR restores behavior added in 2736974436513da1919746e184e6fa708bf1aeba
Issue:
On daemon reload with with swarm configuration, it is possible for the following failure in creating the ingress network:
```
INFO[0002] Gossip cluster hostname aboch-XPS-01bd4c59753f 
INFO[0002] Docker daemon                                 commit=ca4b3c6 graphdriver=aufs version=17.06.0-dev
ERRO[0002] Failed creating ingress network: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again. 
```
debugging revealed the issue is because of the change, where is Agent would return false because the cluster provider is not yet set.
Note: On defer path, ingress network removal with driver won't …
=> Restore isAgent || n.dynamic check

network.go
- in driver(), no need to check for isAgent which itself is vulnerable to some corner cases.
=> Simplify network scope setting logic

networkdb/event_delegate.go
The time to keep a node failed into the failed node list
was originally supposed to be 24h.
If a node leaves explicitly it will be removed from the list of nodes
and put into the leftNodes list. This way the NotifyLeave event won't
insert it into the retry list.
NOTE: if the event is lost instead the behavior will be the same as a failed node.
If a node fails, the NotifyLeave will insert it into the failedNodes
list with a reapTime of 24h. This means that the node will be checked
for 24h before being completely forgot. The current check time is every
1 second and is done by the reconnectNode function.
The failed node list is updated every 2h instead.
=> Node failure timeout fix

ipvs/constants.go, ipvs/ipvs.go, ipvs/ipvs_test.go, ipvs/netlink.go
@mavenugo This is an Inital checkin to get the approach validated.  If you are okay with this i will improve/add coverage for the package.
Also i though we could introduce a file utils.go in ipvs package and moave all the utility related funcs there? what do you think?
=> [IPVS] Implement GetServices(),GetService() and GetDestinations()

controller.go, network.go
The commit contains fix for the issue reported in https://github.com/moby/moby/issues/33415 and
https://github.com/docker/libnetwork/issues/1772. With the feature introduced to support local scope networks in swarm mode (moby/moby#32981) the network configuration to include ipam driver was over-riden in libnetwork. This has been removed with this fix which will allow ipam-driver option to be used for task allocation. 
Verified with the steps posted in the issue docker/libnetwork#1772 as well.
=> Removing the override for ipamdriver for local scope networks in

networkdb/cluster.go, networkdb/delegate.go, networkdb/event_delegate.go, networkdb/networkdb.go
Related to [moby #33346](https://github.com/moby/moby/issues/33346)
In a cluster with one manager if that manager node is rebooted or daemon is restarted the manager node gets isolated from the gossip cluster. This is because in the single manager case its the one bootstrapping the gossip when other worker nodes connect to it. When that node restarts the libnetwork agent has no other node info to bootstrap the gossip.
Change in this PR is to have the workers try reconnecting to the bootstrapping manager periodically. This uses the already available reconnect logic which was originally added for the worker node, ie: if a worker node is isolated in the gossip cluster because of lets say network congestion when it thaws it will connect to the previously connected nodes to rebuild its gossip …
=> Handle single manager reload by having workers reconnect

drivers/overlay/ostweaks_linux.go, drivers/overlay/ostweaks_unsupported.go, drivers/overlay/overlay.go
On linux systems bump up gc_thresholds so to lower the
probability of running with neighbor table overflow issues
=> Set kernel specific config on linux

drivers/overlay/ov_network.go, osl/neigh_linux.go
Fixes #1768 
Noticed this issue when debugging few test case failures in e2e test suite. This is likely to be the root cause for [docker #33076](https://github.com/moby/moby/issues/33076) and the service access issue during container bring up reported in [docker #30321](https://github.com/moby/moby/issues/30321)
This PR implements a different approach to fix this issue. #1783 has an alternative approach, which could have a performance impact.
libnetwork IPAM recycles the IP address when a  task goes down on a node and brought up in another node. For remote tasks overlay network namespace has one static fdb entry programmed by the driver and one dynamic entry learned by the bridge from the data path when a packet is received from the remote container. The dynamic entry ages out after 300 …
=> Remove dynamic mac entry from fdb on endpoint deletion

agent.go, networkdb/networkdb_test.go, networkdb/watch.go
The channel ch.C is never closed, so the condition ok in the if will never be `false`.
Added the listen of the ch.Done() to guarantee
that the goroutine is exiting once the event channel
is closed
=> Fix leak of handleTableEvents

drivers/overlay/overlay.go
The feature was not getting properly triggered, move it as
first operation in the configure
=> Fix OS tweaks call

Makefile, agent.go, agent.proto, common/setmatrix.go, common/setmatrix_test.go, endpoint.go, libnetwork_internal_test.go, network.go, networkdb/networkdb.go, sandbox.go, service.go, service_common.go, service_linux.go
This patch addresses several issues found on the Service Discovery feature.
=> Service discovery hardening

agent.go, drivers/overlay/ostweaks_linux.go, drivers/overlay/ostweaks_unsupported.go, drivers/overlay/ov_network.go, drivers/overlay/overlay.go, networkdb/networkdb_test.go, networkdb/watch.go
Fixed cancelling method call to avoid go routine leaks
=> Backport fix to 17.03

sandbox.go
When sandbox is deleting, another SetKey routine could be also in
progress as there's no lock to protect it, when this happens, there
could be a scene that one sandbox is removed, but it's osSbox file
"/var/run/docker/netns/xxxx" left on system and will never be cleaned.
So add a inDelete check for SetKey() to eliminate the race.
=> [bug]Fix race between sandbox.delete() and SetKey()

agent.go
There was an extra parameter not in the formatters
=> Fix handleEPTable log

drivers/windows/windows_store.go
The docker daemon doesn't start on windows after an endpoint leaks. It fails with error Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to get endpoints from store: failed to decode endpoint IPv4 address (<nil>) after json unmarshal: invalid CIDR address: <nil>
This is because there is no ip for an endpoint in transparent network. We need to handle that during marshal and unmarshal.
=> Fixes docker daemon not starting after endpoint leak 

MAINTAINERS
Flavio has been contributing various useful features in Docker 17.05
and 17.06 releases and also an active maintainer who helps with various
bug fixes and PR reviews
=> Flavio as Libnetwork maintainer

agent.go, common/setmatrix.go, libnetwork_internal_test.go, network.go, service.go, service_common.go, service_linux.go
Found an issue where the deletion of the entry from serviceBindings map inside the rmServiceBinding was creating a possible race with a new addServiceBindings.
The deletion from the map was allowing a new go routine to create a completely new service object and race with the final part of the rmServiceBinding.
Another issue identified was the possible reuse of an IP from a service in the svcRecords map. This table is keyed by network ID, so services if they are reusing the same name but different service id cannot be distinguished when they are creating or deleting entries. In a perturbance scenario where a service is updated, notification coming from endpoints that are remote can be delayed and cause state corruption on the new service with local endpoints. To address this issue, move …
=> Service discovery race on serviceBindings delete. Bug on IP reuse

agent.go, common/setmatrix.go, libnetwork_internal_test.go, network.go, service.go, service_common.go, service_linux.go
=> Backport sd race network

agent.go, common/setmatrix.go, libnetwork_internal_test.go, network.go, service.go, service_common.go, service_linux.go
* Correct SetMatrix documentation
The SetMatrix is a generic data structure, so the description
should not be tight to any specific use
* Service Discovery reuse name and serviceBindings deletion
- Added logic to handle name reuse from different services
- Moved the deletion from the serviceBindings map at the end
of the rmServiceBindings body to avoid race with new services
* Avoid race on network cleanup
Use the locker to avoid the race between the network
deletion and new endpoints being created
* CleanupServiceBindings to clean the SD records
Allow the cleanupServicebindings to take care of the service …
=> Backport to 17.06 Service discovery race on serviceBindings delete

networkdb/delegate.go, networkdb/networkdb.go
When the last task(s) are brought down on a node, network leave event is
also sent. network leave could potentially race with the task delete
events and if happens to complete first the task delete events won't be
sent out resulting in stale entries in the remote nodes. Clean up all
the state from a node for a network when a network leave event is
received from a node.
=> backport libnetwork #1704 to 1.13/17.03 branch

networkdb/delegate.go
Commit 90103909401ecbe2b39216bb44dc79b89eee2b7e added a number of debugging messages for node join/leave events.
This patch checks if a node already was listed, and otherwise skips the logging to make the logs a bit less noisy.
relates to https://github.com/docker/libnetwork/pull/1775
addresses https://github.com/moby/moby/issues/33962
ping @sanimej PTAL - we may want to have this in a 17.06.x patch release
=> Make node join event logging less noisy

cluster/provider.go, cmd/dnet/dnet.go
use builtin package context rather than vendored one
Since go 1.7, package context has been one builtin package in golang. So I think it is useful to use that directly. I searched globally in libnetwork except the vendored package and changed the two places.
=> use builtin package context rather than vendored one

network_windows.go
Signed-off-by: John Howard <jhoward@microsoft.com>
Very simple fix. Been annoying for way too long running the Windows daemon in debug mode and seeing 
```
level=debug msg="Launching DNS server for network%!(EXTRA string=none)"
```
@msabansal @mavenugo
=> Fix debug statement in startResolver

networkdb/cluster.go, networkdb/delegate.go, networkdb/networkdb.go, networkdb/networkdb_test.go
A rapid (within networkReapTime 30min) leave/join network
can corrupt the list of nodes per network with multiple copies
of the same nodes.
The fix makes sure that each node is present only once
=> NetworkDB incorrect number of entries in networkNodes

drivers/bridge/bridge_test.go, iptables/iptables.go
Solve the flakiness of the TestLinkContainers.
From a code standpoint I don't see any way that the chain should not exists.
I noticed that some of the previous tests are not properly doing the check if they are running into a container.
=> Avoid flakiness of TestLinkContainers

docs/remote.md
The libnetwork implementation and design spec conflict on the type of the IPv[4|6]Data.Gateway field. The spec requires it to be a regular IP address string (with no prefix length), whereas the implementation sends an IP address in CIDR notation.
This seems to be a bug in implementation (since network plugin has no need for the prefix length), but a change at this point could break existing remote plugins. So we are updating the spec to match the implementation instead. That's unfortunate, but better than having a spec conflict. See issue #1745 for details.
CC @aboch, @mavenugo 
Fixes #1745.
=> Fix the Gateway type in remote network plugin spec

agent.go, config/config.go, networkdb/cluster.go, networkdb/message.go, networkdb/networkdb.go, networkdb/networkdb_test.go
Introduce the possibility to specify the max buffer length
in network DB. This will allow to pass the proper MTU to 
networkDB
=> NetworkDB to honor the Network Control Plane MTU

drivers/overlay/ov_network.go
When the gc_thresh3 value is reached kenel might remove existing neighbor entries. On an l3 miss try to reprogram the neighbor entry if the peer is valid.
Ideally the gc_thresh* values should be bumped up to avoid this issue. Since most customer are not aware of this setting #1789 increases it as part of the overlay driver init. 
This patch is a best effort attempt to help if the user has for some reason reduced this value. neighbor entry programming will succeed if the arp table is currently not at gc_thresh3 value.
=> Attempt neighbor entry reprogramming on L3 miss

cluster/provider.go, cmd/dnet/dnet.go
Reverts docker/libnetwork#1841
This breaks the integration with Moby:
```
---> Making bundle: binary (in bundles/17.06.0-dev/binary)                                                                                                                                                                     
Building: bundles/17.06.0-dev/binary-daemon/dockerd-17.06.0-dev                                                                                                                                                                                                             
daemon/cluster/cluster.go:238: cannot use c (type *Cluster) as type cluster.Provider in argument to c.config.Backend.DaemonJoinsCluster:
*Cluster does not implement cluster.Provider (wrong type for WaitForDetachment method)
have …
```
=> Revert "use builtin package context rather than vendored one"

bitseq/sequence.go, bitseq/sequence_test.go
The byteoffset calculation was skewed to double include the offset value calculated. The double calculation happens if the starting ordinal is part of the head sequence block. This error in calculation could result in duplicate bit getting allocated eventually propogating to ipam and vni id allocations
=> Fixing issue with bit allocation byteoffset calculation

osl/neigh_linux.go
Deletion of the dynamic mac is expected to work only if there was active
traffic with that endpoint and a dynamic entry exists. It can also age
out. Hence the mac removal failing is not error. Removing it to make the
debugging easier when parsing the logs.
=> Remove the error message on mac delete failure..

.gitignore, diagnose/diagnose.go, networkdb/delegate.go, networkdb/networkdb.go, networkdb/networkdbdiagnose.go, test/networkDb/Dockerfile, test/networkDb/README, test/networkDb/dbclient/ndbClient.go, test/networkDb/dbserver/ndbServer.go, test/networkDb/dummyclient/dummyClient.go, test/networkDb/testMain.go
- Diagnose framework that exposes REST API for db interaction
- Dockerfile to build the test image
- Periodic print of stats regarding queue size
- Client and server side for integration with testkit
=> NetworkDB testing infra

common/caller.go, common/caller_test.go, drivers/overlay/joinleave.go, drivers/overlay/ov_network.go, drivers/overlay/ov_serf.go, drivers/overlay/overlay.go, drivers/overlay/peerdb.go
Remove the need for the wait group and avoid new
locks
=> Funnel peerAdd and peerDelete in a channel

common/caller.go, common/caller_test.go, drivers/overlay/joinleave.go, drivers/overlay/ov_network.go, drivers/overlay/ov_serf.go, drivers/overlay/overlay.go, drivers/overlay/peerdb.go
Remove the need for the wait group and avoid new
locks
Added utility to print the method name and the caller name
=> [17.06 backport] Funnel peerAdd and peerDelete in a channel

common/caller.go, common/caller_test.go, drivers/overlay/joinleave.go, drivers/overlay/ov_network.go, drivers/overlay/ov_serf.go, drivers/overlay/overlay.go, drivers/overlay/peerdb.go
Remove the need for the wait group and avoid new
locks
Added utility to print the method name and the caller name
=> [17.03 backport] Funnel peerAdd and peerDelete in a channel

networkdb/broadcast.go, networkdb/cluster.go, networkdb/delegate.go, networkdb/event_delegate.go, networkdb/networkdb.go
Several fixes aimed to optimize and strengthen the networkDB component
=> Network db stabilization

networkdb/broadcast.go, networkdb/cluster.go, networkdb/delegate.go, networkdb/event_delegate.go, networkdb/networkdb.go, networkdb/networkdb_test.go
Backport fixes to `bump_17.06.0` branch:
* #1860 Network db stabilization
* #1836 NetworkDB incorrect number of entries in networkNodes
The commit 297c3d4 taken from #1836 is needed to make the cherry pick go in clean.
Cherry picked commits 297c3d4 bede778 4cf74e8 26db0b9:
```
$ git cherry-pick -s -x 297c3d4 bede778 4cf74e8 26db0b9
```
=> [17.06] backport networkdb fixes

endpoint_info.go
Reverts docker/libnetwork#1876
Signed-off-by: Flavio Crisciani flavio.crisciani@docker.com
=> Revert "[backport 17.03] Fixes bug that mistook gw6 for gw."

endpoint_info.go
Reverts docker/libnetwork#1875
Signed-off-by: Flavio Crisciani flavio.crisciani@docker.com
=> Revert "[backport 17.06] Fixes bug that mistook gw6 for gw."

endpoint_info.go
Reverts docker/libnetwork#1868
The current change is correct but is introducing failures in the integration test pipeline, needs debug
=> Revert "Fixes bug that mistook gw6 for gw."

endpoint_info.go
Fixes bug that mistakes gw6 for gw
which causes this bug https://github.com/moby/moby/issues/25981
Signed-off-by: Frank Yang <yyb196@gmail.com>
=> Fixes bug which makes restoring endpoint mess

agent.go, common/caller.go, common/caller_test.go, drivers/overlay/joinleave.go, drivers/overlay/ov_network.go, drivers/overlay/ov_serf.go, drivers/overlay/overlay.go, drivers/overlay/peerdb.go, networkdb/networkdb.go
First commit moves the peerAdd/peerDelete operation behind a channel
Second commit deals with a possible deadlock on the pMap Lock. Because of the lazy instantiation logic of the overlay driver, the initSandbox has in all cases to fetch peers from the DB. Moreover this operation has to be atomic on the whole table to avoid a race with subsequent peerAdd/peerDelete that can asynchronously come from the networkDB.
=> Service connectivity issue

agent.go, common/caller.go, common/caller_test.go, drivers/overlay/joinleave.go, drivers/overlay/ov_network.go, drivers/overlay/ov_serf.go, drivers/overlay/overlay.go, drivers/overlay/peerdb.go, networkdb/networkdb.go
First commit moves the peerAdd/peerDelete operation behind a channel
Second commit deals with a possible deadlock on the pMap Lock. Because of the lazy instantiation logic of the overlay driver, the initSandbox has in all cases to fetch peers from the DB. Moreover this operation has to be atomic on the whole table to avoid a race with subsequent peerAdd/peerDelete that can asynchronously come from the networkDB.
Backport of: https://github.com/docker/libnetwork/pull/1893
This also include backport that was missing of: https://github.com/docker/libnetwork/pull/1842
=> [Backport 17.06] service connectivity issue

agent.go, common/caller.go, common/caller_test.go, drivers/overlay/joinleave.go, drivers/overlay/ov_network.go, drivers/overlay/ov_serf.go, drivers/overlay/overlay.go, drivers/overlay/peerdb.go, networkdb/networkdb.go
First commit moves the peerAdd/peerDelete operation behind a channel
Second commit deals with a possible deadlock on the pMap Lock. Because of the lazy instantiation logic of the overlay driver, the initSandbox has in all cases to fetch peers from the DB. Moreover this operation has to be atomic on the whole table to avoid a race with subsequent peerAdd/peerDelete that can asynchronously come from the networkDB.
Backport of: https://github.com/docker/libnetwork/pull/1893
=> [Backport 17.03] service connectivity issue

agent.go, common/caller.go, common/caller_test.go, drivers/overlay/joinleave.go, drivers/overlay/ov_network.go, drivers/overlay/ov_serf.go, drivers/overlay/overlay.go, drivers/overlay/peerdb.go, networkdb/networkdb.go
First commit moves the peerAdd/peerDelete operation behind a channel
Second commit deals with a possible deadlock on the pMap Lock. Because of the lazy instantiation logic of the overlay driver, the initSandbox has in all cases to fetch peers from the DB. Moreover this operation has to be atomic on the whole table to avoid a race with subsequent peerAdd/peerDelete that can asynchronously come from the networkDB.
Backport of: #1893
=> [Backport 17.07] service connectivity issue

osl/interface_linux.go, osl/namespace_linux.go, osl/options_linux.go, osl/sandbox.go, sandbox.go
Refreshed the PR: https://github.com/docker/libnetwork/pull/1585
Addressed comments suggesting to remove the IPAlias logic not anymore used
=> Add service virtual IP to sandbox's loopback address

drivers/overlay/ov_network.go, osl/neigh_linux.go
The mount propagation is causing wierd issues in specific scenarios.
Reverting the patch temporarily until the root-cause is identified.
This reverts commit ae6824ea646a89853afa145a90f56e449f4d3a4f.
=> Revert "Remove dynamic mac entry from fdb on endpoint deletion"

drivers/overlay/peerdb.go
The peerDbDelete was passing the wrong field to the underlay
Delete operation causing the mac entry to not being deleted
from the bridge on the overlay. This caused connectivity issue
when a container that before was remote was now scheduled
on the local node. The entry was such:
bridge fdb show | grep -i 02:42:0a:01:00:02
02:42:0a:01:00:02 dev vxlan0 master br0
02:42:0a:01:00:02 dev vxlan0 dst 172.31.14.63 link-netnsid 0 self permanent
That was still pointing to a remove node
=> PeerDbDelete was passing the wrong field

drivers/overlay/joinleave.go, drivers/overlay/ov_network.go, drivers/overlay/ov_serf.go, drivers/overlay/overlay.go, drivers/overlay/peerdb.go
In the peerDelete the updateDB flag was always true
In the peerAdd the updateDB flag was always true except for
the initSandbox case. But now the initSandbox is handled by the
go routing of the peer operations, so we can move that flag
down and remove it from the top level functions
=> Remove useless flags on peer operations

drivers/overlay/ov_network.go
Prevents an issue where the goroutine may jump to a new OS thread during
execution putting it into a mount/network NS that is unexpected.
=> Lock goroutine to OS thread while changing NS

drivers/overlay/ov_network.go, osl/neigh_linux.go
Restore previously reverted fix: https://github.com/docker/libnetwork/pull/1792
Backport fix that ensure proper OS thread locking: https://github.com/docker/libnetwork/pull/1911
=> [backport 17.06] Overlay fix for IP reuse

drivers/overlay/ov_network.go
Backport fix that ensure proper OS thread locking: #1911
=> [backport 17.07] Overlay fix for IP reuse

cmd/dnet/dnet.go
The cluster provider interface does not need GetNetworkKeys
and SetNetworkKeys
Signed-off-by: Hui Kang <kangh@us.ibm.com>
=> dnet: remove unused method for dnetConnection struct

drivers/bridge/bridge_test.go, drivers/ipvlan/ipvlan_setup.go, drivers/macvlan/macvlan_setup.go, drivers/overlay/ov_network.go, drivers/overlay/overlay.go, drivers/solaris/overlay/ov_network.go, drivers/solaris/overlay/overlay.go, ipam/allocator.go, types/types.go
Use the string concatenation operator instead of using `Sprintf` for simple string concatenation. This is usually easier to read, and allows the compiler to detect problems with the type or number of operands, which would be runtime errors with `Sprintf`.
=> all: Avoid trivial uses of Sprintf

drivers/windows/overlay/joinleave_windows.go, drivers/windows/overlay/ov_endpoint_windows.go, drivers/windows/overlay/ov_network_windows.go, drivers/windows/overlay/overlay_windows.go, drivers/windows/overlay/peerdb_windows.go, drivers/windows/windows.go
=> Tasks connected to a swarm network will have 1 endpoint on windows RS3.

ipvs/ipvs.go, ipvs/ipvs_test.go, ipvs/netlink.go
We vendor libnetwork's ipvs library into kubernetes and want a batch API for flushing IPVS services.
Do we have plan to support the flush API for IPVS service?
related issue:
#1930
=> Support flush API for IPVS service

config/config.go
Avoid negative numbers and also set a lower bondary.
500 will mean 400 bytes minimum payload that will allow
at least a couple of gossip message to fit.
There is not theoretical limit becasue the message is made of
strings so there is still the possibility to have cases where
the 400 bytes are not enough to fit a single message, but
in that case we should start thinking why do I need a node
name that is long as an enciclopedia
=> Add a minimum value for the CP MTU

endpoint.go, endpoint_info.go, sandbox.go, service.go, service_common.go, service_linux.go, service_windows.go, vendor.conf, vendor/github.com/Microsoft/hcsshim/hnsendpoint.go, vendor/github.com/Microsoft/hcsshim/hnspolicylist.go, vendor/github.com/Microsoft/hcsshim/interface.go, vendor/github.com/Microsoft/hcsshim/legacy.go
This is 1 of 3 PRs (the other 2 are in swarmkit and moby repos).
This change enables ILB/ELB functionality on windows using a per-node, per-network LB endpoint.  The per-node, per-network LB endpoint was discussed with docker 
as a solution to https://github.com/moby/moby/issues/30820.  Note that only windows is using the LB endpoint.  We have not changed the linux networking code to take advantage of the LB endpoint.
=> Enabling ILB/ELB on windows using per-node, per-network LB endpoint.

libnetwork_test.go
This should be `com.docker.network.driver.mtu`
fixes https://github.com/docker/libnetwork/issues/1906
ping @abhinandanpb PTAL
=> Fix test using com.docker.network.mtu

agent.go, networkdb/broadcast.go, networkdb/cluster.go, networkdb/delegate.go, networkdb/networkdb.go, networkdb/networkdb_test.go, test/networkDb/dbserver/ndbServer.go
Separate the hostname from the node identifier. All the messages
that are exchanged on the network are containing a nodeName field
that today was hostname-uniqueid. Now being encoded as strings in
the protobuf without any length restriction they plays a role
on the effieciency of protocol itself. If the hostname is very long
the overhead will increase and will degradate the performance of
the database itself that each single cycle by default allows 1400
bytes payload
=> NetworkDB create NodeID for cluster nodes

networkdb/delegate.go
The comparison was against the wrong constant value.
As described in the comment the check is there to guarantee
to not propagate events realted to stale deleted elements
=> Fix comparison against wrong constant

networkdb/delegate.go
The comparison was against the wrong constant value.
As described in the comment the check is there to guarantee
to not propagate events realted to stale deleted elements
(cherry picked from commit 6f11d298eee5bbdff6403e4443490f04e99b467e)
=> [backport 17.06] Fix comparison against wrong constant

networkdb/delegate.go
The comparison was against the wrong constant value.
As described in the comment the check is there to guarantee
to not propagate events realted to stale deleted elements
(cherry picked from commit 6f11d298eee5bbdff6403e4443490f04e99b467e)
=> [backport 17.03] Fix comparison against wrong constant

networkdb/networkdb.go
Repair (*Broadcaster).run goroutine leak 
When execute 'docker swarm init' and 'docker swarm leave -f' on a node
repeatedly, the (*Broadcaster).run goroutine leak.
•What I did
Execute 'docker swarm init' and 'docker swarm leave -f' on a node
repeatedly
•How I did it
while true; do docker swarm init ; sleep 3 ; docker swarm leave -f ; done &
•How to verify it
'free -m', watch the 'available' item . constant loss explans the goroutine leak.
=>  Repair (*Broadcaster).run goroutine leak 

bitseq/sequence.go, bitseq/sequence_test.go, bitseq/store.go, drivers/overlay/ov_network.go, drivers/overlay/ovmanager/ovmanager.go, drivers/solaris/overlay/ov_network.go, drivers/solaris/overlay/ovmanager/ovmanager.go, idm/idm.go, idm/idm_test.go, ipam/allocator.go, ipam/allocator_test.go, ipamapi/labels.go, libnetwork_internal_test.go
Previously the bitseq alloc was allocating the first available bit from the beginning of the bit sequence for each sequence handle. With this commit the bitseq alloc will proceed
from the current allocation. This change will affect the way ipam and vni
allocation is done currently. The ip allocation will prcoeeed  sequentially from the previous allocation as opposed to the first available IP. So even if the IPs are released it will not be reused until the allocator rolls over to the beginner of the bit sequence.
The commit also contains a fix for byteoffset allocation which plays a role in calculating the allocated ordinal. This scenerio play when the starting ordinal is  part of the head sequence block and the available bit is part of subsequent blocks in the bitseq.
Signed-off-by: …
=> Serializing bitseq alloc

drivers/overlay/peerdb.go, drivers/overlay/peerdb_test.go
=> Fix IPMask marshalling

drivers/overlay/ov_network.go
fixes https://github.com/docker/for-linux/issues/89
thanks @alainvanhoof for reporting
ping @abhi PTAL
=> Fix typo in overlay log message

iptables/iptables.go
Without `-n`, iptables will attempt to lookup hostnames for IP
addresses, which can slow down the call dramatically.
Since we don't need this, and generally don't even care about the
output, use the `-n` flag to disable this.
Signed-off-by: Brian Goff <cpuguy83@gmail.com>
=> Disable hostname lookup on chain exists check

Dockerfile.build
Bumps the Go version used to 1.8.4, which contains security fixes;
https://groups.google.com/forum/#!topic/golang-announce/1hZYiemnkdE
Build of the Dockerfile was currently failing for me because https://honnef.co/ is currently down (https://github.com/dominikh/go-tools/issues/197)
=> Bump Go to 1.8.4

circle.yml
In case of merge commit, the sha passed to the codecov tool
is the one of the merged commit intstead of the merge commit
this creates error because the base commit is always different.
Passing it explicitely should fix it
=> Explicitly pass the sha to codecov

controller.go, network.go, networkdb/networkdb.go, service_common.go
Attachable containers they are tasks with no service associated
their cleanup was not done properly so it was possible to have
a leak of their name resolution if that was the last container
on the network.
Cleanupservicebindings was not able to do the cleanup because there
is no service, while also the notification of the delete arrives
after that the network is already being cleaned
=> Handle cleanup DNS for attachable container

controller.go, network.go, networkdb/networkdb.go, service_common.go
Attachable containers they are tasks with no service associated
their cleanup was not done properly so it was possible to have
a leak of their name resolution if that was the last container
on the network.
Cleanupservicebindings was not able to do the cleanup because there
is no service, while also the notification of the delete arrives
after that the network is already being cleaned
(cherry picked from commit 1c04e1980dfd6debab6e43d9db672c0f01528868)
=> [backport 17.06] Handle cleanup DNS for attachable container

iptables/iptables.go
Backport of fix:
* https://github.com/docker/libnetwork/pull/1974 Disable hostname lookup on chain exists check
With cherry-pick of commit 8dce207:
```
$ git cherry-pick -s -x 8dce207
```
No conflicts.
=> [17.06] Disable hostname lookup on chain exists check

service_common_test.go
Backport:
* #1991 Add test for cleanupServiceDiscovery
With cherry-pick of 52a9ab5:
```
$ git cherry-pick -s -x 52a9ab5
```
No conflicts.
=> [17.06] Add test for cleanupServiceDiscovery

iptables/iptables.go
backport fix:
* #1974 Disable hostname lookup on chain exists check
with cherry-pick git commit 8dce207
```
$ git cherry-pick -s -x 8dce207
```
cherry-pick when it clean
=> [release/v0.9] Disable hostname lookup on chain exists check

controller.go, network.go, networkdb/networkdb.go, service_common.go, service_common_test.go
backport:
* #1985 Handle cleanup DNS for attachable container
* #1991 Add test for cleanupServiceDiscovery
with cherry-pick of git commits 1c04e19 52a9ab5:
```
$ git cherry-pick -s -x 1c04e19 52a9ab5
```
conflict with file `service_common.go` resolved by adding functions:
* ~`func (c *controller) getLBIndex(sid, nid string, ingressPorts []*PortConfig) int`~
* `func (c *controller) cleanupServiceDiscovery(cleanupNID string)`
=> [release/v0.9] Handle cleanup DNS for attachable container

drivers/windows/windows.go
Workaround for https://github.com/docker/libnetwork/issues/1950 to treat failure to save endpoint to store as non fatal. These endpoints are just required for cleanup in case of docker service crash and saving them is not really required and should not be considered fatal.
=> Ignore failure to save hns endpoint to store

support.sh
Addresses failure to collect iptables information if lock is held during
data capture. Follows the reccomendation of iptables stderr in this
scenario:
```
Another app is currently holding the xtables lock. Perhaps you want to
use the -w option?
```
Signed-off-by: Trapier Marshall <trapier.marshall@docker.com>
=> wait for iptables lock in support script

portmapper/proxy.go
This is necessary to support moby/moby#34226. The binary name `docker-proxy` is currently hardcoded in libnetwork. This is the smallest possible change to allow us to configure the binary name, by setting the following arg on `go build` of the engine binary:
```
--ldflags "-X github.com/docker/docker/vendor/github.com/docker/libnetwork/portmapper.userlandProxyCommandName=$PROXY_BINARY_NAME"
```
=> Support override of binary name

endpoint_cnt.go, store.go
endpoint_cnt object is created during network create and destroyed when
network is deleted. But the updateToStore function creates an object
when it is not present in the store. endpoint_cnt is a mutable object
and is updated during endpoint create and delete events. If endpoint
create or delete happens after the network is deleted, it can
incorrectly create an endpoint_cnt object in the store and that can
cause problems when the same network is created again later.
The fix is to not create the endpoint_cnt object when endpoint_cnt is
incremented or decremented
This handles the error seen in https://github.com/moby/moby/issues/35310.
But I think https://github.com/moby/moby/issues/35310 needs a more complete fix which is not handled in this PR
Signed-off-by: Madhu Venugopal …
=> endpoint_cnt store updates should not create an object

networkdb/cluster.go, networkdb/delegate.go, networkdb/networkdb.go, networkdb/networkdb_test.go
- Create a test to verify that a node that joins
in an async way is not going to extend the life
of a already deleted object
=> Add test to confirm garbage collection

cmd/dnet/dnet.go, drivers/bridge/bridge.go, drivers/bridge/setup_ip_tables.go, drivers/overlay/ov_endpoint.go, drivers/solaris/overlay/ov_endpoint.go, endpoint_info.go, iptables/iptables.go, sandbox_dns_unix.go
cherry-pick of https://github.com/docker/libnetwork/pull/1947 for the 17.09 branch
```
git checkout -b 17.09-backport-fix-lint upstream/bump_17.09
git cherry-pick -s -S -x 9e5748ad7dc65318889693365a53492be94b1521
```
The package updated and now shows new warnings that had to be corrected to let the CI pass
=> [17.09] Fix lint issues

iptables/iptables.go
cherry-pick of https://github.com/docker/libnetwork/pull/1974 for 17.09
```
git checkout -b 17.09-backport-iptables_no_dns_lookup upstream/bump_17.09
git cherry-pick -s -S -x 8dce207dddc3f805b852088a60cc27bfe54b065e
```
Without `-n`, iptables will attempt to lookup hostnames for IP
addresses, which can slow down the call dramatically.
Since we don't need this, and generally don't even care about the
output, use the `-n` flag to disable this.
(cherry picked from commit 8dce207dddc3f805b852088a60cc27bfe54b065e)
=> [17.09] Disable hostname lookup on chain exists check

diagnose/diagnose.go, networkdb/cluster.go, networkdb/delegate.go, networkdb/event_delegate.go, networkdb/networkdb.go, networkdb/networkdbdiagnose.go, test/networkDb/Dockerfile
The previous logic was not properly handling the case of a node that was failing and oining back in short period of time.
The issue was in the handling of the network messages.
When a node joins it sync with other nodes, these are passing the whole list of nodes that at best of their knowledge are part of a network. At this point if the node receives that node A is part of the network it saves it before having received the notification that node A is actually alive (coming from memberlist).
If node A failed the source node will receive the notification while the new joined node won't because memberlist never advertise node A as available. In this case the new node will never purge node A from its state but also worse, will accept any table notification where node A is the owner and so …
=> NetworkDB node management race

drivers/overlay/ov_network.go, drivers/overlay/overlay_test.go, ipvs/ipvs.go, ipvs/netlink.go, vendor.conf, vendor/github.com/vishvananda/netlink/README.md, vendor/github.com/vishvananda/netlink/addr_linux.go, vendor/github.com/vishvananda/netlink/bridge_linux.go, vendor/github.com/vishvananda/netlink/conntrack_linux.go, vendor/github.com/vishvananda/netlink/filter.go, vendor/github.com/vishvananda/netlink/filter_linux.go, vendor/github.com/vishvananda/netlink/handle_linux.go, vendor/github.com/vishvananda/netlink/handle_unspecified.go, vendor/github.com/vishvananda/netlink/link.go, vendor/github.com/vishvananda/netlink/link_linux.go, vendor/github.com/vishvananda/netlink/neigh.go, vendor/github.com/vishvananda/netlink/neigh_linux.go, vendor/github.com/vishvananda/netlink/netlink_unspecified.go, vendor/github.com/vishvananda/netlink/nl/bridge_linux.go, vendor/github.com/vishvananda/netlink/nl/conntrack_linux.go, vendor/github.com/vishvananda/netlink/nl/link_linux.go, vendor/github.com/vishvananda/netlink/nl/nl_linux.go, vendor/github.com/vishvananda/netlink/qdisc_linux.go, vendor/github.com/vishvananda/netlink/route.go, vendor/github.com/vishvananda/netlink/route_linux.go, vendor/github.com/vishvananda/netlink/rule.go, vendor/github.com/vishvananda/netlink/rule_linux.go
Add netlink timeouts to all the netlink operations
Vendored netlink library to pick the required methods (temporary my branch)
=> Netlink timeouts

controller.go, diagnose/server.go
This is the right way to call for a clean shutdown
=> Call the Shutdown on the server

drivers/bridge/bridge.go, drivers/bridge/bridge_test.go, drivers/bridge/setup_firewalld.go
The CreateNetworkin the bridge driver was not able to properly
handle concurrent operations causing 2 issues:
1) crash from nil pointer exception. (Fixes: moby/moby#34515)
2) not proper handling of conflicting configuration
This commit addresses the 2 previous mentioned issues
and adds a test for it.
The test with the original code has a low failure frequency
to confirm the fix I had to add a time.Sleep in the body of the
CreateNetwork so to have a 100% failure
This PR is a follow up of this: https://github.com/docker/libnetwork/pull/1909
=> Fix concurrent CreateNetwork in bridge driver

network_windows.go
New versions of Windows now ship with a default network which is of type ICS. This network supports its own DNS server. We found an issue where docker was intercepting requests on these networks.
=> Fix for docker intercepting DNS requests on ICS network

ipams/windowsipam/windowsipam.go
Docker deamon fails to start when launched with --fixed-cidr parameter on windows.
This is because we are sending an invalid gateway address. Sending a gateway address was a temporary workaround which was added to prevent the daemon from crashing and is not needed any more so removing that.
=> Docker deamon doesn't work with --fixed-cidr on windows

network.go
This is to address issue https://github.com/docker/libnetwork/issues/1850 .
While  creating NetworkEndpoint , if DockerD crashes before saving the object into store there will be Veth interface leak on the host. To address this issue, updateToStore call is moved up in the code flow before creating addEndpoint. In case of failure during addEndpoint, we delete from store with defer func. So it should be taken care in the event of failure in later point.
=>  moved updateToStore call in CreateEndPoint before we call addEndpoint

bitseq/sequence.go, bitseq/sequence_test.go, bitseq/store.go, drivers/overlay/ov_network.go, drivers/overlay/ovmanager/ovmanager.go, drivers/solaris/overlay/ov_network.go, drivers/solaris/overlay/ovmanager/ovmanager.go, idm/idm.go, idm/idm_test.go, ipam/allocator.go, ipam/allocator_test.go, ipamapi/labels.go, libnetwork_internal_test.go
Cherry-pick of https://github.com/docker/libnetwork/pull/1788 for 17.09
```
git checkout -b 17.09-backport-ipam_alloc upstream/bump_17.09
git cherry-pick -s -S -x 5790b5c17ce7a6e2733ba0f4dfccced8144237e3
git cherry-pick -s -S -x 0184de8fc5074f94a74a0025ff60dab69cc442a9
git cherry-pick -s -S -x a2bcac00122a43d771af77ff060794dd02bb4a00
```
=> [17.09] Serializing bitseq alloc

diagnose/server.go, networkdb/delegate.go, networkdb/event_delegate.go, networkdb/networkdb_test.go, networkdb/networkdbdiagnose.go, networkdb/nodemgmt.go, test/networkDb/dbclient/ndbClient.go, test/networkDb/dbserver/ndbServer.go
Created method to handle the node state change with cleanup operation
associated.
Realign testing client with the new diagnostic interface.
=> Consolidate node management logic

diagnose/server.go, networkdb/delegate.go, networkdb/event_delegate.go, networkdb/networkdb_test.go, networkdb/networkdbdiagnose.go, networkdb/nodemgmt.go, test/networkDb/dbclient/ndbClient.go, test/networkDb/dbserver/ndbServer.go
Created method to handle the node state change with cleanup operation
associated.
Realign testing client with the new diagnostic interface
(cherry picked from commit b499aa926cbb558c7b390e9c3757769d07ad13ed)
=> Cleanup node management logic

Dockerfile.build
change base image tag from 1.8.4 to 1.8.5  to enable unit test in arm64 as golang:1.8.4 does not support arm64v8 . help me check @calavera @vdemeester @tomdee @erikh 
Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>
=> enable unit test in arm64

osl/namespace_linux.go, osl/sandbox_linux_test.go
This is to address issue https://github.com/moby/moby/issues/35757.
In sandbox creation we disable IPV6 config. But this causes problem in live-restore case
where all IPV6 configs are wiped out on running container. Hence extra check has been added
take care of this issue.
=> Enable IPV6 config on Sandbox creation on live-restore case

drivers/overlay/ov_network.go, drivers/overlay/overlay_test.go, ipvs/ipvs.go, ipvs/netlink.go, vendor.conf, vendor/github.com/vishvananda/netlink/handle_linux.go, vendor/github.com/vishvananda/netlink/nl/nl_linux.go
Master PR: https://github.com/docker/libnetwork/pull/1976
This vendor a fork of the netlink library that holds only the required changes for setting the netlink timeouts.
Before this change on network deletion the watchMiss go routine remains stuck on the syscall recv and leak 1 go routine and 1 thread that is executing the syscall
=> [Backport 17.06] Netlink socket timeouts

resolver.go, resolver_test.go
The Docker embedded server was not handling DNS queries of type MX for containers. They were instead being passed down to the host leading to `NXDOMAIN` responses not compliant with SMTP RFC 5321 (in case someone wanted to host a mail server in a container and deliver emails to the server). This PR adds support to respond to MX queries in a way compliant with RFC 5321 for containers.
Note that providing a full mechanism for starting a mail server in a container/service and registering MX RRs within the Docker resolver is beyond the scope of this PR.
=> Handle DNS queries of type MX

drivers/overlay/ov_network.go
Swarm mode does not really have anymore a use for the watchMiss.
Peer entries are configured at configuration time.
If the gcthresh denies the insertion the peerAdd will fail.
=> Remove watchMiss for swarm mode

sandbox_dns_unix.go, service_common_test.go
When ndots was being explicitely passed in the daemon conf
the configuration landing into the container was corrupted
e.g. options ndots:1 ndots:0
The fix just removes the user option so that is not replicated
FIXES: https://github.com/docker/libnetwork/issues/1988
=> Fix ndots configuration

endpoint.go, sandbox.go
This PR contains a fix for moby/moby#30321. There was a moby/moby#31142
PR intending to fix the issue by adding a delay between disabling the
service in the cluster and the shutdown of the tasks. However
disabling the service was not deleting the service info in the cluster.
Added a fix to delete service info from cluster and verified using siege
to ensure there is zero downtime on rolling update of a service.
=> Delete service info from cluster when service is disabled

drivers/overlay/ov_network.go, drivers/overlay/overlay_test.go
The netlink deserialize is fetching information for the link.
This require the go routine to be in the correct namespace to
succeed
=> Fix watchMiss thread context

osl/namespace_linux.go, osl/sandbox_linux_test.go
Cherry-pick of https://github.com/docker/libnetwork/pull/2043 for 17.12. I left out some unrelated commits from the PR
cherry picked from commit 76bfcb0eb14686d3c25683df22e14bc1d3b093ef, no conflicts
In sandbox creation we disable IPV6 config. But this causes problem in live-restore case
where all IPV6 configs are wiped out on running container. Hence extra check has been added
take care of this issue.
=> [17.12] Enable IPV6 config on Sandbox creation on live-restore

drivers/overlay/ov_network.go, drivers/overlay/overlay_test.go
1) (https://github.com/docker/libnetwork/pull/2047) removes watchMiss for swarm mode
2) (https://github.com/docker/libnetwork/pull/2051) set the proper thread context for watchMiss for swarm classic cases. The upgrade of the netlink library introduced further operations that requires the watchMiss to be set in the proper namespace.
=> [Backport 17.12] watchMiss fixes

networkdb/delegate.go, networkdb/event_delegate.go, networkdb/networkdb.go, networkdb/networkdb_test.go, vendor.conf, vendor/github.com/hashicorp/memberlist/README.md, vendor/github.com/hashicorp/memberlist/config.go, vendor/github.com/hashicorp/memberlist/memberlist.go, vendor/github.com/hashicorp/memberlist/net.go, vendor/github.com/hashicorp/memberlist/state.go, vendor/github.com/hashicorp/memberlist/suspicion.go, vendor/github.com/hashicorp/memberlist/transport.go, vendor/github.com/hashicorp/memberlist/util.go
- Revendoring memberlist diff: hashicorp/memberlist@v0.1.0...master
- Insert back failed nodes when join is notified by memberlist
- Delete same behavior of create, cannot delete a key already deleted
=> Memberlist revendor and optimizations

osl/namespace_linux.go, osl/sandbox_linux_test.go
In sandbox creation we disable IPV6 config. But this causes problem in live-restore case
where all IPV6 configs are wiped out on running container. Hence extra check has been added
take care of this issue.
Original PR: https://github.com/docker/libnetwork/pull/2043
=> [Backport 17.06] Enable IPV6 config on Sandbox creation on live-restore - BackPort

sandbox_dns_unix.go, service_common_test.go
Setting ndots to 0 does not allow to resolve search domains
The default will remain ndots:0 that will directly resolve
services, but if the user specify a different ndots value
just propagate it into the container
=> Fix user specified ndots option

Makefile, agent.go, cmd/diagnostic/Dockerfile.client, cmd/diagnostic/Dockerfile.dind, cmd/diagnostic/README.md, cmd/diagnostic/daemon.json, cmd/diagnostic/main.go, controller.go, diagnostic/server.go, diagnostic/types.go, networkdb/networkdb.go, networkdb/networkdb_test.go, networkdb/networkdbdiagnostic.go, test/networkDb/dbserver/ndbServer.go, test/networkDb/dummyclient/dummyClient.go
1) decode internal state of service discovery and overlay
2) remediate in case of orphan entries
3) realign naming with moby/moby api
4) GetEntry should return error if the key is under deletion (added unit test)
=> Diagnostic client

drivers/windows/labels.go, drivers/windows/windows.go
This change adds support for OutboundNAT policy to the Windows driver passed via a generic option.
=> Added OutboundNAT policy support for Windows

support.sh
filtered out ucp- containers because we already get all their data in the support dump, and they don't use overlay networking which is what we are focusing on here.  Added some formatting to container inspects to make it a little easier to read
@trapier @fcrisciani
=> Improved support script

network_windows.go
cherry-pick of https://github.com/docker/libnetwork/pull/2014 for 17.06
```
git checkout -b 17.06-icsdnsissue upstream/bump_17.06
git cherry-pick -s -S -x ba2de36fb4877b19f24c3dbe822c384887c7bca6
```
no conflicts
=> [17.06] Fix for docker intercepting DNS requests on ICS network

cmd/diagnostic/Dockerfile.dind, cmd/diagnostic/README.md, cmd/diagnostic/main.go
Usually a diagnostic session wants to check the local state
without this flag the network is joined and left every iteration
altering actually the daemon status.
Also if the diagnostic client is used against a live node, the
network leave has a very bad side effect of kicking the node
out of the network killing its internal status.
For the above reason introducing the flag -a to be explicit
so that the current state is always preserved
=> Add an explicit flag to join network in diagnostic

service_common.go
Set a limit to the max size of the transient log to avoid
filling up logs in case of issues
FIXES: https://github.com/docker/libnetwork/issues/1983
=> Limit max length transient log

drivers/overlay/ov_network.go
Signed-off-by: ZhiPeng Lu <lu.zhipeng@zte.com.cn>
I think it should be calling LinkDel to delete link device when the error of LinkByName is NULL.
ping @coolljt0725  @aboch
=> fix for #1333, calling LinkDel to delete link device when the err is NULL

network.go
Libnetwork should not delete an ingress network just because its endpoint count
drops to 1 (the IP address of the sandbox).  This addresses a regression
where the ingress sandbox could be deleted on workers when the last
container leave said sandbox.
Adding this fix will ultimately require and accompanying moby/moby fix in order to 
preserve the ability to remove the ingress network manually.  As it turns out, moby
already has the code required to remove the load balancing endpoint in the
daemon.deleteLoadBalancerSandbox() method.  Since removing the ingress network
in moby invokes the daemon.releaseIngress() function to help it, the only change 
required to reinstate ingress network removal along with this fix is to invoke 
deleteLoadBalancerSandbox() within releaseIngress().  This will …
=> Prevent ingress deletion when endpoint count == 1

bitseq/sequence.go, bitseq/sequence_test.go, ipam/allocator.go, ipam/allocator_test.go
While investigating duplicate IP issue in IPAM library the following bugs were found:
1) Race condition: IPAM library seems to assume the present of datastore to achieve atomicity. However IPAM library can be used without datastore , for eg swarmkit can use the ipam by setting the datastore to nil.  The race condition causes corruption of the bitsequence which might lead to duplicate IPs by releasing non deallocated IP bits and also cause IP leaks due to certain bit being set even though it was not supposed to be allocated.
2) Free bit logic: The logic in getAvailableBit checks for the presence of a free bit from a start bit in a block. However if the start bit is right after the last available bit, it will return the last bit in the block as the next available bit even though it is not …
=> Fix for Duplicate IP issues

ipam/allocator_test.go, ipam/parallel_test.go, vendor.conf, vendor/github.com/golang/sync/LICENSE, vendor/github.com/golang/sync/PATENTS, vendor/github.com/golang/sync/README.md, vendor/github.com/golang/sync/semaphore/semaphore.go
Added tests for swarm mode and also some new parallel tests with various subnets
=> IPAM tests

bitseq/sequence.go, bitseq/sequence_test.go, ipam/allocator.go, ipam/allocator_test.go, ipam/parallel_test.go, vendor.conf, vendor/github.com/golang/sync/LICENSE, vendor/github.com/golang/sync/PATENTS, vendor/github.com/golang/sync/README.md, vendor/github.com/golang/sync/semaphore/semaphore.go
While investigating duplicate IP issue in IPAM library the following bugs were found:
Race condition: IPAM library seems to assume the present of datastore to achieve atomicity. However IPAM library can be used without datastore , for eg swarmkit can use the ipam by setting the datastore to nil. The race condition causes corruption of the bitsequence which might lead to duplicate IPs by releasing non deallocated IP bits and also cause IP leaks due to certain bit being set even though it was not supposed to be allocated.
Free bit logic: The logic in getAvailableBit checks for the presence of a free bit from a start bit in a block. However if the start bit is right after the last available bit, it will return the last bit in the block as the next available bit even though it is not free. …
=> [Backport 17.06] Fix for Duplicate IP issues

resolver.go, resolver_test.go
This PR covers the following:
1. Implements fix for https://github.com/docker/libnetwork/issues/1664
2. Fixes a reference to members of `resp` outside null check that may lead to a null exception.
3. Unit tests involving a local DNS server that can be expanded and programmed to cover external DNS tests.
=> Retry other external DNS servers on ServFail

cmd/diagnostic/README.md, networkdb/networkdb.go, networkdb/networkdbdiagnostic.go
- Readme example was using wrong flag
- Network peers were not exposed properly
=> Fix README flag and expose orphan network peers

drivers/bridge/bridge.go, drivers/bridge/bridge_test.go, drivers/bridge/setup_firewalld.go
The CreateNetwork in the bridge driver was not able to properly
handle concurrent operations causing 2 issues:
1) crash from nil pointer exception
2) not proper handling of conflicting configuration
This commit addresses the 2 previous mentioned issues
and adds a test for it.
The test with the original code has a low failure frequency
to confirm the fix I had to add a time.Sleep in the body of the
CreateNetwork so to have a 100% failure
(cherry picked from commit bca4d8881e2d1a9dcf2527e7bf91a4184cdfb325)
=> [backport 17.06] Fix concurrent CreateNetwork in bridge driver

support.sh
This patch replaces awk with cut to workaround issues present with
running this script within ucp-dsinfo.
Signed-off-by: Kyle Squizzato <kyle.squizzato@docker.com>
=> Modify awk to use cut in check_ip_overlap

drivers/bridge/bridge.go, drivers/bridge/bridge_test.go, drivers/bridge/setup_ip_tables.go, drivers/bridge/setup_ip_tables_test.go
Carry https://github.com/docker/libnetwork/pull/1534
- - -
- This reduces complexity from O(N^2) to O(2N)
Related to docker/docker#26435
Reported as example the time measurement for creating 50 bridge networks and for pruning them.
Also because of the removal of the loop in isolateNetwork(), the timing is drastically improved:
```
CURRENT		  NEW
Creation of the 50th network:
real	0m3.035s	0m0.146s
user	0m0.004s	0m0.008s
sys	0m0.004s	0m0.000s
Creation of all 50 networks:
real	0m43.785s	0m6.931s
user	0m0.336s	0m0.324s
sys	0m0.084s	0m0.148s
Pruning of the 50 networks:
real	1m2.136s	0m7.342s
user	0m0.004s	0m0.000s
sys	0m0.008s	0m0.016s
```
=> [Carry 1534] Improve scalabiltiy of bridge network isolation rules

drivers/overlay/ostweaks_linux.go
If a sysadmin happens to have set a larger value for any of the properties which are managed by this file, they would be overridden.
The changes proposed in this PR allow a sysadmin to have preexisting property values which are larger than the values set in this file.
=> Allow for larger preset property values, do not override

networkdb/delegate.go
`handleNodeEvent` is calling `changeNodeState` which writes to various
maps on the ndb object.
Using a write lock prevents a panic on concurrent read/write access on
these maps.
Related to moby/moby#36814
=> networkdb: Use write lock in handleNodeEvent

networkdb/cluster.go, networkdb/delegate.go, networkdb/networkdb.go
Steps To Reproduce:
- 3 managers 3 workers cluster
- Stop all managers in the cluster (leave the workers running)
- Wait a minute and start all managers
Expected Results:
- All nodes converge into a single gossip cluster
Actual Results:
- The workers and the managers ended up on 2 different gossip clusters. This causes `overlay` and unpredicted networking issues between containers on the 2 different clusters.
Workaround:
- Restart "All" the workers to force re-joining the manager cluster 
or
- To avoid a restart, use the [diagnostic tool ](https://github.com/docker/libnetwork/blob/master/cmd/diagnostic/README.md)with the `/join` endpoint 
PR fix:
This PR adds a go routine that runs every minute and checks that **at least** one node from the `bootStrap` list (ie: managers nodes) is  part …
=> Adding a recovery mechanism for a split gossip cluster

iptables/iptables.go
It turns out that when running under RHEL 7.3 (and possibly other distributions), Linux can be configured with firewalld, but still run into contention on the xtables lock when performing iptables operations even though use of firewalld doesn't specify the `--wait` flag for iptables.  An example of this as seen in e2e tests is as follows:
```
Apr 10 15:24:18 tests-BUILD-28-rhel-7-3-dm-ee-test-rhel-0 dockerd[3453]: time="2018-04-10T15:24:18.405670490-04:00" level=debug msg="Firewalld passthrough: ipv4, [-t nat -I DOCKER-INGRESS -p tcp --dport 30017 -j DNAT --to-destination 172.18.0.2:30017]"
Apr 10 15:24:20 tests-BUILD-28-rhel-7-3-dm-ee-test-rhel-0 dockerd[3453]: time="2018-04-10T15:24:20.413670601-04:00" level=error msg="Failed to add ingress: setting up rule failed, [-t nat -I …
```
=> filter xtables lock warnings when firewalld is active

iptables/iptables.go
As per https://github.com/docker/libnetwork/pull/2135, add the wait time into the warning log to inform the user how long the xtables locks are being waited on.
Signed-off-by: Chris Telfer <ctelfer@docker.com>
=> Add wait time into xtables lock warning

drivers/overlay/encryption.go, drivers/overlay/ov_network.go, drivers/overlay/ovmanager/ovmanager.go
While reviewing the code for https://github.com/docker/libnetwork/issues/1765, I came across several race conditions in the overlay driver code.   These make classic read-modify-write mistakes by not holding their locks through the modifications.  This means that parallel invocations can lead to inconsistent state.
When reviewing, please look at the 3 commits individually.  They don't overlap in code, but if you look at the commit you will find an explanation for why I think there is a problem here as well as any tradeoffs I see in the proposed fix.
=> Fix race conditions in the overlay network driver

bitseq/sequence.go, ipam/allocator.go
=> Adding logs for ipam state

MAINTAINERS
- Add Abhi and Chris
- Remove inactive maintainers
=> Maintainers update

Makefile
=> Makefile: build image is a prerequisite of the shell target

controller.go, endpoint.go, resolver.go, sandbox.go, sandbox_store.go
Fix order of endpoints when there are more than two. See #2093 for details.
=> Use ordered array instead of heap for sb.endpoints

endpoint.go
Libnetwork should remove cluster service info including networkDB entries and DNS entries for container endpoints that are not part of a service as well as those that are part of a service.  This used to be the normal mode of operation.  However cluster info removal moved to sandbox.DisableService() in an effort to more gracefully handle endpoint removal from a service (which proved insufficient).  Subsequent changes that did peroperly handle graceful endpoint removal unfortunately also got rid of the newly-mandatory call to sandbox.DisableService() preventing proper cleanup for non-service container endpoints.
Signed-off-by: Chris Telfer <ctelfer@docker.com>
=> Remove non-service cluster info on sbLeave

service_linux.go
Make sure that iptables operations on ingress
are serialized.
Before 2 racing routines trying to create the ingress chain
were allowed and one was failing reporting the chain as
already existing.
The lock guarantees that this condition does not happen anymore
example log:
```
d4f707da69923fc1cbe4070efe65572cbe4b69e98ca228191fd p:0xc42144d600 nid:zgifl0o3uk6kdbn1321fe6agn skey:{3dwedosh75dk5cisy7iq3zpso 30000:80/TCP}"
Jun 07 07:07:37 master-1 dockerd[2758]: time="2018-06-07T07:07:37.133068284Z" level=debug msg="Firewalld passthrough: ipv4, [-t nat -nL DOCKER-INGRESS]"
Jun 07 07:07:37 master-1 dockerd[2758]: time="2018-06-07T07:07:37.134315246Z" level=debug msg="Firewalld passthrough: ipv4, [-t filter -nL DOCKER-INGRESS]"
Jun 07 07:07:37 master-1 dockerd[2758]: …
```
=> Possible race on ingress programming

drivers/overlay/ov_network.go
Commit bd613df2  prevented data corruption due to simultaneous driver.CreateNetwork()/driver.DeleteNetwork() by holding the network lock through the read/modify part of the operation.  However, part of the DeleteNetwork operation entails sending a message to the peerDB to tell that goroutine to flush entries on deletion.  This can lead to a deadlock where:
* driver.DeleteNetwork() starts and acquires driver.Lock()
* peerDB receives some other request (e.g. EventNotify) and blocks on driver.Lock()
* driver.DeleteNetwork() attempts a peerDB flush and blocks waiting on the synchronous peerDB operation channel
This patch fixes the issue by deferring the peerDB flush operation until after DeleteNetwork() unlocks driver.Lock().   Commit bd613df2 only modified CreateNetwork() and DeleteNetwork() …
=> Fix spurious deadlock in overlay driver

service_linux.go
backport of https://github.com/docker/libnetwork/pull/2178 for the bump18.03 branch
```
git checkout -b 18.03-backport-race-ingress upstream/bump_18.03
git cherry-pick -s -S -x 7bb62d0172f8e676388d4d78e510c4d9fd4c1d06
```
no conflicts
Make sure that iptables operations on ingress
are serialized.
Before 2 racing routines trying to create the ingress chain
were allowed and one was failing reporting the chain as
already existing.
The lock guarantees that this condition does not happen anymore
(cherry picked from commit 7bb62d0172f8e676388d4d78e510c4d9fd4c1d06)
=> [18.03] Possible race on ingress programming

support.sh
also made the heading for host iptables state clearer
this is to facilitate troubleshooting of the following error from the Docker daemon:
```
Error response from daemon:  subnet sandbox join failed for "10.0.2.0/24":  error creating vxlan interface:  file exists
```
... where the proximate cause is typically temporary `vx-` interfaces lingering in the host namespace after dockerd restart.
Signed-off-by: Trapier Marshall <trapier.marshall@docker.com>
=> support.sh: add host links

ipam/allocator_test.go, ipam/structures.go, libnetwork_internal_test.go
A part of the ipam library allows to use same subnets for 2 different networks. However this is not honored elsewhere in the whole library and leads to inconsistent behavior. The semantic is not honored for overlapping subnets as well. The request for overlapping subnets is rejected. 
This change ensures that semantics are kept consistent by rejecting requests for an already allocated pool as well. So users will not be able to create networks with already allocated subnet/overlapping subnet
=> Adding a check for subnet pool overlap

ipam/allocator.go, ipam/allocator_test.go
This patch changes the algorithm for selecting the next pool to allocate from an address space.   Previously, the list of potential subnets was fixed and the allocator always searched for an available subnet starting from the beginning of the list.  This means that as soon as libnetwork frees a network, it will likely use the same subnet range for the next network that it allocates.   There is nothing wrong with this in principle, but it does have the effect of making debugging a bit more tedious at times when subnets overlap frequently in the logs.
This patch keeps a cursor per address space pointing to the subnet to consider next for allocation and on each successful search of the predefined pools, sets it to the the following subnet.  The algorithm is robust against changing predefined …
=> Avoid reusing subnets when allocating from pools

ipam/allocator_test.go
Requsting for the same subnet pool will result in error. So modifying the test case to report error on repeated subnet pool requests.
=> Fixing the unit test for overlapping subnet

Dockerfile.build
This brings libnetwork up to date with moby/moby.
=> Dockerfile.build: Bump Go to 1.10.2

service_linux.go
backport of #2178
Make sure that iptables operations on ingress
are serialized.
Before 2 racing routines trying to create the ingress chain
were allowed and one was failing reporting the chain as
already existing.
The lock guarantees that this condition does not happen anymore
(cherry picked from commit 7bb62d0172f8e676388d4d78e510c4d9fd4c1d06)
=> [Backport 17.06] Possible race on ingress programming

network.go
Fix related to bug: https://github.com/docker/for-linux/issues/348
We should perform updateToStore(ep) after n.addEndpoint or do update twice, otherwise response from network plugin will not be written to KV storage. This results in container creation with broken network config.
Signed-off-by: Siarhei Rasiukevich <raskintech@gmail.com>
=> Fix net driver response loss on createEndpoint

networkdb/cluster.go, networkdb/networkdb.go
Backport bugfix
Signed-off-by: Dani Louca <dani.louca@docker.com>
(cherry picked from commit 744334d441587278813cddbb3f79eb12a48fad1c)
=> [backport 17.06] Adding a recovery mechanism for a split gossip cluster

controller.go, default_gateway.go, endpoint.go, endpoint_info.go, network.go, osl/namespace_linux.go, osl/sandbox.go, sandbox.go, service_common.go, service_linux.go, service_unsupported.go, service_windows.go, store.go
Docker swarm mode supports load balancing traffic to endpoints in a server using a distributed load balancing approach.  In this model, all containers a swarm network can act as load balancers for any service resident on a network that the container is present on.  This has the advantage of not requiring service traffic to cross the network twice (once to the load balancer and once to the endpoint) as in a more traditional architecture.  It also avoids dangers of having a single point of failure and the problems of having to scale the capacity of the load balancer itself.  Rather, the load balancing performance can scale as the compute power and network capacity of the scales.
The main problem with the current approach is its own strength.  It relies on distributing the load balancing …
=> Improve load balancing scalability in swarm mode

networkdb/cluster.go, networkdb/networkdb.go, networkdb/networkdb_test.go
Previous logic was not accounting that each node is
in the node list so the bootstrap nodes won't retry
to reconnect because they will always find themselves
in the node map
Added test that validate the gossip island condition
=> Adjust corner case for reconnect logic

sandbox_dns_unix.go, service_common_test.go
Addresses https://github.com/moby/moby/issues/37349
This PR has a couple of changes:
The "message" argument in assert.Equal expects a format string; the current string was not that, resulting in an incorrect message being printed;
--- FAIL: TestDNSOptions (1.28s)
Location:       service_common_test.go:92
Error:  	Not equal: "ndots:5" (expected)
!= "ndots:0" (actual)
Messages:	The option must be ndots:5 instead:%!(EXTRA string=ndots:0)
This patch removes the message altogether, because assert.Equal already prints enough information to catch the error;
--- FAIL: TestDNSOptions (1.28s)
Location:       service_common_test.go:92
Error:  	Not equal: "ndots:5" (expected)
!= "ndots:0" (actual)
This is the actual fix: `ndots:0` is a valid DNS option; previously, `ndots:0` was ignored, leading to …
=> Fix duplicate ndots:0, and improve validation

iptables/iptables.go
Backport of:
* https://github.com/docker/libnetwork/pull/2135
* https://github.com/docker/libnetwork/pull/2142
These fixes prevent libnetwork from returnning errors when iptables / firewalld outputs transient warnings while succeeding at its intended operations.
=> 17.06 backport iptables output filter

ipam/allocator_test.go
Go 1.7 added the subtest feature which can make table-driven tests much easier to run and debug. Some tests are not using this feature.
Further reading: [Using Subtests and Sub-benchmarks](https://blog.golang.org/subtests)
=> test: update tests to use sub-benchmarks

cmd/proxy/network_proxy_test.go, controller.go, drivers/overlay/ostweaks_linux.go, drvregistry/drvregistry_test.go, network.go, networkdb/networkdb_test.go, osl/kernel/knobs.go, osl/kernel/knobs_linux.go, osl/kernel/knobs_linux_test.go, osl/kernel/knobs_unsupported.go, osl/namespace_linux.go, osl/sandbox.go, sandbox.go, types/types_test.go
Refactored the ostweaks file and made it more generic to be reused.
Related to https://github.com/moby/moby/issues/8795
=> Add knobs on LB sandbox

.circleci/config.yml
Avoid confusion with the golang versioning
=> CircleCI use latest image

ipam/allocator.go, ipam/allocator_test.go, ipam/structures.go, types/types.go
This pull adds some unit tests for the changes to reject overlapping pool allocations in #2148.
=> Test overlapping pool allocation

drivers/bridge/bridge.go, drivers/bridge/bridge_store.go, drivers/ipvlan/ipvlan_endpoint.go, drivers/ipvlan/ipvlan_joinleave.go, drivers/ipvlan/ipvlan_network.go, drivers/ipvlan/ipvlan_store.go, drivers/macvlan/macvlan_endpoint.go, drivers/macvlan/macvlan_joinleave.go, drivers/macvlan/macvlan_network.go, drivers/macvlan/macvlan_store.go, drivers/overlay/encryption.go, drivers/overlay/joinleave.go, drivers/overlay/ov_endpoint.go, drivers/overlay/ov_network.go, drivers/overlay/overlay.go, drivers/windows/overlay/ov_endpoint_windows.go, drivers/windows/windows.go, drivers/windows/windows_store.go, network.go, networkdb/cluster.go, sandbox_store.go, service_linux.go
The previous code used string slices to limit the length of certain
fields like endpoint or sandbox IDs.  This assumes that these strings
are at least as long as the slice length.  Unfortunately, some sandbox
IDs can be smaller than 7 characters.   This fix addresses this issue
by systematically converting format string calls that were taking
fixed-slice arguments to use a precision specifier in the string format
itself.  From the golang fmt package documentation:
For strings, byte slices and byte arrays, however, precision limits
the length of the input to be formatted (not the size of the output),
truncating if necessary. Normally it is measured in runes, but for
these types when formatted with the %x or %X format it is measured
in bytes.
This nicely fits the desired behavior: it will …
=> Use fmt precision to limit string length

cmd/networkdb-test/dbclient/ndbClient.go, cmd/networkdb-test/testMain.go, diagnostic/types.go, networkdb/broadcast.go, networkdb/cluster.go, networkdb/delegate.go, networkdb/networkdb.go, networkdb/networkdbdiagnostic.go
Added some optimizations to reduce the messages in the queue:
1) on join network the node execute a tcp sync with all the nodes that it is aware part of the specific network. During this time before the node was redistributing all the entries. This meant that if the network had 10K entries the queue of the joining node will jump to 10K. The fix adds a flag on the network that would avoid to insert any entry in the queue till the sync happens. Note that right now the flag is set in a best effort way, there is no real check if at least one of the nodes succeed.
2) limit the number of messages to redistribute coming from a TCP sync. Introduced a threshold that limit the number of messages that are propagated, this will disable this optimization in case of heavy load.
The other commit is …
=> NetworkDB qlen optimization

networkdb/cluster.go, networkdb/networkdb.go, networkdb/networkdb_test.go
Backport of https://github.com/docker/libnetwork/pull/2200 for 18.03
```
git checkout -b 18.03-backport-networkdb-retry upstream/bump_18.03
git cherry-pick -s -S -x 843a0e4267697fbd7806f6a667621b69f0c63a43
```
cherry-pick was clean, no conflits
ping @fcrisciani @ctelfer PTAL
Previous logic was not accounting that each node is
in the node list so the bootstrap nodes won't retry
to reconnect because they will always find themselves
in the node map
Added test that validate the gossip island condition
=> [18.03] Adjust corner case for reconnect logic

cmd/networkdb-test/dbclient/ndbClient.go, cmd/networkdb-test/testMain.go, diagnostic/types.go, networkdb/broadcast.go, networkdb/cluster.go, networkdb/delegate.go, networkdb/networkdb.go, networkdb/networkdbdiagnostic.go
backport of https://github.com/docker/libnetwork/pull/2216 for the 18.03 branch
```
git checkout -b 18.03-backport-netdb-qlen-issue upstream/bump_18.03
git cherry-pick -s -S -x dd5a9eaba3974e06f7b678c6cc02c58d2e18dd30
git cherry-pick -s -S -x 5ed38221164e04c78d20f17839aab52fafd7fe88
```
cherry-pick was clean, no conflicts
=> [18.03] NetworkDB qlen optimization

osl/namespace_linux.go
backport of https://github.com/docker/libnetwork/pull/2122 for 17.06
```
git checkout -b 17.06-backport-esc-509 upstream/bump_17.06
git cherry-pick -s -S -x 618db13202f7f510dab67f54ddd879c6828eb761
```
cherry-pick was clean, no conflicts
ping @quadespresso @fcrisciani @ctelfer PTAL
=> [17.06] Updated handling of disable_ipv6 file

drivers/overlay/joinleave.go, drivers/overlay/ov_network.go, drivers/overlay/overlay.go, drivers/overlay/peerdb.go, osl/interface_linux.go
This function takes the patch offered in https://github.com/docker/libnetwork/pull/1800 and attempts to address the issues found in https://github.com/docker/libnetwork/issues/1765.  It removes a race condition documented in the issue where "re-once"ing the creation of an overlay sandbox can race with incoming join requests to cause a leak/collision with the vxlan interface.  This PR addresses said issue by removing the "re-once" pattern and replacing it with a traditional mutex+boolean initializer pattern.  This also allows removing some restore error handling by having the sandbox join/leave perform proper cleanup on error.  More information is available in the commit logs of the PR.
=> Fix overlay vxlan races

.circleci/config.yml, Makefile
`make check` will now regenerate the `.pb.go` files and fail if the results are different from what is checked into the repository.
=> Check that generated protocol buffer code is up to date

controller.go, network.go, sandbox.go
Change the sandbox IDs for the sandboxes of load-balancing endpoints to be "lb_XXXXXXXXX" where XXXXXXXXX is the first 9 characters of the network ID that this sandbox load balances for.  This makes it easier to find these sandboxes in /var/run/docker/netns and thus makes debugging easier.
Signed-off-by: Chris Telfer <ctelfer@docker.com>
=> Give LB sandboxes predictable names

Dockerfile
Gogoprotobuf has changed upstream and now generates different output.   Check out a specific commit to avoid this.
We may be able to do something like this with `go get` in 1.11 with 'module aware mode':
```
go get github.com/gogo/protobuf/protoc-gen-gogo@v1.0.0
```
=> Dockerfile: Install a fixed version of gogoprotobuf

drivers/bridge/bridge_test.go, ipam/allocator.go, ipam/allocator_test.go, ipams/builtin/builtin_unix.go, ipams/builtin/builtin_windows.go, ipamutils/utils.go, ipamutils/utils_test.go, netutils/utils_linux.go, netutils/utils_test.go
This change brings global default address pool feature into
libnetwork. Idea is to reuse same code flow and functions that were
implemented for local scope default address pool.
Function InitNetworks carries most of the changes. local scope default
address pool init should always happen only once. But Global scope
default address pool can be initialized multiple times.
=> Global Default Address Pool support

ipam/allocator.go, ipamutils/utils.go
ipamutils has two default address pool. Instead of allowing them to
be accessed directly, adding get functions so that other packages
can use get APIs.
=> Add getter function for Default Address Pools

ipam/allocator.go, ipam/allocator_test.go
Backport change to subnet allocation to avoid reallocating recently freed subnets from master to 17.06: 
* git checkout bump_17.06
* git checkout -b 17.06-backport-subnet-serial-alloc
* git cherry-pick 9756ff7ed 836813d8c
=> Backport serlialized subnet allocation to 17.06

networkdb/networkdb_test.go
```
make lint
networkdb/networkdb_test.go:88:2: should replace t.Error(fmt.Sprintf(...)) with t.Errorf(...)
networkdb/networkdb_test.go:136:2: should replace t.Error(fmt.Sprintf(...)) with t.Errorf(...)
make: *** [lint] Error 1
```
Signed-off-by: Lei Gong <lgong@alauda.io>
=> fix error when make lint

resolver_unix.go, service_linux.go
- Description for the changelog
Rolling back the port configs if failed to programIngress()
Signed-off-by: fanjiyun <fan.jiyun@zte.com.cn>
=> Rolling back the port configs if failed to programIngress()

config/config.go, sandbox_externalkey_unix.go
part of https://github.com/moby/moby/issues/37375 (in rootless mode, exec-root should be like `/run/user/4242/docker` rather than `/run/docker`)
The docker daemon needs to be modified as follows:
diff --git a/daemon/oci_linux.go b/daemon/oci_linux.go
index 00ace320df..ea7daa72df 100644
--- a/daemon/oci_linux.go
+++ b/daemon/oci_linux.go
@@ -809,7 +809,7 @@ func (daemon *Daemon) createSpec(c *container.Container) (retSpec *specs.Spec, e
s.Hooks = &specs.Hooks{
Prestart: []specs.Hook{{
Path: target,
-                                   Args: []string{"libnetwork-setkey", c.ID, daemon.netController.ID()},
+                                   Args: []string{"libnetwork-setkey", c.ID, daemon.netController.ID(), "-exec-root="+daemon.configStore.GetExecRoot()},
}},
}
}
Signed-off-by: Akihiro Suda …
=> allow propagating custom exec-root (e.g. "/run/docker") to libnetwork-setkey

drivers/windows/windows_store.go
When dockerd.exe is not stopped cleanly (such as when Windows is
restarted), the endpoints are not cleaned up. When using a transparent
network, the endpoint IPv4 address is blank. When dockerd.exe starts up
again, libnetwork restores the endpoint, which would not have been
stored on a clean shutdown of dockerd.exe. That fails because the IPv4
address is blank. This change warns instead of failing.
Signed-off-by: John Stephens <johnstep@docker.com>
=> Do not fail with an empty transparent IPv4 address

resolver.go
This addresses/alleviates https://github.com/docker/libnetwork/issues/2082 and https://github.com/docker/libnetwork/issues/2214
The new proposed limit (1024) should remediate the issue for most users.
=> Increase max concurrent requests for DNS from 100 to 1024

ipvs/ipvs.go, ipvs/netlink.go
This patch modifies the `Destination` struct so that the stats for
that destination are also reported.
=> Add `Stats` to the `Destination`

controller.go, ipvs/constants.go, network.go, osl/namespace_linux.go, osl/sandbox.go, sandbox.go, service_linux.go
This is a WIP to update the load balancing to support direct server return (DSR).  The notion, at a high level is that instead of the IPVS load balancer modifying the destination IP address of a packet, it only modifies the destination MAC address and leaves the VIP in place.   Furthermore, it avoids performing SNAT on the outgoing packet.   The tasks in a service would each be programmed with the VIP(s) as an IP alias on the loopback interface so that they can receive and accept said packet.  This requires that the stack enable IP forwarding but libnetwork sets this by default (in Linux) already for other reasons.  To round out the picture, the server must also have ARP configured so that it does not respond to ARP queries for the VIP nor attempt ARP queries with the VIP as a source …
=> Use direct server return in east-west overlay load balancing

controller.go, ipvs/constants.go, network.go, osl/namespace_linux.go, osl/sandbox.go, sandbox.go, service_linux.go
Backport the DSR overlay network load balancing mode to 18.09 branch:
* git checkout bump_18.09
* git checkout -b backport-dsr
* git cherry-pick -x d17b42a 0c76756
=> Backport DSR feature to bump_18.09

iptables/iptables.go
=> debian has iptables-legacy and iptables-nft now

iptables/iptables.go
backport of https://github.com/docker/libnetwork/pull/2285 for 18.03
addresses https://github.com/moby/moby/issues/38099
```
git checkout -b 18.03_backport_iptables_legacy upstream/bump_18.03
git cherry-pick -s -S -x 7da66eea9f68e4abc83ed2892114ec565eddd66a
```
cherry-pick was clean; no conflicts
=> [18.03 backport] debian has iptables-legacy and iptables-nft now

iptables/iptables.go
backport of https://github.com/docker/libnetwork/pull/2285 for 18.09
addresses https://github.com/moby/moby/issues/38099
```
git checkout -b 18.09_backport_iptables_legacy upstream/bump_18.09
git cherry-pick -s -S -x 7da66eea9f68e4abc83ed2892114ec565eddd66a
```
cherry-pick was clean; no conflicts
=> [18.09 backport] debian has iptables-legacy and iptables-nft now

Dockerfile, drivers/overlay/encryption.go, drivers/overlay/ov_utils.go, drivers/overlay/overlay.go, drivers/overlay/overlayutils/utils.go
This PR chnages allow user to configure VxLAN UDP
port number. By default we use 4789 port number. But this commit
will allow user to configure port number during swarm init.
VxLAN port can't be modified after swarm init.
=> VXLAN UDP Port configuration support

service_common.go
**- What I did**
Do not add IP to name records for aliases so IP to name resolution will always reply container name.
**- How I did it**
Send ipMapUpdate = false to addSvcRecords function so it will not add IP to name records https://github.com/docker/libnetwork/blob/09e39d99d5c769cb7d167058504581d1cfc779e3/network.go#L1422-L1427
**- How to verify it**
This can be easily tested with commands:
```
docker network create --internal --attachable --driver overlay --scope swarm foo-network
docker run -it --name bar-container --rm --network foo-network nicolaka/netshoot
for i in {1..1000}
do
nslookup $(hostname -i) | grep "arpa" | grep -v "bar-container"
done
```
without this one about 100-150 / 1000 tests fails.
Fixes moby/moby#34882
=> Do not add IP to name records for aliases

netutils/utils_linux.go
Improve error if auto-selecting IP-range failed.
Issue: #2305 
[Detailed information](https://github.com/moby/moby/issues/36512)
=> Improve error if auto-selecting IP-range failed

drivers/overlay/overlayutils/utils.go
Looks like concurrent reads should be possible, so use a RWMutex instead of Mutex.
=> Use sync.RWMutex for VXLANUDPPort

network.go, networkdb/cluster.go
It is possible that the node is not yet present in
the node list map. In this case just print a warning
and return. The next iteration would be fine
=> Fix possible nil pointer exception

default_gateway.go, network.go, networkdb/cluster.go
backport of https://github.com/docker/libnetwork/pull/2325 for 18.03
relates to https://github.com/moby/moby/issues/38618
```
git checkout -b 18.03_backport_fix_crash upstream/bump_18.03
git cherry-pick -s -S -x 1954e1c4b2cbdac2ef851acba12ead3ff6791290
```
cherry-pick was clean; no conflicts
It is possible that the node is not yet present in
the node list map. In this case just print a warning
and return. The next iteration would be fine
=> [18.03 backport] Fix possible nil pointer exception

default_gateway.go, network.go, networkdb/cluster.go
backport of https://github.com/docker/libnetwork/pull/2325 for 18.09
relates to https://github.com/moby/moby/issues/38618
```
git checkout -b 18.09_backport_fix_crash upstream/bump_18.09
git cherry-pick -s -S -x 1954e1c4b2cbdac2ef851acba12ead3ff6791290
```
cherry-pick was clean; no conflicts
It is possible that the node is not yet present in
the node list map. In this case just print a warning
and return. The next iteration would be fine
=> [18.09 backport] Fix possible nil pointer exception

drivers/overlay/overlayutils/utils.go
Minor changes following review of the engine pull request
for this feature;
- Remove the name of the function from the error message as it's not a debug message.
- Add the valid range to the error message, so that a user has sufficient information to address the problem.
- Update GoDoc for the function to describe the default port, and valid port-ranges.
=> Touch-up error-message and godoc for ConfigVXLANUDPPort

Dockerfile
I'll backport this to the release branches (which use Go 1.10). Perhaps bump master to Go 1.11 after that
=> Bump Go to 1.10.7

Dockerfile, default_gateway.go, network.go
backport of https://github.com/docker/libnetwork/pull/2320 for the 17.06 branch
```
git checkout -b 17.06_backport_fix_build upstream/bump_17.06
git cherry-pick -s -S -x fd6be31abb9a44a61286cbc4671519086cc313cb
```
=> [17.06 backport] Fix gosimple, and update to Golang 1.10.7

Dockerfile
backport of https://github.com/docker/libnetwork/pull/2332 for the 18.09 branch
ping @fcrisciani ptal
=> [18.09 backport] Bump Go to 1.10.7

agent.go
This fixes a problem where the agent on a controller is stopped when a node leaves a swarm and is never restarted. By adding a check to see if the agent is nil the agent init routine will run and the other checks that guard against multiple agents will still function as intended. Here's some more information about how this problem presents itself https://github.com/docker/for-linux/issues/495.
=> Fix for problem where agent is stopped and does not restart

drivers/bridge/setup_ip_forwarding.go
I found typo when I explore source code. If this PR is not appropriate, feel free to close.
=> Typo in drivers/bridge/setup_up_forwarding.go

drivers_experimental_linux.go, drivers_linux.go
IPVLAN driver had been retained in experimental for multiple releases
with the requirement to have a proper L3 control-plane (such as BGP) to
go along with it which will make this driver much more useful. But
based on the community feedback,
https://github.com/moby/moby/issues/21735, am proposing to move this
driver out of experimental.
=> Moving IPVLAN driver out of experimental

iptables/iptables.go
This reverts commit 7da66eea9f68e4abc83ed2892114ec565eddd66a.
Libnetwork should only use the iptables binary. Iptables v1.8 and above
uses the nftables backend. The translations for all the rules used by
libnetwork is supported by the new iptables binary.
=> Revert "debian has iptables-legacy and iptables-nft now"

iptables/iptables.go
reverts https://github.com/docker/libnetwork/pull/2287 (backport of https://github.com/docker/libnetwork/pull/2285)
relates to https://github.com/moby/moby/issues/38099
same as https://github.com/docker/libnetwork/pull/2343
This reverts commit 5a2b0bd6a1e13562c6711c6a5c1f22c97a0ffac3, reversing
changes made to c2b3907ffccf3ffc6a5c19bbda08620b140cbe84.
=> [18.03] Revert "Merge pull request #2287 from thaJeztah/18.03_backport_iptables_legacy"

iptables/iptables.go
reverts https://github.com/docker/libnetwork/pull/2286 (backport of https://github.com/docker/libnetwork/pull/2285)
relates to https://github.com/moby/moby/issues/38099
same as https://github.com/docker/libnetwork/pull/2343
This reverts commit f27ba28f7510103b118b54ae7fbfa00e8a3ed1ad, reversing
changes made to 6da50d1978302f04c3e2089e29112ea24812f05b.
=> [18.09 backport] Revert "Merge pull request #2286 from thaJeztah/18.09_backport_iptables_legacy"

ipvs/ipvs.go, ipvs/ipvs_test.go, ipvs/netlink.go
GetConfig and SetConfig allow to change the IPVS connection timeouts for TCP, TCPFIN and UDP
We vendor libnetwork's ipvs library into kubernetes and we would like to change the default IPVS timeouts (and probably make them configurable).
It's my first PR in this repository, so of course don't hesitate to let me know if things should be done differently. I'm also happy to create an issue if necessary.
=> IPVS: Add support for GetConfig/SetConfig

docs/networkdb.md, networkdb/cluster.go
This documentation addition is based on reading the code in the `networkdb` directory.
=> Add NetworkDB docs

drivers/windows/overlay/ov_endpoint_windows.go, drivers/windows/overlay/peerdb_windows.go
When multiple networks are present in a Swarm Cluster, multiple peerAdd or peerDelete calls are an issue for different remote endpoints. These threads are updating the remote endpoint to HNS parallelly. In 2016 HNS code base, we don't have synchronization around remoteEndpoint addition and deletion. So serializing the peerAdd and peerDelete calls from docker network driver.
=> Adding synchronization around peerAdd and peerDelete to prevent network connectivity issue

drivers/windows/overlay/ov_endpoint_windows.go, drivers/windows/overlay/peerdb_windows.go
When multiple networks are present in a Swarm Cluster, multiple peerAdd or peerDelete calls are an issue for different remote endpoints. These threads are updating the remote endpoint to HNS parallelly. In 2016 HNS code base, we don't have synchronization around remoteEndpoint addition and deletion. So serializing the peerAdd and peerDelete calls from docker network driver.
=> cherry-pick #2356

drivers/windows/overlay/joinleave_windows.go
=> Print proper error log when peerAdd fails

drivers/windows/overlay/joinleave_windows.go
=> Cherry-pick #2357 : Adding error log if peerAdd fails

agent.go
backport of https://github.com/docker/libnetwork/pull/2307 for the  18.09 branch
=> [18.09 backport] Cleanup the cluster provider when the agent is closed

agent.go
backport of https://github.com/docker/libnetwork/pull/2307 for the 18.03 branch
=> [18.03 backport] Cleanup the cluster provider when the agent is closed

drivers/windows/overlay/ov_endpoint_windows.go, drivers/windows/overlay/ov_network_windows.go, drivers/windows/port_mapping.go, drivers/windows/windows.go, portallocator/portallocator.go, portallocator/portallocator_windows.go, portmapper/mapper.go, portmapper/mapper_linux.go, portmapper/mapper_windows.go, portmapper/proxy_windows.go
For overlay, l2bridge, and l2tunnel, if the user does not specify a host port, windows driver will select a random port for them.  This matches linux behavior.
For ics and nat networks the windows OS will choose the port.
=> (windows) Pick a random host port if the user does not specify a host port. 

drivers/windows/overlay/ov_endpoint_windows.go, drivers/windows/overlay/ov_network_windows.go, drivers/windows/port_mapping.go, drivers/windows/windows.go, portallocator/portallocator_windows.go, portmapper/mapper.go, portmapper/mapper_linux.go, portmapper/mapper_windows.go, portmapper/proxy_windows.go
For overlay, l2bridge, and l2tunnel, if the user does not specify a host port, windows driver will select a random port for them.  This matches linux behavior.
For ics and nat networks the windows OS will choose the port.
=> [18.09 BACKPORT] Pick a random host port if the user does not specify a host port.

drivers/windows/port_mapping.go, drivers/windows/windows.go
We were using a different key for the port mapper.
During AllocatePorts, the portbindings hostIP was nil.  So, the key to the port mapper was <HostIP:nil, host port, etc...>
However, during ReleasePorts, the portbindings hostIP was 0.0.0.0.  So, the key to port mapper was <HostIP:0.0.0.0, host port, etc...>
Since thoe HostIP was different (nil vs 0.0.0.0), we never removed the entry from the port mapper.  This resulted in us leaking all the port bindings in port mapper.
=> Forcing a nil IP specified in PortBindings to IPv4zero (0.0.0.0).

drivers/windows/port_mapping.go, drivers/windows/windows.go
backport of https://github.com/docker/libnetwork/pull/2376 for 18.09
=> [18.09 backport] Forcing a nil IP specified in PortBindings to IPv4zero (0.0.0.0).

controller.go
Only increment Endpoint count for --config-only networks when the respective --config-from inherited network has been successfully created
Fixes - https://github.com/moby/moby/issues/35101#issuecomment-334732993
=> Clean up --config-only networks after --config-from networks have ungracefully exited

libnetwork_test.go
Splitting this change from https://github.com/docker/libnetwork/pull/2118
This test was producing error messages due to missing endpoints
in the plugin API;
```
=== RUN   TestValidRemoteDriver
ERRO[0039] error getting capability for valid-network-driver due to NetworkDriver.GetCapabilities: 404 page not found
```
=> Fix TestValidRemoteDriver GetCapabilities errors

network.go, resolver.go, resolver_test.go
RFC434 states that DNS Servers should be case insensitive
This commit makes sure that all DNS queries will be translated
to lower ASCII characters and all svcRecords will be saved in
lower case to abide by the RFC
Fixes - https://github.com/moby/moby/issues/21169
=>     Make DNS records and queries case-insensitive

controller.go, firewall_linux.go
This allows the `--iptables=false` argument to the `dockerd` to work correctly
by checking if IPTables is enabled before creating the user filter rules
in the controller.
This probably fixes: 
- #2158 
- https://github.com/moby/moby/issues/35777
- https://github.com/docker/for-linux/issues/136
and possibly more. I didn't dig too deep.
=> controller: Check if IPTables is enabled for arrangeUserFilterRule

Dockerfile, Makefile, controller.go
Also fixes issue reported by ineffassign
taken from https://github.com/docker/libnetwork/pull/2385
=> [18.09 backport] remove gosimple - package is gone and it's not important

controller.go
backport of https://github.com/docker/libnetwork/pull/2373 for 18.09
The endpoint count for --config-only networks
was being incremented even when the respective --config-from
inherited network failed to create a network
This was due to a variable shadowing problem with err causing
the deferred function to not execute correctly.
Using the same err variable across the entire function fixes
the issue
Fixes: moby/moby#35101
=> [18.09 backport] Correctly clean up --config-only networks

libnetwork_test.go
backport of https://github.com/docker/libnetwork/pull/2364
This test was producing error messages due to missing endpoints
in the plugin API;
```
=== RUN   TestValidRemoteDriver
ERRO[0039] error getting capability for valid-network-driver due to NetworkDriver.GetCapabilities: 404 page not found
```
=> [18.09 backport] Fix TestValidRemoteDriver GetCapabilities errors

resolver_unix.go, service_linux.go
Signed-off-by: fanjiyun <fan.jiyun@zte.com.cn>
This is a backport of PR #2069
git cherry-pick db50782482a148e9a06e46a236a37e5f6e560e8a Merged cleanly
CC: @arkodg @joeabbey
=> Backporting PR #2069 to bump_18.09

libnetwork_test.go
backport of https://github.com/docker/libnetwork/pull/2364
This test was producing error messages due to missing endpoints
in the plugin API;
```
=== RUN   TestValidRemoteDriver
ERRO[0039] error getting capability for valid-network-driver due to NetworkDriver.GetCapabilities: 404 page not found
```
=> [18.03 backport] Fix TestValidRemoteDriver GetCapabilities errors

docs/design.md
I was reading over the description of the Endpoint and it struck me as a bit odd: 
`An Endpoint can belong to *only one* network but may only belong to *one* Sandbox.`
I just wanted to rephrase it so that it's clear that an Endpoint has a one to one relationship with the Sandbox and a Network. If that is not the case, then I'm sorry for proposing the change. I'm only just starting to take a deeper dive into Docker networking.
=> Change wording for Endpoint description

cmd/proxy/main.go, cmd/proxy/network_proxy_test.go, portmapper/mapper.go, portmapper/proxy.go, types/types.go, vendor.conf, vendor/github.com/ishidawataru/sctp/GO_LICENSE, vendor/github.com/ishidawataru/sctp/ipsock_linux.go, vendor/github.com/ishidawataru/sctp/sctp.go, vendor/github.com/ishidawataru/sctp/sctp_linux.go, vendor/github.com/ishidawataru/sctp/sctp_unsupported.go
closes https://github.com/docker/libnetwork/pull/2370
This commit updates the vendored ishidawataru/sctp and adapts its used
types.
Signed-off-by: Sascha Grunert <sgrunert@suse.com>
=> [carry 2370] Update sctp package

networkdb/cluster.go, networkdb/delegate.go, networkdb/networkdb.go
Backport of #2216 to 17.06.  This should be considered a starting point.  Behaves as expected.  Needs further review from a logic standpoint.
```
git checkout -b 17.06-netdb-qlen-issue origin/bump_17.06
git cherry-pick -sx 5ed38221164e04c78d20f17839aab52fafd7fe88
```
|Location|Conflict Reason|Resolution|
|--|--|--|
|`networkdb/broadcast.go:113`,`networkdb/broadcast.go:171`|`node` was removed by #2216. `nDB.config.NodeName` changed to `nDB.config.NodeID` via #1936 and was then removed in #2216|"ours". Keeping this message in since I don't know when and why it became unnecessary. See https://github.com/docker/libnetwork/pull/2216/commits/5ed38221164e04c78d20f17839aab52fafd7fe88#r200441648. Decision to leave this in amenable to further research into why it was removed with #2216, which …
=> [Backport 17.06] NetworkDB qlen optimization

controller.go
splitting this of https://github.com/docker/libnetwork/pull/2118, but a similar change was already merged in https://github.com/docker/libnetwork/pull/2183, which had a nice description so I blatantly copied that 😂 
moby/moby commit https://github.com/moby/moby/commit/b27f70d45 (https://github.com/moby/moby/pull/36119) wraps the ErrNotFound error returned when
a plugin cannot be found, to include a backtrace.   This changes the type of the error, so contoller.loadIPAMDriver no longer converts it to a
ibnetwork plugin.NotFoundError.
This is a similar patch as was merged in aacec8e1adb71934c7fa56404c024eb74ad7fdc0 (https://github.com/docker/libnetwork/pull/2183)
=> controller.loadIPAMDriver: Unwrap error type returned by PluginGetter

drivers/bridge/netlink_deprecated_linux_rawsockaddr_data_int8.go, drivers/bridge/netlink_deprecated_linux_rawsockaddr_data_uint8.go
Add riscv64 build tags to unbreak the build. If needed I can rename the files cause they are not arm specific (even before this pr).
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>
=> bridge: add riscv64 build tags

Dockerfile, Makefile, controller.go, resolver.go
Also fixes issue reported by ineffassign
Signed-off-by: Tibor Vass <tibor@docker.com>
We have some other PRs to merge to 17.06 and without this it won't build.
=> [17.06 backport] remove gosimple - package is gone and it's not important

drivers/windows/windows.go, drivers_windows.go
In windows we have supported these two additional types since RS1.
Internal network allows inter container connectivity with support for host/container communication.
Private network allows just inter container connectivity.
This PR enables these two networking modes on windows
=> Add support for Internal and Private network types on windows

vendor.conf, vendor/github.com/gogo/protobuf/go.mod, vendor/github.com/gorilla/mux/go.mod, vendor/github.com/vishvananda/netns/README.md, vendor/github.com/vishvananda/netns/netns_linux.go, vendor/golang.org/x/crypto/go.mod, vendor/golang.org/x/sys/go.mod
Signed-off-by: Tibor Vass <tibor@docker.com>
cc @tonistiigi 	@carlosedp I'm surprised this was not needed for https://github.com/moby/moby/pull/39423 or was it an oversight?
=> vendor: update netns to 7109fa855

Dockerfile, drivers/bridge/setup_ip_tables.go, drivers/overlay/ostweaks_linux.go, drivers/windows/windows.go, network.go, osl/namespace_linux.go, resolvconf/resolvconf_test.go
backport of https://github.com/docker/libnetwork/pull/2408 for the 18.09 branch
note that 18.09 is not yet running on Go 1.12, so we might want to hold off until that is merged (work in progress PR to move to 1.11; https://github.com/docker/engine/pull/168)
I'll add "WIP", but we can decide to already merge this if we think that's good to have
=> [WIP][18.09 backport] Update to Golang 1.12.6

ipvs/netlink.go
Providing fix for hardcoded AF_INET argument in parseIP function call for "destinations". This leads to issues with IPv6 addresses thus they handled as IPv4. 
This patch provides a solution equivalent as its is used for "services":
https://github.com/herrwagner/libnetwork/blob/217bc0e7296b474afb5318b609dee673e819a00e/ipvs/netlink.go#L323-L334
=> Fix hardcoded AF_INET for IPv6 address handling

drivers/ipvlan/ipvlan_network.go, drivers/macvlan/macvlan_network.go
check value of netlabel.Internal not just it's existence
Signed-off-by: Pavel Matěja <pavel@verotel.cz>
fixes #2410
=> Macvlan network handles netlabel.Internal wrong

controller.go
The --internal netlabel is discarded now.
Signed-off-by: Pavel Matěja <pavel@verotel.cz>
Fix #2413
=> Allow network with --config-from to be --internal

iptables/iptables.go, ns/init_linux.go
It's not customary for user space programs to modprobe stuff in general. Modern distributions will autoload modules (if it is indeed a module and not built-in) on access anyway, so it's also not necessary to manually modprobe stuff.
Therefore, this replaces modprobe by actual accesses of the devices. See also https://github.com/moby/moby/pull/38930
=> Use fewer modprobes

resolver_unix.go, service_linux.go
This is a backport of #2069, which was cherry-picked from the 17.06 backport (https://github.com/docker/libnetwork/pull/2381).
> git cherry-pick -sx 2ce42422aba7b17c6822b
Clean cherry-pick (from 17.06), no issues.
=> [18.03 backport] Rolling back the port configs if failed to programIngress() (ENGCORE-914)

Dockerfile, Makefile
This allows overriding the version of Go without making modifications in the
source code, which can be useful to test against multiple versions.
For example:
make GO_VERSION=1.13beta1 build
=> Dockerfile: use GO_VERSION build-arg for overriding Go version

libnetwork_linux_test.go, ns/init_linux.go, osl/namespace_linux.go, osl/sandbox_linux_test.go, osl/sandbox_test.go, testutils/context_unix.go
Go 1.10 fixed the problem related to thread and namespaces.
Details:
golang/go@2595fe7
In few words there is no more the possibility to have a go routine
running on a thread that is another namespace.
In this commit some cleanup is done and the method SetNamespace is
being removed. This will save tons of setns syscall, that were happening
way too frequently possibily to make sure that each operation was being
done in the host namespace.
I suspect that also all the drivers not running in a different
namespace would be able to drop also the lock of the OS Thread but
will address it in a different commit
=> Syscalls reduction

libnetwork_linux_test.go, ns/init_linux.go, osl/namespace_linux.go, osl/sandbox_linux_test.go, osl/sandbox_test.go, testutils/context_unix.go
This reverts commit f755c90fb40a81dde411e5fc451bab42f85aac3a.
Testing to see if this commit caused `TestCreateParallel` to fail or not
=> Revert "Adjust LockOSThread"

Dockerfile, osl/namespace_linux.go
More info at - 
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/golang-announce/65QixT3tcmg/DrFiG6vvCwAJ
=> Bumps the GO Version to 1.12.8 which contains security fixes

ipvs/ipvs_test.go, ipvs/netlink.go
Signed-off-by: Tom Zhao <zlwangel@gmail.com>
Fix: https://github.com/docker/libnetwork/issues/2431
=> Fix parseIP error when parseIP before get AddressFamily

driverapi/driverapi.go, drivers/windows/windows.go, drivers/windows/windows_store.go, network.go
In windows HNS manages IPAM.  If the user does not specify a subnet, HNS will choose one
for them.  However, in order for the IPAM to show up in the output of "docker inspect",
we need to update the network IPAMv4Config field.
=> Updating IPAM config with results from HNS create network call.

drivers/bridge/setup_ip_forwarding.go
Follow-up email to security@docker.com, ping @justincormack
Related to https://github.com/moby/moby/issues/14041 and https://github.com/docker/libnetwork/pull/1526
By default, when Docker starts up (to configure the bridge network driver) it enables `ip_forward` flag and it sets iptables `FORWARD` chain policy to `DROP` (unless daemon's `iptables` option is set to `false`). Then Docker inserts `ACCEPT` rules based on the configured networks.
If another software (or an administrator) enables `ip_forward` flag _before_ Docker boot, iptables policy configuration is skipped, resulting in the default policy being `ACCEPT`. Docker still configures all other rules, but they have no meaning because they are only `ACCEPT` rules (and the default is `ACCEPT` anyway). These lead to a local attacker …
=> Always configure iptables forward policy

support/Dockerfile, support/support.sh
The output of "bridge fdb show" command invoked under a network
namespace is unpredicable. Sometime it returns empty, and sometime
non-stop rolling output. This perhaps is a bug in kernel
and/or iproute2 implementation. To work around, display fdb  for
each bridge.
=> Resolve "bridge fdb show" hang issue

ipvs/constants.go, ipvs/ipvs_test.go
Small change related to #2452 
Two new scheduling method constants were added for ipvs
=> weighted scheduling methods constants for ipvs

store.go
Fixed getNetworkFromStore, which returned incorrect network information - notably, the 'resolver' field was empty.
This fixes https://github.com/moby/moby/issues/38901
Signed-off-by: Espen Suenson <mail@espensuenson.dk>
=> Fixed getNetworkFromStore, which returned an incorrect struct

drivers/bridge/setup_ipv6.go
Signed-off-by: Kamil Domański <kamil@domanski.co>
Currently the error message `Could not add route to IPv6 network %s via device %s` obscures the cause of the issue by not logging the original error as well.
=> log the actual error when failing to add IPv6 route

sandbox_externalkey_unix.go
Signed-off-by: Grant Millar <rid@cylo.io>
Use short controller ID in setkey in order to avoid https://github.com/moby/moby/issues/39608 where using a custom exec-root which contains > 27 chars before the controller ID causes the daemon to fail starting with:
```
failed to start daemon: Error initializing network controller: error obtaining controller instance: listen unix /cylostore/sdj/9598/var/run/docker/libnetwork/b2757cb82eadaaea94aab22529663e38c3bf799369f5b578fe8a5bb4bcefe0f0.sock: bind: invalid argument
```
This happens due to hitting the UNIX_PATH_MAX limit (which is 108, ours is 115 in the example above). The patch gives us 79 chars to play with vs 27.
=> Shorten controller ID in exec-root to not hit UNIX_PATH_MAX

controller.go
Use types.MaskableError instead of doing a string comparison
=> Fix Error Check in NewNetwork

firewall_linux.go
This reverts commit 820deef78e53c49f13797a93537325a4b8d53014, reversing
changes made to 19e372a98f736c48e65563db5d7a474fa42d94b4.
=> Revert "Merge pull request #2339 from phyber/iptables-check"

controller.go, firewall_linux.go
reverts https://github.com/docker/libnetwork/pull/2339
[ENGCORE-1114]
[ENGCORE-1114]: https://docker.atlassian.net/browse/ENGCORE-1114
=> [19.03] revert controller: Check if IPTables is enabled for arrangeUserFilterRule ENGCORE-1114

config/config.go, portallocator/portallocator.go, portallocator/portallocator_freebsd.go, portallocator/portallocator_linux.go, portallocator/portallocator_test.go, portallocator/portallocator_windows.go
Also reduce the allowed port range as the total number of containers
per host is typically less than 1K.
This change helps in scenarios where there are other services on
the same host that uses ephemeral ports in iptables manipulation.
The workflow requires changes in docker engine (
moby/moby#40055) and this change. It
works as follows:
1. user can now specified to docker engine an option
--published-port-range="50000-60000" as cmdline argument or
in daemon.json.
2. docker engine read and pass this info to libnetwork via
config.go:OptionDynamicPortRange.
3. libnetwork uses this range to allocate dynamic port henceforth.
4. --published-port-range can be set either via SIGHUP or
restart docker engine
5. if --published-port-range is not set by user, a OS specific
default range is used for …
=> Allowed libnetwork caller to set ephemeral port 

Dockerfile
Golang 1.12.12
-------------------------------
full diff: https://github.com/golang/go/compare/go1.12.11...go1.12.12
go1.12.12 (released 2019/10/17) includes fixes to the go command, runtime,
syscall and net packages. See the Go 1.12.12 milestone on our issue tracker for
details.
https://github.com/golang/go/issues?q=milestone%3AGo1.12.12
Golang 1.12.11 (CVE-2019-17596)
-------------------------------
full diff: https://github.com/golang/go/compare/go1.12.10...go1.12.11
go1.12.11 (released 2019/10/17) includes security fixes to the crypto/dsa
package. See the Go 1.12.11 milestone on our issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.12.11
[security] Go 1.13.2 and Go 1.12.11 are released
Hi gophers,
We have just released Go 1.13.2 and Go 1.12.11 to address …
=> Update Golang 1.12.12 (CVE-2019-17596)

Dockerfile
backport of https://github.com/docker/libnetwork/pull/2472
Golang 1.12.12
-------------------------------
full diff: https://github.com/golang/go/compare/go1.12.11...go1.12.12
go1.12.12 (released 2019/10/17) includes fixes to the go command, runtime,
syscall and net packages. See the Go 1.12.12 milestone on our issue tracker for
details.
https://github.com/golang/go/issues?q=milestone%3AGo1.12.12
Golang 1.12.11 (CVE-2019-17596)
-------------------------------
full diff: https://github.com/golang/go/compare/go1.12.10...go1.12.11
go1.12.11 (released 2019/10/17) includes security fixes to the crypto/dsa
package. See the Go 1.12.11 milestone on our issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.12.11
[security] Go 1.13.2 and Go 1.12.11 are released
Hi …
=> [19.03 backport] Update Golang 1.12.12 (CVE-2019-17596)

Dockerfile, Makefile
Backports of:
- https://github.com/docker/libnetwork/pull/2420 Dockerfile: use GO_VERSION build-arg for overriding Go version
- https://github.com/docker/libnetwork/pull/2434 Bumps the GO Version to 1.12.8 which contains security fixes
- https://github.com/docker/libnetwork/pull/2472 Update Golang 1.12.12 (CVE-2019-17596)
=> [18.09 backport] Update Golang 1.12.12 (CVE-2019-17596)

agent.go, drivers/overlay/overlay.go
Issue - "index out of range" panic in drivers/overlay/encryption.go:539
due to a mismatch in indices between curKeys and spis due to
case where updateKeys might bail out due to an error and
not update the spis
Context - This issue can be hit when a worker node gets disconnected from the manager, for more than 1 key rotation interval (12h), that in itself its something to worry about, and even though the workloads get shifted to a new node, once the worker node reconnects, due to the issue mentioned above, causes dockerd to panic
Fix - Reconfigure keys when there is a key update failure
=> Fix panic in drivers/overlay/encryption.go

agent.go, drivers/overlay/overlay.go
backport of https://github.com/docker/libnetwork/pull/2462
Issue - "index out of range" panic in drivers/overlay/encryption.go:539
due to a mismatch in indices between curKeys and spis due to
case where updateKeys might bail out due to an error and
not update the spis
Fix - Reconfigure keys when there is a key update failure
(cherry picked from commit 4420ee92f5b3b951f98a36b2bc8144a19b560a22)
=> [18.09 backport] Fix panic in drivers/overlay/encryption.go

agent.go, drivers/overlay/overlay.go
backport of https://github.com/docker/libnetwork/pull/2462
Issue - "index out of range" panic in drivers/overlay/encryption.go:539
due to a mismatch in indices between curKeys and spis due to
case where updateKeys might bail out due to an error and
not update the spis
Fix - Reconfigure keys when there is a key update failure
(cherry picked from commit 4420ee92f5b3b951f98a36b2bc8144a19b560a22)
=> [19.03 backport] Fix panic in drivers/overlay/encryption.go

sandbox_externalkey_unix.go
backport of https://github.com/docker/libnetwork/pull/2443 for the 19.03 branch
relates to https://github.com/moby/moby/pull/39822
relates to / addresses https://github.com/moby/moby/issues/39608
=> [19.03 backport] Shorten controller ID in exec-root to not hit UNIX_PATH_MAX

endpoint.go, endpoint_test.go, sandbox_dns_unix.go, sandbox_dns_windows.go
Partially addresses moby/moby#13228
This fixes a very real usecase for me. I'd like to run an application that misbehaves if its hostname doesn't resolve to its listen address. The resolver find the hostname in `/etc/hosts` and returns only the IPv4 address.
=> etchosts: include the container's IPv6 address if available

drivers/bridge/setup_device.go
systemd and udev in their default configuration attempt to set a
persistent MAC address for network interfaces that don't have one
already ([systemd-def-link]). We set the address only after creating the
interface, so there is a race between us and udev. There are several
outcomes (that actually occur, this race is very much not a theoretical
one):
* We set the address before udev gets to the networking rules, so udev
sees `/sys/devices/virtual/net/docker0/addr_assign_type = 3`
(NET_ADDR_SET). This means there's no need to assign a different
address and everything is fine.
* udev reads `/sys/devices/virtual/net/docker0/addr_assign_type` before
we set the address, gets `1` (NET_ADDR_RANDOM), and proceeds to
generate and set a persistent address.
Old versions of udev (pre-v242, i.e. without …
=> bridge: Fix hwaddr set race between us and udev

drivers/bridge/setup_device.go
backport of https://github.com/docker/libnetwork/pull/2380 for the 19.03 branch
systemd and udev in their default configuration attempt to set a
persistent MAC address for network interfaces that don't have one
already [systemd-def-link]. We set the address only after creating the
interface, so there is a race between us and udev. There are several
outcomes (that actually occur, this race is very much not a theoretical
one):
* We set the address before udev gets to the networking rules, so udev
sees `/sys/devices/virtual/net/docker0/addr_assign_type = 3`
(NET_ADDR_SET). This means there's no need to assign a different
address and everything is fine.
* udev reads `/sys/devices/virtual/net/docker0/addr_assign_type` before
we set the address, gets `1` (NET_ADDR_RANDOM), and proceeds to …
=> [19.03 backport] bridge: Fix hwaddr set race between us and udev

drivers/bridge/bridge.go, drivers/bridge/bridge_store.go, drivers/bridge/labels.go, drivers/bridge/setup_ipv4.go
Introduce "com.docker.network.bridge.inhibit_ipv4" option to the bridge
network driver. If set, this option will prevent docker from setting or
modifying Layer-3 (IP) configuration on the bridge interface in any way.
This option should allow connecting containers to pre-existing network
segments (with e.g., pre-existing default gateways) while simultaneously
preserving our ability to communicate with the host and/or configure the
properties of the host-side container virtual network interface (e.g.,
delay/loss/jitter via netem), which can not be done using macvlan.
Also see following Moby project issue: https://github.com/moby/moby/issues/37430
=> Allow bridge net driver to skip IPv4 configuration of bridge interface

drivers/bridge/bridge.go, drivers/bridge/bridge_store.go, drivers/bridge/bridge_test.go, drivers/bridge/setup_ip_tables.go, netlabel/labels.go
This commit allows a user to specify a Host IP via the
com.docker.network.host_ipv4 label which is used as the
Source IP during SNAT for bridge networks .
The use case is for hosts with multiple interfaces and
this label can dictate which IP will be used as Source IP
for North-South traffic
In the absence of this label, MASQUERADE is used which picks the Source IP
based on Next Hop from the Route Table
Addresses: https://github.com/moby/moby/issues/30053
=> Support for com.docker.network.host_ipv4 driver label

drivers/ipvlan/ipvlan_network.go, drivers/macvlan/macvlan_network.go
Using dummy interface allows communication beween containers only if
they are running on the same node in swam.
Signed-off-by: Pavel Matěja <pavel@verotel.cz>
=> Fix internal macvlan network to work in swarm

drivers/ipvlan/ipvlan_joinleave.go, drivers/macvlan/macvlan_joinleave.go
Since docker container can be connected to combination of several
internal and external networks change of default gateway of the internal
ones breaks communication via the external ones.
This fixes only macvlan network type
Signed-off-by: Pavel Matěja <pavel@verotel.cz>
This should close #2406
=> Macvlan internal network should not change default gateway

Dockerfile, bitseq/sequence_test.go
Follow-up to https://github.com/docker/libnetwork/pull/2513, but keeping it separate so that we can cherry-pick the previous update to release branches if needed.
I'll rebase this one after https://github.com/docker/libnetwork/pull/2513 is merged
=> Dockerfile: update to Go 1.13.8

drivers/bridge/bridge_store.go
**- What I did**
When I upgrade the docker of my laptop from 19.03 to the latest master branch, docker.service startup failed with panic:
```
Feb 27 01:44:56 localhost systemd: Starting Docker Application Container Engine...
Feb 27 01:44:57 localhost dockerd: panic: interface conversion: interface {} is nil, not bool
Feb 27 01:44:57 localhost dockerd: goroutine 1 [running]:
Feb 27 01:44:57 localhost dockerd: github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge.(*networkConfiguration).UnmarshalJSON(0xc0006ee410, 0xc00097b1e0, 0x189, 0x189, 0x7f9979d15510, 0xc0006ee410)
Feb 27 01:44:57 localhost dockerd: /go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/drivers/bridge/bridge_store.go:201 +0xb9a
Feb 27 01:44:57 localhost dockerd: …
```
=> Fix InhibitIPv4 nil panic

network.go, service_common.go
Deleting a network sandbox on Linux implicitly clears OS (ipvs) load
balancer state.  Deleting an HNS network on Windows by contrast does not
inherently remove its corresponding VFP load balancers. The method to
remove load balancers belongs to the network and so must be called prior
to or while deleting a network. This commit reverts one line from
c47239d1e78950f9cc6fcab1d4e029e7df07082a, reintroducing a call to
explicitly remove backend load balancers during network removal.
Fixes #2527
Mirantis Ref: FIELD-2259
=> Cleanup VFP during overlay network removal

network.go, service_common.go
=> [18.09 backport] Cleanup VFP during overlay network removal

drivers/ipvlan/ipvlan_network.go, drivers/macvlan/macvlan_network.go
https://github.com/docker/libnetwork/pull/2419 and
https://github.com/docker/libnetwork/pull/2407
attempted to seperate out empty parent and internal for
macvlan and ipvlan networks
However it didnt pass the integration tests in moby
https://github.com/moby/moby/pull/40596 and exposed some
more plumbing that needed to be done to make sure
we separate the two things
If the -o parent is empty we create a dummylink
and if internal is set we dont add a default gateway
and make sure north-south communication cannot take place
(only east-west / container-container can)
=> Macvlan: Separate empty parent and internal

drivers/bridge/setup_ip_forwarding.go
Reverts docker/libnetwork#2450.
Fallout from changing the forwarding default policy to deny was greater than anticipated.
=> Revert "Always configure iptables forward policy"

ipams/builtin/builtin_unix.go
**- What I did**
from moby/moby#40388
> Things to fix;
> - if `base=10.123.0.0` is invalid, it should produce an error
> - if the given configuration file does not contain `default-address-pools`, it should not reset the value set on the command-line
_Originally posted by @thaJeztah in https://github.com/moby/moby/issues/40388#issuecomment-576238514_
This PR will produce an error if given an invalid address pool like `base=10.123.0.0,size=24`  (missing `/16`)
**- How I did it**
if the default address pool is invalid, `ConfigLocalScopeDefaultNetworks` will return an error, so just return the error rather than omit it and it's quite safe. 
The output likes: 
```
Mar 17 00:10:29 master dockerd[12069]: failed to start daemon: Error initializing network controller: error obtaining controller …
```
=> Fixes moby/moby#40388, produce an error with invalid address pool

agent.go, controller.go, network.go
This PR carryforwards https://github.com/moby/libnetwork/pull/2239
and incorporates the suggestions in comments to fix the NPE and
potential NPEs due to null value returned by ep.Iface()
closes https://github.com/moby/libnetwork/pull/2239
addresses https://github.com/moby/moby/issues/37506
=> Fix NPE due to null value returned by ep.Iface()

agent.go, controller.go, network.go
backport of https://github.com/moby/libnetwork/pull/2544
addresses https://github.com/moby/moby/issues/37506
This PR carryforwards https://github.com/moby/libnetwork/pull/2239
and incorporates the suggestions in comments to fix the NPE and
potential NPEs due to a null value returned by ep.Iface()
=> [19.03 backport] Fix NPE due to null value returned by ep.Iface()

controller.go, firewall_linux.go, firewall_others.go, firewall_test.go
This fix addresses https://docker.atlassian.net/browse/ENGCORE-1115
Expected behaviors upon docker engine restarts:
1. IPTableEnable=true, DOCKER-USER chain present
-- no change to DOCKER-USER chain
2. IPTableEnable=true, DOCKER-USER chain not present
-- DOCKER-USER chain created and inserted top of FORWARD
chain.
3. IPTableEnable=false, DOCKER-USER chain present
-- no change to DOCKER-USER chain
the rational is that DOCKER-USER is populated
and may be used by end-user for purpose other than
filtering docker container traffic. Thus even if
IPTableEnable=false, docker engine does not touch
pre-existing DOCKER-USER chain.
4. IPTableEnable=false, DOCKER-USER chain not present
-- DOCKER-USER chain is not created.
=> DOCKER-USER chain not created when IPTableEnable=false.

vendor.conf, vendor/github.com/moby/ipvs/netlink.go
full diff: https://github.com/moby/ipvs/compare/v1.0.0...v1.0.1
- Fix compatibility issue on older kernels (< 3.18) where the address
family attribute for destination servers do not exist
- Fix the stats attribute check when parsing destination addresses
- NetlinkSocketsTimeout should be a constant
=> vendor: update moby/ipvs v1.0.1

resolver.go
Addresses https://github.com/moby/moby/issues/41003
Addresses https://github.com/moby/moby/issues/20494#issuecomment-631339768
Commit d5e341e updated the DNS library
and updated the error handling.
Due to changes in the library, we now had to check the response itself
to check if the response was truncated (Truncated DNS replies should
be sent to the client so that the client can retry over TCP).
However, bea32b0 added an incorrect
`nil` check to fix a panic, which ignored situations where
an error was returned, but no response (for example, if we failed
to connect to the DNS server).
In that situation, the error would be ignored, and further down we
would consider the connection to have been succesfull, but the DNS
server not returning a result.
After a "successful" lookup (but no …
=> Resolver: fix error handling if we didn't receive a response

iptables/firewalld.go, iptables/iptables.go
If firewalld is running, create a new docker zone and
add the docker interfaces to the docker zone to allow
container networking for distros with Firewalld enabled
Fixes: https://github.com/moby/libnetwork/issues/2496
Debug output
```
[vagrant@centos8 ~]$ uname -a
Linux centos8 4.18.0-80.el8.x86_64 #1 SMP Tue Jun 4 09:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[vagrant@centos8 ~]$ sudo firewall-cmd --info-zone docker
docker (active)
target: ACCEPT
icmp-block-inversion: no
interfaces: docker0
sources: 
services: 
ports: 
protocols: 
masquerade: no
forward-ports: 
source-ports: 
icmp-blocks: 
rich rules: 
[vagrant@centos8 ~]$ sudo docker run -it alpine nslookup www.google.com
Server:		10.0.2.3
Address:	10.0.2.3:53
Non-authoritative answer:
Name:	www.google.com
Address: …
```
=> Add docker interfaces to firewalld docker zone

resolver.go
backport of https://github.com/moby/libnetwork/pull/2551
Addresses https://github.com/moby/moby/issues/41003
Addresses https://github.com/moby/moby/issues/20494#issuecomment-631339768
Commit d5e341e updated the DNS library
and updated the error handling.
Due to changes in the library, we now had to check the response itself
to check if the response was truncated (Truncated DNS replies should
be sent to the client so that the client can retry over TCP).
However, bea32b0 added an incorrect
`nil` check to fix a panic, which ignored situations where
an error was returned, but no response (for example, if we failed
to connect to the DNS server).
In that situation, the error would be ignored, and further down we
would consider the connection to have been succesfull, but the DNS
server not …
=> [19.03 backport] Resolver: fix error handling if we didn't receive a response

controller.go, store.go
noticed this while reviewing https://github.com/moby/libnetwork/pull/2554, so thought I'd open as a pull request
This function always returned `nil`, so we can remove the error return, and update other functions that were handling errors.
=> store.getNetworksFromStore() remove unused error return

network.go, store.go
Fixes https://github.com/docker/for-linux/issues/888
Fix 'failed to get network during CreateEndpoint' during container starting.
Change the error type to `libnetwork.ErrNoSuchNetwork`, so `Start()` in docker engine `daemon/cluster/executor/container/controller.go` will recreate the network.
Signed-off-by: Xinfeng Liu <xinfeng.liu@gmail.com>
=> Fix 'failed to get network during CreateEndpoint'

drivers/bridge/bridge.go, drivers/bridge/setup_device.go
forward-porting https://github.com/moby/libnetwork/commit/153d0769a1181bf591a9637fd487a541ec7db1e6 from bump_19.03 to master
related: https://github.com/kubernetes/kubernetes/issues/91507
quoting https://github.com/docker/docker.github.io/pull/10940#issuecomment-637437540
> In the Docker default configuration the container network interface is a virtual ethernet link going to the host (veth interface).
> In this configuration, an attacker able to run a process as root in a container can send and receive arbitrary packets to the host using the CAP_NET_RAW capability (present in the default configuration).
> 
> If IPv6 is not totally disabled on the host (via ipv6.disable=1 on the kernel cmdline), it will be either unconfigured or configured on some interfaces, but it’s pretty likely that …
=> [master] bridge: disable IPv6 router advertisements

drivers/bridge/setup_device.go
addresses https://github.com/docker/for-linux/issues/1033
Previously, failing to disable IPv6 router advertisement prevented the daemon to start.
An issue was reported by a user that started docker using `systemd-nspawn "machine"`,
which produced an error;
failed to start daemon: Error initializing network controller:
Error creating default "bridge" network: libnetwork:
Unable to disable IPv6 router advertisement:
open /proc/sys/net/ipv6/conf/docker0/accept_ra: read-only file system
This patch changes the error to a log-message instead.
=> log error instead if disabling IPv6 router advertisement failed

drivers/bridge/setup_device.go
backport of https://github.com/moby/libnetwork/pull/2563 for 19.03
addresses https://github.com/docker/for-linux/issues/1033
Previously, failing to disable IPv6 router advertisement prevented the daemon to
start.
An issue was reported by a user that started docker using `systemd-nspawn "machine"`,
which produced an error;
failed to start daemon: Error initializing network controller:
Error creating default "bridge" network: libnetwork:
Unable to disable IPv6 router advertisement:
open /proc/sys/net/ipv6/conf/docker0/accept_ra: read-only file system
This patch changes the error to a log-message instead.
=> [19.03 backport] log error instead if disabling IPv6 router advertisement failed

network.go, store.go
This is a backport of https://github.com/moby/libnetwork/pull/2554 that I'm hoping we can merge into the bump_18.09 branch. Thanks!
=> [18.09 backport] Fix 'failed to get network during CreateEndpoint

libnetwork_test.go
Trying to prevent having containerd as a dependency; see the discussion on https://github.com/moby/libnetwork/pull/2559#discussion_r434545503
There's still one use in api/types that I think we can replace, so I'll open a PR for that in moby/moby https://github.com/moby/libnetwork/blob/28277c0c98d0dba7a361d3d448975c4237625f37/vendor/github.com/docker/docker/api/types/network/network.go#L126
=> testing: remove use of docker/docker/errdefs in tests

drivers/bridge/netlink_deprecated_linux.go, drivers/bridge/setup_device.go, drivers/macvlan/macvlan_network.go, drivers/macvlan/macvlan_setup.go
All distros that are supported by Docker now have at least kernel version 3.10, so these checks should no longer be needed.
=> Skip redundant kernel version checks

.circleci/config.yml, Makefile
The "stable" option gave Docker 17.09, which is pretty old
=> CircleCI: update to Docker 19.03.12, and enable BuildKit

client/mflag/flag.go
relates to https://github.com/moby/libnetwork/pull/2559#discussion_r434545503
The homedir package was only used to print default values for flags that contained paths inside the user's home-directory in a slightly nicer way (replace `/users/home` with `~`).
Given that this is not critical, we can replace this with golang's function, which does not depend on libcontainer.
There's still one use of the homedir package in docker/docker/opts, which is used by the dnet binary (but only requires the homedir package when running in rootless mode);
https://github.com/moby/libnetwork/blob/13a4da01ec396d4bd59cc2108a7d183d7ac7fddd/cmd/dnet/dnet.go#L418-L419
calls out to `opts.ParseHost()`, which uses `homedir.GetRuntimeDir()`
https://github.com/moby/libnetwork/blob/7f60f05552dd6f88aa0a36640186fe155c47 …
=> client/mflag: remove use of docker/docker/pkg/homedir

types/types.go
These errors were not in use, so we can remove them
=> types: remove some dead code

drivers/bridge/bridge.go, drivers/bridge/bridge_test.go, drivers/bridge/port_mapping.go, drivers/bridge/setup_firewalld.go, drivers/bridge/setup_ip_forwarding.go, drivers/bridge/setup_ip_forwarding_test.go, drivers/bridge/setup_ip_tables.go, drivers/bridge/setup_ip_tables_test.go, drivers/overlay/encryption.go, drivers/overlay/filter.go, firewall_linux.go, firewall_test.go, iptables/firewalld_test.go, iptables/iptables.go, iptables/iptables_test.go, libnetwork_test.go, portmapper/mapper.go, resolver_unix.go, service_linux.go
This is mainly a rebase (with some additions) of the MR #2023 from @wrridgwa.
Original description:
> This pull request addresses this open issue moby/moby#25407
> Previously when IPv6 was enabled on Docker, ip6tables weren't manipulated to do Port Forwarding and IP masquerading. This PR addresses that in a way similar to the IPv4 implementation.
> 
> Relies on the following Moby PR to bring the EnableIPv6 flag through to libnetwork: moby/moby#35252
> 
> When combined with the Docker pull request, the fix can be verified after starting a container in bridge mode with port forwarding and IPv6 enabled:
> 
> Compare the iptables -t nat -L command with the ip6tables -t nat -L command
> Compare iptables -t filter -L command with ip6tables -t filter -L command
> Ping6 from within a running …
=> Enable IPv6 NAT (rebase of #2023)

service_linux.go
In findLBEndpointSandbox, there are a number of checks which can return an error message. The final check will cause the program to crash if the sandbox doesn't return an endpoint, as the error message calls methods on the null pointer. This patch fixes this to use the previous (valid) pointer to get information for the error message.
=> service_linux: Fix null dereference in findLBEndpointSandbox

endpoint.go, endpoint_test.go, sandbox_test.go
```
func JoinOptionPriority(ep Endpoint, prio int) EndpointOption {
return func(ep *endpoint) {
// ep lock already acquired
c := ep.network.getController()
c.Lock()
sb, ok := c.sandboxes[ep.sandboxID]
c.Unlock()
if !ok {
logrus.Errorf("Could not set endpoint priority value during Join to endpoint %s: No sandbox id present in endpoint", ep.id)
return
}
sb.epPriority[ep.id] = prio
}
}
```
maybe we don't need this parameters `ep Endpoint` ? I made some changes for this.
Relevant PRs:
[moby/moby#40974](https://github.com/moby/moby/pull/40974) (open)
[docker/cli#2529](https://github.com/docker/cli/pull/2529)(open)
Signed-off-by: fanjiyun <fan.jiyun@zte.com.cn>
=> reduce parameters for func JoinOptionPriority

service_linux.go
=> [19.03 backport] service_linux: Fix null dereference in findLBEndpointSandbox

drivers/bridge/bridge.go
Relates to https://github.com/moby/moby/issues/41774
=> Make sure IPv6 is enabled for IP6tables

cmd/proxy/proxy.go, cmd/proxy/sctp_proxy.go, cmd/proxy/tcp_proxy.go, cmd/proxy/udp_proxy.go, drivers/bridge/port_mapping.go, drivers/bridge/port_mapping_test.go, libnetwork_test.go, portmapper/mapper.go, portmapper/mapper_linux.go, portmapper/proxy.go
1. Allocate either a IPv4 and/or IPv6 Port Binding (HostIP, HostPort, ContainerIP,
ContainerPort) based on the input and system parameters
2. Update the userland proxy as well as dummy proxy (inside port mapper) to
specifically listen to either the IPv4 or IPv6 network
=> Fix IPv6 Port Forwarding for the Bridge Driver

drivers/bridge/port_mapping.go
Allow proxying IPv6 traffic to the container's IPv4 interface
if `--ipv6` is disabled and the container does not have a
IPv6 address, when the docker-proxy / `userland-proxy` is enabled
on `dockerd`
Relates to https://github.com/moby/libnetwork/issues/2607
=> Fix regression in docker-proxy

drivers/bridge/port_mapping.go
Use HostIP to decide which portmapper object to store the binding
in consistently in the allocate and release method (https://github.com/moby/libnetwork/blob/448016ef11309bd67541dcf4d72f1f5b7de94862/drivers/bridge/port_mapping.go#L208)
=> Use hostIP to decide on Portmapper version

drivers/bridge/port_mapping.go, libnetwork_test.go
Make `docker run -p 80:80` functional again on environments with kernel boot parameter `ipv6.disable=1`.
Fix moby/moby#42288
--- 
Tested on Ubuntu 21.04.
Previously, `docker run -p 80:80` with `ipv6.disable=1` was failing with an error: 
```docker: Error response from daemon: driver failed programming external connectivity on endpoint naughty_moore (038e9ed4b5ea77e1c52462d6d04ad001fbad9beb185a6511aadc217c8a271608): Error starting userland proxy: listen tcp6 [::]:80: socket: address family not supported by protocol.```
=> fix port forwarding with ipv6.disable=1

netutils/utils_linux.go, netutils/utils_test.go
Signed-off-by: Mikael Svensson <mikael.svensson@nasdaq.com>
PR for completing https://github.com/moby/moby/pull/43360 to backbort fix from https://github.com/moby/moby/pull/42598 to moby 20.10
Update to https://github.com/moby/moby/pull/43360  will happen when this is merged.
=> Only check if route overlaps routes with scope: LINK

drivers/windows/windows.go, vendor.conf, vendor/github.com/Microsoft/hcsshim/errors.go, vendor/github.com/Microsoft/hcsshim/internal/hcs/errors.go, vendor/github.com/Microsoft/hcsshim/internal/hcs/system.go, vendor/github.com/Microsoft/hcsshim/internal/hns/hnspolicy.go
Backporting: moby/moby#43634
Vendoring moby branch hcsshim for microsoft/hcsshim#1371
Full hcsshim diff: https://github.com/microsoft/hcsshim/compare/9dcb42f100215f8d375b4a9265e5bba009217a85...a11a2c44e8a4aa9d66314b1d759ef582df5ab5e8
=> [20.10] Fix for Windows port conflict with published ports in host mode for overlay.

controller.go, osl/namespace_linux.go, service_linux.go
Pull https://github.com/moby/moby/pull/43146 and
https://github.com/moby/moby/pull/43670 into 20.10
relates to #35082, moby/libnetwork#2491
Previously, values for expire_quiescent_template, conn_reuse_mode,
and expire_nodest_conn were set only system-wide. Also apply them
for new lb_* and ingress_sbox sandboxes, so they are appropriately
propagated
Signed-off-by: Ryan Barry <rbarry@mirantis.com>
=> [20.10] Apply peformance tuning to new sandboxes also

iptables/iptables.go, vendor/github.com/docker/docker/rootless/rootless.go
Fix moby/moby#43781
"Cherry-pick" https://github.com/moby/moby/pull/43793
> **- What I did** Fix:
> 
> * [No networking in rootless docker with firewalld #43781](https://github.com/moby/moby/issues/43781)
> 
> **- How I did it**
> 
> Skip firewalld management when running with RootlessKit
> 
> **- How to verify it**
> 
> ```
> sudo systemctl enable firewalld
> dockerd-rootless-setuptool.sh install -f
> docker --context=rootless run --rm alpine sh -euxc 'apk add neofetch && neofetch'
> ```
> 
> **- Description for the changelog**
> 
> libnetwork: skip firewalld management for rootless
> 
> **- A picture of a cute animal (not mandatory but encouraged)** 
> 🐧
=> [20.10] libnetwork: skip firewalld management for rootless

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, README.md
libnetwork has been merged to the main repo of Moby  (https://github.com/moby/moby/tree/master/libnetwork) since Docker 22.06.
=> README.md: repo was moved to https://github.com/moby/moby/tree/master/libnetwork

config/config.go, portallocator/portallocator.go, portallocator/portallocator_test.go
Signed-off-by: Scott Buckfelder <buckscot@amazon.com>
> **Warning**
> libnetwork was moved to https://github.com/moby/moby/tree/master/libnetwork
>
> libnetwork has been merged to the main repo of Moby since Docker 22.06.
>
> The old libnetwork repo (https://github.com/moby/libnetwork) now only accepts PR for Docker 20.10,
> and will be archived after the EOL of Docker 20.10.
Reference Issue : https://github.com/moby/moby/issues/44423
This PR backports the current behavior in moby/moby to 20.10.  The PR for master is [#43066](https://github.com/moby/moby/pull/43066)
Ran `make` and `make unit-tests`.  The unit tests had one failure that also exists in the master branch
```
--- FAIL: TestDNSOptions (0.16s)
service_common_test.go:65: assertion failed: expected [timeout:2 attempts:5 ndots:0] …
```
=> Revert: Added API to set ephemeral port allocator range

store.go
References https://github.com/moby/moby/pull/42545
> **Warning**
> libnetwork was moved to https://github.com/moby/moby/tree/master/libnetwork
>
> libnetwork has been merged to the main repo of Moby since Docker 22.06.
>
> The old libnetwork repo (https://github.com/moby/libnetwork) now only accepts PR for Docker 20.10,
> and will be archived after the EOL of Docker 20.10.
reference PR: https://github.com/moby/moby/pull/42545
I've attempted to preserve the original author of the commit for full credit to them for the solution in this PR.
One person commented in the PR that they are hitting this on 20.10; I am also hitting this issue on 20.10.10 and it would be amazing if this could be merged and included in the next v20 point release!
Please let me know if there is anything I can do to …
=> BACKPORT: libnetwork: processEndpointCreate: Fix deadlock between getSvcRecords and processEndpointCreate

network.go, service_common.go, service_windows.go
Removal of PolicyLists from Windows VFP must be performed prior to removing the corresponding HNS network. Otherwise PolicyList removal fails with HNS error `"The network was not found."`  
This ordering requirement was introduced to Windows Server 2019 in an update some time in 2020.  Have reached out to Microsoft to request additional context with respect to what OS version(s) in the change was shipped with and the rationale for the change.
Accommodate the OS sequencing requirement by delaying network deletion until after cleaning up service bindings.
This PR also:
* Introduces error logging for the affected HNS calls.
* Provides a performance improvement to Linux overlay network cleanup by making explicit service loadbalancer dataplane cleanup logic conditional to Windows (where it is …
=> Fix HNS policylist error "network not found" during network removal 

drivers/overlay/ov_network.go
- v20.10 backport of https://github.com/moby/moby/pull/43379
Operations performed on overlay network sandboxes are handled by dispatching operations send through a channel. This allows for asynchronous operations to be performed which, since they are not called from within another function, are able to operate in an idempotent manner with a known/measurable starting state from which an identical series of iterative actions can be performed.
However, it was possible in some cases for an operation dispatched from this channel to write a message back to the channel in the case of joining a network when a sufficient volume of sandboxes were operated on.
A goroutine which is simultaneously reading and writing to an unbuffered channel can deadlock if it sends a message to a channel then waits …
=> libnetwork/overlay:fix join sandbox deadlock

drivers/windows/windows.go
- v20.10 backport of https://github.com/moby/moby/pull/45211
=> d/windows: log EnableInternalDNS val after setting it

store.go
- 20.10 backport of https://github.com/moby/moby/pull/42545
- Fixes https://github.com/moby/moby/issues/46661
- Fixes #2649 
We had some hosts with quite a bit of cycling containers that ocassionally causes docker daemons to lock up. Most prominently `docker run` commands do not respond and nothing happens anymore.
Looking at the stack trace the following is at least likely sometimes a cause to that: Two goroutines g0 and g1 can race against each other:
* (g0) 1. getSvcRecords is called and calls (*network).Lock() --> Network is locked.
* (g1) 2. processEndpointDelete is called, and calls (*controller).Lock() --> Controller is locked
* (g1) 3. processEndpointDelete tries (*network).ID() which calls (*network).Lock().
* (g0) 4. getSvcRecords calls (*controller).Lock().
3./4. are deadlocked …
=> Fix deadlock between getSvcRecords and processEndpointDelete
