moby/libnetwork

driverapi/driverapi.go, drivers/bridge/bridge.go, drivers/bridge/network_test.go, sandbox/configure_linux.go, sandbox/namespace_linux.go, sandbox/sandbox.go, sandbox/sandbox_unsupported.go, sandbox/sandbox_unsupported_test.go
- Converted IP address and gateway values to be proper types
- Added unsupported implementations for sandbox and sandbox_test
=> Change IP address and gateway to use proper types

.gitignore, Makefile, README.md, circle.yml
Update Makefile to generate coverage data
Add Build Status and Coverage Badges to README
=> Test Coverage and Build Status

README.md, network.go
=> Fix typos and formatting in docs. Add Godoc badge.

cmd/readme_test/readme.go, drivers/bridge/bridge.go, drivers/bridge/setup_verify.go, error.go, libnetwork_test.go, network.go
- Added more testcases for libnetwork API testing
- Added new error types for all of libnetwork errors
- Added a test binary to test README.md code
- Fixed a bug in bridge driver where when the bridge already exists
the bridgeInterface.bridgeIPv4 is not getting initialized properly
=> Add more test cases to test libnetwork API 

Makefile, drivers/bridge/setup_verify_test.go
- Fixed the makefile which was not checking failures in test code
- Cleaned up the makefile to remove output clutter
=> Makefile fixes to check for failures

ROADMAP.md
No intent was harmed by this change (I hope).
=> Minor language cleanup in ROADMAP.md

drivers/bridge/error.go, drivers/bridge/setup_ipv4.go, pkg/portallocator/portallocator.go, portmapper/mapper.go
Signed-off-by: bin liu <liubin0329@gmail.com>
=> fix some typos

README.md, cmd/readme_test/readme.go, driverapi/driverapi.go, driverapi/driverapi_test.go, drivers/bridge/bridge.go, drivers/bridge/network_test.go, libnetwork_test.go, netutils/utils.go, netutils/utils_test.go, network.go, sandbox/configure_linux.go
- Added new getter methods
- Modified signature of Network.CreateEndpoint()
- Taken care of @mrjana comments
=> Enhance Endpoint interface

libnetwork_test.go, network.go
=> Add Network method to return list of endpoints

sandbox/sandbox_test.go
Add  TestSandboxInfoEqual in driverapi_test.go
Signed-off-by: Mingzhen Feng <fmzhen@zju.edu.cn>
=> Add TestSandboxInfoEqual in sandbox_test.go

README.md, cmd/readme_test/readme.go, cmd/test/main.go, drivers/bridge/bridge.go, drivers/bridge/error.go, libnetwork_test.go, network.go
=> Rename simplebridge to bridge

drivers/bridge/bridge.go, drivers/bridge/network_test.go
- This address one of the requirements of Issue #78
- Taken care of @mrjana  comments
=> Libnetwork bridge to handle MTU option

libnetwork_test.go, sandbox/configure_linux.go, sandbox/namespace_linux.go, sandbox/sandbox.go, sandbox/sandbox_linux_test.go, sandbox/sandbox_test.go
- Fixed an assortment of bugs in sandbox
- Added more test coverage to sandbox
- Re-enabled Bridge test case which got disabled because
lower case test case function name
=> Fix assortment of sandbox issues

libnetwork_test.go, network.go
Add methods to walk Endpoints and Networks
=> Add methods to walk Endpoints and Networks

libnetwork_test.go, network.go
=> Provide Query API for NetworkController

test/integration/README.md, test/integration/daemon-configs.bats, test/integration/daemon.cfg, test/integration/helpers.bash
Pre-reqs :
* docker machine (https://github.com/docker/machine)
* bats (https://github.com/sstephenson/bats)
* virtualbox
=> Initial bats based integration test infra for testing daemon network configs

Godeps/Godeps.json, Godeps/_workspace/src/github.com/docker/docker/pkg/homedir/homedir.go, Godeps/_workspace/src/github.com/docker/docker/pkg/homedir/homedir_test.go, Godeps/_workspace/src/github.com/docker/docker/pkg/mflag/LICENSE, Godeps/_workspace/src/github.com/docker/docker/pkg/mflag/README.md, Godeps/_workspace/src/github.com/docker/docker/pkg/mflag/example/example.go, Godeps/_workspace/src/github.com/docker/docker/pkg/mflag/flag.go, Godeps/_workspace/src/github.com/docker/docker/pkg/mflag/flag_test.go, Godeps/_workspace/src/github.com/docker/libcontainer/user/MAINTAINERS, Godeps/_workspace/src/github.com/docker/libcontainer/user/lookup.go, Godeps/_workspace/src/github.com/docker/libcontainer/user/lookup_unix.go, Godeps/_workspace/src/github.com/docker/libcontainer/user/lookup_unsupported.go, Godeps/_workspace/src/github.com/docker/libcontainer/user/user.go, Godeps/_workspace/src/github.com/docker/libcontainer/user/user_test.go, client/client.go, client/client_test.go, client/network.go
This is an experiment by modularizing the client UI handler in libnetwork while the actual UI hook to the docker chain can come from Docker Project.
=> libnetwork client

drivers/bridge/setup_ip_tables.go
- Docker PR link: https://github.com/docker/docker/pull/11526
=> Port PR #11526 to libnetwork

Godeps/Godeps.json, Godeps/_workspace/src/github.com/docker/docker/pkg/etchosts/etchosts.go, Godeps/_workspace/src/github.com/docker/docker/pkg/etchosts/etchosts_test.go, drivers.go, drivers/null/null.go, endpoint.go, libnetwork_test.go, sandbox/namespace_linux.go
Also added null driver support and update Godeps
=> Add basic /etc/hosts file management support in libnetwork

netutils/utils.go
=> Fix a minor but in utils parsing UDP/TCP ports

README.md, cmd/readme_test/readme.go, driverapi/driverapi.go, drivers/bridge/bridge.go, drivers/bridge/bridge_test.go, drivers/null/null.go, endpoint.go, libnetwork_test.go, netutils/utils.go
=> Provide API to retrieve Endpoint operational data

drivers/bridge/bridge.go, drivers/bridge/bridge_test.go, drivers/bridge/link.go, endpoint.go, libnetwork_test.go, netutils/utils.go, pkg/options/options.go
This is built on top of @fmzhen's commit (which takes care of the changes needed in bridge code) and takes care of the missing changes in test code and to change libnetwork API in endpoint.go.
=> Separate ExpsoedPorts from PortBindings

drivers/bridge/bridge.go
=> In bridge.go: Join(), Leave(), getnetwork() are not thread safe

endpoint.go, error.go, libnetwork_test.go
=> Handled endpoint delete with active containers attached to it

README.md, ROADMAP.md, docs/bridge.md, docs/design.md, docs/legacy.md, docs/overlay.md, docs/remote.md
Driver design documents are not addressed yet.
=> Updated Design, Readme and Roadmap Documents

docs/design.md
Signed-off-by: Kunal Kushwaha <kunal.kushwaha@gmail.com>
=> Small typo fixed

libnetwork_test.go
=> Cleaning up the ActiveContainer test properly

portmapper/mapper_test.go
- Removed MockProxy
- TestMapAllPortsSingleInterface is greedy and consumes a lot of time and resources and hence introduced the -test.short for all other tests except this test.
- Added UDP test
- explicit test for execProxy to satisfy code-coverage tools
=> Added more test coverage for the portmapper package

docs/remote.md, driverapi/driverapi.go, drivers/remote/driver.go
=> Fixed some convoluted texts in remote.md and fixed a remote driver bug

controller.go, error.go, libnetwork_test.go, network.go
=> NewNetwork and CreateEndpoint to validate resource name

drivers/bridge/link_test.go, netutils/utils_test.go
Add some tests
Signed-off-by: Mingzhen Feng <fmzhen@zju.edu.cn>
=> Add some tests

controller.go, error.go, libnetwork_test.go, network.go
(Requested by docker reviewer on libnetwork integration PR)
=> By ID and By Name query methods to return error

pkg/iptables/firewalld.go, pkg/iptables/iptables.go, pkg/iptables/iptables_test.go, pkg/resolvconf/dns/resolvconf.go, pkg/resolvconf/resolvconf.go
Updated resolvconf and iptables packages based on upstream
changes which we need for libnetwork rebase. There were
docker engine changes based on this so we need this to
be integrated now.
=> Update resolvconf and iptables packages

pkg/portallocator/portallocator.go, pkg/portallocator/portallocator_test.go, portmapper/mapper.go
=> Change portallocator New() method to Get()

endpoint.go, libnetwork_test.go
When an update is done to the container resolv.conf file
and it was inheriting host entries, then we should not
re-read the host entries when the container leaves and
re-joins the endpoint.
=> Fix DNS entry update issue

api/api.go, controller.go, error.go, libnetwork_test.go, network.go
- As requested by Docker committers
=> Network and Endpoint query methods to return error on not found

drivers/bridge/bridge.go, drivers/bridge/bridge_test.go, drivers/bridge/port_mapping.go, drivers/bridge/setup_ip_tables.go, drivers/bridge/setup_ipv4.go, iptables/firewalld.go, iptables/firewalld_test.go, iptables/iptables.go, iptables/iptables_test.go, libnetwork_test.go, portmapper/mapper.go, portmapper/mapper_test.go
- Port https://github.com/docker/docker/pull/12165 to libnetwork
- More tests will be added later
=> Optional Userland Proxy

docs/design.md
Signed-off-by: Brent Salisbury <brent.salisbury@docker.com>
=> fixing a link in design.md

api/api.go, api/api_test.go, api/types.go, client/network.go, cmd/dnet/dnet.go, cmd/dnet/flags.go
- Remove redundant info in request body
- Fix URLs, consistency and restrict regex
=> Changes in rest api

api/api_test.go
=> Fix test failure in api

api/api.go, api/api_test.go
=> REST API: Support query by partial id

api/api.go, api/api_test.go, client/client.go, client/client_test.go, client/network.go, client/types.go, cmd/dnet/dnet.go
Also supporting name, id & partial-id lookups for all the network
commands
=> Modified Client to make use of the corrected REST API & service endpoint support

docs/bridge.md, docs/design.md
Had problems with rebase on #185 thus created a new PR adding also #197 PR
*Added notes from dave-tucker
*Added Proofing design documentation input from dereckson
Signed-off-by: Sotiris Salloumis <sotiris.salloumis@gmail.com>
=> Proofing design and bridge documentations

drivers/bridge/bridge.go
- Currently validation is run before the processing
of well-known labels is completed.
=> In bridge, network config to be validated last

endpoint.go, sandbox/sandbox.go
Signed-off-by: Mingzhen Feng <fmzhen@zju.edu.cn>
=> fixed some typos

libnetwork_test.go
fix issue: https://github.com/docker/libnetwork/issues/181
Signed-off-by: Bao Yonglei <baoyonglei@huawei.com>
=> Fix createTestNetwork bug

sandbox/namespace_linux.go, sandbox/sandbox_linux_test.go
Loopback interface was s not brought up when wemoved
to clone method of creating namespace. e. Adding it.
Also taking care of PR R comments.
=> Loopback interface not  brought up

sandbox/namespace_linux.go
Instead of sleeping reworked the code to use recurring ticks.
Also cleaned up unnecessary defers.
=> Rework garbage collection code to use tick

network.go, sandbox/namespace_linux.go, sandbox/sandbox_linux_test.go
Fixed the remaining data races in the libnetwork code.
=> Fix miscellaneous data races

drivers/bridge/bridge.go, drivers/bridge/setup_fixedcidrv6.go, drivers/bridge/setup_ipv6.go
Ported the code over and adjusted to the setup process and the new netlink library
Fixes https://github.com/docker/docker/issues/13426
=> Fixes https://github.com/docker/docker/issues/13426

MAINTAINERS
=> Add Alessandro as a libnetwork maintainer

client/service_experimental.go
=> Fix dnet service cli help o/p

api/types.go, client/types.go
Signed-off-by: Kunal Kushwaha <kunal.kushwaha@gmail.com>
=> API struct tagged to produce proper output when marshalled #217

drivers/remote/driver.go, drivers/remote/driver_test.go, drivers/remote/messages.go
Required since #193 
Signedeoff-by: Tom Denham <tom.denham@metaswitch.com>
=> Update remote driver to use destination prefix.

drivers/remote/driver.go, drivers/remote/driver_test.go, drivers/remote/messages.go
Signed-off-by: Tom Denham <tom.denham@metaswitch.com>
=> Add static routes to the remote driver.

controller.go, endpoint.go, libnetwork_test.go, sandbox/configure_linux.go, sandbox/namespace_linux.go, sandbox/sandbox.go, sandboxdata.go, sandboxdata_test.go
Please see the commit notes for more information.
=> Add endpoint priority during join and cleanup libnetwork test code

drivers/bridge/bridge.go
- For the docker1.7.0_integ branch
=> Change in bridge EndpointOperInfo()

drivers/bridge/bridge.go, drivers/bridge/bridge_test.go, drivers/bridge/port_mapping.go, drivers/bridge/port_mapping_test.go, drivers/bridge/setup_ip_tables.go, drivers/bridge/setup_ip_tables_test.go
=> One port mapper per bridge network

libnetwork_test.go, network.go
=> duplicate endpoint error handling

api/api_test.go, drivers/bridge/bridge.go, drivers/bridge/bridge_test.go, drivers/host/host.go, drivers/host/host_test.go, drivers/null/null.go, drivers/null/null_test.go, libnetwork_test.go
=> Add restrictions for default drivers/bridge name

drivers/bridge/bridge.go, drivers/bridge/bridge_test.go, drivers/bridge/setup_ip_tables.go
=> Provide isolation b/w bridge networks

drivers/bridge/bridge.go
- lock network struct before accessing config in NetworkCreate
- reorganize locks so that we lock only what needed and when needed
- conflict method really belongs to networkConfig not bridgeNetwork
=> Minor changes in bridge.go

endpoint.go, network.go
Unless it is a forbidden error, libnetwork should not fail a forced
delete of a network and endpoint if the driver throws an error.
=> handling error condition for network and endpoint deletes

drivers/bridge/bridge.go
Currently we craete container mac address completely
randomly. But we probably need to generate based on
IP so that the mac address stays the same for a given
IP.
=> Generate container mac address based on IP

sandbox/sandbox_test.go, sandboxdata_test.go
- and check for error on sandbox.Destroy() in tests
=> Make sure sandbox files are removed after tests

docs/design.md
The comments in the code don't explain enough about what is expected of the driver, and this is arguably a better place for such an explanation.
=> Add note on EndpointInfo semantics

Godeps/Godeps.json, Godeps/_workspace/src/github.com/docker/libkv/.travis.yml, Godeps/_workspace/src/github.com/docker/libkv/LICENSE, Godeps/_workspace/src/github.com/docker/libkv/README.md, Godeps/_workspace/src/github.com/docker/libkv/libkv.go, Godeps/_workspace/src/github.com/docker/libkv/libkv_test.go, Godeps/_workspace/src/github.com/docker/libkv/script/.validate, Godeps/_workspace/src/github.com/docker/libkv/script/coverage, Godeps/_workspace/src/github.com/docker/libkv/script/travis_consul.sh, Godeps/_workspace/src/github.com/docker/libkv/script/travis_etcd.sh, Godeps/_workspace/src/github.com/docker/libkv/script/travis_zk.sh, Godeps/_workspace/src/github.com/docker/libkv/script/validate-gofmt, Godeps/_workspace/src/github.com/docker/libkv/store/consul/consul.go, Godeps/_workspace/src/github.com/docker/libkv/store/consul/consul_test.go, Godeps/_workspace/src/github.com/docker/libkv/store/etcd/etcd.go, Godeps/_workspace/src/github.com/docker/libkv/store/etcd/etcd_test.go, Godeps/_workspace/src/github.com/docker/libkv/store/helpers.go, Godeps/_workspace/src/github.com/docker/libkv/store/mock/mock.go, Godeps/_workspace/src/github.com/docker/libkv/store/store-test.go, Godeps/_workspace/src/github.com/docker/libkv/store/store.go, Godeps/_workspace/src/github.com/docker/libkv/store/zookeeper/zookeeper.go, Godeps/_workspace/src/github.com/docker/libkv/store/zookeeper/zookeeper_test.go, datastore/datastore.go, datastore/mock_store.go, network.go
=> Replace swarm store with libkv

api/api.go, api/api_test.go, api/types.go, client/client_service_test.go, client/client_test.go, client/network.go, client/service.go, client/types.go, cmd/dnet/dnet.go, endpoint.go, endpoint_info.go, error.go, libnetwork_test.go
=> Rework service UI

config/config.go, config/config_test.go, netlabel/labels.go
=> support for daemon labels

api/api.go
=> workaround to a minor bug in mux which filters out empty query

client/client_test.go, client/service.go
=> Add implementation for lookupContainerID

bitseq/sequence.go, bitseq/sequence_test.go, bitseq/store.go, datastore/datastore.go, idm/idm.go, idm/idm_test.go, ipam/allocator.go, ipam/allocator_test.go, ipam/contract.go, ipam/store.go, netutils/utils.go, types/types.go, types/types_test.go
Provides a new ip address management package for multi host networking
=> ipam and idm for multi host

bitseq/sequence.go, bitseq/store.go, idm/idm.go
=> Fix datastore value handling in bitseq

endpoint_info.go
=> Fix endpoint ip data-store sync issue

controller.go, endpoint.go, etchosts/etchosts.go, etchosts/etchosts_test.go, network.go
This PR brings experimental service discovery to libnetwork
=> Service discovery lite

store.go
=> Ignoring locally scoped endpoints/networks from distributed delete

sandboxdata.go
=> removed a duplicate and incorrect unlock

sandbox/neigh_windows.go
=> Fixing a windows compile error in docker during vendor-in

store.go
Not super necessary, but more clean.
Signed-off-by: David Calavera <david.calavera@gmail.com>
=> Remove extra conditional.

Godeps/Godeps.json, Godeps/_workspace/src/github.com/vishvananda/netns/netns_linux.go, Godeps/_workspace/src/github.com/vishvananda/netns/netns_linux_arm64.go
Update to the latest netns to get build fixes for arm64.
@hqhq: FYI
=> netns: Update to latest for arm64

docs/overlay.md
Signed-off-by: Matt Bentley <mbentley@mbentley.net>
=> Fixed URL used by curl in overlay readme

endpoint.go, libnetwork_test.go, sandbox/interface_linux.go, sandbox/sandbox.go, sandbox/sandbox_linux_test.go
=> Endpoint to expose interfaces' statistics

sandbox/interface_linux.go
- When invoked from docker, endpoint.Statistics() returns
the statistics of the host's interfaces.
Issue is tracked down to ioutil.ReadFile(). For some
reason even if invoked from inside the sandbox netns,
it ends up reading the stats file from the default netns,
when invoked from docker.
If same operation is run from inside a dedicated binary,
it works as expected.
- Replacing it with exec.Command("cat", <file>) solves the issue
=> Endpoint interface stats read fails when invoked from docker

Godeps/Godeps.json, Godeps/_workspace/src/github.com/vishvananda/netns/netns_linux_arm.go
=> Updating to latest netns to fix amd64 / RPI issues

endpoint.go, libnetwork_test.go, sandbox/namespace_linux.go, sandbox/sandbox.go, sandbox/sandbox_linux_test.go
- Reworked implementation for docker_1.7.0_integ branch
=> Interface Statistics() API

docs/overlay.md
=> small typo in the requirements

drivers/overlay/ov_utils.go, drivers/overlay/overlay.go
=> Use IANA assigned VXLAN port

docs/Vagrantfile, docs/vagrant.md
Just a bit of documentation which I think can help other folks trying to get a feel for things.
Contains a Vagrantfile that I stuck in the same directory, might be better somewhere.
=> Some users docs with a Vagrant setup

portallocator/portallocator.go
fix file descriptor leak of "/proc/sys/net/ipv4/ip_local_port_range"
=> fix file descriptor leak of ".../ip_local_port_range"

sandbox/interface_freebsd.go, sandbox/namespace_unsupported.go, sandbox/neigh_freebsd.go, sandbox/sandbox_freebsd.go, sandbox/sandbox_unsupported.go
Signed-off-by: Alexey Guskov <lexag@mail.ru>
=> make libnetwork compile on freebsd (again)

client/network.go
There is check in docker TestSuit. This check-in in with reference of [PR #14626](https://github.com/docker/docker/pull/14626)
Signed-off-by: Kunal Kushwaha <kunal.kushwaha@gmail.com>
=> Reduced the two spaces for network help

api/api.go, api/api_test.go
- So that it will not discard empty query fields
=> Pass proper regex to mux for query fields

libnetwork_test.go, sandboxdata.go
The controller sandboxes hashmap is not being protected by a lock
while deleting it in `LeaveAll` call. This may result in a race
whereby any other read access that happens with the lock held is
also vulnerable to return random sandbox data which could result
in totally unpredictable behavior.
Also as part of the fix check if `s.endpoints` is empty and log an
error in `rmEndpoint` so that we don't bring down the process
for this unexpected error.
=> Fix data race in controller sandboxes

drivers/bridge/bridge.go, drivers/bridge/netlink_deprecated_linux.go, netutils/utils.go
- We have more than one function doing the same thing
=> Reorganize MAC generation functions

drivers/bridge/bridge.go
The way kernel modules are loaded could lead to false warnings. This PR fixes it.
@mavenugo @dave-tucker This is the continuation of the PR #341 (I don't know what happened with my initial branch, sorry about this). I followed your advices and updated my patch.
@dave-tucker as you said, checking /proc/sys/net/bridge is a good way to do, as we can see in https://github.com/torvalds/linux/blob/f760b87f8f12eb262f14603e65042996fe03720e/net/bridge/br_netfilter_hooks.c
=> Fix module loading return.

drivers/bridge/setup_ip_forwarding.go, drivers/bridge/setup_ipv4.go, drivers/bridge/setup_ipv6.go
fixes #405
Signed-off-by: Tomas Kral <tomas.kral@gmail.com>
=> write to /proc/sys/net/ipv4/ip_forward only if is not already enabled

Godeps/Godeps.json, Godeps/_workspace/src/github.com/vishvananda/netlink/nl/nl_linux.go, Godeps/_workspace/src/github.com/vishvananda/netlink/nl/route_linux.go, Godeps/_workspace/src/github.com/vishvananda/netlink/route_linux.go
=> Updated Godeps to the latest vishvanandha/netlink

drivers/overlay/ov_utils.go
Signed-off-by: Santhosh Ram Manohar <santhosh@docker.com>
=> Pass the vxlan port in network endian order

drivers/overlay/ov_network.go
The current lazy network sandbox initialization code has a race
in that if multiple go routines race to join the network the second
and subsequent go routines might try to use the sandbox before it is
fully initialized. Fix this by blocking the go routines in once.Do
calls and also take of care of rolling back properly in case of
error.
=> Fix racy joinSandbox behavior

netutils/utils.go
- It was doing unnecessary things.
=> Simplify NetworkOverlaps function

drivers/bridge/netlink_deprecated_linux_armppc64.go, drivers/bridge/netlink_deprecated_linux_notarm.go
Signed-off-by: Srini Brahmaroutu <srbrahma@us.ibm.com>
=> Adding ppc64le build tag to compile on IBM Power

sandbox/namespace_linux.go
Since panicking on setns failure affects daemon
availability convert them to error log messages.
=> Do not panic on setns failure

sandbox/namespace_linux.go
Because it doesn't mean anything.
Signed-off-by: David Calavera <david.calavera@gmail.com>
=> Do not print the word `nil` in a log.

osl/namespace_linux.go
Signed-off-by: David Calavera <david.calavera@gmail.com>
=> Cherry-picking #482 to master

sandbox/namespace_windows.go, sandbox/sandbox_freebsd.go, sandbox/test_freebsd.go, sandbox/test_windows.go
=> Do not import testing in the main binary.

drivers/bridge/bridge_test.go, drivers/bridge/setup_ipv4_test.go
=> Fix go fmt errors in the build

bitseq/sequence.go
- incorrect handling during datastore write
Fixes #495 
=> Fix bitsequence set()

drivers/bridge/bridge_test.go
There were two pending PRs with package level
changes but no source level conflicts. This got
merged because git cannot detect this.
=> Fix CI failure due to conflicting merges

osl/namespace_linux.go
Signed-off-by: Shijiang Wei <mountkin@gmail.com>
=> remove the useless get netns code in createNetworkNamespace

api/api.go, api/types.go, controller.go, endpoint.go, libnetwork_test.go, osl/namespace_linux.go, osl/namespace_unsupported.go, osl/namespace_windows.go, sandbox.go
This address a part of https://github.com/docker/libnetwork/issues/429.
=> Support to provide external key to sandbox

libnetwork_test.go
=> Fix CI failure due to mistaken imports

config/config.go, config/config_test.go, controller.go
=> Limit valid object names

Godeps/Godeps.json, Godeps/_workspace/src/github.com/docker/libkv/README.md, Godeps/_workspace/src/github.com/docker/libkv/libkv.go, Godeps/_workspace/src/github.com/docker/libkv/libkv_test.go, Godeps/_workspace/src/github.com/docker/libkv/store/consul/consul.go, Godeps/_workspace/src/github.com/docker/libkv/store/consul/consul_test.go, Godeps/_workspace/src/github.com/docker/libkv/store/etcd/etcd.go, Godeps/_workspace/src/github.com/docker/libkv/store/etcd/etcd_test.go, Godeps/_workspace/src/github.com/docker/libkv/store/store.go, Godeps/_workspace/src/github.com/docker/libkv/store/zookeeper/zookeeper.go, Godeps/_workspace/src/github.com/docker/libkv/store/zookeeper/zookeeper_test.go, Godeps/_workspace/src/github.com/docker/libkv/testutils/utils.go, datastore/datastore.go
=> Update libkv to latest commit

.gitignore
Docker-DCO-1.1-Signed-off-by: Phil Estes <estesp@linux.vnet.ibm.com> (github: estesp)
=> Add cmd/dnet/dnet binary to .gitignore

osl/interface_linux.go
Fixes #485
The code previously relied on an uninteded side effect. When the
interface name was set, this causes the interface to come up
prematurely. Once that side effect was removed, routes could
no longer be set.
This change ensures that routes are only set after the interface
is brought up.
ping @mrjana @mavenugo ptal
=> Set interfaces routes after the interface is up

endpoint_info.go
Fixes #545
Signed-off-by: Tom Denham <tom@tomdee.co.uk>
=> Remove unwanted lock

bitseq/sequence.go, bitseq/sequence_test.go
=> Allow to set bits in a range in bitseq

default_gateway.go, endpoint.go, sandbox.go
=> Serialize the endpoint join/leave at the sandbox level

README.md, controller.go
=> Fix outdated docs and comments

network.go
=> Fixed a bug in AuxAddresses handling in libnetwork core

drivers/overlay/joinleave.go, drivers/overlay/ov_endpoint.go, drivers/overlay/ov_network.go, drivers/overlay/ov_serf.go, drivers/overlay/peerdb.go
Added the subnet construct in the overlay driver. Bridge and the vxlan dev will be created per subnet.
=> Support for multiple subnets in a overlay network

drivers/overlay/ov_serf.go
There were some unconditional debug logging in serf.
Removed them and made then go through logrus writers
based on what error level the log string contains.
=> Remove unconditional serf debug logging

cmd/dnet/dnet.go, datastore/datastore.go, datastore/datastore_test.go, drivers/bridge/bridge.go, drivers/bridge/bridge_store.go, drivers/bridge/bridge_test.go, ipam/allocator_test.go, network.go, test/integration/dnet/bridge.bats, test/integration/dnet/helpers.bash
- See commit messages for more details.
=> Make bridge driver networks persistent

api/api.go, api/api_test.go, api/types.go, client/network.go, client/types.go, cmd/dnet/dnet.go, drivers/bridge/bridge.go, drivers/bridge/bridge_test.go, drivers/bridge/labels.go, netlabel/labels.go, netlabel/labels_test.go, network.go, types/types.go, types/types_test.go
- Enable client to pass driver options via labels during network create
Deprecates #218
=> Labels support for Network Create

endpoint.go, error.go
=> Fixed a couple of error messages to address UX related comments

drivers/bridge/bridge_store.go
=> Fixed a bridge driver bug in unmarshalling DefaultBridge

sandbox.go
Currently when container has a restart policy and gets
restarted, docker does not release networking and allocate
it back. But it presents libnetwork with a new sandbox while
all the network resources are locked in the old sandbox. This
commit attempts to move all the network resources from the old
sandbox to the new sandbox when libnetwork is presented with the
new sandbox.
=> Move sandbox resources when container restarts

network.go
=> Few more fixes identified during integration

drivers/bridge/bridge_store.go, network.go
=> Default bridge need not have persistence in bridge driver

network.go
- Do not allow empty ipam type setting to overwrite default
- NetworkInfo to provide IPAM Configuration information
=> Miscellaneous changes for ipam docker integration

drivers/overlay/joinleave.go, drivers/overlay/ov_network.go
=> Fix the overlay cleanup in the multi-subnet case

Godeps/Godeps.json, Godeps/_workspace/src/github.com/docker/libkv/store/boltdb/boltdb.go
=> Update libkv godeps

controller.go, datastore/datastore.go, endpoint.go, endpoint_cnt.go, libnetwork_internal_test.go, network.go, store.go
- See commit messages for more information
=> Separate endpoint count into a different object

ipam/allocator.go, ipam/store.go
Added a check to see if address space is valid in
addrSpaces map before accessing it.
=> Check if address space valid in getStore

Vagrantfile
=> Updated Vagrant with the latest UX

default_gateway.go, default_gateway_freebsd.go, default_gateway_linux.go, default_gateway_windows.go
=> Made use of map[string]string for nw options in default-gateway impl

docs/ipam.md, ipamapi/contract.go, network.go
=> IPAM driver documentation

controller.go
=> Initializing generic to emtpy map

api/api.go, api/api_test.go, api/types.go, client/network.go, client/types.go, controller.go, network.go
=> Changed Labels to DriverOpts

controller.go, libnetwork_internal_test.go
-  As it got accidentally broken by another commit
Closes #659 
=> Fix ipam state cleanup logic

Vagrantfile
Thanks @runseb for catching the issue.
=> Fixed Vagrantfile to use systemd script

sandbox.go, sandbox_store.go, test/integration/dnet/bridge.bats, test/integration/dnet/run-integration-tests.sh
Please see commit messages for more information
=> Make sandbox cleanup robust for ungraceful exits

datastore/datastore.go
=> Fix the daemon panic on consul server restart

drivers/overlay/ov_network.go
=> Fixes #680

store.go
=> Dont fail the Get functions if there is an error in one of the stores

controller.go, datastore/datastore.go, hostdiscovery/hostdiscovery.go, hostdiscovery/hostdiscovery_api.go, hostdiscovery/hostdiscovery_test.go
=> Add watch retrigger when store restarts

endpoint.go
=> Fix Endpoint Unmarshal to retrieve the fields correctly

default_gateway.go
=> Default Gateway endpoints must be annonymous

endpoint.go, network.go
Currently the local containers of a global scope
network will get it's service records updated
from both a local update and global update. There
is no way to check if this is a local endpoint when
a remote update comes in via watch because we add
the endpoint to local endpoint list during join, while
the remote update happens during createendpoint.
The right thing to do is update the local endpoint list
and start watching during createndpoint and remove the watch
during delete endpoint. But this might result in the container
getting it's own record in it's /etc/hosts. So added a filtering
logic to filter out self records when updating the container's
/etc/hosts
=> Avoid duplicate entries in /etc/hosts

store.go, test/integration/dnet/helpers.bash, test/integration/dnet/overlay-consul.bats
See commit messages for more information
=> Cleanup service db for the network on last container leave

controller.go, drivers/overlay/overlay.go
=> log an error if advertise is configured with a non-local ip-address

endpoint.go, endpoint_cnt.go, sandbox.go
=> Some functions' logic cleanup

endpoint_info.go
- Retrieve from default gateway network's peer endpoint if present
=> Fix in DriverInfo()

cmd/dnet/dnet.go, drivers/bridge/bridge.go, test/integration/dnet/bridge.bats, test/integration/dnet/helpers.bash, test/integration/dnet/overlay-consul.bats
See commit messages for more info
=> Reconcile persistent state after driver config

sandbox.go, sandbox_store.go
=> set cntlr sandbox before cleaning endpoints in ungraceful restart case

docs/ipam.md
Signed-off-by: Alex Chan <alex@alexwlchan.net>
=> Tidy up the IPAM driver doc

bitseq/sequence.go, bitseq/sequence_test.go, endpoint.go, endpoint_info.go, ipam/allocator.go, network.go, sandbox.go, store.go, test/integration/dnet/multi.bats
Cherry-picking #750, #755, #761, #768, #769, #771, #777
=> Cherry-picking a few fixes for 1.9.2

etchosts/etchosts.go, etchosts/etchosts_test.go
Benchmarks comparison:
```
Benchmark results:
benchmark           old ns/op     new ns/op     delta
BenchmarkDelete     4315186       2245829       -47.96%
benchmark           old allocs     new allocs     delta
BenchmarkDelete     4645           10             -99.78%
benchmark           old bytes     new bytes     delta
BenchmarkDelete     1590011       4832          -99.70%
```
That operations was 55% of time of container stop in Docker project.
=> Speedup etchosts delete

bitseq/sequence_test.go
- Cover random allocation/deallocation
=> Increase test coverage in bitsequence

ipam/allocator.go, ipam/allocator_test.go
- Test random de-allocation of allocated addresses
which is closer to real use case
- Test db reconstruction after read from datastore
=> Improve ipam test coverage

network.go
Related to docker/docker#18626
Signed-off-by: Wen Cheng Ma <wenchma@cn.ibm.com>
=> Add IpamInfo() function to retrun ipamV4Info and ipamV6Info

drivers/overlay/filter.go, drivers/overlay/ov_network.go, drivers/overlay/ov_utils.go
=> Cherry pick overlay fixes

endpoint.go
=> Add support for Endpoint's preferred IPv6 address

README.md, cmd/readme_test/readme.go
Examples now run to completion.
Also:
- print out info (hw address) that is available when using bridge driver
- check for errors every time
Closes #837
=> Fix up example code

drivers/bridge/bridge.go, drivers/bridge/bridge_test.go, drivers/bridge/setup_ip_tables.go, drivers/bridge/setup_ip_tables_test.go, drivers/overlay/filter.go, iptables/iptables.go
- from subnet to interface
Related to https://github.com/docker/docker/issues/18297
=> Change isolation rules for multiple bridge networks

network.go
=> Add network options to NetworkInfo to display internal network option

drivers/bridge/interface.go, drivers/bridge/setup_ipv6.go, drivers/bridge/setup_verify.go
- Also remove any residual IPv6 address during the setup verify step
Related to https://github.com/docker/docker/issues/19139
=> Check if present before programming IPv6 in bridge

api/api.go, api/types.go, client/service.go, client/types.go, endpoint.go, network.go, sandbox.go, test/integration/dnet/bridge.bats, test/integration/dnet/helpers.bash
@mrjana @sanimej PTAL. 
updated with Integration Tests including shared global alias.
=> Global alias support

drivers/bridge/bridge.go, drivers/bridge/setup_ip_tables.go, libnetwork_test.go, test/integration/dnet/bridge.bats
Relates to https://github.com/docker/docker/pull/18926
=> Add internal network support for bridge networks

endpoint.go
=> EP lock shouldn't be held when trying for network lock

store.go
Race is with network.getController() method.
=> Fix race in setting ctrlr for network

CHANGELOG.md
=> Adding changelog for vendoring libnetwork into docker

CHANGELOG.md
=> changelog for v0.5.4

network.go
=> Allow network-scoped alias to be resolved for anonymous endpoint

CHANGELOG.md
=> changelog for v0.5.5

CHANGELOG.md, resolver.go, sandbox.go
=> Setup embedded DNS server correctly on container restart

config/config.go, endpoint.go, network.go, sandbox.go
Signed-off-by: Wen Cheng Ma <wenchma@cn.ibm.com>
=> Fixes some typo errors

sandbox.go
=> Enable embedded DNS server on network connect to a user defined network

sandbox.go
Related to [docker/docker #15819] (https://github.com/docker/docker/issues/15819)
=> Loopback IP shouldn't be filtered from resolv.conf in host mode

sandbox.go
Fixes [docker/docker #19448] (https://github.com/docker/docker/issues/19448)
=> Embedded DNS server should resolve only in docker network domain

resolver.go
miekg package already takes care of TCP handling. Adding the Listener code to support TCP as the transport for the DNS requests.
=> Adding TCP listener to the resolver

libnetwork_test.go, sandbox.go, sandbox_test.go
=> expose Endpoints API for a Sandbox

drivers/overlay/overlay.go
- A vestige of experimental overlay driver
=> Remove overlay's ipAllocator

network.go
=> Expose the enableIPv6 setting

CHANGELOG.md, drivers/overlay/joinleave.go, drivers/overlay/ov_endpoint.go, drivers/overlay/ov_network.go, osl/interface_linux.go, sandbox.go
=> Cherry-picking fixes for 0.6.0-rc6

drivers/bridge/setup_ip_tables.go
Related to https://github.com/docker/docker/issues/18354
=> Allow inter-network connectivity via exposed ports

store.go
=> getNetworksFromStore should return all valid networks

resolver.go
Fixes [docker/docker #20132] (https://github.com/docker/docker/issues/20132)
=> Set the compress flag for the responses from external DNS servers

store.go
=> getNetworksFromStore should not fail on inconsistent network state

CHANGELOG.md
=> changelog for v0.7.0-dev.2

resolver.go
Relates to [docker/docker #20350] (https://github.com/docker/docker/issues/20350)
=> Add a check for invalid/junk messages

Dockerfile.build, Makefile, api/api_test.go, bitseq/sequence_test.go, cmd/dnet/dnet.go, driverapi/driverapi_test.go, drivers/bridge/bridge_test.go, drivers/bridge/link_test.go, etchosts/etchosts_test.go, hostdiscovery/hostdiscovery_test.go, libnetwork_internal_test.go, libnetwork_test.go, network.go, portmapper/proxy.go
So used to this on other repository, just felt it might worth proposing :wink:.
🐸
Signed-off-by: Vincent Demeester <vincent@sbr.pm>
=> Use gofmt with -s instead of goimports

CHANGELOG.md
=> changelog for v0.7.0-dev.3

resolver.go
=> cherry-pick fixes to release/v0.6 branch (1.10.2 candidates)

CHANGELOG.md
=> Changelog for v0.6.2-rc1

Godeps/Godeps.json, Godeps/_workspace/src/github.com/vishvananda/netlink/addr_linux.go, Godeps/_workspace/src/github.com/vishvananda/netlink/addr_test.go, Godeps/_workspace/src/github.com/vishvananda/netlink/class.go, Godeps/_workspace/src/github.com/vishvananda/netlink/class_linux.go, Godeps/_workspace/src/github.com/vishvananda/netlink/link.go, Godeps/_workspace/src/github.com/vishvananda/netlink/link_linux.go, Godeps/_workspace/src/github.com/vishvananda/netlink/nl/link_linux.go, Godeps/_workspace/src/github.com/vishvananda/netlink/nl/link_linux_test.go, Godeps/_workspace/src/github.com/vishvananda/netlink/xfrm_state_linux.go
- Fixes #892
Signed-off-by: Nurahmadie <nurahmadie@gmail.com>
=> Update vishvananda/netlink package

drivers.go, drivers/bridge/bridge.go, drivers/overlay/ov_network.go, ipamapi/contract.go, ipams/null/null.go, ipams/null/null_test.go, libnetwork_test.go
Fixes https://github.com/docker/libnetwork/issues/809
=> Add nil ipam driver

docs/ipam.md
- ipam.md should only describe the contract
which is relevant to remote ipam plugins.
Addresses https://github.com/docker/libnetwork/pull/908#issuecomment-185807096
=> Fix IPAM driver documentation

api/api.go, api/api_test.go, api/types.go, client/types.go, default_gateway.go, driverapi/driverapi.go, drivers/bridge/bridge.go, drivers/bridge/bridge_test.go, drivers/bridge/labels.go, drivers/bridge/port_mapping.go, drivers/bridge/port_mapping_test.go, drivers/host/host.go, drivers/null/null.go, drivers/overlay/ov_network.go, drivers/remote/api/api.go, drivers/remote/driver.go, drivers/windows/windows.go, endpoint.go, libnetwork_internal_test.go, libnetwork_test.go, sandbox.go
=> Move exposed ports and port bindings from Endpoint to Sandbox

CHANGELOG.md
=> changelog for v0.7.0-dev.4

etchosts/etchosts.go, etchosts/etchosts_test.go
Fixes #966 
Related to [docker/docker #20997] (https://github.com/docker/docker/issues/20997)
=> Fix out of bound slice access in etchosts.go/Delete()

network.go
Related to [docker/docker #20847] (https://github.com/docker/docker/issues/20847)
=> If anonymous container has alias names use it for DNS PTR record

drivers/ipvlan/ipvlan.go, drivers/macvlan/macvlan.go
=> Adding the missing ExternalConnectivity driver methods

drivers/ipvlan/ipvlan_endpoint.go, drivers/ipvlan/ipvlan_joinleave.go, drivers/ipvlan/ipvlan_network.go, drivers/ipvlan/ipvlan_setup.go, drivers/macvlan/macvlan_endpoint.go, drivers/macvlan/macvlan_joinleave.go, drivers/macvlan/macvlan_network.go, drivers/macvlan/macvlan_setup.go
=> Use osl.InitOSContext appropriately

drivers/ipvlan/ipvlan_endpoint.go
=> ipvlan slaves must inherit the mac-address from parent

CHANGELOG.md
* Experimental support of macvlan and ipvlan drivers
=> changelog for 0.7.0-dev.6

drivers/ipvlan/ipvlan_network.go, drivers/ipvlan/ipvlan_setup.go, drivers/macvlan/macvlan_network.go, drivers/macvlan/macvlan_setup.go
- Kernel requirements are checked w/o modprobe now
=> Removed experimental drivers modprobe check

CHANGELOG.md
=> changelog for 0.7.0-dev.7

drivers/ipvlan/ipvlan_network.go, drivers/macvlan/macvlan_network.go
=> Reject a null v4 IPAM slice in exp vlan drivers

network.go
This adds label support for networks on creation.
Refs: https://github.com/docker/docker/pull/21270
=> Label support for networks on creation

CHANGELOG.md
=> Changelog for v0.7.0-dev.9

network.go
- If the flag is not set, do not query IPAM driver for IPv6 pool/addresses reservation, regardless whether they were was passed.
=> Honor enableIPv6 network flag on IP allocation

libnetwork_test.go, network.go, resolver.go, sandbox.go
Name to IPv6 is maintained in a separate hash table to keep the v4 lookup optimal.
=> Adds AAAA record handling for the embedded DNS

CHANGELOG.md
=> Changelog for v0.7.0-dev.10

drivers/bridge/bridge.go, iptables/iptables.go
- in bridge driver modprobe for br_netfilter only if EnableIPTables==true
- also call FirewalldInit() only if EnableIPTables==true
- move modprobe for nf_nat and xt_conntrack in iptables.initCheck()
Related to https://github.com/docker/docker/issues/16964
=> modprobe when needed

endpoint.go, resolver.go
=> On network disconnect clear the cached connections to external nameservers

libnetwork_internal_test.go, network.go
Related to https://github.com/docker/docker/issues/21849
=> Persist ipam driver options

bitseq/sequence.go, bitseq/store.go
I suggest to enable -race for tests also.
=> bitseq: fix races

drivers/overlay/filter.go
- When creating and programming the global overlay chain,
gracefully handle the case where the chain already exists.
Today the driver logs an Error and does not attempt to insert
the return rule if the chain is already present.
Related to https://github.com/docker/docker/issues/21912
=> Overlay driver to check for chain presence

resolver.go, sandbox.go
Increase the concurrent query limit and minor debug changes..
=> Increase concucrrent query limit

sandbox.go
=> Fix default gw logic for internal networks

osl/route_linux.go
=> Fix bug in osl.SetGatewayIPv6() function

Godeps/Godeps.json, Godeps/_workspace/src/github.com/vishvananda/netlink/Makefile, Godeps/_workspace/src/github.com/vishvananda/netlink/nl/nl_linux.go, Godeps/_workspace/src/github.com/vishvananda/netlink/xfrm_state.go, Godeps/_workspace/src/github.com/vishvananda/netlink/xfrm_state_linux.go
=> Vendor vishvananda/netlink b824519

libnetwork_internal_test.go, libnetwork_test.go, network.go, resolver.go, sandbox.go, service.go
Initial changes to support SRV records in embedded DNS. This change has the DNS handling and the required data structures and lookup function. Changes to populate the SRV records properly will be added in subsequent commits.
=> Add support for SRV query in embedded DNS

ipvs/constants.go, ipvs/ipvs.go, ipvs/ipvs_test.go, ipvs/netlink.go
This PR adds netlink support to manipulate ipvs configuration.
=> Add IPVS netlink support

Godeps/Godeps.json, Godeps/_workspace/src/github.com/vishvananda/netlink/filter.go, Godeps/_workspace/src/github.com/vishvananda/netlink/filter_linux.go, Godeps/_workspace/src/github.com/vishvananda/netlink/nl/nl_linux.go, Godeps/_workspace/src/github.com/vishvananda/netlink/nl/tc_linux.go, Godeps/_workspace/src/github.com/vishvananda/netlink/xfrm_policy.go, Godeps/_workspace/src/github.com/vishvananda/netlink/xfrm_policy_linux.go
- Brings in a couple of fixes needed by #1199 
=> Update netlink to 7995ff5

endpoint.go
Embedded DNS problem after renaming container. Step1:change in libnetwork side
#22466 
Signed-off-by: Daniel Zhang <jmzwcn@gmail.com>
=> Embedded DNS problem after renaming container. Step1:change in libnetwork side

networkdb/cluster.go, networkdb/delegate.go
=> Fix couple of panics in networkdb

service_linux.go
Also do not log error messages when adding a destination and it already
exists. This can happen because of duplicate gossip notifications.
=> Do not attempt LB plumbing until sandbox is ready

controller.go
Agent initialization wait method is added to make sure callers for
controller methods which depend on agent initialization to be complete
can wait on it.
=> Add agent initialization wait method in controller

agent.go, cluster/provider.go, cmd/dnet/dnet.go, controller.go, networkdb/cluster.go, networkdb/networkdb.go, types/types.go
=> Add support for encrypting gossip traffic

network.go
Signed-off-by: vikaschoudhary16 <choudharyvikas16@gmail.com>
=> Update address-space in ipam-info for remote driver

service_linux.go
- Moved ingress port forwarding rules to its own chain
- Flushed the chain during init
- Bound to the swarm ports so no hijacks it.
=> Move ingress port forwarding rules to a chain

controller.go
=> Set controller ingress state only if ingress

drivers/overlay/ovmanager/ovmanager.go
=> Overlay driver's NetworkAllocate method must honor driver options

agent.go, discoverapi/discoverapi.go, drivers/overlay/encryption.go, drivers/overlay/joinleave.go, drivers/overlay/ov_network.go, drivers/overlay/overlay.go, drivers/overlay/peerdb.go
- Allows network layer encryption for overlay driver
=> Overlay driver to support network layer encryption

service_linux.go
Right now if no vip is provided only when a new loadbalancer is created
we add the service records of the backend ip. But it should happen all
the time. This is to make DNS RR on service name work.
=> Add all backend ip into service records if no vip

controller.go
=> Handle the case of reseting the Cluster Provider for leave caes

drivers/overlay/ov_network.go
=> Fix panic if miss notification sock is nil

controller.go
Reverts docker/libnetwork#1233
Signed-off-by: Jana Radhakrishnan mrjana@docker.com
=> Revert "Handle the case of reseting the Cluster Provider for leave caes"

config/config.go, controller.go
=> Handle the case of reseting the Cluster Provider for leave cases

drivers/overlay/ov_network.go, drivers/overlay/ov_utils.go
=> Cleanup any stale overlay bridge with overlapping subnet in hostMode

networkdb/cluster.go
The wait in bulkSyncNode was meant for bulkSync initiator. Not for
responder. Fix the incorrect code which was also waiting unnecessarily
on response which it will never get and will eventually time out.
=> Do not wait on ack in bulksync response

agent.go
=> Resolve host-name before trying the interface-name in agent bind

networkdb/broadcast.go
When broadcasting table event, make sure the broadcast queue is
valid. The network may have been removed while in the process of sending
the broadcast.
=> Make sure broadcast queue is valid broadcasting

service_linux.go
=> Add support for ingress LB in localhost

networkdb/delegate.go
Bulksync is not meant to be rebroadcast in gossip. Stopped
rebroadcasting bulksync updates.
=> Do not rebroacast bulk sync updates

ipvs/ipvs.go
=> Make sure to close nshandle in ipvs.New

networkdb/delegate.go
=> Make sure node map is valid before accessing it

drivers_experimental_linux.go, drivers_linux.go
=> Moving MacVlan driver out of experimental

drivers/overlay/encryption.go
=> Reduce overlay encryption log noise

controller.go, endpoint.go, network.go, store.go
Related: https://github.com/docker/docker/issues/23560
=> Refresh special driver networks if present in store

sandbox.go, sandbox_dns_unix.go, sandbox_dns_windows.go, sandbox_store.go
=> Setup external DNS servers after daemon restart with live-restore

networkdb/cluster.go
Due to a slice management logic error the bulk sync for loop can go on
indefinitely and eventually leading to an OOM error. Fixed the logic so
that an infinite loop never occurs. Also changed the bulk sync wait
timeout to use a timer rather than use time.After as time.After is known
to consume a lot of memory when called in a tight loop.
=> Fix infinite loop in bulk sync

drivers/bridge/bridge.go
Because of the changes for libnetwork to support live-restore, an issue has been introduced which can be recreated following the steps below.
With the new persist changes in driver for the default bridge network, control has to chnage and Libnetwork directive must be honored so that driver state will reconcile with libnetwork state.
Steps to reproduce:
```
Step                        docker network ls | grep bridge
0) remove  local kv
1) start   1.11.2:      a44b8e3c87b7        bridge              bridge  
2) stop    1.11.2
3) start   1.12.rc1:    37a965037ed8        bridge              bridge
4) stop    1.12.rc1
5) start   1.11.2:      47986d1209a8        bridge              bridge
6) stop    1.11.2
7) start   1.12.rc1:    FAILS:
FATA[0001] Error starting daemon: Error initializing …
```
=> Bridge driver to detect and remove stale network 

networkdb/cluster.go
=> Add debugs for key change events in networkdb

osl/interface_linux.go
add three times retry to make sure interface up successful
fix #1247
=> make sure interface up successful

resolver.go
Related to [#22185](https://github.com/docker/docker/issues/22185)
UDP connections to external servers are cached. For forwarded queries there is a 4 second read timeout. But if a reply comes after 4 seconds it will remain in the socket buffer and will be received on the next call. Since it was a reply for an earlier query it should be ignored.
=> For cached connections ignore late replies after read timeout

docs/macvlan.md
=> Fixed missing v6 enable flag in macvlan doc

datastore/datastore.go
Fix https://github.com/docker/libnetwork/issues/1201 by don't lock datastore for global scope
=> Remove Lock in datastore for global scope

client/types.go, drivers/bridge/errors.go
=> Fix sanbox typo

osl/route_linux.go
=> Make sure route selected is direct

service_linux.go
While scaling down, currently we are removing the service record even if
the LB entry for the vip is not fully removed. This causes resolution
issues when scaling down. Fixed it by removing the service record only
if the LB for the vip is going away.
=> Do not remove service record while scaling down

agent.go
This has a dependency on [swarmkit #1065](https://github.com/docker/swarmkit/pull/1065)
=> Switch overlay encryption to use IPSec subsystem keys

etchosts/etchosts.go, sandbox_dns_unix.go, sandbox_externalkey_unix.go
Ensures network connections and file are closed when done writing.
See https://github.com/docker/docker/issues/24070
=> Fix file descriptor leaks

osl/interface_linux.go, osl/options_linux.go, osl/sandbox.go, sandbox.go
addresses issues such as https://github.com/docker/docker/issues/24377 and ability to ping services by its name.
=> Add Virtual-IP of an endpoint as a secondary IP

controller.go
=> Return proper error types on sandbox creation

drivers/bridge/bridge_store.go, drivers/ipvlan/ipvlan_store.go, drivers/macvlan/macvlan_store.go, drivers/overlay/overlay.go
=> Overlay driver to cleanup stale endpoints

drivers/ipvlan/ipvlan_endpoint.go
Signed-off-by: Lei Jitang <leijitang@huawei.com>
=> ipvlan: remove endpoint from network on deleting endpoint

drivers/overlay/encryption.go, drivers/overlay/joinleave.go
Fixes #1309 
Adjust MTU for AEAD ESP packets
=> Adjust container's veth MTU when encryption is on

controller.go
- Code got somehow removed by recent changes
Related to https://github.com/docker/docker/issues/24827
=> Save the controller config on config reload

controller.go
Related to https://github.com/docker/docker/issues/24778
=> Lock in isAgent() and inMaster()

resolver.go
=> Send truncated external responses to the client

sandbox.go, sandbox_store.go
relates to https://github.com/docker/docker/issues/25109
=> Better error handling in restoring sandbox states

libnetwork_test.go
Remove code as it's not being used. 
Signed-off-by: Erich Cordoba <erich.cm@yandex.com>
=> Remove commented code from libnetwork_test.go

api/api_test.go, client/network.go, cmd/dnet/dnet.go, datastore/datastore.go, docs/ipam.md, driverapi/driverapi.go, drivers/ipvlan/ipvlan_setup.go, drivers/ipvlan/ipvlan_setup_test.go, drivers/macvlan/macvlan_setup_test.go, drivers/remote/driver_test.go, hostdiscovery/hostdiscovery_test.go, ipamapi/contract.go, ipams/remote/remote_test.go, ipamutils/utils.go, ipvs/ipvs.go, libnetwork_test.go, netutils/utils.go, network.go, options/options.go, service_linux.go, types/types.go
=> use grep to find a/an misuse

controller.go, default_gateway.go, drivers/bridge/bridge.go, network.go, service_linux.go
=> fix typo in comments and log

agent.go
If not enough keys are provided to SetKeys, this may cause a panic. This
should not cause problems with the current integration in Docker 1.12.0,
but the panic might happen loading data created by an earlier version,
or data that is corrupted somehow. Add a length check to be defensive.
This is related to https://github.com/docker/docker/issues/24406.
=> Check size of keys slice

drivers/overlay/peerdb.go
Signed-off-by: Matt Bajor <matt@notevenremotelydorky.com>
=> Fix typo in error message

sandbox.go
From within the tasks of a given service, all the backends should be accessible. But the ingress network load balancer is not plumbed to the service tasks because it is unnecessary resource consumption. Hence the name resolution should prioritize returning the VIP/IPs on the user overlay network rather than the ingress network.
Related to [docker #25340] (https://github.com/docker/docker/issues/25340). But with latest libnetwork & docker master the symptom will be slightly different.
=> For service name DNS resolution prioritize IP on user overlay network

agent.go, controller.go
When the keyring length was changed and ipsec keys were introduced in later RCs of 1.12 release previous version of key rotation handling was left around to handle transition from older to newer RC. For the 1.12 release the cluster has to be initialized afresh. Removing the unused functions and adding a check for number of keys.
=> Remove unused key handling functions

network.go
=> network: fix race in read access to map

service_linux.go
The SNAT rules added for LB egress is broader and breaks load balancing
if the service is connected to multiple networks. Make it conditional
based on the subnet to which the network belongs so that the right SNAT
rule gets matched when egressing the corresponding network.
=> Add a narrower SNAT rule for LB egress

controller.go
=> Nil check ingressSandbox before deleting

netutils/utils_test.go, service_linux.go
=> Do not try LB populate on interface-less endpoint

network.go
=> Fix potential deadlock in getSvcRecords()

cluster/provider.go, cmd/dnet/dnet.go
=> Adjust WaitForDetachment to also accept networkID

drivers/bridge/bridge.go
Related to https://github.com/docker/docker/issues/26251
=> Cleanup on error in ProgramExternalConnectivity

sandbox.go
Signed-off-by: Alexander Morozov <lk4d4math@gmail.com>
=> add missed defer to unlock

drivers/bridge/bridge.go, drivers/bridge/setup_ip_tables_test.go, portmapper/mapper.go, portmapper/mapper_test.go, portmapper/mock_proxy.go, portmapper/proxy.go
libnetwork change for https://github.com/docker/docker/pull/26882 based on @aboch's comment at https://github.com/docker/docker/pull/26882#discussion_r80364014
@aboch PTAL
Signed-off-by: Antonio Murdaca <runcom@redhat.com>
=> bridge,portmapper: custom docker-proxy path

controller.go
Related to https://github.com/docker/docker/issues/26404
=> Clear ingress resources on graceful shutdown

drivers/macvlan/macvlan_network.go
Signed-off-by: Rony Weng <ronyweng@synology.com>
=> Fix macvlan private mode argument vaildation

Dockerfile.build
=> Update golang version to 1.7.1

networkdb/cluster.go
=> networkdb: fix race in access to nodes len

Godeps/Godeps.json, Godeps/_workspace/src/github.com/docker/docker/pkg/plugingetter/getter.go, Godeps/_workspace/src/github.com/docker/docker/pkg/term/term_windows.go, cmd/ovrouter/ovrouter.go, config/config.go, controller.go, driverapi/driverapi.go, drivers/ipvlan/ipvlan_test.go, drivers/macvlan/macvlan_test.go, drivers/overlay/overlay_test.go, drvregistry/drvregistry.go, ipamapi/contract.go
Signed-off-by: Anusha Ragunathan <anusha@docker.com>
=> Update plugingetter import path.

iptables/iptables.go
Fixes #1484 
Related to https://github.com/docker/docker/issues/27063
=> Check for presence before installing forward rules

endpoint.go
Related to https://github.com/docker/docker/issues/24637, https://github.com/docker/docker/issues/27157
=> Do not update hosts file with internal networks endpoint IP

iptables/iptables.go, service_linux.go
Signed-off-by: Alessandro Boch aboch@docker.com
=> Block non exposed port traffic on ingress nw interfaces

docs/design.md
Modify the serial number which begins from 1 instead of from 0.
Signed-off-by: yuexiao-wang wang.yuexiao@zte.com.cn
=> Modify the serial number for design document

datastore/datastore.go, discoverapi/discoverapi.go, docs/macvlan.md, drivers/macvlan/macvlan_endpoint.go, drivers/macvlan/macvlan_network.go, drivers/macvlan/macvlan_setup.go, endpoint.go, error.go, network.go, resolvconf/resolvconf.go
=> fix nits in comments and log

network.go, networkdb/networkdb.go
Usage of this API is to show the peer list in the `docker network inspect` output for trouble shooting..
This will work for swarm mode overlay networks on nodes that have a task running locally.
ex: since `ingress` network is instantiated on all nodes, it should show all nodes
```
vagrant@net-1:~$ docker network inspect ingress
[
{
"Name": "ingress",
"Id": "22igx395ep5bayb7eiw2vgipr",
"Created": "2016-10-25T21:38:03.968552332Z",
"Scope": "swarm",
"Driver": "overlay",
"EnableIPv6": false,
"IPAM": {
"Driver": "default",
"Options": null,
"Config": [
{
"Subnet": "10.255.0.0/16",
"Gateway": "10.255.0.1"
}
]
},
"Internal": false,
"Attachable": false,
"Containers": {
"ingress-sbox": {
"Name": "ingress-endpoint",
"EndpointID": "38e1ca082bc8c88bc76a45b250686a4405b3a88d5cdb6ef24de247a4f6781b54", …
```
=> Add NetworkDB API to fetch the per network peer (gossip cluster) list

Godeps/Godeps.json, Godeps/_workspace/src/github.com/Microsoft/hcsshim/baselayer.go, Godeps/_workspace/src/github.com/Microsoft/hcsshim/container.go, Godeps/_workspace/src/github.com/Microsoft/hcsshim/errors.go, Godeps/_workspace/src/github.com/Microsoft/hcsshim/hcsshim.go, Godeps/_workspace/src/github.com/Microsoft/hcsshim/hnsfuncs.go, Godeps/_workspace/src/github.com/Microsoft/hcsshim/importlayer.go, Godeps/_workspace/src/github.com/Microsoft/hcsshim/interface.go, Godeps/_workspace/src/github.com/Microsoft/hcsshim/legacy.go, Godeps/_workspace/src/github.com/Microsoft/hcsshim/preparelayer.go, Godeps/_workspace/src/github.com/Microsoft/hcsshim/process.go, Godeps/_workspace/src/github.com/Microsoft/hcsshim/utils.go, Godeps/_workspace/src/github.com/Microsoft/hcsshim/waithelper.go, Godeps/_workspace/src/github.com/Microsoft/hcsshim/zhcsshim.go, default_gateway.go, default_gateway_freebsd.go, default_gateway_linux.go, default_gateway_solaris.go, default_gateway_windows.go, drivers/windows/labels.go, drivers/windows/overlay/joinleave_windows.go, drivers/windows/windows.go, endpoint_info.go, endpoint_info_unix.go, endpoint_info_windows.go
Support for Default gateways with overlay network for windows.
Windows CI results:
PS C:\Windows\system32> C:\Tools\HNSCI.ps1 -remoteMachine 10.123.177.230
Describing HNS Network and Endpoint tests
Context Validate NAT Networks
[+] Should be able to build IIS Image 2.99s
[+] Should Publish all ports 5.26s
[+] Should Publish specific port 3.1s
[+] Should be able to ping external host 2.06s
[+] Validate hair pinning works 31.12s
[+] Validate service discovery 6.52s
[+] Should work with transparent network after service restart 8.4s
Context Validate Transparent Networks
[+] Should able to create single Transparent network. 7.14s
[+] Should able to create multiple Transparent network. 10.44s
[+] Should be able to ping external host 9s
[+] Should able to communicate across containers. 14.09s …
=> Default GW support for overlay networks

Godeps/Godeps.json, Godeps/_workspace/src/github.com/docker/libkv/.travis.yml, Godeps/_workspace/src/github.com/docker/libkv/MAINTAINERS, Godeps/_workspace/src/github.com/docker/libkv/store/boltdb/boltdb.go, Godeps/_workspace/src/github.com/docker/libkv/store/zookeeper/zookeeper.go, datastore/datastore.go
Fixes #1399
Related to https://github.com/docker/docker/issues/26251
=> Increase timeout in local store config

networkdb/networkdb.go
see https://github.com/docker/docker/pull/28285 for context.
fixes https://github.com/docker/docker/issues/28284
=> fix unsafe acces on arm

client/client.go, cmd/dnet/dnet.go, drivers/overlay/ov_endpoint.go, drivers/overlay/peerdb.go, drivers/solaris/overlay/ov_endpoint.go, drivers/solaris/overlay/peerdb.go, iptables/iptables.go
They are currently failing the CI
They happen because of this recent change https://github.com/golang/lint/commit/206c0f020eba0f7fbcfbc467a5eb808037df2ed6
=> Fix new golint reported errors

osl/neigh_linux.go
- stop iterating after changing the list reference
Related to https://github.com/docker/editions/issues/439
=> Fix bug in DeleteNeighbor

Godeps/Godeps.json, Godeps/_workspace/src/github.com/vishvananda/netlink/bpf_linux.go, Godeps/_workspace/src/github.com/vishvananda/netlink/filter.go, Godeps/_workspace/src/github.com/vishvananda/netlink/handle_linux.go, Godeps/_workspace/src/github.com/vishvananda/netlink/link.go, Godeps/_workspace/src/github.com/vishvananda/netlink/link_linux.go, Godeps/_workspace/src/github.com/vishvananda/netlink/neigh_linux.go, Godeps/_workspace/src/github.com/vishvananda/netlink/nl/link_linux.go, Godeps/_workspace/src/github.com/vishvananda/netlink/nl/nl_linux.go, Godeps/_workspace/src/github.com/vishvananda/netlink/route_linux.go, Godeps/_workspace/src/github.com/vishvananda/netlink/rule_linux.go, Godeps/_workspace/src/github.com/vishvananda/netlink/xfrm_state_linux.go, drivers/overlay/ov_network.go, drivers/overlay/ov_utils.go, ns/init_linux.go, osl/namespace_linux.go
=> Set a timeout to the netlink handle sockets

default_gateway.go
Related to https://github.com/docker/docker/issues/28630
=> Fix bug in needDefaultGW()

idm/idm.go, idm/idm_test.go
The mapping from id range to bit range was wrong.
=> Fix a bug in idm.GetIDInRange()

bitseq/sequence.go, controller.go, drivers/bridge/setup_ip_tables.go, drivers/overlay/overlay.go, drivers/solaris/bridge/bridge.go, ipvs/ipvs.go, network_windows.go, networkdb/networkdb.go
Found some misspelled word with [client9/misspell](https://github.com/client9/misspell)
=> Fixed misspelling

drivers/bridge/setup_ip_forwarding.go
Another `logrus` refactoring
Relate previous PR is https://github.com/docker/libnetwork/pull/1531
=> Refactoring logrus import and formatting

drivers/bridge/setup_ip_tables.go
(cherry picked from commit 59d91e5)
Related to https://github.com/docker/docker/issues/29108
=> [Port to 1.12.x] Respect icc option for internal networks

config/config.go, controller.go, drivers_experimental_linux.go, drivers_freebsd.go, drivers_linux.go, drivers_solaris.go, drivers_stub_linux.go, drivers_windows.go
related to https://github.com/docker/docker/issues/29368
=> Handling the new experimental daemon flag

Godeps/Godeps.json, Godeps/_workspace/src/github.com/docker/docker/pkg/plugingetter/getter.go, drivers/remote/driver.go, ipams/remote/remote.go
For more details : docker/docker#29665 and docker/docker#29556
=> Make use of GetAllManagedPluginsForCap to avoid loading v1-plugins

cmd/proxy/network_proxy_test.go, networkdb/networkdb_test.go, osl/interface_linux.go, osl/namespace_linux.go, osl/sandbox_linux_test.go
- Based on whether ipv6 is address is present on the interface
Related to https://github.com/docker/docker/issues/20569
Signed-off-by: Alessandro Boch aboch@docker.com
=> Control IPv6 on container's interface

docs/remote.md
Signed-off-by: Yi EungJun eungjun.yi@navercorp.com
=> docs/remote.md: Remove unnecessary backquote

network.go
fixes https://github.com/docker/docker/issues/29726
=> make network connect error message readable

controller.go, docs/macvlan.md, driverapi/driverapi.go, drivers/windows/overlay/peerdb_windows.go, libnetwork_linux_test.go, sandbox.go
=> fix nits in error and log

network.go
=> ResolveName should return copy of IPs - cherry-pick for v0.9 branch

docs/ipam.md
=> doc update

drivers/overlay/ov_network.go
Hi there,
Today we meet a strange error when create a service on our friends' virtual machine, but I have no extra log for actually conflict with, so maybe we should log for this.
```
starting container failed: subnet sandbox join failed for \"10.255.0.0/16\": overlay subnet 10.255.0.0/16 has conflicts in the host while running in host mode
```
Signed-off-by: realityone realityone@me.com
=> Add log when check is overlap with host nameservers or route table

cmd/proxy/tcp_proxy.go
Suggested in https://github.com/docker/libnetwork/pull/1598#discussion_r94898635
PTAL @sanimej 
=> proxy: clean up code (addendum to #1598)

service_linux.go
- Failed to _add_ firewall mark... should be _delete_
=> Fix incorrect error log message

agent.go, config/config.go, config/config_test.go, controller.go, error.go, ipvs/ipvs.go, ipvs/netlink.go, network.go, networkdb/event_delegate.go, networkdb/watch.go, service_common.go, service_linux.go, service_windows.go
Cherry-pick of
4b3008e95e6be93ec8eaaadf9e888ea211534cd0
522e141ca66cd90d7e877887bc2b56c602962314
d3194e4506ad7990c48bf05edb3e4237c956af2e
4995474142a4ea7e5830f5721d9fc12d358afe48
4131b4d9f4dae48ca0cee356075e0ea8e26985a0
07877f913bb207b91fc1fe1ead4c4ab75b4b5462
=> Cherry picks for 1.13.x

ipvs/netlink.go
=> Do not leak ipvs netlink socket

drivers/overlay/ov_network.go
=> Report failure in subscribing to neighbor notifications

docs/ipam.md
Signed-off-by: Quan Tian <tianquan@cloudin.cn>
=> Fix typo in IPAM doc

ipvs/ipvs_test.go
Signed-off-by: fate-grand-order <chenjg@harmonycloud.cn>
=> handle err and fix t.Skip() in ipvs/ipvs_test.go

datastore/datastore.go, drivers/overlay/encryption.go, drivers/overlay/ov_network.go, drivers/overlay/ov_serf.go, drivers/overlay/overlay.go, drivers/overlay/peerdb.go, endpoint_info.go, ipvs/netlink.go, osl/neigh_linux.go, store.go
Porting:
5e7857a1f8684b20b968d670c77d1a9c1f0c536c
4dd1d9c502f0dc50e2ec8b56bddad4bffb00fc97
3492cea1dfa166bd99ff65d1c1f4e303ef0f5a9d
ff0b1cccb0c6d691780ab8953fd4485e686da93f
760abd041b3100007987423140db1f169c84dab9
e1565882e8802cbb0e25d492e6b2dfc68123f590
b1fdb14edf453ccc0473c206689d85e5c7f2488e
5f11f5289c14530379e2afd982bf74bb0fb3ebfa
=> Port fixes to release/v0.9 branch for docker 1.13.x

drivers/overlay/encryption.go, drivers/overlay/ov_network.go
- even if sender won't be able to decrypt the responses
=> Once a network is encrypted, do not accept clear packets from it

network.go
- To help trace missing/extra service records
=> Add logs around service records modifications

controller.go, network.go
=> Expose ingress network option

endpoint.go
=> Remove enpoint state from cluster on join failure

api/api_test.go
Signed-off-by: fate-grand-order <chenjg@harmonycloud.cn>
=> fix some misspells in api/api_test.go

controller.go
Related to docker/docker/issues/32173
- Also, perform the cleanup only on shutdown.
On cluster leave the removal will be initiated
by the owner, the docker daemon.
=> Do not clear ingress network in libnetwork

error.go, store.go
For https://github.com/docker/docker/pull/31912
PTAL @aboch 
=> improve error for getStore()

osl/namespace_linux.go
Related to docker/docker/issues/32433
=> Do not manage ipv6 for host mode containers

endpoint.go
=> fix endpoint error

docs/remote.md
Signed-off-by: Quan Tian <tianquan@cloudin.cn>
=> Fix typo in remote.md

endpoint.go
This is a follow-up of #1716 fix after https://github.com/docker/libnetwork/pull/1716#discussion_r111647318 revealed  the logic was broken in another error path by a recent change.
- Moved the `sbJoin` function to use named return error variable, to avoid to break the logic again in future
- Improved the error messages
=> Make sure sbJoin programming rollback happens on each error

agent.go
Fix initialization of starting vector
=> Fix for remote addr parsing

networkdb/cluster.go
For bulksync we only pick one random node and if that fails there is no retry currently. Adding one retry. I am not explicitly checking if the node picked up 2nd time is same as the first because in bigger clusters its unlikely.
=> retry once on a bulk sync failure

support.sh
=> Add network inspect -v to the support script

network.go
=> Reject scope settings in config-only network

drivers/overlay/peerdb.go
Changed some prints into proper logging, also
was missing the \n at the end
=> Removed printfs

Makefile, agent.go, agent.proto, common/setmatrix.go, common/setmatrix_test.go, endpoint.go, libnetwork_internal_test.go, network.go, networkdb/networkdb.go, sandbox.go, service.go, service_common.go, service_linux.go
This patch addresses several issues found on the Service Discovery feature.
=> Backport Service discovery hardening

support.sh
=> Include network inspect in support script

networkdb/networkdb.go
=> Fix go generate for protobuf

drivers/windows/labels.go, drivers/windows/windows.go, drivers_windows.go
We were missing some basic properties. Added that.
Signed-off-by: Sandeep Bansal <sabansal@microsoft.com>
=> Changes to support ICS network on windows

Dockerfile.build, Makefile, agent.go, endpoint_info.go, libnetwork_linux_test.go, libnetwork_test.go, network.go, resolver.go, sandbox.go, sandbox_externalkey_unix.go, sandbox_store.go
Add the gosimple tool check in the Makefile
Fix all the issues identified
=> Add gosimple tool

service_linux.go
Fixes #1827
Signed-off-by: Jacob Wen <jian.w.wen@oracle.com>
=> iptables: jump to DOCKER-USER first

drivers/overlay/joinleave.go, drivers/overlay/ov_network.go, drivers/overlay/ov_serf.go, drivers/overlay/peerdb.go, drivers/solaris/overlay/peerdb.go, osl/neigh_linux.go, osl/sandbox.go
=> Cherry-pick overlay driver fixes for 17.03 backport

config/config.go
=> Fix warn log

endpoint_info.go
Fixes bug that mistook gw6 for gw.
Signed-off-by: Frank Yang <yyb196@gmail.com>
=> Fixes bug that mistook gw6 for gw.

drivers/bridge/bridge_test.go, iptables/iptables.go
(cherry picked from commit 73ebaefe9c75e7762bfe2052e45933d799cf8738)
=> [17.06 backport] Avoid flakiness of TestLinkContainers

service_linux.go
Fixes #1827
Signed-off-by: Jacob Wen <jian.w.wen@oracle.com>
(cherry picked from commit 8c5992203172b387f74cf06bf1d36a3d17dc1f7e)
=> [backport 17.06] iptables: jump to DOCKER-USER first

drivers/bridge/bridge_test.go, iptables/iptables.go
(cherry picked from commit 73ebaefe9c75e7762bfe2052e45933d799cf8738)
=> [backport 17.03] Avoid flakiness of TestLinkContainers

endpoint_info.go
Signed-off-by: Frank Yang <yyb196@gmail.com>
(cherry picked from commit 2cd3a73be64cdec2464cbd3ef573403aa511d4f6)
=> [backport 17.06] Fixes bug that mistook gw6 for gw.

endpoint_info.go
Signed-off-by: Frank Yang <yyb196@gmail.com>
(cherry picked from commit 2cd3a73be64cdec2464cbd3ef573403aa511d4f6)
=> [backport 17.03] Fixes bug that mistook gw6 for gw.

endpoint_info.go
=> [Backport 17.03] Fix gw field on restore

endpoint_info.go
Master PR: https://github.com/docker/libnetwork/pull/1887
=> [Backport 17.06] Fix gw field on restore

resolver.go
This patch improves debugging for the resolver;
- prefix debug messages with `[resolver]` for easier finding in the daemon logs
- use `A` / `AAAA` for query-types in the logs instead of their numeric code
- add debug messages if the external DNS did not return a result
- print sucessful results (t.b.d.)
@fcrisciani @sanimej I added these messages while debugging something; thought they may be useful in general :smile:
=> Improve debugging for resolver

sandbox_dns_unix.go
**Steps to reproduce:**
```
16472add8a1bf7422a31e2cc89bca0300cb1384a9e43d90d9f147b40f0c8313c
docker: Error response from daemon: open /etc/resolv.conf: no such file or directory.
#
cfdb959909806c94f2172e4c010072c03942270ad3fd57fe77b709e8aac76eb9
```
`/etc/resolv.conf` is not an essential file in filesystem. (see
http://man7.org/linux/man-pages/man5/resolv.conf.5.html)
> If this file does not exist, only the name server on the local machine
> will be queried
It's baffling to users that containers can start with an empty
`resolv.conf` but cannot without this file.
This PR:
* ignore this error and use default servers for containers in `bridge` mode networking.
* create an empty resolv.conf in `/var/lib/docker/containers/<id>` in `host` mode networking.
Signed-off-by: Yuanhong Peng …
=> Bugfix: Ignore "no such file" error when docker cannot find `resolv.conf`

circle.yml
Signed-off-by: Hui Kang <hkang.sunysb@gmail.com>
=> Remove unused packages in circle.yml

portallocator/portallocator_freebsd.go
Hello,
I am working on getting a modern version of docker to work on FreeBSD as a docker host.
These are the first changes I have made.
=> Add support for FreeBSD in portallocator

circle.yml
=> Enable codeconv reporting

common/setmatrix_test.go
- Add unit tests for some of the functions of set_matrix
=> Increase code coverage for set_matrix

cmd/dnet/dnet.go, drivers/bridge/bridge.go, drivers/bridge/setup_ip_tables.go, drivers/overlay/ov_endpoint.go, drivers/solaris/overlay/ov_endpoint.go, endpoint_info.go, iptables/iptables.go, sandbox_dns_unix.go
The package updated and now shows new warnings that had to be corrected
to let the CI pass
=> Fix lint issues

drivers/overlay/peerdb.go, drivers/overlay/peerdb_test.go
Fix marshalling and add test
(cherry picked from commit c32647ec928b2f87dacb76b6754283f613dcd24e)
=> Fix IPMask marshalling

service_common_test.go
Unit test for the cleanupServiceDiscovery,
follow up of PR: #1985
=> Add test for cleanupServiceDiscovery

controller.go, store.go
=> Addressing feedback from lbfix PR 

networkdb/delegate.go
The previous logic was not properly handling the case of a node
that was failing and coming back in short period of time.
The issue was in the handling of the network messages.
When a node joins it sync with other nodes, these are passing
the whole list of nodes that at best of their knowledge are part
of a network. At this point if the node receives that node A is part
of the network it saves it before having received the notification
that node A is actually alive (coming from memberlist).
If node A failed the source node will receive the notification
while the new joined node won't because memberlist never advertise
node A as available. In this case the new node will never purge
node A from its state but also worse, will accept any table notification
where node A is the owner and so …
=> [backport 17.06] NetworkDB node management race

controller.go, firewall_linux.go, firewall_others.go
=> Reload DOCKER-USER chain on firewalld reload.

Dockerfile.build
release notes: https://golang.org/doc/devel/release.html#go1.9.minor
full diff: https://github.com/golang/go/compare/go1.9.2...go1.9.3
=> Bump Go to 1.9.3

cmd/ssd/Dockerfile, cmd/ssd/README.md, cmd/ssd/ssd.py
=> Import the ssd tool in libnetwork

cmd/ssd/ssd.py
Currently we hardcode the path to the system binaries, example: `/usr/sbin/ipvsadm`  
This PR makes it dynamic by adding a `which` like function in case the binary was in a different path.
The changes make the code portable in case a user wants to run the script by itself or in a different environment/image. 
In addition, a small error check is added in case the network has no services.
Signed-off-by: Dani Louca <dani.louca@docker.com>
=> Make SSD portable and useable outside the default image & error check when network on a particular node has no services.

config/config.go, controller.go, drivers/bridge/bridge_test.go, drivers_ipam.go, ipam/allocator_test.go, ipams/builtin/builtin_unix.go, ipams/builtin/builtin_windows.go, ipamutils/utils.go, ipamutils/utils_test.go, netutils/utils_test.go
This is separate commit on libnetwork to address PR https://github.com/moby/moby/pull/36054
=> Allow user to specify default address pools for docker networks

ipams/windowsipam/windowsipam.go
cherry-pick of https://github.com/docker/libnetwork/pull/1916 for 17.06
no conflicts
=> [17.06] Docker deamon doesn't work with --fixed-cidr on windows

service_common.go
If the len was less than the max length, there was a panic
=> Fix crash if the len was < maxSetStringLen

drivers/bridge/bridge.go, drivers/ipvlan/ipvlan_endpoint.go, drivers/ipvlan/ipvlan_network.go, drivers/macvlan/macvlan_endpoint.go, drivers/macvlan/macvlan_network.go, drivers/overlay/ov_network.go
We can know the reason for the failure of deleting the link device.
Signed-off-by: ZhiPeng Lu <lu.zhipeng@zte.com.cn>
=> Add warning message for the failure of deleting link device

support.sh
Add a simple check and a summary report for the support script.
Report:
```
==SUMMARY==
Processed 3 networks
IP overlap found: 1
Processed 167 containers
```
Overlap found:
```
*** OVERLAP on Network 0ewr5iqraa8zv9l4qskp93wxo ***
2  "192.168.1.138",
```
=> Add check for IP overlap in support.sh

drivers/windows/windows.go
Signed-off-by: John Stephens <johnstep@docker.com>
When Windows Server 2016 is restarted with the Docker service running, it is possible for endpoints to be deleted from the libnetwork store without being deleted from HNS. This does not occur if the Docker service is stopped cleanly first, or forcibly terminated (since the endpoints still exist in both). This change works around the issue by removing any stale HNS endpoints for a network when creating it.
@pradipd @msabansal
=> Delete stale HNS endpoints when creating a network

README.md
Signed-off-by: Abhinandan <abhi@docker.com>
=> Adding goreport card

ipam/parallel_test.go
=> Add test for parallel request pool

ipam/allocator_test.go
Releasing a pool which has already been released should fail; this
change increases coverage by a fraction by exercising this path.
=> ipam/allocator_test: Test pool double-release behavior

ipam/allocator.go, types/types.go, types/types_test.go
Fix some typos and mis-named functions.
=> Fix trivial typos

controller.go, endpoint.go, resolver.go, sandbox.go, sandbox_store.go, sandbox_test.go
Solves #2093 b). PR is based on #2103.
=> Improve interface order

types/types.go, types/types_test.go
Use net.splitHostPort() instead of our own logic in func (p *PortBinding)
FromString(s string) error.   This means that IPv6 literals, including
IPv4 in IPv6 literals, can now be parsed from the string form of
PortBindings.   Zoned addresses do not work - net.splitHostPort() parses
them but net.ParseIP() cannot and returns an error.   This is ok because
we do not have a slot to store the zone name in PortBinding anyway.
=> types: Handle IPv6 literals correctly in port bindings

vendor.conf, vendor/github.com/hashicorp/go-sockaddr/ifaddr.go, vendor/github.com/hashicorp/go-sockaddr/ifaddrs.go, vendor/github.com/hashicorp/go-sockaddr/ipv4addr.go, vendor/github.com/hashicorp/go-sockaddr/rfc.go, vendor/github.com/hashicorp/go-sockaddr/route_info_linux.go, vendor/github.com/hashicorp/go-sockaddr/sockaddr.go
diff:
https://github.com/hashicorp/go-sockaddr/compare/acd314c5781ea706c710d9ea70069fd2e110d61d...6d291a969b86c4b633730bfc6b8b9d64c3aafed9
=> Vendor go-sockaddr

ipam/allocator_test.go, ipam/structures.go, libnetwork_internal_test.go
Backport PRs: https://github.com/docker/libnetwork/pull/2148 and https://github.com/docker/libnetwork/pull/2189
=> [backport 18.03] Adding a check for subnet pool overlap

support/Dockerfile, support/run.sh
Before running the support script
try to fetch the latest version
=> Add auto update to support.sh

.dockerignore, .gitignore
Try to reduce the docker context for the build
=> Added back dockerignore

cmd/networkdb-test/dbclient/ndbClient.go
Add retry field to cluster-peers probe
=> Add retry to cluster-peers

Makefile
In order to support different branches
create master tag
=> Create tag for master code

support/support.sh
The fate (exit code and timing) of exited containers is often useful in back-tracking swarmkit IPAM issues that manifest in libnetwork gossip control plane.
Collect information on `container ls -a` instead of just `container ls`.
Used a bashim to keep the number of docker API calls the same.
=> support.sh: also inspect stopped containers

README.md
It's not too hard to figure these out, but it's easier if they're already in the example.
=> Add required imports to example code in README.md

diagnostic/server.go, drivers/overlay/peerdb.go, internal/caller/caller.go, internal/caller/caller_test.go, internal/setmatrix/setmatrix.go, internal/setmatrix/setmatrix_test.go, libnetwork_internal_test.go, libnetwork_linux_test.go, network.go, networkdb/networkdbdiagnostic.go, osl/kernel/knobs.go, resolvconf/resolvconf.go, sandbox.go, sandbox_dns_unix.go, service.go, service_common.go
- Restructure common to pkg directory to be more compliant with the golang directory structure
- Use the resolv.conf passed from the daemon
Addresses: https://github.com/docker/libnetwork/issues/2187
Moby side: https://github.com/moby/moby/pull/37485
=> Proper handling sandbox options

drivers/bridge/bridge.go
=> bridge: fix error handling for stale default gateways

drivers/ipvlan/ipvlan_endpoint.go
Signed-off-by: Rui Cao <ruicao@alauda.io>
=> Fix typo: assigment -> assignment

ipam/parallel_test.go
=> typo fix about mismatch

resolver.go
relates to https://github.com/moby/moby/pull/37180, https://github.com/moby/moby/issues/20494, https://github.com/docker/compose/issues/5991
- NXDOMAIN is an authoritive answer, so when receiving an NXDOMAIN, we're done.
From RFC 1035: Name Error - Meaningful only for responses from an authoritative
name server, this code signifies that the domain name referenced in the query
does not exist.
FROM RFC 8020: When an iterative caching DNS resolver receives an NXDOMAIN
response, it SHOULD store it in its cache and then all names and resource
record sets (RRsets) at or below that node SHOULD be considered unreachable.
Subsequent queries for such names SHOULD elicit an NXDOMAIN response.
- REFUSED can be a transitional status: (https://www.ietf.org/rfc/rfc1035.txt)
The name server refuses to …
=> Handle NXDOMAIN, REFUSED and log errors

Dockerfile
=> Update golint tool

Dockerfile
(cherry picked from commit 29237c01a9613d88a8a781da88fbe5dc7fa39d7d)
=> [Backport 18.09] Update golint tool

.circleci/config.yml
=> Use docker stable engine

default_gateway.go
=> Fix gosimple

netutils/utils_linux.go
Follow-up to https://github.com/docker/libnetwork/pull/2306/files#r245129786
ping @euanh @mavenugo PTAL
=> Use errors.Wrap to preserve original error

support/support.sh
Starting from 18.09, there's a per node LB for each overlay
network, this change adds the checks (ip, bridge, iptables, ipvsadm) on node LB.
This change should not break on older docker versions.
=> add checks on node LB in support.sh

resolver_unix.go, service_linux.go
Signed-off-by: Dani Louca <dani.louca@docker.com>
This is a backport of PR #2069
CC: @arkodg @mavenugo
=> Backporting PR #2069 to bump_17.06

MAINTAINERS
- Add Euan and Elango
- Remove inactive maintainers
=>  Maintainers update

Dockerfile, drivers/bridge/setup_ip_tables.go, drivers/overlay/ostweaks_linux.go, drivers/windows/windows.go, network.go, osl/namespace_linux.go, resolvconf/resolvconf_test.go
moby/moby is currently using 1.12.6 - we should keep up
=> Update to Golang 1.12.6

test/integration/dnet/run-integration-tests.sh
TrivialFix
Signed-off-by: Hui Kang <kangh@us.ibm.com>
=> Removed unused integration test code

Dockerfile
(cherry picked from commit 29237c01a9613d88a8a781da88fbe5dc7fa39d7d)
=> [Backport 17.06] Update golint tool

MAINTAINERS
ping @mavenugo @euanh @selansen @fcrisciani PTAL
=> Add Arko to maintainers

osl/namespace_linux.go
TL;DR
Updates to improve load balancer performance at a high load scenario.
Resolves https://github.com/moby/moby/issues/35082
Detailed explanation is provided at https://github.com/moby/moby/issues/35082#issuecomment-565245210
=> Improving load balancer performance

network.go, service_common.go
=> [19.03 backport] Cleanup VFP during overlay network removal

resolver.go
=> Fixes a panic in the DNS resolver

resolver.go
See https://github.com/moby/libnetwork/pull/2540
=> [19.03 backport] resolver panic backport

drivers/bridge/bridge.go, drivers/bridge/setup_device.go
Please consider backporting this fix for [CVE-2020-13401](https://nvd.nist.gov/vuln/detail/CVE-2020-13401). Thanks!
Signed-off-by: Samuel Karp <skarp@amazon.com>
(cherry picked from commit 153d0769a1181bf591a9637fd487a541ec7db1e6)
Signed-off-by: Sam Whited <sam@samwhited.com>
=> [18.09 backport] bridge: disable IPv6 router advertisements

portmapper/mapper.go, portmapper/mapper_linux.go, portmapper/mapper_windows.go
This should fix moby/moby#41699
=> Added improved IP validation for port mapper

drivers/bridge/setup_ip_tables.go, iptables/iptables.go
=> Fixed IPv6 portmapper iptables chain initialization

iptables/iptables.go
This should address moby/moby#41861
=> fixed IPv6 iptables rules for enabled firewalld

network.go
fixes https://github.com/moby/libnetwork/issues/2632
addresses https://github.com/moby/moby/issues/42032
=> Enforce order of lock acquisitions on network/controller, fixes #2632

vendor.conf, vendor/github.com/ishidawataru/sctp/NOTICE, vendor/github.com/ishidawataru/sctp/go.mod, vendor/github.com/ishidawataru/sctp/ipsock_linux.go, vendor/github.com/ishidawataru/sctp/sctp.go, vendor/github.com/ishidawataru/sctp/sctp_linux.go, vendor/github.com/ishidawataru/sctp/sctp_unsupported.go
full diff: https://github.com/ishidawataru/sctp/compare/6e2cb1366111dcf547c13531e3a263a067715847...f2269e66cdee387bd321445d5d300893449805be
=> vendor: github.com/ishidawataru/sctp f2269e66cdee387bd321445d5d300893449805be

iptables/iptables.go, iptables/iptables_test.go
- Cherry-pick moby/moby#43060
- Fixes moby/moby#42127
- Fixes moby/moby#44331
=> [20.10] Check iptables options before looking for ip6tables binary
