README.md
cmd/test/main.go
driverapi/driverapi.go
drivers.go
drivers/bridge/bridge.go
drivers/bridge/bridge_test.go
drivers/bridge/interface.go
drivers/bridge/interface_test.go
drivers/bridge/network_test.go
drivers/bridge/setup.go
drivers/bridge/setup_device.go
drivers/bridge/setup_device_test.go
drivers/bridge/setup_fixedcidrv4.go
drivers/bridge/setup_fixedcidrv4_test.go
drivers/bridge/setup_fixedcidrv6.go
drivers/bridge/setup_fixedcidrv6_test.go
drivers/bridge/setup_ip_forwarding.go
drivers/bridge/setup_ip_forwarding_test.go
drivers/bridge/setup_ip_tables.go
drivers/bridge/setup_ip_tables_test.go
drivers/bridge/setup_ipv4.go
drivers/bridge/setup_ipv4_test.go
drivers/bridge/setup_ipv6.go
drivers/bridge/setup_ipv6_test.go
drivers/bridge/setup_verify.go
drivers/bridge/setup_verify_test.go
libnetwork_test.go
network.go

Closes #43 
- Added api enhancement to pass driver specific config
- Refactored simple bridge driver code for driver specific config
- Added an undocumented option to add non-default bridges without
manual pre-provisioning to help libnetwork testing
- Reenabled libnetwork test to do api testing

Added driver specific config support

---

drivers/bridge/bridge.go
pkg/portallocator/portallocator.go
pkg/portallocator/portallocator_test.go
portmapper/mapper.go

DESCRIPTION:
As part of bringing libnetwork bridge driver features
in parity with docker/daemon/network/driver/bridge
features (Issue #46), this commit addresses the
bridge.RequestPort() API.
Currenlty docker/api/server.go needs an hold of port
allocator in order to reserve a transport port which
will be used by the http server on the host machine,
so that portallocator does not give out that port when
queried by portmapper as part of network driver operations.
ISSUE:
Current implementation in docker is server.go directly
access portmapper and then portallocator from bridge pkg
calling bridge.RequestPort(). This also forces that function
to trigger portmapper initialization (in case bridge init()
was not executed yet), while portmapper life cycle should
only be controlled by bridge …

Port Allocator as a libnetwork package

---

drivers/bridge/bridge.go
drivers/bridge/error.go
drivers/bridge/setup_device.go
drivers/bridge/setup_device_test.go
drivers/bridge/setup_fixedcidrv4.go
drivers/bridge/setup_fixedcidrv4_test.go
drivers/bridge/setup_fixedcidrv6.go
drivers/bridge/setup_ip_forwarding.go
drivers/bridge/setup_ip_forwarding_test.go
drivers/bridge/setup_ip_tables.go
drivers/bridge/setup_ipv4.go
drivers/bridge/setup_ipv6.go
drivers/bridge/setup_verify.go

Changed all the naked error returns in bridge driver to proper error
types, except the naked error returns which were just prefixing
strings to previously returned error strings.
Fixes #53 

Change all the naked error returns in bridge driver to proper error types

---

network.go

This allows users to operate on endpoints by ID; for example, return the ID to the user on creation.

Expose Endpoint IDs in their public interface.

---

libnetwork_test.go

- It is working on default netns, leaving many
vethxxx to cleanup after it runs

Fix libnetwork_test.go

---

drivers/bridge/interface.go

Fixed a typo and removed capitalization of function names in comments. Fixes #75
Signed-off-by: Mohammad Banikazemi <mbanikazemi@gmail.com>

Fixing a few typos

---

drivers/bridge/bridge.go
drivers/bridge/error.go
drivers/bridge/network_test.go
libnetwork_test.go

- Store *Interface on endpoint create
- Remove from bridgeEndpoint ip params now available in Interface
- On endpoint delete attempt a removal of veth plugged into bridge
- (tested disabling defer netutils.SetupTestNetNS(t)() in libnetwrok_test)
- Fix bridge to  store endpoints per sandbox
- Fix bug in error.go which causes stack overflow

Issue #68: In bridge.go driver remove veth on endpoint delete

---

cmd/readme_test/readme.go
drivers/bridge/bridge.go
drivers/bridge/bridge_test.go
drivers/bridge/error.go
drivers/bridge/network_test.go
libnetwork_test.go
network.go

- This addresses one requirement from Issue #79
- Defined EndpointConfiguration struct for bridge driver
which contains the user's preferred mac address for the
sanbox interface
- Addressed @mrjana comments

Libnetwork bridge to handle --mac-address option

---

cmd/readme_test/readme.go
cmd/test/main.go
driverapi/driverapi.go
drivers/bridge/bridge.go
libnetwork_test.go
network.go

- To reflect work flow. NewDriver() => ConfigureDriver()
and no NetworkDriver returned.
libnetwork clients would refer to a driver/network type, then
internally controller will retrieve the correspondent driver
instance, but this is not a concern of the clients.
- Remove NetworkDriver interface
- Removed stale blank dependency on bridge in libnetwork_test.go
- Taken care of @mrjana comments

Refactor NetworkController interface

---

sandbox/configure_linux.go
sandbox/namespace_linux.go

- setGatewayIP() => programGateway() becsause it is
causing confusion with setGateway() and setGatewayIPv6()

Rename setGatewayIP() in sandbox pkg

---

drivers/bridge/bridge.go
drivers/bridge/bridge_test.go
drivers/bridge/error.go
drivers/bridge/interface.go
drivers/bridge/network_test.go
drivers/bridge/setup_ipv4.go
drivers/bridge/setup_ipv4_test.go
drivers/bridge/setup_ipv6.go
drivers/bridge/setup_ipv6_test.go

- Basically this is porting docker PR #9381 to libnetwork
- Added a Config.Validate() method where to consolidate
a priori validation of bridge configuration
- Have bridgeInterface store the current v4/v6 default gateways
- Introduced two setupStep functions to set the requested def gateways
- Taken care of mrjana's comments

Issue #88: Handle default v4/v6 gw setting

---

README.md
ROADMAP.md
cmd/readme_test/readme.go
driverapi/driverapi.go
drivers/bridge/bridge.go
drivers/bridge/bridge_test.go
drivers/bridge/network_test.go
drivers/bridge/setup_ipv6.go
error.go
libnetwork_test.go
network.go
sandbox/configure_linux.go
sandbox/namespace_linux.go
sandbox/sandbox_linux_test.go

- Added support for Join/Leave methods to Endpoint.
- Removed sandbox key argument from CreateEndpoint.
- Refactored bridge driver code to remove sandbox key.
- Fixed bridge driver code for gaps in ipv6 behavior
observed during docker integration.
- Updated test code, readme code, README.md according
api change.
- Fixed some sandbox issues while testing docker ipv6
integration.

Add support for Join/Leave methods to Endpoint

---

endpoint.go

ISSUE:
- JoinOption type takes the exported interface Endpoint as parameter.
This does not allows libnetwork to control the setter functions
which will be executed by processOptions(). Client can now craft
any func (e Endpoint), pass it to Endpoint.Join() and have it executed.
Beside the fact this allows the client to shot himself in the foot,
there seem not to be a real need in having the JoinOption take the
Endpoint interface as parameter.
CHANGE:
- Changing the JoinOption signature to take a pointer to the unexported
endpoint structure. So now libnetwork is the only one that can define
the Join() method's options setter functions via the self referenced
JoinOption[...] functions.

Control scope of JoinOption functions

---

drivers/bridge/setup_ipv4.go
netutils/utils.go

using a len(net.IP) to check for ipv4 or ipv6 is a bad idea.
And that was exactly done in NetworkOverlaps() function with the
assumption that any ipv4 net.IP will be of 4 bytes. Golang Net package
makes no such assumptions.
This assumption actually broke a particular use-case where the
NetworkOverlaps fails to identify a genuine overlap and that causes
datapath issues.
With this fix, we explicitely check for v4 or v6

Incorrect assumption with golang net package causes Overlapping IP

---

drivers/bridge/bridge.go
drivers/bridge/bridge_test.go

- Changed ContainerConfiguration to simply use strings
- Made ContainerConfiguration fields to be exported so
options package can access them.

Link integration fixes

---

Makefile

If we can't upload to coveralls, don't fail the build.
Goveralls and Coveralls have been a little flaky and started throwing
http 422 errors, although I still see coverage being reported.
It's best in the interim to ignore these, although this should be
removed in future when the service is more stable

Don't fail the build on coveralls upload

---

controller.go
docs/remote.md
driverapi/driverapi.go
drivers.go
drivers/bridge/bridge.go
drivers/bridge/bridge_test.go
drivers/bridge/network_test.go
drivers/bridge/port_mapping_test.go
drivers/null/null.go
drivers/remote/driver.go
drivers/remote/driver_test.go
libnetwork_internal_test.go

This commits brings in a functionality for remote drivers to register
with LibNetwork. The Built-In remote driver is responsible for the
actual "remote" plugin to be made available.
Having such a mechanism makes libnetwork core not dependent on any
external plugin mechanism and also the Libnetwork NB apis are free of
Driver interface.

Remote Driver Registration

---

Makefile
endpoint.go
error.go
libnetwork_test.go
sandbox/namespace_linux.go

- Refactored the Join/Leave code so they are synchronized across multiple go-routines
- Added parallel test coverage to test mult-thread access to Join/Leave
- Updated sandbox code to revert back to caller namespace when removing interfaces
- Changed the netns path to /var/run/netns so the cleanup is simpler on machine
reboot scenario

Make endpoint Join and Leave multi-thread safe

---

.gitignore
Makefile

Make builds run faster by making an image with the build dependencies already installed. This comes at the expense of that image potentially being out-of-date with respect to the build dependencies, unless care is taken.

Create build image with dependencies installed

---

endpoint.go
libnetwork_test.go

If resolvConfPath is unavailable and if the internally generated .hash file
is still present, then updateDNS should not consider the presence of internally
generated .hash. Rather, it must handle it as a case of using this
resolvConfPath for the first time.

Ignore the OldHash if the resolvConfPath is invalid

---

api/api.go

Fix the misuse the urlNwName and urlNwID in routepath for GetEndpoint rest api.
Signed-off-by: junxu <xujun@cmss.chinamobile.com>

Fix misuse urlNwName and urlNwID in api.

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/docker/docker/pkg/ioutils/readers_test.go
Godeps/_workspace/src/github.com/docker/docker/pkg/ioutils/writeflusher.go
Godeps/_workspace/src/github.com/docker/docker/pkg/ioutils/writers_test.go
Godeps/_workspace/src/github.com/docker/docker/pkg/mflag/flag.go
Godeps/_workspace/src/github.com/docker/docker/pkg/parsers/kernel/kernel.go
Godeps/_workspace/src/github.com/docker/docker/pkg/parsers/kernel/kernel_windows.go
Godeps/_workspace/src/github.com/docker/docker/pkg/plugins/client.go
Godeps/_workspace/src/github.com/docker/docker/pkg/plugins/client_test.go
Godeps/_workspace/src/github.com/docker/docker/pkg/plugins/discovery.go
Godeps/_workspace/src/github.com/docker/docker/pkg/plugins/discovery_test.go
Godeps/_workspace/src/github.com/docker/docker/pkg/plugins/plugins.go
Godeps/_workspace/src/github.com/docker/docker/pkg/reexec/command_windows.go
Godeps/_workspace/src/github.com/docker/docker/pkg/stringid/stringid.go
Godeps/_workspace/src/github.com/docker/docker/pkg/stringid/stringid_test.go
controller.go
driverapi/driverapi.go
drivers/remote/driver.go
libnetwork_test.go

Now that the modular plugin infra is available as a Docker Package, we can integrate it to support Remote Driver.
This PR integrates Libnetwork and the Plugin Infra to dynamically discover `NetworkDriver`.
Being a modular package, there is no dependancy on the Docker runtime itself as evidenced in the tests added to libnetwork_test.

Libnetwork Integration with Plugin and Remote Driver Backend

---

sandbox/namespace_linux.go

Change namespace path to be /var/run/docker/netns since
/var/run/netns is being used by iproute2 and it is mounted
as MS_SHARED which causes some complications during integration.

Change default namespace path

---

iptables/iptables_test.go

- Which is needed when running make (test in container)

Restore anonymus import in iptables_test.go

---

controller.go
libnetwork_test.go

There is a panic when two containers joining a host
network leave one after another. The problem was that
in controller.go the sandboxData was not stored as a
pointer reference. So when we got the data from the map
it was the copy of the data and refcnt increment was done
on that. Changed it to hold a reference.  Also added a test
case to test it.

Fix panic on leave of host driver endpont leave

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/docker/docker/pkg/parsers/filters/parse.go
Godeps/_workspace/src/github.com/docker/docker/pkg/parsers/filters/parse_test.go
Godeps/_workspace/src/github.com/docker/docker/pkg/parsers/operatingsystem/operatingsystem_linux.go
Godeps/_workspace/src/github.com/docker/docker/pkg/parsers/operatingsystem/operatingsystem_test.go
Godeps/_workspace/src/github.com/docker/docker/pkg/parsers/operatingsystem/operatingsystem_windows.go
Godeps/_workspace/src/github.com/docker/docker/pkg/parsers/parsers.go
Godeps/_workspace/src/github.com/docker/docker/pkg/parsers/parsers_test.go
Godeps/_workspace/src/github.com/docker/docker/pkg/term/tc_linux_cgo.go
Godeps/_workspace/src/github.com/docker/docker/pkg/term/tc_other.go
Godeps/_workspace/src/github.com/docker/docker/pkg/term/term.go
Godeps/_workspace/src/github.com/docker/docker/pkg/term/term_windows.go
Godeps/_workspace/src/github.com/docker/docker/pkg/term/termios_darwin.go
Godeps/_workspace/src/github.com/docker/docker/pkg/term/termios_freebsd.go
Godeps/_workspace/src/github.com/docker/docker/pkg/term/termios_linux.go
Godeps/_workspace/src/github.com/docker/docker/pkg/term/winconsole/console_windows.go
Godeps/_workspace/src/github.com/docker/docker/pkg/term/winconsole/console_windows_test.go
Godeps/_workspace/src/github.com/docker/docker/pkg/term/winconsole/term_emulator.go
Godeps/_workspace/src/github.com/docker/docker/pkg/term/winconsole/term_emulator_test.go
api/api.go
api/types.go
client/client.go
client/client_test.go
client/network.go
client/types.go
cmd/dnet/dnet.go
cmd/dnet/dnet_test.go
cmd/dnet/flags.go

- Fixed a few bugs in the client package
- Integrated client with API package (also separated types.go from api.go for readability)
- Added a new dnet tool to test and manage libnetwork & drivers end-to-end.
1. Start the dnet daemon `dnet -d`
2. Execute dnet commands `dnet network [create | rm | ls | info] -d <driver-name> <network-name>`
3. Use `dnet --help` for usage documentation
* More UI additions coming up in subsequent PRs.

Client / API integration & dnet tool

---

sandbox/namespace_linux.go
sandbox/sandbox_test.go

It may happen that the application (docker) may exit ungracefully
exit without calling leaves on endpoint and may result in stale
namespace files. So if a sandbox is created with the same key
attempt to cleanup the file if it exists before creating the
sandbox.

Cleanup namespace files

---

iptables/iptables.go

Porting https://github.com/docker/docker/pull/12437

---

endpoint.go
libnetwork_test.go

The container's /etc/resolv.conf permission was getting setup
as 0600 while it should be 0644 for every user inside the
container to be able to read it. The tempfile that we create
initially to populate the resolvconf content is getting created
with 0600 mode. Changed it to 0644 once it is created since there
is noway to pass mode option to ioutil.Tempfile

Fix /etc/resolv.conf permission issue

---

portmapper/mapper_test.go

This reverts commit 1d342509505b7f46b27d4c235c74319b519bd3e9.
(But retains the newly added & useful UDP test)
We need to identify the root-cause of how this never failed earlier.
Considering the fact that userland proxy is being deprecated, it is okay to revert to unblock folks.
Fixes #189 

Revert "Added more test coverage for portmapper package."

---

drivers/remote/driver.go
drivers/remote/driver_test.go
drivers/remote/messages.go
libnetwork_test.go

Implementation of `drivers/remote` using the plugins.Client to do RPCs with the remote process. 
Developed in conjunction with the prototypical https://github.com/squaremo/weave/tree/plugin_ipam, and using adaptations in https://github.com/squaremo/docker/tree/network_extensions to try it out (that fork has this branch vendored-in).
TODO

Implement remote driver

---

driverapi/driverapi.go
drivers/bridge/bridge.go
endpoint.go
endpoint_info.go
libnetwork_test.go
sandbox/namespace_linux.go
sandbox/sandbox.go
sandbox/sandbox_linux_test.go

Currently the driver api allows the driver to specify the
full interface name for the interface inside the container.
This is not appropriate since the driver does not have the full
view of the sandbox to correcly allocate an unambiguous interface
name. Instead with this PR the driver will be allowed to specify
a prefix for the name and libnetwork and sandbox layers will
disambiguate it with an appropriate suffix.

Modify driver Join api to only allow dst prefix

---

portmapper/mapper.go
portmapper/mapper_test.go
portmapper/proxy.go

It is needed in cases when mapped port is already bound, or another
application bind mapped port. All this will be undetected because we use
iptables and not net.Listen.

Add dummy proxy on port map

---

api/api.go
api/api_test.go
cmd/dnet/dnet.go

Though libnetwork api is supposed to handle the sub router, it is given
the entire URL to deal with. But the current api.go assumes the network/
to be in the root path.
We need this patch to make it work seamlessly with docker & dnet UI & API

Added a catch-all root hierarchy for the API path

---

api/api.go
api/api_test.go
client/network.go
drivers/bridge/bridge.go
drivers/bridge/bridge_test.go
drivers/bridge/interface.go
drivers/bridge/interface_test.go
drivers/bridge/network_test.go
drivers/bridge/port_mapping.go
drivers/bridge/port_mapping_test.go
drivers/bridge/setup.go
drivers/bridge/setup_device.go
drivers/bridge/setup_device_test.go
drivers/bridge/setup_fixedcidrv4.go
drivers/bridge/setup_fixedcidrv4_test.go
drivers/bridge/setup_fixedcidrv6.go
drivers/bridge/setup_fixedcidrv6_test.go
drivers/bridge/setup_ip_forwarding.go
drivers/bridge/setup_ip_forwarding_test.go
drivers/bridge/setup_ip_tables.go
drivers/bridge/setup_ip_tables_test.go
drivers/bridge/setup_ipv4.go
drivers/bridge/setup_ipv4_test.go
drivers/bridge/setup_ipv6.go
drivers/bridge/setup_ipv6_test.go
drivers/bridge/setup_verify.go
drivers/bridge/setup_verify_test.go
libnetwork_test.go

Support network options in rest api

---

client/network.go
drivers/bridge/bridge.go
drivers/bridge/bridge_test.go
drivers/bridge/network_test.go
drivers/bridge/port_mapping_test.go
drivers/bridge/setup_ipv4.go

Bridge driver to support multiple networks

---

sandbox/namespace_linux.go
sandbox/sandbox_linux_test.go
sandbox/sandbox_test.go

The networkNamespace struct will record all interfaces joined into this sandbox.
While RemoveInterface method does't remove the leaved interfaces.
Signed-off-by: junxu <xujun@cmss.chinamobile.com>

Fix RemoveInterface in sandbox

---

api/api.go
cmd/dnet/dnet.go

In one of the previous commit, we went to the extreme of supporting just
the /{version}/networks. Though that satisfied the requirements for UI
integration, it is not fully consistent with Docker APIs.
Docker API supports both /{version}/resource and /resource and hence we
must add the same support for networks resource.

Added API support for both /vx.x/networks & /networks

---

driverapi/driverapi.go
drivers/bridge/bridge_test.go
drivers/remote/driver_test.go
endpoint.go
endpoint_info.go
sandbox/configure_linux.go
sandbox/namespace_linux.go
sandbox/sandbox.go
sandbox/sandbox_linux_test.go
sandbox/sandbox_test.go
types/types.go

As suggested by @mrjana  and @mavenugo here's a rough outline for the API changes required to allow drivers to set static routes in the sandbox. 
Can you comment on this approach? If you think you could accept this PR I'll write the implementation and UTs.
I also expect I'll need to change the remote driver once @squaremo 's changes go in.

Add ability for drivers to set static routes

---

sandbox/namespace_linux.go
sandbox/sandbox_linux_test.go
sandbox/sandbox_test.go

This PR attempts to work around bugs present in kernel
version 3.18-4.0.1 relating to namespace creation
and destruction. This fix attempts to avoid certain
system calls to not get in the kernel bug path as well
as lazily garbage collecting the name paths when they are removed.

Workaround kernel bugs s related to namespaces

---

sandbox/namespace_linux.go

Removing this as this may cause problems when
multiple instances are  running.

Remove the init time cleanup of namespace files

---

drivers/bridge/bridge.go

Try to modprobe bridge driver specific kernel modules in case
they are not loaded into the kernel.

Modprobe bridge driver specific kernel modules

---

portallocator/portallocator.go

Do not have log output in packages that applications consume because the
output can mess with logs, stdout/stderr of applications and such and
there is nothing that the consumer can do about it other than change the
package that they are using.
Fixes https://github.com/docker/docker/issues/13373
Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

Do not warn in packages

---

README.md
api/api.go
api/api_test.go
cmd/readme_test/readme.go
controller.go
endpoint.go
libnetwork_test.go

Now that Endpoint interface has the Info method there is no
need to return container data as a return value in the Join
method. Removed the return value and fixed all the callers.

Remove container data return value from Join

---

sandbox/configure_linux.go

Without this they don't have the desired effect.
The default when creating these types of routes with `ip route add` is link - the old setting of universe was just wrong.

Change scope to LINK when setting device routes

---

endpoint.go

Here I noticed that variable "name" declared but not used, so remove those lines.

cleanup: remove unused variable

---

drivers/bridge/bridge.go

- To also return the configured exposed ports, besides the
port bindings; as now libnetwork/endpoint.go endpoint setters
separate the exposed ports and port binding configs.
Docker daemon will take care of aggregating the two sources
for presentation.

Change in bridge EndpointOperInfo()

---

Makefile
drivers/bridge/bridge_test.go
endpoint_info.go
hostdiscovery/hostdiscovery.go
hostdiscovery/hostdiscovery_api.go
hostdiscovery/hostdiscovery_disabled.go
hostdiscovery/hostdiscovery_test.go

In order to vendor-in libnetwork to docker, we need to remove the swarm
dependency even though it is used as library. using this PR, a new build
flag libnetwork_discovery is introduced in order to avoid pulling in the
unused hostdiscovery functionality into docker.
We are working with the Swarm project to see if we can modularize the
discovery package to become independent so that we can include them as a
vendor-in package in docker.

Moving hostdiscovery under build tag

---

client/network.go
drivers/bridge/bridge.go

This fix provides seamless connectivity for the newly created network using Bridge driver.
We should not be forcing the user to pass these default configuration for each bridge being created.
Also fixed a minor bug in client to choose bridge as the default driver

WIP : default configs for new network in bridge driver

---

drivers_freebsd.go

Cross-platform network drivers are introduced, making a stub to be able to compile libnetwork in FreeBSD.

make libnetwork compile on freebsd

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/vishvananda/netns/netns.go
Godeps/_workspace/src/github.com/vishvananda/netns/netns_linux.go
Godeps/_workspace/src/github.com/vishvananda/netns/netns_linux_386.go
Godeps/_workspace/src/github.com/vishvananda/netns/netns_linux_amd64.go
Godeps/_workspace/src/github.com/vishvananda/netns/netns_linux_arm.go
Godeps/_workspace/src/github.com/vishvananda/netns/netns_linux_ppc64le.go
Godeps/_workspace/src/github.com/vishvananda/netns/netns_unspecified.go

Current version of netns used in libnetwork do not have requisite syscall
entry for PowerPC (ppc64le) arch. Consequently docker which uses libnetwork fails
to create any network enabled containers on Power systems.
This patch updates netns to latest commit 5478c060110032f972e86a1f844fdb9a2f008f2c
to add ppc64le syscall entry.
Signed-off-by: Pradipta Kr. Banerjee <bpradip@in.ibm.com>

Update netns to include support for PowerPC LE (ppc64le) architecture

---

controller.go
sandbox/namespace_linux.go
sandbox/sandbox_linux_test.go
sandbox/sandbox_test.go

Right now the namespace paths are cleaned up every
garbage collection period. But if the daemon is restarted
before all the namespace paths of removed containers are
garbage collected they will remain there forever. The fix
is to provide a GC() api so that garbage collection can be
triggered immediately.

Add support to trigger immediate garbage collection

---

sandbox/namespace_unsupported.go

Signed-off-by: John Howard <jhoward@microsoft.com>
@swernli @mrjana 
This PR is part of the proposal described in docker/docker issue 10662 to port the docker daemon to Windows. Commit https://github.com/docker/libnetwork/commit/d4a567660796d8f0f8e850d386172654133bbc40 breaks compilation on Windows. This PR fixes that.

Windows: Allow compilation (again)

---

sandbox/namespace_linux.go

Calling GC() without ever creating a network namespace (sandbox on
Linux) will hang as the GC loop is not running (and therefore the
channel is not being listened to).
Tested via Docker that this corrects a daemon shutdown error if the
daemon is started and stopped without any containers or networks being
created while the daemon is up.
Docker-DCO-1.1-Signed-off-by: Phil Estes <estesp@linux.vnet.ibm.com>

Check GC loop is active/necessary before triggering GC

---

drivers/bridge/bridge.go

Currently we craete container mac address completely
randomly. But we probably need to generate based on
IP so that the mac address stays the same for a given
IP.

Generate container mac address based on IP

---

drivers/bridge/bridge.go
iptables/iptables.go
iptables/iptables_test.go

* When userland-proxy is disabled, enable hairpin mode on the host-side of the veth
* When userland-proxy is enabled, fix the iptable rules appropriately

enable hairpin mode on the bridge port & fix iptables rule

---

drivers/bridge/bridge.go
iptables/iptables.go
iptables/iptables_test.go

* When userland-proxy is disabled, enable hairpin mode on the host-side of the veth
* When userland-proxy is enabled, fix the iptable rules appropriately

Cherry-picked : enable hairpin mode on the bridge port & fix iptables rule

---

README.md
api/api_test.go
client/service.go
cmd/dnet/dnet.go
cmd/dnet/flags.go
cmd/readme_test/readme.go
cmd/test/main.go
config/config.go
controller.go
libnetwork_internal_test.go
libnetwork_test.go
store.go

The configuration format for docker runtime is based on daemon flags and
hence adjusting the libnetwork configuration to accomodate it by moving
the TOML based configuration to the dnet tool.
Also changed the controller configuration via options

Moved the TOML based Configuration to dnet

---

sandbox/interface_windows.go
sandbox/namespace_unsupported.go
sandbox/namespace_windows.go
sandbox/sandbox_unsupported.go

Signed-off-by: John Howard <jhoward@microsoft.com>
@swernli. After Sandbox was refactored to an Interface, Windows compilation was broken again. This fixes it up.

Windows: Fix compile after SB interface

---

controller.go

Since the Config is a read-only entity, Confg() method returned a value
instead of the pointer. In cases the config is nil, we should return an
empty config.

Return an empty config if nil

---

api/api.go
client/client_service_test.go
client/network.go
client/service.go
cmd/dnet/dnet.go
cmd/dnet/libnetwork.toml
config/config.go
config/config_test.go
controller.go
network.go

1. replaced --net option for service UI with SERVICE.[NETWORK] format
2. Making using of the default network/driver backend support
3. NetworkName and NetworkType from the UI/API can be empty string
and it will be replaced with DefaultNetwork and DefaultDriver
As per the design goals, we wanted to keep libnetwork core free of
handling defaults. Rather, the clients (docker & dnet) must handle the
defaultness of these entities.
Also, since there is no API to get these Default values from the
backend, UI will not handle the default values either.

Few changes to the UI and API implementation

---

client/client.go

In one of the latest docker UI updates, the flags structure expects to
have a ShortUsage function. Without that any UI event that triggers an
short usage panics.

Fixed a basic UI regression due to a recent godep update

---

drivers/bridge/bridge.go

This is required to have consistent behaviour as in 1.6.2.

Cleaning up iptables nat table on driver bootup

---

iptables/iptables.go
iptables/iptables_test.go

The `iptables.Exists` function is wrong in two ways:
1. The iptables -C call doesn't add `-j DOCKER` and fails to match
2. The long path takes ordering into account in comparison and fails to match
This patch fixes issue 1 by including `-j DOCKER` in the check.
Sorry for the lack of test: it's super late and I can't think anymore, but we definitely need to add one (I can try and do this tomorrow, or feel free to PR against my branch and I'll take it).
Fixes docker/docker#13956

Fix duplicated iptables rules

---

controller.go
datastore/datastore.go
endpoint.go
libnetwork_test.go
network.go
store.go

Along with the delete processing, have reorganized the code to reduce the number of events and streamlined the initial endpoint watch notifications strictly after network notifications which solves some corner case issues.

Distributed delete processing

---

cmd/dnet/libnetwork.toml
store.go

Currently we rely on watch to catchup after the init. But there could be
a small time window on which, we might end up in a race condition on
network creates. By reading and populating networks during init, we
avoid any such conditions, especially for default network handling.

Reading the top level element (network) from datastore on init

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/docker/libcontainer/netlink/MAINTAINERS
Godeps/_workspace/src/github.com/docker/libcontainer/netlink/netlink.go
Godeps/_workspace/src/github.com/docker/libcontainer/netlink/netlink_linux.go
Godeps/_workspace/src/github.com/docker/libcontainer/netlink/netlink_linux_arm.go
Godeps/_workspace/src/github.com/docker/libcontainer/netlink/netlink_linux_notarm.go
Godeps/_workspace/src/github.com/docker/libcontainer/netlink/netlink_linux_test.go
Godeps/_workspace/src/github.com/docker/libcontainer/netlink/netlink_unsupported.go
drivers/bridge/setup_device.go

Please see commit notes for more information

Use ioctl to create bridge

---

controller.go

without this fix, overlay driver returns an error and that causes the
daemon to quit.

set the kv-provider driver labels only if it is a valid config

---

endpoint.go

leave must not use join options in the defer during failures

---

controller.go
endpoint.go
error.go
libnetwork_test.go
sandbox/route_linux.go
sandboxdata.go
sandboxdata_test.go

Currently container can join one endpoint when it is started.
More endpoints can be attached at a later point in time. But
when that happens this attachment should only have meaning
only as long as the container is alive. The attachment should
lose it's meaning when the container goes away. Cuurently there
is no way for the container management code to tell libnetwork
to detach the container from all attached endpoints. This PR
provides an additional API `LeaveAll` which adds this
functionality,
To facilitate this and make the sanbox lifecycle consistent
some slight changes have been made to the behavior of sandbox
management code. The sandbox is no longer destroyed when the
last endpoint is detached from the container. Instead the sandbox
ie kept alive and can only be destroyed with a …

Add LeaveAll support

---

etchosts/etchosts.go
etchosts/etchosts_test.go
network.go

There is no need to update the /etc/hosts files
of containers for endpoints which are created/deleted
in a network whose interface list is empty

Do not update /etc/hosts for empty endpoints

---

drivers/bridge/bridge.go

The usage of getNetwork can cause nil pointer error when the network not found
```
network, err := d.getNetwork(nid)
if err != nil {
return err
}
endpoint, err := network.getEndpoint(eid)
if err != nil {
return err
}
```

Update error return in bridge driver's getNetwork

---

Godeps/Godeps.json
bitseq/sequence.go
bitseq/store.go
config/config.go
controller.go
datastore/datastore.go
datastore/datastore_test.go
datastore/mock_store.go
drivers/overlay/ov_network.go
endpoint.go
ipam/allocator.go
ipam/store.go
network.go
store.go

This commit relies on https://github.com/docker/libkv/commit/60c7c881345b3c67defc7f93a8297debf041d43c
In that commit, AtomicPutCreate takes previous = nil to Atomically create keys
that don't exist.  We need a create operation that is atomic to prevent races
between multiple libnetworks creating the same object.
Previously, we just created new KVs with an index of 0 and wrote them to the
datastore.  Consul accepts this behaviour and interprets index of 0 as
non-existing, but other data backends do no.
- Add Exists() to the KV interface.  SetIndex() should also modify a KV so
that it exists.
- Call SetIndex() from within the GetObject() method on DataStore interface.
- This ensures objects have the updated values for exists and index.
- Add SetValue() to the KV interface.  This allows …

Datastore handles creating objects atomically.

---

drivers/bridge/bridge.go

In my host, it prints a warning, there's no useful error message:
```
WARN[0000] Running modprobe bridge nf_nat failed with message: , error: exit status 1 
```
I figure out this is because of missing br_netfilter module, so I just update the code to make it clearer.

Update modprobe bridge output

---

drivers/bridge/bridge.go

Some parts of the bridge driver code needs to use a different kernel
api or use the already existing apis in slightly different ways to
make the bridge driver work in RHEL/Centos 6.6. This PR provides
those fixes.

Fix networking issues in RHEL/Centos 6.6

---

drivers/host/host.go
endpoint.go
libnetwork_test.go

For the moment in 1.7.1 since we provide a resolv.conf set api
to the driver honor that so that for host driver we can use the
the host's /etc/resolv.conf file as is rather than putting the
contents through a filtering logic.
It should be noted that the driver side capability to set the
resolv.conf file is most likely going to go away in the future
but this should be fine for 1.7.1

Honor driver side resolv.conf file

---

bitseq/sequence.go

- We must ignore key not found error when querying
datastore for initial state.
- Regression introduced by e2a63dff5a38a0f26f7f0c36356f3a6a28f4efeb

Fix incorrect error handling in bitseq constructor

---

bitseq/store.go

When bit sequence is trying to get key/value from the
data store it should always unmarshall the json data
before using it, as the data is JSON marshalled before
storing it in the data store.

BitSequence should unmarshal data during get

---

Makefile

When building libnetwork, I got the following error 
```
package github.com/tools/godep
imports github.com/kr/fs
imports golang.org/x/tools/go/vcs: unrecognized import path "golang.org/x/tools/go/vcs"
```
This is because golang.org is blocked in China by GFW. But there is a mirror of golang.org/x/tools at github, I suggest to use this mirror repo instead.

Use github golang tools mirror

---

drivers/bridge/bridge.go
drivers/bridge/setup_bridgenetfiltering.go
drivers/bridge/setup_bridgenetfiltering_test.go

This is a port of docker PR #11405 code into the libnetwork codebase.
It will solve docker issue #11404.
Signed-off-by: Alec Benson <albenson@redhat.com>

Refactor of docker PR #11405

---

drivers/bridge/bridge.go
drivers/bridge/setup_fixedcidrv6_test.go

When fixed-cidrv6 is used, the allocation and release must happen from
the appropriate network. Allocation is done properly in createendpoint,
but the DeleteEndpoint wasnt taking care of this case.

Fixed a bug in DeleteEndpoint to properly release v6 ip

---

README.md

libnetwork.New() should return a controller and an error. The
example in README.md ignore the error now, which will let the
codes can not be compiled by Go.

FIX incorrect usage about libnetwork.New() in README.md

---

drivers/overlay/peerdb.go

When you start a container after some other container has already
been started in the same network, the current container will have
an fdb which points to a wrong vtep to reach the already started
container. This makes the network connectivity to not work. The root
cause of the issue is because of golang does variable capture by
reference in closures and so we cannot use the return values from
range iterators directly. It needs to be copied to a locally scoped
variable and then use that copy as a capture variable in the closure.
Fixes #338 

Sometimes fdb points to wrong vtep

---

sandbox/route_linux.go

there was an extra Lock(), which caused a deadlock during static route removal.

deadlock fix in RemoveStaticRoute

---

drivers/bridge/bridge.go
drivers/bridge/bridge_test.go
drivers/bridge/setup_ipv4.go

- Currently both network and host bits in the subnet are passed
when requesting an address from ipallocator.
The way ip allocator determines the first available
IP is tainted when caller passes the subnet host bits.
- Verified this patch applied to libnetwork vendored in docker
fixes the issue when starting the daemon.
- Verified issue is also present in libnetwork master. In bridge_test.go
changes to TestCreateFullOptions() are necessary to uncover the issue
(if fix wasn't there)
- Fixes #287

Pass a canonical subnet to ipallocator

---

drivers/bridge/bridge.go
drivers/bridge/link.go
drivers/bridge/setup_firewalld.go
drivers/bridge/setup_ip_tables.go
portmapper/mapper.go

On a system with firewalld enabled, start two containers (name them one and two, respectively). Link them together. In the first, run "nc -l -p 1234". In the other, run "nc one 1234". Prior to this patch, this will not work. After this patch, everything works as expected. 
On systems with firewalld turned off (or not present), everything still works fine. 
The  error is caused by an out-of-order IP table rule. 
Iptables -nvL on an affected system shows the following:
```
Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
pkts bytes target     prot opt in     out     source               destination         
0     0 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
0     0 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate …
```

Fix ICC on Fedora systems with Firewalld

---

drivers/bridge/bridge.go

Set the hairpin mode using the sysfs interface which
looks like it is working all the way to the oldest
of RHEL6.6 kernels.

Use sysfs to set hairpin mode

---

drivers/bridge/bridge.go
drivers/bridge/setup_ipv4.go
types/types.go

Two changes were missing:
- On allocation of bridge ip was not passing canonical subnet
- Canonical subnet has to be passed on ip release
as well, otherwise ipallocator will attempt
ip release from a non registered nw, and addresses do not get actually released

Misc fixes to ip allocation in bridge driver

---

drivers/bridge/bridge.go
drivers/bridge/bridge_test.go
drivers/bridge/setup_ipv4.go
drivers/bridge/setup_ipv4_test.go
ipallocator/allocator.go
netutils/utils.go

- NetworkRange() function on which ipallocatore relies
to get the subnet limits has a bug in computing the upper limit IP
- in case container subnet is specified (fixedCIDR), bridge driver has to
reserve bridge and gateway addresses only if they belong to the
container subnet
- Make ipallocator more robust converting the passed network
to a canonical one before using its string form as a key in its public APIs
- Fixes issue reported in docker/docker #14859 [comment](https://github.com/docker/docker/issues/14859#issuecomment-125124552)

Misc fixes to ipallocator & bridge driver about FixedCIDR

---

drivers/bridge/bridge.go

In case an error occured the unused interfaces should be cleared.
See https://github.com/docker/docker/issues/14738#issuecomment-124035441

make sure the interfaces is cleared on error

---

drivers/bridge/setup_device.go

- Kernel version check logic was wrong

Incorrect kernel version check in bridge

---

drivers/bridge/bridge.go
drivers/bridge/setup_device.go

As seen in https://github.com/docker/docker/issues/14738 there is
general instability in the later kernels under race conditions when ioctl
calls are used in parallel with netlink calls for various operations.
(We are yet to narrow down to the exact root-cause on the kernel).
For those older kernels which doesnt support some of the netlink APIs,
we can fallback to using ioctl calls. Hence bringing back the original
code that used netlink (https://github.com/docker/libnetwork/pull/349).
Also, there was an existing bug in bridge creation using netlink which
was setting bridge mac during bridge creation. That operation is not
supported in the netlink library (and doesnt throw an error either).
Included a fix for that condition by setting the bridge mac after
creating the bridge. …

Prefer Netlink over ioctl

---

docs/Vagrantfile
docs/vagrant-systemd/docker.service

14.10 reached EOL recently and hence experimental builds are not built for
that distro any more. Upgrading it to 15.04 means handling the systemd
specific docker daemon configs required for multi-host networking.

Fixing Vagrant to use ubuntu 15.04 to pull Experimental docker version

---

drivers/bridge/setup_ip_tables.go

```
[root@c182 /data/home/gaia]# iptables -S POSTROUTING -t nat
-P POSTROUTING ACCEPT
-A POSTROUTING -s 192.168.1.0/24 ! -o docker0 -j MASQUERADE 
-A POSTROUTING -s 192.168.1.0/24 ! -o docker0 -j MASQUERADE 
-A POSTROUTING -s 192.168.1.0/24 ! -o docker0 -j MASQUERADE 
//docker log
time="2015-07-13T16:01:07.998115730+08:00" level=debug msg="/sbin/iptables, [-t nat -C POSTROUTING -s 192.168.1.1/24 ! -o docker0 -j MASQUERADE]" 
time="2015-07-13T16:01:08.000518242+08:00" level=debug msg="/sbin/iptables, [-t nat -I POSTROUTING -s 192.168.1.1/24 ! -o docker0 -j MASQUERADE]" 
```
https://github.com/docker/docker/pull/12437 removed regexp from `Exists` function and it has side effects on creating these duplicate rules with old iptable version.
Since …

Fix duplicate POSTROUTING MASQUERADE rules

---

drivers/bridge/setup_ipv4.go
drivers/bridge/setup_ipv4_test.go

- that was causing all the statically allocated bridge networks to be /24

Bug in bridge network mask

---

README.md

Since type `portBinding` has been moved to package  `libnetwork/types` [1], so update the example.
[1]https://github.com/docker/libnetwork/blob/master/types/types.go#L26

Fix example package error

---

endpoint.go
sandbox/namespace_linux.go

Please review; I think it's of moderate importance as ignoring error from MkdirAll can lead to some other error later and it could be hard to track the cause down to failed MkdirAll.

Simplify and fix os.MkdirAll() usage

---

drivers/bridge/bridge.go
drivers/bridge/errors.go
drivers/bridge/setup_ip_forwarding.go
drivers/bridge/setup_ip_forwarding_test.go

This seems redunant:
https://github.com/docker/libnetwork/compare/docker:master...runcom:remove-unused-config-check?expand=1#diff-d7584a11ca25df23d34e42758563aba7L15
`ErrIPFwdCfg` is not used anymore, the function doesn't depend on the config...
The test for `ErrIPFwdCfg` is removed
Since it's only called checking the config from the outside. Hope it's good :)
Signed-off-by: Antonio Murdaca <runcom@linux.com>

Remove unused config check

---

api/api_test.go
drivers/bridge/bridge.go
drivers/bridge/bridge_test.go
drivers/bridge/link.go
drivers/bridge/network_test.go
drivers/bridge/port_mapping_test.go
drivers/bridge/setup_firewalld.go
drivers/bridge/setup_ip_tables.go
drivers/bridge/setup_ip_tables_test.go
iptables/firewalld_test.go
iptables/iptables.go
iptables/iptables_test.go
libnetwork_test.go
portmapper/mapper.go
portmapper/mapper_test.go

for the bridge driver. Moves two config options, namely EnableIPTables and EnableUserlandProxy
from networks to the driver. Fixes #242 
Signed-off-by: Mohammad Banikazemi <MBanikazemi@gmail.com>

Separates the driver-specific and network-specific iptable operations

---

endpoint.go

- In case of sandboxAdd() failure, drive.Leave() call
in first executed defer resets err to nil. Secondly
executed defer in charge of resetting ep.container to nil
will not be executed, leaving endpoint thinking it is still
joined by the container.

Fix bug "...has already joined the endpoint"

---

drivers/bridge/bridge.go

- In DeleteEndpoint(), veth removal is a best effort,
as it could have alreayd been removed by sandbox destroy.
Therefore if veth is not found, cleanup defer function
should not run.

Fix in bridge delete endpoint

---

drivers/bridge/port_mapping.go
libnetwork_test.go
portallocator/portallocator.go
portallocator/portallocator_test.go
portmapper/mapper.go
types/types.go

See https://github.com/docker/docker/pull/12927 for docker portion.
This adds support for PortMapper.MapRange and PortAllocator.RequestPortInRange, used by the docker pull #12927.
Changes should be backwards compatible for use by docker master.

Adding libnetwork support to publish on custom host port ranges.

---

drivers/overlay/ov_endpoint.go

After a container restart sometimes the same IP that was assigned before gets assigned. But the mac is randomly generated. So other containers in the same overlay will have a connectivity issue till a new ARP gets generated.
Closes #395 

Overlay driver should assign interface mac based on the IP

---

resolvconf/resolvconf.go
resolvconf/resolvconf_test.go
sandbox.go

This is needed to expose DNS options like 'ndots' into containers.
https://github.com/docker/docker/issues/14069
Signed-off-by: Tim Hockin <thockin@google.com>

Add DNS 'options' support

---

api/api_test.go
drivers/bridge/bridge.go
drivers/bridge/bridge_test.go
drivers/bridge/interface_test.go
drivers/bridge/network_test.go
drivers/bridge/port_mapping_test.go
drivers/bridge/setup_device_test.go
drivers/bridge/setup_fixedcidrv4_test.go
drivers/bridge/setup_fixedcidrv6_test.go
drivers/bridge/setup_ip_tables_test.go
drivers/bridge/setup_ipv4_test.go
drivers/bridge/setup_ipv6_test.go
drivers/bridge/setup_verify_test.go
drivers/overlay/ov_utils.go
libnetwork_test.go
netutils/test_utils.go
sandbox/namespace_linux.go
sandbox/namespace_windows.go
sandbox/sandbox_freebsd.go
sandbox/sandbox_test.go
sandbox/test_linux.go

Make sure to always explicitly set namespace for all
kernel bound network operations irrespective of whether
the operation is performed in init namespace or a user
defined namespace. This already happens for user defined
netns. But doesn't happen for initial netns that libnetwork
runs in.

Explicitly set namespace for all network operations

---

options/options.go
options/options_test.go

If initializing bridge driver with `netOption := options.Generic{"EnableIPMasquerade": "true"}`, it will cause a panic.
```
panic: reflect.Set: value of type string is not assignable to type int [recovered]
panic: reflect.Set: value of type string is not assignable to type int
goroutine 5 [running]:
testing.func·006()
/usr/src/go/src/testing/testing.go:441 +0x181
reflect.Value.assignTo(0x5358c0, 0xc20802a4b0, 0x58, 0x5bd6d0, 0xb, 0x5351c0, 0x0, 0x0, 0x0, 0x0)
/usr/src/go/src/reflect/value.go:2125 +0x368
reflect.Value.Set(0x5351c0, 0xc20802a4e0, 0xc2, 0x5358c0, 0xc20802a4b0, 0x58)
/usr/src/go/src/reflect/value.go:1298 +0x96
github.com/docker/libnetwork/options.GenerateFromModel(0xc20800a510, 0x574220, 0xc20802a498, 0x0, 0x0, 0x0, 0x0) …
```

Fix panic due to mismatched types

---

resolvconf/resolvconf.go
resolvconf/resolvconf_test.go
sandbox.go

Two issues:
- container resolv.conf getting regenerated even when no dns configs are passed
- updateHosts should be skipped for host networking mode
- incorrect check on dnsOptions

Fix resolv.conf and hosts handling in sandbox

---

controller.go
libnetwork_test.go
sandbox.go

- Convinience API which detaches the sandbox from
all endpoints, resets and reapply config options,
setup discovery files, reattach to the endpoints.
No change to the osl sandbox in use.

Add Refresh() to Sandbox

---

portmapper/mapper.go

Make sure that port mapper state is not updated while we are trying to remap everything.

lock port mapper when reapplying iptables rules

---

Makefile
wrapmake.sh

Currently when libnetwork tests are run inside a container
you cannot interrupt them in the middle by pressing ctrl-c
even though all the tests run in foreground. Fix this by running
tests by wrapping the make invocation inside the container
with a shell scripts which installs the SIGINT handler.
Without the handler the kernel does not deliver signals
to the process with PID 1(which in this case was make itself)
and hence make could never be interrupted. With this fix
we capture SIGINT in the shell script and re-raise it in the
the child process (which is make) and that makes the make
interruptible.

Allow tests to be interrupted

---

api/api.go

Error messages are always discarded and it makes diagnostic difficult
when error occurs.
Before:
$ dnet network create -d overlay ov1
error : ""
$ docker network create -d overlay ov1
Error response from daemon: ""
After:
$ dnet network create -d overlay ov1
error : "no datastore configured. cannot obtain vxlan id"
$ docker network create -d overlay ov1
Error response from daemon: "no datastore configured. cannot obtain vxlan id"
Breakage caused by  7b8bb3e
Signed-off-by: Toshiaki Makita <makita.toshiaki@lab.ntt.co.jp>

Don't discard error message on sending response

---

api/api_test.go

Test if error messages from daemon are not empty strings.
Confirmed it fails without 8aa9f4e.
--- FAIL: TestEndToEndErrorMessage (0.03s)
api_test.go:2266: Empty response error message.
Signed-off-by: Toshiaki Makita <makita.toshiaki@lab.ntt.co.jp>

Add TestEndToEndErrorMessage

---

drivers/bridge/bridge.go
drivers/bridge/bridge_test.go
drivers/bridge/setup_ipv4.go
drivers/bridge/setup_ipv4_test.go

- Do not discard errors on ip allocation for gw and bridge
- Release addresses on network delete
- Add some context on top of ipallocator returned error

Fixes ip allocation for multi bridge networks

---

Godeps/_workspace/src/github.com/docker/libkv/.travis.yml
Godeps/_workspace/src/github.com/docker/libkv/libkv.go
Godeps/_workspace/src/github.com/docker/libkv/libkv_test.go
Godeps/_workspace/src/github.com/docker/libkv/script/travis_consul.sh
Godeps/_workspace/src/github.com/docker/libkv/store/consul/consul.go
Godeps/_workspace/src/github.com/docker/libkv/store/consul/consul_test.go
Godeps/_workspace/src/github.com/docker/libkv/store/etcd/etcd.go
Godeps/_workspace/src/github.com/docker/libkv/store/etcd/etcd_test.go
Godeps/_workspace/src/github.com/docker/libkv/store/mock/mock.go
Godeps/_workspace/src/github.com/docker/libkv/store/store.go
Godeps/_workspace/src/github.com/docker/libkv/store/zookeeper/zookeeper.go
Godeps/_workspace/src/github.com/docker/libkv/store/zookeeper/zookeeper_test.go
Godeps/_workspace/src/github.com/docker/libkv/testutils/utils.go
drivers/bridge/bridge.go
drivers/bridge/bridge_test.go

Bridge driver panics in `CreateNetwork` if called without
a prior `Config` call. This causes issues in dnet which
tries to create network using default driver configuration.
It should be valid to call `CreateNetwork` without a prior
`Config` call in which case we need to assume default driver
config.
Fixed this by properly initializing the driver config pointer.
Also introduced a `configured` bool to make sure that still
`Config` is called exactly once for the instance of the bridge
driver.

Fix bridge driver panic in CreateNetwork

---

client/service.go

fix bug for `docker service ls` error:
"Failed to retrieve backend list for service xxx (json: cannot
unmarshal object into Go value of type []client.sandboxResource)"
Detailed error info is like this:
```
$ docker service publish test
$ docker service ls
Failed to retrieve backend list for service 1293e3ca8d221f9bf8a023c4bc7b9e65143c7f308bbd2d04f18f89050ab95901 (json: cannot unmarshal object into Go value of type []client.sandboxResource)SERVICE ID          NAME                NETWORK             CONTAINER
1293e3ca8d22        test                bridge
```
It looks like we are trying to unmarshal body into wrong object format.
I'm not very familiar with this part of code, let me know if there is any problem about this. :)

Fix bug for `docker service ls`

---

cmd/dnet/dnet.go

Signed-off-by: Toshiaki Makita <makita.toshiaki@lab.ntt.co.jp>
---
Note: Docker has the same problem in api/server/server_experimental_unix.go.
"docker service attach" doesn't work.

Add missing sandboxes routes

---

client/service.go

CmdServiceDetach() incorrectly uses containerID where sandboxID is
expected. Thus, procDeleteSandbox() fails to find the corresponding
sandbox and returns the "Resource not found" error.
Signed-off-by: Toshiaki Makita <makita.toshiaki@lab.ntt.co.jp>

Fix inability to detach service

---

.gitignore
Makefile
cmd/dnet/dnet.go
test/integration/dnet/helpers.bash
test/integration/dnet/simple.bats

Currently libnetwork does not have any integration test infra
support to tests libnetwork code end2end purely as a black
box. This initial commit adds the infra support to enable
test cases for this.

Add integration test infra

---

test/integration/dnet/helpers.bash

- So test will not fail because container is already there
Prefer this to re-use the containers as it would contain
states from last run
- A stale consul or dnet container condition will happen
in case the previous integ test run aborted

Remove stale consul container first

---

client/client_test.go
client/service.go

- it is supposed to be called after lookupContainerID()
but the latter is not guaranteed to succeed and in
case of connection error will return what was passed
to it.
So in order to be able to operate with both long and short
container ids in case of lookupContainerID() failure,
always search by `partial-container-id`

Make lookupSandboxID() reliable

---

libnetwork_test.go

- otherwise "ValidKey" file is left behind

Cleanup external sandbox from test

---

docs/remote.md
drivers/remote/api/api.go
drivers/remote/driver.go
drivers/remote/driver_test.go

Related issue:  #486
Add one capability negotiation interaction process after plugin handshake, use
this to determine plugin's capability instead of default "global" scope.

Add negotiation process for driver scope

---

endpoint.go

Instead of passing the pointer to &ep.iface the current
code is passing the value. So the source variable is not
getting updated properly.

Fix unmarshal error in endpoint interface

---

Makefile
store.go
store_test.go

For both etcd and zookeeper, it's not allowed to watch a not exist node.
Tested on my laptop. Please don't review until https://github.com/docker/libkv/pull/41 get's in.

Fix for zookeeper backend

---

Makefile

- and cleanup dnet binary when done

Make integration-tests an indipendent target

---

cmd/dnet/dnet.go
drivers/remote/driver.go
test/integration/dnet/simple.bats

There are multiple goals of introducing test driver plugin
- Need a driver which can be configured to simulate
different driver behaviors
- For pure libnetwork multi-host integration testing
a test driver configured for global scope can be used
without trying to use a real driver like overlay
which comes with it's own dependencies which can't
be satisfied all enviroments(I am looking at you
circleci)
This PR also makes all test cases that we have so far to be run
in circleci without any skipping needed.

Introduce test remote plugin in dnet

---

osl/namespace_linux.go
sandbox.go

Directories should be 0755, not 0644
Docker-DCO-1.1-Signed-off-by: Phil Estes <estesp@linux.vnet.ibm.com> (github: estesp)

Correct perms for directory creation

---

Makefile
test/integration/dnet/dnet.bats
test/integration/dnet/helpers.bash
test/integration/dnet/multi.bats
test/integration/dnet/run-integration-tests.sh
test/integration/dnet/simple.bats

- Create a wrapper script to run intergation tests
so that setups and teardowns happen in more
optimal manner
- Add traps to cleanup containers on failure or
user interrupt
- Introduce basic multi-node integration tests
- Removed default network, default driver tests
as they may not be useful in the near future

Introduce multi-node integration tests

---

default_gateway.go
drivers/overlay/joinleave.go
endpoint.go
sandbox.go

If a containers endpoints doesn't have the GW set by the driver libnetwork creates an endpoint on a 
bridge network which acts as default gateway for external connectivity.

Support for default gateway for containers

---

bitseq/store.go
controller.go
datastore/datastore.go
datastore/datastore_test.go
drivers/overlay/ov_network.go
endpoint.go
ipam/store.go
network.go
store.go
store_test.go

Providing KVObject option to skip persisting object in kvstore

---

Makefile
client/service.go
cmd/dnet/dnet.go
sandbox.go
test/integration/dnet/helpers.bash
test/integration/dnet/overlay.bats
test/integration/dnet/run-integration-tests.sh

This PR introduces end to end overlay integration tests. To make it work the following commits were
made:
- Add necessary bats testing code and functions
- Add sandbox ID to the `service ls` output so that it can be used to setup container
- The test found an important /etc/hosts bug which was fixed

Introduce end to end overlay integration test

---

api/api.go
api/api_test.go
cmd/dnet/dnet.go
default_gateway.go
drivers/bridge/bridge.go
drivers/bridge/bridge_test.go
drivers/bridge/errors.go
drivers/bridge/setup_device.go
drivers/bridge/setup_device_test.go
drivers/bridge/setup_ipv4.go
libnetwork_test.go
sandbox_test.go

Replaced it with DisallowNonDefaultBridge and it can be used ONLY in
a special case for docker0 bridge from docker, instead of calling it
from all other case.

Flip the default for the flag AllowNonDefaultBridge in bridge driver

---

controller.go
drivers/bridge/bridge.go
drivers/bridge/bridge_test.go
drivers/bridge/setup_device.go
drivers/bridge/setup_device_test.go
drivers/bridge/setup_ipv4.go
drivers/overlay/ov_network.go
drivers/overlay/overlay.go
drivers/overlay/overlay_test.go
sandbox_externalkey.go
store_test.go

- Using network-id as bridge name for networks created using bridge driver.
- Moved overlay configure() out of Init() and into network create.

Fixes in bridge and overlay drivers

---

drivers/overlay/ov_serf.go
drivers/overlay/overlay.go

With the recently introduced docker discovery, the self node discovery
notification can reach the overlay driver after the remote node
discovery notification.  In scenarios such as 2 node setup, it seems more
likely. In those scenarios, the serfJoin is not triggered and hence the
neighborship is not formed between the 2 nodes.
The fix is to retain the knowledge of the neighbor and reuse it
immediately after the serfInit is done. Since we do the serfJoin just
once, there is no harm in changing the neighIP to a new value even if it
is not used.

serfJoin doesnt happen if self notification comes later

---

drivers/overlay/joinleave.go
drivers/overlay/overlay.go
drivers/overlay/peerdb.go

With the new Discovery model, join can happen even before serf is
initliazed. It could also happen due to misconfiguration of
--cluster-advertise. The local endpoint join must succeed and later when
the serf initializes and joins the cluster, it will push the local db to
the cluster.

Allowing local joins to happen even when serf is not initialized

---

bitseq/sequence.go

- When creating the handle, write it to store if not present. 
Currently it is written to store only on first bit allocation, lazily. 

Fix in bitseq.NewHandle()

---

ipam/allocator.go
ipam/allocator_test.go
ipam/store.go
ipam/structures.go
ipam/utils.go

- based on address space scope, default ipam will store the
pools configuration in the local or global datastore.
- address scope locality is known for default local/global
ipam address spaces. And it will be configured out of band
for custom address spaces when UX will allow to specify them.

Default IPAM to handle local ds

---

ipam/allocator.go

Currently the default ipam implementation ignores the prefered ip if the
request is made if sub-pool is configured. The priority should be other
way around.

ipam must honor preferedIP ahead of random allocation from subPool

---

resolvconf/dns/resolvconf.go

this is a minor error that could cause some unexpected results;
and actually this following form would be more compact:
```go
+const IPLocalhost = `((127(\.[0-9]{1,3}){3})|(::1))`
```
Let me know if you need unit test cases I can write some.

fix the regexp for matching an ip address

---

ipam/allocator.go
ipam/utils.go
ipamutils/utils.go
ipamutils/utils_test.go

+ Now that IPAM driver is part of CNM (therefore IP allocation is no longer part of bridge driver), libnetwork will provide this ipam utility pkg for docker daemon code to retrieve the network/address to pass on to libnetwork in the form of `IpamConfig` for the default `docker0` bridge network, in order to maintains existing behavior for end user.
+ Have default ipam driver reuse this package

ipamutils package

---

libnetwork_test.go
osl/interface_linux.go
osl/sandbox.go
osl/sandbox_linux_test.go
sandbox.go
types/types.go

Exposing osl package outside libnetwork is not neccessary and the
InterfaceStatistics anyways belong to the types package.

Moved InterfaceStatistics from osl into types package

---

cmd/ovrouter/ovrouter.go
drivers.go
drivers/overlay/overlay.go
netlabel/labels.go

- Renamed netlabel prefixes to accomodate both global
and local store configs.
- Added a `private` marker.
- Skipping the data store configs for remote driver
so that external plugins don't get it as there is
no secure and sane way to coordinate providing
data store access to external plugins.

Pass down store configs to driver

---

datastore/datastore.go
store_test.go

Currently every `NewDatastore` creates a brand new
libkv store handle. This change attempts to share
the libkv store handle across various datastore handles
which share the same scope configuration. This enables
libnetwork and drivers to have different datastore handle
based on the same configuration but share the same
underlying libkv store handle.
This is mandatory for boltdb libkv backend because no two
clients can get exclusive access to boltdb file at the same
time. For other backends it just avoids the overhead of having
too many backend client instances

Share libkv store handles across datastore handles

---

ipam/allocator.go
libnetwork_internal_test.go
network.go

- libnetwork should reserve only the auxiliary
addresses which belong to the requested pool

Fix in handling aux addresses

---

controller.go
endpoint.go
endpoint_info.go
libnetwork_internal_test.go
network.go

Same as it does for v4 addresses. Only differences:
+ on network create it does not auto request an IPv6 pool if explicit V6 `IpamConfig` was not passed as network option
+ on endpoint create it does not consider an error to receive an empty list of `IpamInfo` for IPv6

libnetwork to handle allocation of ipv6

---

controller.go
endpoint.go
libnetwork_test.go
sandbox.go
sandbox_store.go
store_test.go
test/integration/dnet/bridge.bats

Currently when docker exits ungracefully it may leave
dangling sandboxes which may hold onto precious network
resources. Added checkpoint state for sandboxes which
on boot up will be used to clean up the sandboxes and
network resources.
On bootup the remaining dangling state in the checkpoint
are read and cleaned up before accepting any new
network allocation requests.

Cleanup dangling sandboxes on boot up

---

config/config.go
config/config_test.go
network.go

* endpoint names can contain `.`
* any newly added variables must be checked for nil before type assertion in unmarshal
(due to existing data in the store)

Fixed a few issues identified during docker integration

---

config/config.go
config/config_test.go

This adds a new options configuration routine that the engine
can call in order to configure TLS for libnetworks KV store.
Signed-off-by: Daniel Hiltgen <daniel.hiltgen@docker.com>

Add support for configuring TLS

---

test/integration/dnet/bridge.bats
test/integration/dnet/helpers.bash

Currently integration test is a bit flaky because of
variability in the dnet bootup time. Fixed it to wait for
dnet to come up before performing any tests.

Make the integration tests robust

---

network.go
store.go

Today we try to increment/decrement endpoint count
only once even if it is a key modified error. In case
of key modified error we should retry it to allow it to
succeed.

Network ep count increment/decrement needs retry

---

libnetwork_internal_test.go
network.go

- Both an empty and nil list of IpamConf object
will trigger autoallocation for ipv4.
Autoallocation for ipv6 will still be excluded
in the two cases above.

Relax restriction on IpamConfig

---

bitseq/sequence.go
bitseq/sequence_test.go
drivers/overlay/ov_network.go
idm/idm.go
ipam/allocator.go
ipam/allocator_test.go
ipam/structures.go
ipam/utils.go
libnetwork_test.go
sandbox_store.go

- Removed 2^32-1 bit number limitation in bitsequence
This simplify IPv6 subnet management in IPAM
- Reduced log verbosity in IPAM and sandbox store

Remove num bit limitation in bitsequence

---

ipamutils/utils.go
ipamutils/utils_linux.go
ipamutils/utils_windows.go

currently ipamutils package uses apis which are linux
specific and makes windows compile error out. Separated
the OS specific apis into linux and windows files to
diverge the implementation.

Make ipamutils compile for windows

---

config/config.go
datastore/datastore.go
datastore/datastore_test.go

This is required in order to provide a clean switchover.

Moved the default local and global store to new root

---

ipams/remote/api/api.go
ipams/remote/remote.go
ipams/remote/remote_test.go

- Avoid net.IP and net.IPNet types to ease marshalling/unmarshalling
at client and server side

Change in remote IPAM API payload

---

test/integration/dnet/helpers.bash
test/integration/dnet/run-integration-tests.sh

- With the selectively running a suite support
one can do the following to select which suite
of tests to run:
SUITES="simple multi" sudo -E make integration-tests
- Refactored and cleaned up some ununsed code in helpers.bash
- Added discover string parse function to parse discovery
string into provider and address

Add support for selectively running a suite

---

test/integration/dnet/helpers.bash
test/integration/dnet/overlay-etcd.bats
test/integration/dnet/overlay-zookeeper.bats
test/integration/dnet/run-integration-tests.sh

- Added etcd integration test for overlay
- Added etcd integration test for multinode
with mock test driver suitable for circleci
- Added multinode tests for zookeeper
- Made the script smart enough to only start
data stores necessary for the requested suites

Add etcd integrations tests

---

datastore/datastore.go

Signed-off-by: Lei Jitang <leijitang@huawei.com>
fixes https://github.com/docker/docker/issues/17007
For HA, user always specify multiple store address.

Fix docker daemon failed to start with multiple cluster store address

---

drivers/bridge/bridge_test.go
ipamutils/utils_linux.go

During the run of `TestCreateMultipleNetworks()` (which runs in  a netns) occasionally `ipamutils.ElectInterfaceAddresses()` returns a network which is already being used, causing the test to fail. While debugging the test failure it turned out  the root cause was netutils.CheckRouteOverlaps() returning host routes during the failure. This looks the same issue that was fixed by #476. 
Now that the address pool election is moved away from bridge code into ipamutils via #588 , its execution is no longer tied to the netns by the fix introduced in #476.
In fact the random `TestCreateMultipleNetworks()` failures in circle ci started after #588.
Closes #652 

Explicitly set namepsace for ipamutils.ElectInterface

---

Makefile
netutils/utils.go

Use `netlink.LinkByName` instead of `net.InterfaceByName`, it improved container starting speed in docker tremendously.
Also I fixed image name in `Makefile`.

Improve name gen

---

drivers/bridge/bridge.go
endpoint.go

Bridge driver should return maskable error during Leave
or DeleteEndpoint since this can be an expected sceanrio
when libnetwork tries to leave and delete default bridge
endpoints and bridge driver does not persist with the default
bridge. This is only expected during an ungraceful exit of
the daemon but will cause confusion to the user if it shows
up as failures on a deamon restart after an ungraceful exit.

Bridge driver should return maskable error

---

controller.go
endpoint.go
store.go

When we bootup cleanup all dangling local
endpoints since they are not needed anymore.
The only reason it can happen is when the process
went down ungracefully after an endpoint is
created but before join is successfull.

Cleanup dangling local endpoints

---

endpoint.go

Do not log unncessary warning messages when you get
maskable error from driver during an endpoint delete.

Handle maskable error during endpoint delete

---

endpoint.go
libnetwork_internal_test.go
network.go

- Allow to create an endpoint as anonymous.
An anonymous endpoint does not get added
to the network service records.

Allow anonymous endpoint

---

ipams/remote/remote.go

- This brings the remote ipam driver in pair with the local one. As of now remote driver package is assuming a valid address in CIDR form is always present in a nil error AddressRequestResponse,      which is no longer true as community has requested to remove this limitation.
- We are ok to remove it until we can provide a null ipam driver option in future releases.
Issue was pointed out by @pyakpyak in [comment](https://github.com/docker/libnetwork/issues/665#issuecomment-149788760)

Allow remote ipam driver to return nil address

---

etchosts/etchosts.go
etchosts/etchosts_test.go
sandbox.go

Introduced a path level lock to synchronize updates
to /etc/hosts writes. A path level cache is maintained
to only synchronize only at the file level.

Synchronize /etc/hosts updates at file level

---

store.go
test/integration/dnet/helpers.bash
test/integration/dnet/overlay-consul.bats

A local endpoint is known to the watch database only
during Join. But the same endpoint can be known to the
watch database as remote endpoint well before the Join
because a CreateEndpoint updates the endpoint to the store.
So on Join when you come to know that this is indeed a
local endpoint remove it from remote endpoint list and add it
to local endpoint list.

Purge remote endpoints from watch if it is local

---

ipam/allocator.go

- Currently allocator pulls all the bitmasks from datastore
before processing each public API. This is not needed as
the APIs already selectively pull the interested bitmask
when needed.

Do not refresh the bitmasks on all operations in IPAM

---

ipam/allocator.go
ipam/allocator_test.go

- Currently ipam allocator implicitly reserves the broadcast address for the ipv4 subnet reducing the length of the respective bitsequence of one during its creation.
This causes issue when somebody request a sub pool of the same size of the master pool: subsequent address requests will fail in bitsequence because range upper limit is greater than bitsequence upper limit.
- Fix: Create the bitsequence with the right size and explicitly reserve the last bit
Closes #698 

Do not manipulate bitseq length to reserve broadcast address

---

endpoint.go

- Currently when a sandbox disconnect from a network
the network's services are not removed from the
sandbox's /etc/hosts file

Clean hosts entries on endpoint leave

---

drivers/overlay/joinleave.go

Overlay driver allows local containers to communicate in overly network
even when the serf is not fully inited. But when the container leaves an
overlay network, it gets stuck waiting on a nil notifyCh, when the serf
is not fully initialized.

Dont notify the leave if the serf is not inited

---

datastore/datastore.go
store_test.go
test/integration/dnet/helpers.bash

In the [Dicovery/README.md](https://github.com/docker/docker/blob/3a24eb2de468c34195dc9fc6b036492a0095bbf1/pkg/discovery/README.md), Docker support the etcd based backend with following format 
```
$ docker daemon -H=<node_ip:2376> --cluster-advertise=<node_ip:2376> --cluster-store etcd://<etcd_ip1>,<etcd_ip2>/<path>
``` 
But I found there will be issue with Docker 1.9 RC1. More details in docker/docker#17298
In the datastore.go, it has the different logic to create Libkv store than docker discovery. 
Signed-off-by: Li Yi <denverdino@gmail.com>

Fix the issue for the --cluster-store URL with path

---

controller.go
endpoint.go
endpoint_cnt.go
libnetwork_test.go
sandbox.go
store.go

Added a handler in libnetwork for container rename. Loops through all the end-points, changes the name and updates the service records. For global scope networks the KV store will get updated as well to fix the service record in the peers.
Fixes 
https://github.com/docker/docker/issues/15727
https://github.com/docker/docker/issues/16485

Handling container rename in libnetwork

---

store.go

Fixes https://github.com/docker/docker/issues/17465
For overlay networks every node maintains a list of remote Endpoints (that are present on peer nodes). When one of those remote EPs go down the list wasn't getting deleted. On a container restart on one of the peers EP ID changes, but the name remains the same. So the extra entries in the list can lead to unintended delete of the service records, thus causing the issue reported in docker #17465

Fix an issue in overlay network peer EP list maintenance

---

drivers/overlay/joinleave.go
sandbox.go
sandbox_store.go

For ungraceful daemon restarts, libnetwork has sandbox cleanup logic to
remove any stale & dangling resources. But, if the store is down during
the daemon restart, then the cleanup logic would not be able to perform
complete cleanup. During such cases, the sandbox has been removed. With
this fix, we retain the sandbox if the store is down and the endpoint
couldnt be cleaned. When the container is later restarted in docker
daemon, we will perform a sandbox cleanup and that will complete the
cleanup round.

Fixes a case of ungraceful daemon restart + unreachable store

---

controller.go

Since we share the host sandbox with many containers we
need to serialize creation of the sandbox. Otherwise
container starts may see the namespace path in inconsistent
state.

Fix race in host sandbox creation

---

controller.go
sandbox.go

There is a race in os sandbox sharing code where two containers which
are sharing the os sandbox try to recreate the os sandbox again which
might result in destroying the os sandbox and recreating it. Since the
os sandbox sharing is happening only for default sandbox, refactored the
code to create os sandbox only once inside a `sync.Once` api so that it
happens exactly once and gets reused by other containers. Also disabled
deleting this os sandbox.
Fixes docker/docker#17577

Fix race in os sandbox sharing

---

controller.go
sandbox.go
sandbox_store.go

At times, when checkpointed sandbox from store cannot be
cleaned up properly we still retain the sandbox in both
the store and in memory. But this sandbox may not
contain important configuration information from docker.
So when docker requests a new sandbox, instead of using
it as is, reconcile the sandbox state from store with the
the configuration information provided by docker. To do this
mark the sandbox from store as stub and never reveal it to
external searches. When docker requests a new sandbox, update
the stub sandbox and clear the stub flag.

Fix stale sandbox from store problem

---

sandbox_store.go

If the endpoint and the corresponding network is
not persistent then skip adding it into sandbox
store.

Skip non-persistent endpoints in sandbox store

---

sandbox.go

It is sufficient to check only if network is available
in store to make the decision of whether to retain the
stale sandbox. If the endpoints are not available then
there is no point in retaining the sandbox anyways. This
fixes some extreme corner cases, where daemon goes down
right in the middle of sandbox cleanup happening.

Retain sandbox only if network is not available

---

controller.go

Clean some unused variables and format code.
also fix typo: change `RegisterOpamDriver()` into `RegisterIpamDriver()`

Clean unused variables

---

ipam/allocator.go
ipam/allocator_test.go
ipam/utils.go

- Callers expect to work with offsets based on master pool
Related to https://github.com/docker/docker/issues/17797

Fix bug in getAddressRange() in ipam driver

---

drivers/bridge/bridge.go

- On network delete, bridge interface removal is a best effort.
If netlink fails to remove the interface, we must not
restore the network in the bridge network db
Bug was found during review https://github.com/docker/libnetwork/pull/591#discussion_r44033870

Fix bug in bridge driver

---

drivers/bridge/bridge.go
drivers/bridge/bridge_test.go
endpoint.go
libnetwork_test.go
network.go

- On default bridge network only
Related to https://github.com/docker/docker/issues/17739

Allow IPv6 allocation post endpoint create via network option

---

store.go

Race can occur between two getEndpointsFromStore or between it and
getNetwork.

Fix race in getEndpointsFromStore

---

endpoint.go
test/integration/dnet/multi.bats

There are cases as seen in https://github.com/docker/docker/issues/17984
the sandbox could be stale in endpoint structure, when the actual
sandbox is removed during the cleanup phase. Hence instead of just
validating for sandboxID, make sure if it is actually present in the
sandboxes DB managed by the controller.

Allow endpoint delete if sandbox identifier is stale

---

endpoint_info.go

- Make sure to return the proper value for the
EndpointInfo interface in case of nil implementer
Related to https://github.com/docker/docker/issues/18009

Fix in endpoint Info() method

---

network.go

- Currently endpoint interface mac address is
not being set in network.go when user specified
the mac address for the container.
Similarly to IP address, MAC address is no longer
a driver specific option only. So libnetwork to parse it and set it into endpoint interface mac.
- Overlay driver expects to get the user defined mac-address
from InterfaceInfo.
Fixes #753 

libnetwork to honor explicit mac-address for all drivers

---

drivers/bridge/bridge.go
drivers/bridge/setup_ip_tables.go
iptables/firewalld_test.go
iptables/iptables.go
iptables/iptables_test.go

Fixed #570
Clean unused iptables rules after bridge network is removed

Cleanup iptables after bridge network is removed

---

bitseq/sequence.go
bitseq/sequence_test.go

- pushReservation fails to correctly detect when
the affected block is the last in the current
sequence. It thinks instead the block is in between
the sequence. Because of this a couple of issues
may happen:
1. The allocation of the last bit causes the creation
of a phantom sequence (length 0) at the end.
(This has no side effects).
2. The allocation of a bit somewhere in the middle of
the bitmask may lead to a completely incorrect
sequence pattern.

Fix bug in bitsequence.pushReservation

---

endpoint.go
sandbox.go

The first issue is an ordering problem where sandbox
attached version of endpoint object should be pushed
to the watch database first so that any other create endpoint
which is in progress can make use of it immediately to update
the container hosts file. And only after that the current
container should try to retrieve the service records from the
service data base and upate it's hosts file. With the previous
order there is a small time window, when another endpoint create
will find this endpoint but it doesn't have the sandbox context
while the svc record population from svc db has already happened
so that container will totally miss to populate the service record
of the newly created endpoint.
The second issue is trying to rebuild the /etc/hosts file from scratch
during endpoint join …

Fix a couple of edge cases in service discovery

---

machines

Usage:
./machines up [consul|etcd|zookeeper]
./machines destroy
Uses Docker Machine to create test environments
We _could_ use these environments to run BATS tests against
This would ensure that all supported backends are working

Use Docker Machine for Test Environments

---

bitseq/sequence.go

Race detector message:
```
WARNING: DATA RACE
Write by goroutine 269:
github.com/docker/libnetwork/bitseq.(*Handle).CopyTo()
/home/moroz/project/workspace/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/bitseq/store.go:85 +0x2f6
github.com/docker/libnetwork/datastore.(*cache).get()
/home/moroz/project/workspace/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/datastore/cache.go:135 +0x307
github.com/docker/libnetwork/datastore.(*datastore).GetObject()
/home/moroz/project/workspace/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/datastore/datastore.go:438 +0x121
github.com/docker/libnetwork/bitseq.(*Handle).set()
/home/moroz/project/workspace/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/bitseq/sequence.go: …
```

bitseq: fix race between CopyTo and set

---

network.go

- On network delete it is preferable to release the gateway address
and address pool before removing the network from the datastore,
given ipam data is a child of network data.

Release address pool before removing the network from store

---

bitseq/sequence.go
bitseq/sequence_test.go
controller.go
ipam/allocator.go
ipam/store.go
ipam/structures.go
ipamapi/contract.go

- Remove from contract predefined errors which are no longer
valid (ex. ErrInvalidIpamService, ErrInvalidIpamConfigService)
- Do not use network driver error for ipam load failure in controller.go
- Bitseq to expose two well-known errors (no more bit available, bit is already set)
- Default ipam to report proper well-known error on RequestAddress()
based on bitseq returned error
- Default ipam errors to comply with types error interface

Adjust ipam errors

---

default_gateway.go
docs/remote.md
endpoint_info.go

Don't connect sbx to default gw nw if default static route is provided

---

drivers/overlay/ov_serf.go

Sometimes, the vxlan kernel code may generate miss
notifications for vxlan bound packets when serf is
not initliazed. In such cases we should not try
doing a query as it will create a panic. We should
error out which will generate a log message.

Do not attempt serf query when not initialized

---

cmd/ovrouter/ovrouter.go
default_gateway.go
driverapi/driverapi.go
drivers/bridge/bridge_test.go
drivers/remote/api/api.go
drivers/remote/driver.go
drivers/remote/driver_test.go
endpoint_info.go

Fixes https://github.com/docker/libnetwork/issues/759 https://github.com/docker/libnetwork/issues/775

Add a network option to disable default gateway

---

endpoint.go
ipamapi/contract.go
network.go

Adds the ability to give driver options when assigning an address.
Also when assigning the ipam gateway address pass the options bellow
```
{
"gateway": "true"
}
```
This will allow ipam drivers to detect whether an address belongs to a gateway or not. 
Currently under CreateEndpoint options are set to nil. This should be changed once EndpointOptions contains driver options for the endpoint it self and driver options for its address.
Signed-off-by: Ryan Belgrave <rmb1993@gmail.com>

Assigning Address driver options

---

endpoint.go

- On Sandbox deletion, during Leave from each
connected endpoint, avoid the default gw
check, which may create an unnecessary
connection to the default gateway network.
- Especially during sandbox cleanup on start
after an ungraceful shutdown of the docker
daemon, the unnecessary connection to the
default gw network is likely to happen, if a 
container was connected to multiple network.

Skip defaultGw check if sandbox is being deleted

---

drivers/overlay/overlay.go
drivers/overlay/peerdb.go

If we use peerMap as value, then we copy its mutex on
`pMap = d.peerDb.mp[nid]` and lock entirely different mutexes every
time.

Fix mutex copy

---

ipamutils/utils_freebsd.go
osl/sandbox_freebsd.go

libnetwork should be able to compile on freebsd after #186 is merged with this changes.

Allow libnetwork to compile on freebsd

---

drivers/bridge/setup_bridgenetfiltering.go

Replaced reference to dockerinit by dockerenv for func isRunningInContainer()
This PR refers to https://github.com/docker/docker/issues/18355

Removed dockerinit reference

---

drivers/overlay/filter.go
drivers/overlay/ov_network.go
drivers/overlay/ov_utils.go
osl/interface_linux.go
osl/namespace_linux.go
test/integration/dnet/helpers.bash
test/integration/dnet/overlay-consul-host.bats
test/integration/dnet/run-integration-tests.sh

Add support for overlay networking in older kernels.
Following were done to achieve this:
+ Create the vxlan network in host namespace.
+ This may create conflicts with other private
networks so check for conflicts and fail a
join if there is any conflict.
+ Add iptable based filtering to only allow
subnet bridges in the same network to forward
traffic while different network bridges will
not be able to forward b/w each other. Also
block traffic to overlay network originating
from the host itself.

Add overlay network support in < 3.16 kernels

---

drivers/overlay/filter.go
drivers/overlay/ov_network.go
drivers/overlay/ov_utils.go
osl/interface_linux.go
osl/namespace_linux.go
test/integration/dnet/helpers.bash
test/integration/dnet/overlay-consul-host.bats
test/integration/dnet/run-integration-tests.sh

Add support for overlay networking in older kernels.
Following were done to achieve this:
+ Create the vxlan network in host namespace.
+ This may create conflicts with other private
networks so check for conflicts and fail a
join if there is any conflict.
+ Add iptable based filtering to only allow
subnet bridges in the same network to forward
traffic while different network bridges will
not be able to forward b/w each other. Also
block traffic to overlay network originating
from the host itself.

CherryPick: Add overlay network support < 3.16 kernels

---

controller.go
docs/ipam.md
endpoint.go
ipamapi/contract.go
ipams/remote/api/api.go
ipams/remote/remote.go
ipams/remote/remote_test.go
libnetwork_internal_test.go
network.go

- So that a DHCP based plugin can express it needs
the endpoint MAC address when requested for an IP address.
- In such case libnetwork will allocate one if not already
provided by user

Allow remote IPAM driver to express capability

---

drivers/bridge/setup_ipv6.go
libnetwork_test.go

- Currently bridge driver discards the user specified
network gateway for IPv6 for user defined networks
Related to https://github.com/docker/docker/issues/18657

Bridge driver to honor IPv6 network gateway

---

drivers/overlay/ov_network.go
drivers/overlay/ov_utils.go

Currently we are cleaning up vxlan interfaces by name
before trying to setup an interface with the same name.
But this doesn't work for properly cleaning up vxlan
interfaces with the same vni, if the interface has a
a different name than the one expected. The fix is to
delete the interface based on vni.

Cleanup vxlan interface by id before creating

---

drivers/overlay/filter.go
drivers/overlay/ov_network.go
drivers/overlay/ov_utils.go

We check for existence of all filter rules in
overlay driver before creating it. We should
also do this for chain creation, because even though
we cleanup network chains when the last container
stops, there is a possibility of a stale network
chain in case of ungraceful restart.
Also cleaned up stale bridges if any exist due to
ungraceful shutdown of daemon.

Check existence of network chain before creating

---

drivers/overlay/filter.go

ChainExists should not treat non-nil output as
error because there is always going to be some
output while dumping iptable rules.

Don't treat non-nil output as error in ChainExists

---

resolvconf/dns/resolvconf.go

Only match strings which end with ::1
Fixes #830

Fix regex for IPv6

---

drivers/bridge/bridge.go
drivers/bridge/bridge_test.go
drivers/bridge/setup_ip_tables.go
iptables/iptables.go

Relates to https://github.com/docker/libnetwork/pull/301.
I've seen some dirty rules left on filter table as well. I think it's better to clean up those rules.

Clean up docker chain of filter table as well on driver init

---

Makefile

The default make target should be `all` by convention but
since it is not the first target it wasn't getting triggered
as the default target. Fixed the makefile to make `all`
the first and default target.

Fix default make target

---

Dockerfile.build

A commit today(1/6/2016) in golang.org/x/tools broke
libnetwork builds because it now requires certain
go 1.5 packages while libnetwork still uses go1.4.
Fixed it by manually installing golang.org/x/tools from
release-branch.go1.5 which should work for us
even though it is versioned 1.5. The 1.4 release
branch is too old and doesn't work with latest golint
package.

Fix golang.org/x/tools breakage in go 1.4

---

drivers/overlay/joinleave.go
drivers/overlay/ov_endpoint.go

Related to https://github.com/docker/docker/issues/18814

Delete veth on ep leave in overlay driver

---

cmd/dnet/dnet.go
docs/ipam.md
libnetwork_internal_test.go
libnetwork_test.go
network.go

Accept IpamOptions via NetworkOptionIpam. 
This change also removes subnet specific IPAM Options and moves them to per network. 
See pull docker/docker#17316 for corresponding changes and discussion

Accept IpamOptions via NetworkOptionIpam

---

etchosts/etchosts.go
etchosts/etchosts_test.go

Fix etchosts.Update to not target hosts with given hostname as prefix

---

api/api.go
api/api_test.go
api/types.go
client/service.go
client/types.go
controller.go
default_gateway.go
endpoint.go
libnetwork_internal_test.go
libnetwork_test.go
network.go
sandbox.go
test/integration/dnet/overlay-consul.bats

There are cases in multi-host networking where an ungraceful host shutdown (and the docker daemon in that host never comes back up again) could result in endpoint resources (such as ip-address) being locked up. This PR provides an ability for higher level orchestration systems to force an endpoint cleanup from the datastore and hence the resources can be reused.

Force endpoint delete

---

endpoint.go
test/integration/dnet/overlay-consul.bats

Remove `isNodeAlive` check while force deleting endpoint

---

.gitignore
bitseq/sequence.go
bitseq/sequence_test.go
ipam/allocator.go

- In docker 1.9.0 and 1.9.1 versions, because of a bug in bitseq package (https://github.com/docker/libnetwork/pull/771) some IP address reservation/release patterns may corrupt the ip address database and cause several issues (containers with same IP among others).
The only way to recover is to restart the daemon after deleting the local kv store file. Besides the disruptive workaround, still the issues may happen again, depending of the new reservation/release patterns.
- This change will allow docker engine to self repair the IP database without need for the user to play with the `/var/lib/docker/network/files/local-kv.db` file.
- Following debug logs from upgrading docker 1.9.1 to latest with this change:
```
DEBU[0002] Fixed inconsistent bit sequence:
App: ipam/default/data, ID: …
```

IPAM to migrate from old bitmask to new one

---

drivers/bridge/bridge.go
drivers/bridge/bridge_test.go

- When the flag is false, besides not programming the chains, also skip chains cleanup
- Related to https://github.com/docker/docker/issues/19063

Honor --iptables=false in bridge

---

endpoint.go

> incorrect error message if custom IP if the custom IP-address is not within a subnet of the network.
Will fix docker/docker#19404 once vendored.
🐸
Signed-off-by: Vincent Demeester <vincent@sbr.pm>

Fixes docker/docker#19404

---

controller.go
default_gateway.go
endpoint.go
endpoint_info.go
network.go
sandbox.go
sandbox_store.go
store.go

Stale sandbox and endpoints are cleaned up during controller init.
Since we reuse the exact same code-path, for sandbox and endpoint
delete, they try to load the plugin and it causes daemon startup
timeouts since the external plugin containers cant be loaded at that
time. Since the cleanup is actually performed for the libnetwork core
states, we can force delete sandbox and endpoint even if the driver is
not loaded.

Force delete sandbox during sandboxCleanup

---

libnetwork_test.go
netutils/utils.go
resolvconf/resolvconf.go
resolvconf/resolvconf_test.go
resolver.go
sandbox.go

Retain V6 DNS server in resolv.conf; use only V4 servers for fallback

---

Makefile
ipam/allocator.go
ipam/allocator_test.go
ipam/structures.go

- The pool request code does not behave properly in
case of concurrent requests when client does not
specify a preferred pool. It may dispense the same
predefined pool to different networks.
- The issue is common for local and global
address spaces
- Verified it fixes the issue running parallel network creation requests to docker. ~~Will add tests in libnetwork in following PR update.~~

Fix predefined pool reservation

---

endpoint.go
sandbox.go
test/integration/dnet/helpers.bash

By removing the need to clear the default gateway during sbJoin and
sbLeave to account for other bridge network, the default-gw endpoint
will stay with the container, it will also help retain the container
property.

Reducing the complexity in default gateway service handling

---

default_gateway.go

- Code is not protected against concurrent joins of overlay network

Handle concurrent creation of default GW network

---

docs/ipam.md
endpoint.go
ipam/allocator.go
ipam/allocator_test.go
ipamapi/contract.go

The IPAM API lets you specify a "preferred IP address".  The word "preferred" to me suggests that it is OK to give a different address if that request cannot be satisfied, whereas the code behaves as if the request is non-negotiable.
Related change: https://github.com/docker/docker/pull/19723

Stop referring to requested IP address as "preferred"

---

driverapi/driverapi_test.go
drivers/bridge/bridge_test.go
ipam/allocator_test.go
libnetwork_internal_test.go
types/types_test.go

As discussed here: https://github.com/docker/libnetwork/pull/741/files#r44872866
I searched for potentially affected files with: `grep  -ER '200.:' . |grep -iv '2001:db8'`, so maybe some places slipped through.
Tests still seem to pass, but I am not entirely sure whether I ran them correctly on my local box.
You also might want to take a look at these lines: https://github.com/docker/libnetwork/blob/e8ebc0bf6510343c88d162db08b3d855cbbe75b9/libnetwork_test.go#L1839-L1843
The IPv6 is Google Public DNS, so this might be correct. The IPv4 addresses belong to some Chinese Company and the domain is currently unassigned. You might want to replace the domain by `example.com` and the IPv4 addresses by addresses in some private network.
/cc @aboch

Use documentation IPv6 addresses (RFC 3849) in tests

---

drivers/overlay/ov_network.go

When the daemon is ungracefully shutdown, sometimes
when we try to create the overlay sandbox after coming
back up might get created in a different epoch count
which will result in the vxlan interface not properly
cleaned up. Fix this by explicitly cleaning up all the
previous epoch sandboxes.

Cleanup stale overlay sandboxes

---

CHANGELOG.md
drivers/overlay/ov_network.go

When the daemon is ungracefully shutdown, sometimes
when we try to create the overlay sandbox after coming
back up might get created in a different epoch count
which will result in the vxlan interface not properly
cleaned up. Fix this by explicitly cleaning up all the
previous epoch sandboxes.

CherryPick: Cleanup stale overlay sandboxes

---

drivers/overlay/joinleave.go
drivers/overlay/ov_endpoint.go
drivers/overlay/ov_network.go
osl/interface_linux.go
sandbox.go

- Attempt the veth delete only after both ends are moved into the default network namespace.
Which is after both driver.Leave() and sandbox.clearNetworkResources() are called.

Delete the interface on endpoint delete in overlay

---

controller.go
discoverapi/discoverapi.go
driverapi/driverapi.go
drivers/bridge/bridge.go
drivers/host/host.go
drivers/null/null.go
drivers/overlay/overlay.go
drivers/overlay/overlay_test.go
drivers/remote/api/api.go
drivers/remote/driver.go
drivers/remote/driver_test.go
drivers/windows/windows.go
libnetwork_internal_test.go

- Move DiscoverNew() and DiscoverDelete() methods into the new interface
- Add DatastoreUpdate notification
- Now this interface can be implemented by any drivers, not only network drivers

discoverapi.Discover interface

---

iptables/iptables.go
resolver.go

- iptables to provide a native API
- resolver.go to invoke the iptables native API when programming tables in the container

When programming iptables in container use native API

---

drivers/bridge/setup_ip_tables.go

- On network creation bridge driver registers the `filter` iptables chain with portmapper. portmapper will invoke that chain's `Forward()` method when a endpoint with exposed ports joins the network. 
`Forward()` installs rules in the `nat` DOCKER chain and in the `filter` DOCKER chain (this works under the assumption `filter` and `nat` chains have same name...). When it works on the `nat` table chain, the rule is created differently based on whether the chain object has hairpin mode enabled.
The problem is that on `filter` chain creation the hairpin mode flag is no longer passed, it is always set to false. This will cause an incorrect `nat` rule configuration when `userland-proxy==false`.
Fix this by registering the bridge driver's `natChain` with portmapper on network creation.
- Also …

Register natChain with portmapper

---

api/api.go
api/api_test.go
client/network.go
default_gateway_linux.go
drivers/bridge/bridge_test.go
libnetwork_test.go
network.go

docker/docker#17513
Per point two at the end of https://github.com/docker/docker/pull/17513#issuecomment-164032291

Don't allow passing EnableIPv6 as a driver option (a label)

---

MAINTAINERS

Santhosh has been contributing to various features in 1.9 & 1.10 releases and an active maintainer who helps with bug fixes and PR reviews

Add Santhosh as libnetwork maintainer

---

CHANGELOG.md

Also picking up the changelog for RCs that already made it to the master.

changelog for v0.7.0-dev.1

---

drivers/bridge/bridge.go

Make sure iptables chains are recreated on firewall reload

---

resolver.go

Without the RA bit the replies may not get cached..

Set Recursion Available bit in query responses.

---

drivers/bridge/bridge.go

Related to https://github.com/docker/docker/issues/20145

Bridge driver to Warn if xt_conntrack not present

---

drivers/windows/windows_test.go

Signed-off-by: msabansal <sabansal@microsoft.com>

Fixing bulid break because of improper formatting in windows_test.go

---

config/config.go
controller.go
datastore/datastore.go
discoverapi/discoverapi.go
drivers.go
drivers/bridge/bridge_store.go
drivers/overlay/overlay.go
drivers/overlay/overlay_test.go
ipam/allocator.go
ipamapi/contract.go
ipams/remote/remote.go
netlabel/labels.go
store.go

- This to allow the controller to update the datastore in the local IPAM driver and overlay driver at runtime, via Controller.ReloadConfiguration()

Allow pass global datastore config after boot

---

ipams/windowsipam/windowsipam.go

- happened becasue of two independent commits

Fix cross compilation breakage

---

drivers/bridge/bridge.go

We now report the correct bridge name and network id when
reporting a conflict.
This fixes #914 
Note that `make all` resulted in a few failures, but that seem to be because I'm not able to ping external host from my work network (and some tests ping google.com), not due to this changeset.

Fix error message on bridge network creation conflict.

---

MAINTAINERS

Chen Chun has been contributing various useful features in 1.9 & 1.10
releases and also an active maintainer who helps with bug fixes and PR reviews.

Chen Chun as libnetwork maintainer

---

datastore/datastore.go
discoverapi/discoverapi.go
driverapi/driverapi.go
driverapi/ipamdata.go
idm/idm.go
ipam/structures.go
ipam/utils.go
ipamapi/contract.go
types/types.go

Fix some typos

---

etchosts/etchosts.go
etchosts/etchosts_test.go

This approach allows the user to provide a FQDN as hostname if that is what
they want in their container, or to provide distinct host and domain parts.  In
both cases we will correctly extract the first token for /etc/hosts.
xref: https://github.com/docker/docker/pull/20200 and https://github.com/docker/docker/issues/14282

Extract hostname from (hostname.domainname)

---

drivers/windows/windows.go
drivers/windows/windows_test.go
drivers_windows.go

Also added portmapping support for the windows driver. (Still requires some work in HNS to be fully supported).
CI results from TP5 Build:
C:\gopath\src\github.com\docker\libnetwork\drivers\windows>godep go test -v
=== RUN   TestNAT
--- PASS: TestNAT (0.85s)
=== RUN   TestTransparent
--- PASS: TestTransparent (13.40s)
PASS
ok      github.com/docker/libnetwork/drivers/windows    14.318s
C:\gopath\src\github.com\docker\libnetwork\drivers\windows>godep go test -v
=== RUN   TestNAT
--- PASS: TestNAT (0.87s)
=== RUN   TestTransparent
--- PASS: TestTransparent (13.57s)
PASS
ok      github.com/docker/libnetwork/drivers/windows    14.502s

Renaming driver name to lower case for usability 

---

CHANGELOG.md
api/api_test.go
bitseq/sequence.go
controller.go
driverapi/driverapi.go
driverapi/driverapi_test.go
drivers/bridge/bridge.go
drivers/overlay/filter.go
drivers/windows/windows.go
ipams/windowsipam/windowsipam.go
libnetwork_internal_test.go
network.go
sandbox.go
sandbox_externalkey_unix.go
test/integration/dnet/helpers.bash

All of them were found and fixed by codespell.
Signed-off-by: Stefan Weil <sw@weilnetz.de>

Fix some typos in comments and strings

---

sandbox.go

Not sure why govet didnt catch this obvious error.
addresses https://github.com/docker/docker/issues/20694

Fixed a panic issue in clearNetworkResources

---

resolver.go
sandbox.go

Source external DNS queries from container namespace

---

drivers/bridge/bridge.go
drivers/bridge/bridge_test.go
drivers/remote/driver_test.go
osl/interface_linux.go
osl/options_linux.go
osl/sandbox.go
sandbox.go

- Consistently with what it does for IP addresses, libnetwork
will also program the container interface's MAC address with
the value set by network driver in InterfaceInfo.

Libnetwork to program container interface's MAC

---

iptables/iptables.go
iptables/iptables_test.go

- Fixed Exists to attempt a raw exists check only when  "iptables -C ..." is not supported . This is a problem because the raw check has several bugs.
- Fixed raw exists to not match substring
- Added GetVersion method

Fix iptables.Exists logic

---

libnetwork_test.go
resolver.go
sandbox.go

When more than one container has same --net-alias/--alias name configured embedded server will return multiple A records. This will allow the clients to do DNS RR which provides a basic load balancing capability.

Embedded DNS server to return multiple A records for enabling DNS Round Robin

---

drivers/windows/windows.go
endpoint.go
ipams/windowsipam/windowsipam.go
ipams/windowsipam/windowsipam_test.go

The information was not being displayed because we were trying to set the IP already set through IPAM. Fixing windows IPAM to return nil IP so that it can be overridden once we receive IP from HNS
CI run results:
PS C:\gopath\src\github.com\docker\libnetwork\drivers\windows> godep go test -v
=== RUN   TestNAT
--- PASS: TestNAT (1.06s)
=== RUN   TestTransparent
--- PASS: TestTransparent (13.46s)
PASS
ok      github.com/docker/libnetwork/drivers/windows    14.605s
PS C:\gopath\src\github.com\docker\libnetwork\drivers\windows> godep go test -v
=== RUN   TestNAT
--- PASS: TestNAT (0.86s)
=== RUN   TestTransparent
--- PASS: TestTransparent (13.57s)
PASS
ok      github.com/docker/libnetwork/drivers/windows    14.463s

Fixed IP information not displayed properly in docker network inspect on Windows

---

drivers/overlay/joinleave.go

- Because of the lazy logic in Leave(), the overlay
veth end is not moved from the sandbox to the host
network namspace until the last endpoint leaves.
We cannot rely on this logic to clear the veth pairs,
because on last endpoint leave we have no reference to
the other N-1 veth names.
- The fix is to delete the container veth end on endpoint delete.
This anyways deletes both veth ends, regardless they are in different
namespaces.
~~Note: I'd be happy to remove the code at https://github.com/docker/libnetwork/blob/master/drivers/overlay/ov_network.go#L173
as it is no longer needed.~~ [That cannot be removed as it was not intended to handle the veth pairs that connect to the container sandbox]
Fixes #984

Fix veth leak in overlay driver

---

CHANGELOG.md
drivers/bridge/bridge.go
drivers/bridge/bridge_test.go
drivers/bridge/labels.go
endpoint.go
iptables/iptables.go

- Fix npe in sbJoin error path
- Fail again endpoint Join in case of failure
in programming the external connectivity
- In bridge, look for parent and child container configs
in the generic data
- iptables.Exists() might be called before any other call to
iptables.raw(). We need to call checkInit() then.

Fix docker IT failures for 0.7.0-dev.4 vendoring

---

Makefile
drivers/ipvlan/ipvlan.go
drivers/ipvlan/ipvlan_endpoint.go
drivers/ipvlan/ipvlan_joinleave.go
drivers/ipvlan/ipvlan_network.go
drivers/ipvlan/ipvlan_setup.go
drivers/ipvlan/ipvlan_setup_test.go
drivers/ipvlan/ipvlan_state.go
drivers/ipvlan/ipvlan_store.go
drivers/ipvlan/ipvlan_test.go
drivers/macvlan/macvlan.go
drivers/macvlan/macvlan_endpoint.go
drivers/macvlan/macvlan_joinleave.go
drivers/macvlan/macvlan_network.go
drivers/macvlan/macvlan_setup.go
drivers/macvlan/macvlan_setup_test.go
drivers/macvlan/macvlan_state.go
drivers/macvlan/macvlan_store.go
drivers/macvlan/macvlan_test.go
drivers_experimental_linux.go
drivers_linux.go
drivers_stub_linux.go

- Notes at: https://gist.github.com/nerdalert/c0363c15d20986633fda

Added macvlan and ipvlan drivers

---

drivers/ipvlan/ipvlan_network.go
drivers/ipvlan/ipvlan_setup.go
drivers/macvlan/macvlan_network.go
drivers/macvlan/macvlan_setup.go

ipvlan >= 4.0.0 due to early instability
macvlan >= 3.9

Added kernel version checks for macvlan/ipvlan

---

iptables/firewalld.go

It closes 3 unused goroutines. I don't think that it's good pattern to wait for some software forever.

Close dbus connection if firewalld is not started

---

drivers/ipvlan/ipvlan_network.go
drivers/ipvlan/ipvlan_setup.go
drivers/macvlan/macvlan_network.go

- ipvlan l2 mode is buggy in < 4.2

Bumped ipvlan kernel version to >= 4.2

---

drivers/bridge/setup_ip_tables.go

- With the transition to ipam, bridge ip address stored
in `bridgeInterface` is guaranteed to be the ip of the
OS bridge by the `setupBridgeIPv4` step function.
Therefore the `setupIPTables()` step function no
longer needs to fetch the address from the OS.
This removes unnecessary syscalls to the OS
and removes the code which may cause confusion.

Change in bridge/setup_ip_tables.go

---

controller.go
libnetwork_test.go
network.go
store.go

- ... on ungraceful shutdown during network create
- Allow forceful deletion of network
- On network delete, first mark the network for deletion
- On controller creation, first forcefully remove any network
that is marked for deletion.
Related to https://github.com/docker/docker/issues/20312

Avoid network/endpoint_count inconsistences

---

libnetwork_test.go
sandbox_externalkey_unix.go
sandbox_externalkey_windows.go

Previously hook expected data with a wrong type.
Full netns path is not included with the data
passed with the hook.
Fixes #829
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

Fix netns path setting from hook

---

resolver.go

If the cached connections are not cleared sending the query to the corresponding external server fails for containers with the restart policy configured.

Clear cached udp connections on resolver Stop()

---

endpoint.go
endpoint_cnt.go

During ungraceful shutdown, it is possible that the endpoint_cnt can be
inconsistent with the actual endpoints in a network. This fix will
resolve that inconsistency

Fixing a possible endpoint_cnt state inconsistency issue

---

resolver.go

related to [docker #21240] (https://github.com/docker/docker/issues/21240)

Fix nil pointer reference in ServeDNS() with concurrent go routines.

---

osl/interface_linux.go

Before we call setInterfaceIP() and setInterfaceIPv6(), we construct partial error messages for use if they return errors.  While both functions check for nil addresses, we don't guard against passing nil
addresses to fmt.Sprintf when constructing those messages, which causes us to panic if they're nil.  Add wrappers that supply the text "(no address)" when the address is nil.

Don't quote the addresses when we hit errors setting interface addresses

---

libnetwork_test.go
resolver.go
sandbox.go

Stub resolvers try to resolve a name to IPv6 before trying IPv4. The embedded DNS server was forwarding IPv6 queries if the name can't be resolved to an IPv6 address, even if its a service name present in the docker domain. 
Its better to avoid this because..
1) it can get mapped to wrong/unintended IP 
2) if the external name server is not reachable the resolution takes long waiting for the query to timeout 
3) its better to avoid docker domain service names going to external name servers.

Avoid V6 queries in docker domain going to external nameservers

---

controller.go
store.go

With the current implementation, a config relaod event causes all the
datastores to reinitialize and that impacts objects with Persist=false
such as none and host network.

Reload config should initialize only the appropriate datastore

---

sandbox.go

Logs as 
`DEBU[0000] sandbox set key processing took 303.229µs for container c0d9d3f640137247a[...]`

Log time taken to set sandbox key

---

drivers/overlay/joinleave.go
drivers/overlay/ov_serf.go
drivers/overlay/overlay.go

Join & Leave Serf processing happens in a separate goroutine and there
are cases as in https://github.com/docker/libnetwork/issues/985, it can
cause lookup failures when endpoint delete processing happens before
Serf gets a chance to handle the leave processing.
The fix is to avoid such lookups in this goroutine, but handle the
endpoint and network objects directly.
Fixes #985 

Handle endpoint & network object in notifyEvent avoiding id lookup

---

resolver.go

Limit number of concurrent DNS queries

---

drivers/overlay/ov_network.go

- Concurrent leave/join of one member overlay network can end with the error:
"subnet sandbox join failed for "A.B.C.D/MM": error creating vxlan interface: file exists"
This happens when the join is processed while the leave has already started.
Having the network one member only, the leave resets the once variable for this network subnets
and triggers the sandbox destroy for each subnet's vxlan interface, when the n.joinCnt goes to 0.
But given the destroySandbox() is not atomic, the join thread can trigger the creation of the
vxlan interface in between (given subnet.once was re-initialized) before the leave thread
removes the vxlan interface for this subnet.
- The fix is to not allow interruptions between the re-initialization of the subnet.once var and
consequent vxlan interface …

Do not allow overlay destroySandbox() to be interrupted

---

CHANGELOG.md

- Fixes https://github.com/docker/libnetwork/issues/985
- Fixes https://github.com/docker/libnetwork/issues/945
- Log time taken to set sandbox key
- Limit number of concurrent DNS queries

changelog for 0.7.0-rc.1

---

drivers/bridge/bridge_test.go
ipam/allocator_test.go
ipams/builtin/builtin_unix.go
ipamutils/utils.go
ipamutils/utils_linux.go
ipamutils/utils_test.go

This moves the initialization of the pre-defined networks to where it's
used, in `Allocator`.
This reason for this change is having this be populated in `init()`
causes it to always consume cpu to populate, and memory (4.3MB of
memory) even if the package is unused (like for instnace, in a re-exec).
Here is a memory profile of docker/docker just after starting the daemon of the
top 10 largest memory consumers:
Before:
```
flat  flat%   sum%        cum   cum%
0     0%     0%    11.89MB 95.96%  runtime.goexit
0     0%     0%     6.79MB 54.82%  runtime.main
0     0%     0%     5.79MB 46.74%  main.init
0     0%     0%     4.79MB 38.67%  github.com/docker/docker/api/server/router/network.init
0     0%     0%     4.79MB 38.67%  github.com/docker/libnetwork.init
0     0%     0%     4.29MB 34.63% …
```

Remove pre-defined networks from package init

---

drivers/overlay/ov_network.go

- Otherwise a overlay network delete after daemon restart
will hit a nil pointer dereference while releasing the
vxlan id
Steps to reproduce:
- create an overlay network
- restart the daemon
- delete the overlay network

Have resources initialized before deleting overlay network

---

resolver.go

For queries forwarded over a cached connection to external servers maintain the context for the queries so that reply from the external server can be sent back to the right client connection.

Fix the handling for concurrent queries over UDP

---

default_gateway.go
endpoint.go
sandbox.go
test/integration/dnet/helpers.bash

On stopping a container running on overlay network, daemon prints following logs:
```
WARN[0010] Failed detaching sandbox 1a117bfe9a3274928e371854ed581633c3cf40d25a7eb4ce473a2110cb04153f from endpoint 93f6c261f8a6bcd3ce94ff8bb40e93afbbf13767b9fef653b43c31bb7bdb23f5: failed to get endpoint from store during leave: could not find endpoint 93f6c261f8a6bcd3ce94ff8bb40e93afbbf13767b9fef653b43c31bb7bdb23f5: []
WARN[0010] Failed deleting endpoint 93f6c261f8a6bcd3ce94ff8bb40e93afbbf13767b9fef653b43c31bb7bdb23f5: failed to get endpoint from store during Delete: could not find endpoint 93f6c261f8a6bcd3ce94ff8bb40e93afbbf13767b9fef653b43c31bb7bdb23f5: []
```
- On sandbox delete, the leave and delete of each
endpoint is performed, regardless of whether the endpoint
is the gw network endpoint. This …

Fix when connecting/disconnecting to/from default gw network

---

drivers/bridge/bridge_store.go

- otherwise after daemon reload, the network is no longer internal
Steps to reproduce
- Create an internal bridge network x
- Restart the daemon
- Connect a container to the network x and you can ping 8.8.8.8 from inside the container

Bridge driver needs to store the network config internal flag

---

default_gateway.go
endpoint.go
sandbox.go
test/integration/dnet/helpers.bash

This reverts commit c42884a5b29326840e05549293a4d560d0e4ce2a introduced via https://github.com/docker/libnetwork/pull/1064.
This Patch causes the IT failure in rc.2 & it is not a mandatory patch for the release.

Revert "Do not leave/delete gw endpoint twice"

---

Dockerfile.build

tools/cmd/vet has been deleted and go tool vet works natively on 1.5+

---

resolver.go

With the cached udp connection to an external nameserver the following can happen..
```DEBU[0064] Query name.[1] from 127.0.0.11:42291, forwarding to udp:8.8.8.8 ```
```DEBU[0067] Read from DNS server failed, read udp 172.20.0.2:47916->8.8.8.8:53: i/o timeout ```
now the saved context for the forwarded query will be cleared
```DEBU[0069] Query name.[1] from 127.0.0.11:42291, forwarding to udp:8.8.8.8 ```
Since the first query timed out client resolver retries; when the DNS server is waiting for the response it could receive the reply for the previous query whose context has been cleaned up already.
DEBU[0069] Can't retrieve client context for dns id 6063 
Added a missing nil check for this case and increased the read timeout (typical client resolver timeout is 5 seconds; hence keeping the …

Fix the panic when a query response comes after the read() timesout

---

docs/remote.md
drivers/remote/driver.go

- for endpoints which are not expected to be implemented
by all remote drivers.

Use newly introduce plugins method to validate plugin response 

---

endpoint.go
resolver.go

Currently when the default gw changes because of
other network connections happening in the container
the resolver sockets are not flushed. This results
in a subsequent DNS failure for external queries
A sequence of connecting the container to an overlay
network and subsequently to a bridge network without
disconnecting from any network will result in this
behaviour. This was revealed by one of the libnetwork
IT tests.
This is now fixed as part of the commit by flushing
the external query sockets when a default gw change
is detected.

Resolver sockets not flushed on default gw change

---

drivers/windows/labels.go
drivers/windows/windows.go
types/types.go

This adds QoS policies to the Windows driver passed via a generic option. 
Signed-off-by: Darren Stahl <darst@microsoft.com>

Added maximum egress bandwidth qos for Windows

---

driverapi/driverapi.go
drivers/bridge/bridge.go
drivers/host/host.go
drivers/ipvlan/ipvlan.go
drivers/macvlan/macvlan.go
drivers/null/null.go
drivers/overlay/ov_network.go
drivers/remote/driver.go
libnetwork_internal_test.go

Added NetworkAllocate and NetworkFree apis to the list of
driver apis. The intention of the api is to provide a
centralized way of allocating and freeing network resources
for a network which is cross-host.

Add NetworkAllocate/Free to driver api

---

Makefile
default_gateway_solaris.go
drivers_solaris.go
ipams/builtin/builtin_unix.go
ipamutils/utils_solaris.go
osl/interface_solaris.go
osl/neigh_solaris.go
sandbox_externalkey_solaris.go

This is a build clean PR for libnetwork on Solaris.
This is a part of a larger effort for a native port of Docker on Solaris.
Signed-off-by: Amit Krishnan <krish.amit@gmail.com>

Get libnetwork to build on Solaris

---

driverapi/driverapi.go
drivers/bridge/bridge.go
drivers/host/host.go
drivers/ipvlan/ipvlan.go
drivers/macvlan/macvlan.go
drivers/null/null.go
drivers/overlay/ov_network.go
drivers/overlay/ovmanager/ovmanager.go
drivers/overlay/ovmanager/ovmanager_test.go
drivers/remote/driver.go
drivers/windows/windows.go
drvregistry/drvregistry_test.go
libnetwork_internal_test.go
netlabel/labels.go

Because overlay is a builtin driver and global allocation of overlay
resources is probably going to happen in a different node (a single
node) and the actual plumbing of the network is probably going to happen
in all nodes, it makes sense to split the functionality of allocation
into two different packages. The central component(this package) only
implements the NetworkAllocate/Free apis while the distributed
component(the existing overlay driver) implements the rest of the driver
api. This way we can reduce the memory footprint overall.

Add overlay manager driver

---

drivers/overlay/ov_network.go

Fixes #1069 
Verified with a code change to set the serf eventbuffer to a very low number.

Correct the check in l3 miss handling in overlay driver

---

README.md
api/api.go
api/api_test.go
cmd/dnet/dnet.go
cmd/readme_test/readme.go
controller.go
default_gateway_linux.go
libnetwork_internal_test.go
libnetwork_test.go
sandbox_test.go
store_test.go

Currently the libnetwork function `NewNetwork` does not allow
caller to pass a network ID and it is always generated internally.
This is sufficient for engine use. But it doesn't satisfy the needs
of libnetwork being used as an independent library in programs other
than the engine. This enhancement is one of the many needed to
facilitate a generic libnetwork.

Add support to accepting arbitrary network ID

---

ipam/allocator.go
ipam/store.go

In general the core IPAM and bitseq implementation has
very little assumptions about the presence of a backing
store. But there are a few places where this assumption exists
and this makes it not useful as a simple in-memory allocator.
This PR removes those false assumptions.

Make IPAM work even without a backing store

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/docker/libkv/.travis.yml
Godeps/_workspace/src/github.com/docker/libkv/LICENSE.code
Godeps/_workspace/src/github.com/docker/libkv/MAINTAINERS
Godeps/_workspace/src/github.com/docker/libkv/README.md
Godeps/_workspace/src/github.com/docker/libkv/libkv.go
Godeps/_workspace/src/github.com/docker/libkv/store/boltdb/boltdb.go
Godeps/_workspace/src/github.com/docker/libkv/store/consul/consul.go
Godeps/_workspace/src/github.com/docker/libkv/store/etcd/etcd.go
Godeps/_workspace/src/github.com/docker/libkv/store/store.go
Godeps/_workspace/src/github.com/docker/libkv/store/zookeeper/zookeeper.go
bitseq/sequence_test.go
datastore/cache.go
datastore/datastore.go
drivers/bridge/bridge_store.go
drivers/ipvlan/ipvlan_store.go
drivers/macvlan/macvlan_store.go
ipam/allocator.go
store.go

Currently datastore has dependencies on various kv backends.
This is undesirable if datastore had to be used as a backend
agnostic store management package with it's cache layer. This
PR aims to achieve that.

Remove kvstore backend deps from datastore package

---

ipams/builtin/builtin_unix.go

Make ipams builtin package work for os x target as ipam
driver developers happen to be using os x as well.

Fix ipams builtin package for darwin

---

ipam/allocator.go
ipam/allocator_test.go

Fixing an earlier commit which needlessly registered
boltdb in allocator.go while it is needed only for tests.

Need boltdb Register only in tests

---

ipam/allocator.go

This fixes TestRetrieveFromStore which became flaky after recently ipam changes.

 Make o/p of ipam DumpDatabase() consistent

---

cmd/ovrouter/ovrouter.go
controller.go
driverapi/driverapi.go
drivers/bridge/bridge.go
drivers/bridge/bridge_test.go
drivers/bridge/network_test.go
drivers/bridge/port_mapping_test.go
drivers/host/host.go
drivers/host/host_test.go
drivers/ipvlan/ipvlan.go
drivers/ipvlan/ipvlan_network.go
drivers/macvlan/macvlan.go
drivers/macvlan/macvlan_network.go
drivers/null/null.go
drivers/null/null_test.go
drivers/overlay/ov_network.go
drivers/overlay/ovmanager/ovmanager.go
drivers/remote/driver.go
drivers/remote/driver_test.go
drivers/windows/windows.go
drvregistry/drvregistry_test.go
endpoint_info.go
libnetwork_internal_test.go

With the introduction of a driver generic gossip in libnetwork it is not
necessary for drivers to run their own gossip protocol (like what
overlay driver is doing currently) but instead rely on the gossip
instance run centrally in libnetwork. In order to achieve this, certain
enhancements to driver api are needed. This api aims to provide these
enhancements.
The new api provides a way for drivers to register interest on table
names of their choice by returning a list of table names of interest as
a response to `CreateNetwork`. By doing that they will get notified if a
CRUD operation happened on the tables of their interest, via the newly
added `EventNotify` call.
Drivers themselves can add entries to any table during a `Join` call by
invoking `AddTableEntry` method any number of times …

Add driver api enhancements for gossip

---

resolver.go
resolver_unix.go
resolver_windows.go

Related to #1113 
For the gory details please see the excellent analysis provided by the submitters in the bug report.
Gist of the issue: Go doesn't give any control over how & when the underlying OS threads are created and managed. When we have already set into the net namespace of a container if go runtime creates a new thread its namespaces will be inherited from the current OS thread; in this case the net namespace of the container. Once this happens there is no way to set the namespaces back to the root namespace. This issue gets exposed sometimes when embedded DNS server sets up the iptables because the exec.Run creates go routines and the iptable calls translate to multiple system calls.
To address this moved the iptable setup into a reexec process.
A similar problem could happen …

Move the iptables setup for embedded DNS into a reexec process

---

resolver.go

Fixes #1117 
Related to [docker/docker #22081] (https://github.com/docker/docker/issues/22081)

Fix a panic in handling forwarded queries

---

networkdb/cluster.go
networkdb/networkdb.go

When a node joins a network it sends out a gossip event before it
updates it's own in-memory state. This can create a race where the node
gets the event back from a remote node before we update in-memory state
and we treat that as latest state. To avoid this race, always generate
the gossip after updating local state.

Fix gossip network event overwriting self

---

Makefile
cmd/dnet/dnet.go
cmd/dnet/dnet_linux.go
cmd/dnet/dnet_windows.go
netutils/utils_solaris.go

- Fix circle-ci-cross target
- Remove unsupported os/arch targets (solaris cannot build yet because of cgo in term pkg)
- Fix dnet build for windows/amd64
- Fix a solaris build breakage (ipamutils -> netutils change)
With this change circle ci will now monitor build breakages over windows/amd64, besides linux over 386/amd64/arm

Fix cross compilation issues

---

drivers/overlay/joinleave.go
drivers/overlay/ov_network.go
drivers/overlay/overlay.go
drivers/overlay/overlay_test.go
drivers/overlay/peerdb.go

Currently overlay driver requires a k/v store to allocate a vxlan id and
add an entry in k/v store for network->vxlanIDs binding. But the overlay
driver should be able to work without a k/v store provided libnetwork
can pass along the vxlanIDs needed for the network, rather than the
driver managing it themselves. Modified the driver to work with vxlanIDs
passed down by libnetwork.
Also made changes in the driver to make use of the gossip layer
available in libnetwork if available.

Make overlay driver work without a kv store

---

drivers/windows/windows.go

Allows user to specify ip parameter when running the container.

Static ip support for windows

---

sandbox_dns_unix.go

fix for #1146.
When started with --net=none, there is an invalid entry in /etc/hosts with empty ip. This fix is adding a validation if IP is empty and skips the operation if necessary.

don't add /etc/hosts record if container's ip is empty (--net=none)

---

network.go

- When creating a network with both IPv4 and IPv6 subnets,
if the allocation of the IPv6 pool fails, the already
reserved IPv4 pool does not get released.

Fix cleanup logic in case of ipv6 allocation failure

---

agent.go
api/api.go
api/types.go
client/network.go
client/types.go
cmd/dnet/dnet.go
config/config.go
controller.go
drivers/overlay/overlay.go
drivers/overlay/overlay_test.go
endpoint.go
endpoint_info.go
network.go
networkdb/cluster.go
test/integration/dnet/helpers.bash
test/integration/dnet/overlay-local.bats
test/integration/dnet/run-integration-tests.sh

libnetwork agent mode is a mode where libnetwork can act as a local
agent for network and discovery plumbing alone while the state
management is done elsewhere. This completes the support for making
libnetwork and its associated drivers to be completely independent of a
k/v store(if needed) and work purely based on the state information
passed along by some some external controller or manager. This does not
mean that libnetwork support for decentralized state management via a
k/v store is removed.

Add libnetwork agent mode support

---

sandbox_store.go

During sandboxcleanup operation, a dummy object is created if the
kv-store is inaccessible during the daemon bootup. The dummy object is
used for local processing of sandbox/endpoint cleanup operation. But
unfortunately, since the persist flag was not set, the Skip()
functionality kicked-in when sandbox was written back to the store and
global endpoint was skipped to be tracked.  During a subsequent cleanup
operation, sandbox was removed and the global endpoint was left stale in
the kv-store.
The fix is to set the persist flag in the dummy object and that handles
the sandbox and endpoint states appropriately and endpoint object is
properly cleaned up when the KVStore becomes available.

Set persist flag on the dummy network object during cleanup

---

CHANGELOG.md

Changelog for 0.8.0-dev.2

---

agent.go
controller.go
endpoint.go
network.go
sandbox.go
service.go
store.go
test/integration/dnet/helpers.bash

Add a notion of service in libnetwork so that a group of endpoints
which form a service can be treated as such so that service level
features can be added on top. Initially as part of this PR the support
to assign a name to the said service is added which results in DNS
queries to the service name to return all the IPs of the backing
endpoints so that DNS RR behavior on the service name can be achieved.

Add service support

---

network.go

This PR is to restore this behavior which was inadvertently changed by recent changes

Do not perform the overlap check on user chosen pool

---

ipam/allocator.go

After #1119, IPAM driver needs to be updated to still block a datastore update for the address space if the address space already has a backing datastore.
Before it was enough to check for the address space presence, since it was getting initialized only if it had a backing datastore. Now this assumption is no longer true.

IPAM allocator to not accept a datastore update if already present

---

sandbox_test.go
store.go

- Earlier this was guaranteed by ipam driver intialization
which was not creating a global address space if the
global datastore was missing. Now that ipam address spaces
can be initialized with no backing datastore, insert an
explicit check in libnetwork, which should have been there
regardless.

Do not allow network creation if datastore is missing

---

network.go

During resource cleanup driver resolution does not require the loading of the driver.
If the driver is not yet registered, `driverResolution()` is programmed to not fail and return a nil driver, cap and error. Calling code is therefore expected to gracefully handle this situation.

Protect cap access in driver()

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/vishvananda/netlink/Makefile
Godeps/_workspace/src/github.com/vishvananda/netlink/addr_linux.go
Godeps/_workspace/src/github.com/vishvananda/netlink/bpf_linux.go
Godeps/_workspace/src/github.com/vishvananda/netlink/class.go
Godeps/_workspace/src/github.com/vishvananda/netlink/class_linux.go
Godeps/_workspace/src/github.com/vishvananda/netlink/filter.go
Godeps/_workspace/src/github.com/vishvananda/netlink/filter_linux.go
Godeps/_workspace/src/github.com/vishvananda/netlink/handle.go
Godeps/_workspace/src/github.com/vishvananda/netlink/link.go
Godeps/_workspace/src/github.com/vishvananda/netlink/link_linux.go
Godeps/_workspace/src/github.com/vishvananda/netlink/neigh_linux.go
Godeps/_workspace/src/github.com/vishvananda/netlink/netlink.go
Godeps/_workspace/src/github.com/vishvananda/netlink/nl/nl_linux.go
Godeps/_workspace/src/github.com/vishvananda/netlink/nl/tc_linux.go
Godeps/_workspace/src/github.com/vishvananda/netlink/nl/xfrm_linux.go
Godeps/_workspace/src/github.com/vishvananda/netlink/nl/xfrm_state_linux.go
Godeps/_workspace/src/github.com/vishvananda/netlink/protinfo_linux.go
Godeps/_workspace/src/github.com/vishvananda/netlink/qdisc.go
Godeps/_workspace/src/github.com/vishvananda/netlink/qdisc_linux.go
Godeps/_workspace/src/github.com/vishvananda/netlink/route.go
Godeps/_workspace/src/github.com/vishvananda/netlink/route_linux.go
Godeps/_workspace/src/github.com/vishvananda/netlink/rule_linux.go
Godeps/_workspace/src/github.com/vishvananda/netlink/xfrm.go
Godeps/_workspace/src/github.com/vishvananda/netlink/xfrm_policy.go
Godeps/_workspace/src/github.com/vishvananda/netlink/xfrm_policy_linux.go
Godeps/_workspace/src/github.com/vishvananda/netlink/xfrm_state.go
Godeps/_workspace/src/github.com/vishvananda/netlink/xfrm_state_linux.go
drivers/overlay/ov_utils.go

Brings in:
- Proper endian handling o nvxlan port in netlink
- Fix for setting IPv6 NODAD flag on older kernel
- Allow to retrieve the link statistics
- Netlink Handle
- Additions to xfrm

Vendoring vishvananda/netlink f9bc7a684edbe780a09b87689db6cb1706bf327f

---

test/integration/dnet/helpers.bash

With docker 1.11 based dnet tests, the dnet_exec is sometimes exiting
with exit code 129 because the process is getting a SIGHUP. Although the
reason or source of the SIGHUP is unknown, it is making the tests flaky
because non-zero exit code. Fixed it by trapping SIGHUP inside the
container so that we can run the test code successfully.

Fix flakiness in dnet_exec

---

Dockerfile.build

Security fix for Go:
https://groups.google.com/forum/#!msg/golang-announce/9eqIHqaWvck/kXsfO0ogLAAJ
Note that for docker/docker, we're now in the process to switching to Go 1.6 (again), see https://github.com/docker/docker/pull/22840

Switch to golang 1.5.4

---

circle.yml

Related to #1089
fail to ```go get golang.org/x/tools/cmd/vet``` in Circle Ci test.
For Circle Ci test, must fix not only Dockerfile.build but also  circileci.yml.
Signed-off-by: YujiOshima <yuji.oshima0x3fd@gmail.com>

for fix CI tools/cmd/vet has been deleted

---

controller.go
docs/ipam.md
drvregistry/drvregistry.go
ipamapi/contract.go
ipams/builtin/builtin_unix.go
ipams/remote/api/api.go
ipams/remote/remote_test.go

Related: https://github.com/docker/docker/issues/23078

Avoid persisting ipam data if it can be reconstructed

---

agent.go
agent.pb.go
agent.proto
controller.go
endpoint.go
ipvs/netlink.go
network.go
sandbox.go
service.go
service_linux.go
service_unsupported.go

Ingress load balancer is achieved via a service sandbox which acts as
the proxy to translate incoming node port requests and mapping that to a
service entry. Once the right service is identified, the same internal
loadbalancer implementation is used to load balance to the right backend
instance.

Add ingress load balancer

---

agent.go
cluster/provider.go
cmd/dnet/dnet.go
cmd/dnet/libnetwork.toml
config/config.go
controller.go
endpoint.go
error.go
network.go
test/integration/dnet/helpers.bash
test/integration/dnet/run-integration-tests.sh

https://github.com/docker/libnetwork/pull/1149 brought in the agent mode support in libnetwork.
This PR tries to make this functionality available for other components to make use of.

Provide a way for libnetwork users to make use of Agent mode functionalities

---

controller.go

When leaving a cluster the agentInitDone should be re-initialized so tha
when a new cluster is initialized this is usable.

Reset agentInitDone channel when leaving a cluster

---

drivers/overlay/ov_network.go
drivers/overlay/ov_utils.go

If a new network request is received for a prticular vni, cleanup the
interface with that vni even if it is inside a namespace. This is done
by collecting vni to namespace data during init and later using it to
delete the interface.
Also fixed a long pending issue of the vxlan interface not getting
destroyed even if the sandbox is destroyed. Fixed by first deleting the
vxlan interface first before destroying the sandbox.

Cleanup vxlan interfaces inside namespace

---

drivers/overlay/joinleave.go

In the current implementation, the local peers are being added as remote
peers so gets added to the vxlan neighbor and fdb table. This causes the
local forwarding to get stuck for a few seconds after the bridge mac
table entries for the local peers get aged out. This PR fixes the
problem.

Do not plumb local peers as remote peers

---

agent.go
cluster/provider.go
controller.go

Instead of using Provider interface methods to get the encryption keys added a controller function that will be called by the daemon.

Use controller methods for handling the encyrption keys from agent

---

service_linux.go

When a goroutine which is adding the service and another which is adding
just a destination interleave the destination which is dependent on the
service may not get added and will result in service working at reduced
scale. The fix is to synchronize this with the service mutex.

Fix a lb rule race in loadbalancer

---

endpoint.go
endpoint_info.go
network.go
osl/interface_linux.go
osl/options_linux.go
osl/sandbox.go
sandbox.go

```
~$ docker network create nw1
c5be8936aecc7b276f22a9f3f2f441ef1c33811417d56f044ce6ac2a7a0649dc
~$ docker network create nw2
d05ddc77d6132193988dc0f01beb5fb6dbe2e5119c8595ecce4dda4373fb2e9a
~$ 
~$ docker run -d --name c0 --link-local-ip 169.254.1.1 --net nw1 alpine top
23631c5fc3349176b2dd3edc92b5a442751406edc9cacc5f1ebaf5367da1955f
~$ docker network connect --link-local-ip 169.254.2.2 --link-local-ip fe80::169:254:2:2 nw2 c0
~$ 
~$ docker exec c0 ip addr show eth0 | grep 169
inet 169.254.1.1/16 scope global eth0
~$ docker exec c0 ip addr show eth1 | grep 169
inet 169.254.2.2/16 scope global eth1
inet6 fe80::169:254:2:2/64 scope link 
~$ 
~$ docker stop c0 && docker start c0
c0
c0
~$ docker exec c0 ip addr show eth0 | grep 169
inet 169.254.1.1/16 scope global eth0
~$ docker exec c0 ip …
```

Allow to program Endpoint link-local addresses

---

drivers/overlay/overlay.go

Right now there is an artificial limitation at 1000.

Allow maximum possible VNI

---

ipvs/netlink.go

Instead log a descriptive error message.

Do not panic if failed to get ipvs family

---

sandbox.go

When ingress sandbox is removed, properly cleanup the reference in the
controller.

Properly cleanup ingress sandbox in controller

---

controller.go

If the IPAM pools are not reserved before resource cleanup happens then
the resource release will not happen correctly.

Reserve IPAM pools before resource cleanup

---

drivers/overlay/ov_network.go

If a miss notification arrives on a network's miss go routine currently
it is unconditionally processed. This is unnecessary and can be bad if
there are too many misses. This is especially true for hostmode. Fix
this by filtering out misses that doesn't belong to any of the network's
subnets.
Fixes #1189 

Process only misses on IP belonging to network

---

drivers/overlay/ov_network.go

If we cleaned up a stale network sandbox and an entry for that exists in
vniTbl, then purge it from vniTbl. Otherwise when a new vxlan for that
vni is added to the network, we might destroy the network sandbox
created in the current life.

Purge vniTbl after cleaning up network sandbox

---

networkdb/cluster.go

When a node goes away we purge all the table entries that we learned
from that node but we don't notify the watchers about it. Made sure we
notify the watchers when this happens.

Make sure to notify watchers on node going away

---

datastore/cache.go
datastore/datastore.go

Since the datastore interface is common for persistent and
non-persistent objects we need to provide the same kind of sequencing
and atomicity guarantess to non-persistent data operations as we do for
persistent operations. So added sequencing and atomicity checks in the
data cache layer.

Sequence non-persistent objects in cache

---

docs/design.md

The #Drivers reference needed to be #drivers in order for the anchor to work correctly.

design.md: fixed anchor reference

---

networkdb/cluster.go
networkdb/event_delegate.go
networkdb/networkdb.go

When a node goes away purge all the network attachments from the node
and make sure we don't attempt bulk syncing to that node once removed.

Properly purge node networks when node goes away

---

drivers/macvlan/macvlan_endpoint.go

Endpoint delete from network map in macvlan driver.
Signed-off-by: Sainath Grandhi <sainath.grandhi@intel.com>

Delete endpoint from network map for macvlan driver upon endpoint deletion

---

controller.go
sandbox.go
sandbox_store.go
service_linux.go

When adding a loadbalancer to a sandbox, the sandbox may have a valid
namespace but it might not have populated all the dependent network
resources yet. In that case do not populate that endpoint's loadbalancer
into that sandbox yet. The loadbalancer will be populated into the
sandbox when it is done populating all the dependent network resources.

Do not add loadbalancer to unpopulated sandboxes

---

service_linux.go

Currently even outgoing connection requests are matched to inject into
DOCKER-INGRESS chain. This is not correct because it disrupts access to
services outside the host on the same service port. Instead inject only
the locally destined packets towards DOCKER-INGRESS chain.

Match only locally destined requests for ingress

---

network.go

Reported during docker testing:
```
panic: runtime error: index out of range
goroutine 24782 [running]:
panic(0x1aba540, 0xc82000c040)
/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/docker/libnetwork.(*network).getSvcRecords(0xc8214cc280, 0xc821742dc0, 0x0, 0x0, 0x0)
/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/network.go:1112 +0x45a
github.com/docker/libnetwork.(*endpoint).sbLeave(0xc821742dc0, 0xc821916d20, 0xc821916d00, 0x0, 0x0, 0x0, 0x0, 0x0)
/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/endpoint.go:690 +0x1140
github.com/docker/libnetwork.(*endpoint).Leave(0xc821940000, 0x7f48aa277da0, 0xc821916d20, 0x0, 0x0, 0x0, 0x0, 0x0)
/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/endpoint.go:616 +0x1e9 …
```

Make getSvcRecords() more robust

---

networkdb/cluster.go

Bulk sync should not sync state which is getting deleted

Do not bulk sync state which is getting deleted

---

agent.go
controller.go
discoverapi/discoverapi.go
drivers/overlay/encryption.go
drivers/overlay/overlay.go

Having three keys in the keyring allows key rotation across the cluster without any transient packet loss (https://github.com/docker/swarmkit/pull/980#issuecomment-226627657) 
This PR brings in the changes required to handle three keys in the key ring correctly and translate it to add/delete operations for downstream clients, gossip & overlay driver.
Since 1.12 RC2 currently has the older 2 keys approach, this change is done in backward compatible way so that all managers/nodes doesn't have to updated altogether. Before the 1.12 official release handleKeyChangeV1 function will be removed.

Update key handling logic to process keyring with 3 keys

---

drivers/overlay/ovmanager/ovmanager.go

To support maximum possible overlay networks in swarm mode.

Update ovmanager to support maximum vni

---

drivers/remote/driver.go

- Only NodeDiscovery type messages are meant to be sent to remote drivers.
Other notifications should be treated as no op in remote.go.
Fixes #1296 

Do not error on non NodeDiscovery type messages in remote driver

---

endpoint.go

- If an endpoint is forcibly removed, it should not
matter whether the locator info is present. If
the daemon was started w/o the --cluster-advertise
option (the option is not mandatory), then the
locator would be empty for any endpoint.
Related to https://github.com/docker/docker/issues/20398, https://github.com/docker/docker/issues/23302

Remove locator check on endpoint force removal

---

drivers/overlay/ovmanager/ovmanager.go

Currently ovmanager simply logs an error when there is a vni allocation
failure. Instead it should error out and free all the previously
allocated vnis

ovmanager: Error out on vxlan id alloc failure

---

controller.go
service.go
service_linux.go

While trying to update loadbalancer state index the service both on id
and portconfig. From libnetwork point of view a service is not just
defined by its id but also the ports it exposes. When a service updates
its port its id remains the same but its portconfigs change which should
be treated as a new service in libnetwork in order to ensure proper
cleanup of old LB state and creation of new LB state.

Index service on both id and portconfigs

---

networkdb/cluster.go
networkdb/delegate.go

When deleting entries or when learning about deleted entries remember
then for a longer time to avoid excessive delete duplicates in the
gossip cluster. Also added code changes to ignore event messages
originated from the source node so that it doesn't get added into the
rebroadcast queue.

Retain deleted entries for longer time

---

controller.go
drivers_ipam.go
drvregistry/drvregistry.go
drvregistry/drvregistry_test.go

Moving IPAM initalization out of drvRegistry into libnetwork core

---

Makefile
cmd/proxy/main.go
cmd/proxy/network_proxy_test.go
cmd/proxy/proxy.go
cmd/proxy/stub_proxy.go
cmd/proxy/tcp_proxy.go
cmd/proxy/udp_proxy.go
portmapper/mapper.go
portmapper/mock_proxy.go
portmapper/proxy.go

Rather than re-execing docker as the proxy, create a new command docker-proxy
that is much smaller to save memory in the case where there are a lot of
procies being created. Also allows the proxy to be replaced, for example
in Docker for Mac we have a proxy that proxies to osx instead of locally.
This is the vendoring pull for https://github.com/docker/docker/pull/23312
Signed-off-by: Justin Cormack <justin.cormack@docker.com>

Make the docker proxy a standalone binary not a re-exec

---

drivers/bridge/bridge.go

A network is added to the `d.networks` map before it's fully initialized. That is, it's possible for a network in `d.networks` to exist without having `bridgeIPv4` populated yet. If multiple networks are spun up close to the same time, a panic can occur.
Example:
```
panic(0x1a75d20, 0xc82000e090)
/usr/local/go/src/runtime/panic.go:443 +0x4e9
net.networkNumberAndMask(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/usr/local/go/src/net/ip.go:433 +0x42
net.(*IPNet).Contains(0x0, 0xc82084dbd0, 0x4, 0x4, 0xc820010200)
/usr/local/go/src/net/ip.go:457 +0x25
github.com/docker/libnetwork/drivers/bridge.(*networkConfiguration).conflictsWithNetworks(0xc822249360, 0xc822761380, 0x40, 0xc820866a60, 0x4, 0x4, 0x0, 0x0)
/root/rpmbuild/BUILD/docker-engine/vendor/src/github.com/docker/libnetwork/drivers/bridge/bridge …
```

Avoids panic when checking for conflicts against an uninitalized network

---

networkdb/cluster.go

This patch allows getting rid of annoying debug message

networkdb: do nothing in bulkSync if nodes is empty

---

network.go

If a network is dynamic, make sure the scope of the object doesnt change
based on the cluster-mode

manage network dynamic flag appropriately under various scenarios

---

agent.go
controller.go

When worker leaves and re-join the cluster, make sure it re-joins the gossip for the existing cluster networks.
Related: https://github.com/docker/docker/issues/24463

On agent init, re-join on existing cluster networks

---

sandbox_externalkey_unix.go

the UDS sock is an unique file and the lifetime of it is until the
docker daemon dies (gracefully). Hence there is no need for it to be
under /var/lib and not mandatory to be configurable either.

Moving the UDS file out of /var/lib/docker and into /run/

---

endpoint_cnt.go

Signed-off-by: Lei Jitang <leijitang@huawei.com>
power down during docker stress test and restart, we encounter this error:
`INFO[0008] Fixing inconsistent endpoint_cnt for network bridge. Expected=0, Actual=1
DEBU[0008] starting clean shutdown of all containers...
DEBU[0008] Cleaning up old mountid : start.
DEBU[0008] Cleaning up old mountid : done.
FATA[0008] Error starting daemon: Error initializing network controller: could not delete the default bridge network: network bridge has active endpoints`
and user bolt cli shows that:
`# ./bolt get /var/lib/docker/network/files/local-kv.db libnetwork docker/network/v1.0/endpoint_count/1b331173f5d4ab654afa2f8d659e263ff89f11bfc1a943ab5ac582333a681241/
{"Count":18446744073709551593}`
I debug and found that, during endpoint_cnt updating to …

Fix update endpoint count to store

---

network.go
sandbox.go

We'r got some problem with docker 1.12-rc-4:
```
fatal error: concurrent map read and map write
goroutine 3426519 [running]:
runtime.throw(0x1fb2020, 0x21)
/usr/local/go/src/runtime/panic.go:547 +0x90 fp=0xc8224355a0 sp=0xc822435588
runtime.mapaccess2_faststr(0x175d060, 0xc82098e570, 0xc821193f20, 0xf, 0xc820c73748, 0x6fc601)
/usr/local/go/src/runtime/hashmap_fast.go:307 +0x5b fp=0xc822435600 sp=0xc8224355a0
github.com/docker/libnetwork.(*sandbox).resolveName(0xc8215703c0, 0xc821193f20, 0xf, 0x1dc7b28, 0x0, 0xc821b88268, 0x1, 0x1, 0x1dd7200, 0x1, ...)
/go/src/github.com/docker/docker/vendor/src/github.com/docker/libnetwork/sandbox.go:585 +0x383 fp=0xc8224356f0 sp=0xc822435600
github.com/docker/libnetwork.(*sandbox).ResolveName(0xc8215703c0, 0xc821193f20, 0xf, 0x1, 0x0, 0x0, 0x0, 0x0) …
```

added mutex on read from controller.svcRecords map

---

config/config.go
osl/namespace_linux.go
osl/namespace_unsupported.go
osl/namespace_windows.go
osl/sandbox_freebsd.go

/var/run/docker/netns will still be the default location. But user will be able to override the basepath using --exec-root configuration

Make osl sandbox basepath configurable using --exec-root configuration

---

agent.go
cluster/provider.go
cmd/dnet/dnet.go
discoverapi/discoverapi.go
drivers/overlay/encryption.go
drivers/overlay/joinleave.go
drivers/overlay/ov_serf.go
drivers/overlay/overlay.go
networkdb/cluster.go
networkdb/networkdb.go

With this change, all the auto-detection of the addresses are removed
from libnetwork and the caller takes the responsibilty to have a proper
advertise-addr in various scenarios (including externally facing public
advertise-addr with an internal facing private listen-addr)

Add advertise-addr support

---

docs/macvlan.md

Signed-off-by: Erich Cordoba <erich.cm@yandex.com>

Fix several typos on macvlan docs

---

endpoint.go

Related to [docker/docker #24800] (https://github.com/docker/docker/issues/24800)
This is a collateral from the service related changes in 1.12. 
On endpoint delete it should be ok to call unWatchSvcRecord in both swam and non-swarm mode. In swarm mode it can lead to two deleteSvcRecords calls; one from ep delete and one from EP table event handling. But the 2nd call will be a noop. This is similar to the add case where watchSvcRecord is called from CreateEndpoint.

Update service DB on deletion of containers in bridge networks

---

drivers/overlay/encryption.go
drivers/overlay/ov_network.go
drivers/overlay/overlay.go

- Because of a bug in the netlink xfrm code, our code will
fail to find and remove the states. While we could wait
for the netlink library fix, there is no longer a need to
convert the parsed IP addresses to the canonical notation
given the previous SPI computation (which worked on that
4 byte address assumption) is now replaced by the fnv hash.

Do not force ipv4 addresses to canonical form in overlay enc

---

drivers/overlay/encryption.go
drivers/overlay/ov_network.go
drivers/overlay/ov_utils.go
drivers/overlay/overlay.go

- Being a driver specific flag, user needs to
account for vxlan and, if enabled, ipsec overhead
- Default MTU remains 1500 bytes
Fixes #1021 
Fixes #1330 

Allow user to set the overlay network's mtu

---

drivers/overlay/ov_network.go

- When creating a non encrypted overlay network,
make sure no encryption related mangle rule from
stale network is on the way.

On network creation, reset mangle rule

---

endpoint.go
resolver.go

In 1.11 we made a change to source the external queries from the container namespace. This allows the external resolvers to see the source IP of the container that generated the query. That was useful for resolvers that want to use the source of the query in some way to determine what the response should be.
Along with this there was also a change to cache the external UDP connections after its opened the first time. This avoids having to set into the container namespace and will avoid the chances of new OS thread getting created in the container net ns. For the first query we still have to set into container net ns. Also the caching can't be done for TCP because a long running TCP session to a DNS server is not the usual practice can get RST by the server.
UDP connection caching has …

Remove UDP connection caching in embedded DNS server

---

drivers/overlay/encryption.go

- We need to compare the node notification IP with
the advertise address otherwise when the advertise
address is different from the local address (this
is for the public address outside of the host
that maps 1-to-1 to the local private address)
the local IP will be acocunted as an ipsec host
and extra states will be programmed for it.

Check for advertise IP when deriving ipsec nodes

---

drivers/overlay/encryption.go

- which would leave a stale state behind at each key rotation.

Fix bug in ipsec key rotation

---

network.go

Check for isAgent() outside the network lock to avoid deadlocks

---

ipamapi/contract.go
ipams/remote/remote.go

If a remote plugin returns an empty string in response to RequestAddress(),
the internal helper will return nil which will crash libnetwork in several
places.
Treat an empty string as a new error ipamapi.ErrNoIPReturned.
Signed-off-by: Thomas Graf <tgraf@suug.ch>

Fix crash when remote plugin returns empty address string

---

docs/ipam.md

Changed "lifecyle" to "lifecycle".

docs/ipam.md: spelling error

---

networkdb/delegate.go

Fixes
https://github.com/docker/libnetwork/issues/1363
Easier way to repro: 
- 1 manager and 1 worker in the cluster. 
- A service with a task running in the worker. 
- restart the daemon in the worker.
When we do the cluster init in the worker it joins the manager. In the process there is a state sync which downloads the full networks state from the peer. Since the worker had a task on the network update from the peer will indicate the worker node being part of the network. But on daemon restart the task would have been rescheduled elsewhere and hence the worker node doesn't have any tasks on the network anymore. Since we already created the network for this node in the network db the error `Invalid broadcastQ` will show up on every gossip interval which is 200 ms.
Fix is to not create …

Do not create network entry for the local node in the db based on peer's state sync.

---

endpoint_info.go
service_linux.go

Sometimes you may get stale backend removal notices from gossip due to
some lingering state. If a stale backend notice is received and it is
already processed in this node ignore it rather than processing it.
Also fixing:
Ensure drivertable entries in joininfo is uptodate
The CopyTo function for joininfo is not copying the driver table entries
which then is missing when the endpoint is re-read for the store cache.

Make sure to not remove backends on stale notices

---

service_linux.go

Ingress loadbalancer is only required to be plumbed in ingress sandboxes
of nodes which are the only mechanism to get traffix outside the cluster
to tasks. Since the tasks are part of ingress network, these
loadbalancers were getting added in all tasks which are exposing ports
which is totally unnecessary resource usage. This PR avoids that.

Do not add ingress loadbalancer on service tasks

---

networkdb/delegate.go
networkdb/networkdb.go

ping @mrjana @sanimej @aboch 
I think it might be worth to include this in 1.12.1 because map races could be fatal for a running program.

networkdb: fix data races in map access

---

drivers/overlay/ov_network.go

ping @mrjana @sanimej @aboch 
Fix is not ideal. It would be better to use per id Lock for such stuff. We have special package for that in docker.

overlay: fix data race in map access

---

service_linux.go

Make service loadbalancing to work from within one of the containers of
the service. Currently this only works when the loadbalancer selects the
current container. If another container of the same service is chosen,
the connection times out. This fix adds a SNAT rule to change the source
IP to the containers primary IP so that responses can be routed back to
this container.

Make service LB work from self

---

resolver.go

Docker DNS server proxies external queries by sending it to the configured nameservers.  When sending the query UDP packet size defaults to 512 bytes. If the client has set the ENDS option reply and the reply is > 512 bytes it will get dropped by the DNS library.
When forwarding the query set the dns.Conn UDPSize to be that of the size from the client's EDNS option.

Fix external DNS responses > 512 bytes getting dropped

---

networkdb/cluster.go
networkdb/delegate.go
networkdb/networkdb.go

Fixes https://github.com/docker/libnetwork/issues/1387
When a worker node doesn't have any more tasks on a network, the network gets deleted and the service db for that network also gets removed. When a task on that network starts again service records should be populated again. This wasn't happening correctly because the earlier state in the networkdb wasn't fully cleaned up. Changes to address this are..
- cleanup the network db state when a network is removed on a node
- while the network is in the going away state do not include the state for this network in the bulksync
- also, do not process the table events coming from the peers for this network.

Cleanup networkdb state when the network is deleted locally

---

agent.go
drivers/overlay/ov_network.go
drivers/overlay/peerdb.go

Fixed certain spurious overlay errors which were not errors at all but
showing up everytime service tasks are started in the engine.
Also added a check to make sure a delete is valid by checking the
incoming endpoint id wih the one in peerdb just to make sure if the
delete from gossip is not stale.

Fix spurious overlay errors

---

sandbox.go

If the sandbox doesn't have any EP in ingress network nil was getting added to the epList and resulting in a panic.

Fix a panic introduced by #1389

---

libnetwork_internal_test.go
resolver.go
sandbox.go

Service name for SRV query had a strict check as defined by RFC 2782. This doesn't work for implementations which allow SRV names that not in the 2782 format.
Also fixed the issue of external SRV queries not getting forwarded to the external resolvers.
related to [docker #25534] (https://github.com/docker/docker/issues/25534)

Relax SRV name validation and fix external SRV query handling

---

controller.go

When a node leaves the swarm cluster, we should cleanup the ingress
network and sandbox. This makes sure that when the next time the node
joins the swarm it will be able to update the cluster with the right
information.

Cleanup ingress network and sandbox on leave

---

agent.go
controller.go

On a swarm leave controller's keys should be reset. Otherwise a node joining back after few key rotations will end up incorrect Primary key.  Right now this is not an issue because in the sequence of events keys are received first before the agent is setup. So the the received keys are [stored](https://github.com/docker/libnetwork/blob/master/controller.go#L281) instead of triggering a key rotation. But the correct behavior should be to reset the keys. Also added lock in couple of places.

Reset the encryption keys on swarm leave

---

networkdb/cluster.go
networkdb/delegate.go
networkdb/networkdb.go

In networkdb we should ignore delete events for entries which doesn't
exist in the db. This is always true because if the entry did not exist
then the entry has been removed way earlier and got purged after the
reap timer and this notification is very stale.
Also there were duplicate delete notifications being sent to the
clients. One when the actual delete event was received from gossip and
later when the entry was getting reaped. The second notification is
unnecessary and may cause issues with the clients if they are not
coded for idempotency.

Ignore delete events for non-existent entries

---

controller.go
network.go
service.go
service_linux.go
service_unsupported.go

When leaving the entire gossip cluster or when leaving a network
specific gossip cluster, we may not have had a chance to cleanup service
bindings by way of gossip updates due to premature closure of gossip
channel. Make sure to cleanup all service bindings since we are not
participating in the cluster any more.

Cleanup service bindings when leaving cluster

---

networkdb/delegate.go
networkdb/networkdb.go

In cases a node left the cluster and quickly rejoined before the node
entry is expired by other nodes in the cluster, when the node rejoins we
fail to add it to the quick lookup database. Fixed it.

Ensure add newly joined node to networknodes

---

agent.go

Currently the initDone notification is provided immediately after
initializing the cluster. This may be fine for the first manager. But
for all subsequent nodes which join the cluster we need to wait until
the node completes the joining to the gossip cluster inorder to
synchronize the gossip network clock with other nodes. If we don't have
uptodate clock the updates that this node provides to the cluster may be
discarded by the other nodes if they have entries which are yet to be
reaped but have a better clock.

Notify agentInitDone after joining the cluster

---

store.go

Avoid the whole store endpoint update logic when running in swarm mode
and the endpoint is part of a global scope network. Currently there is
no store update that is happening for global scope networks in swarm
mode, but this code path will delete the svcRecords database when the
last endpoint on the network is removed which is something that is not
required.

Avoid k/v store endpoint update in swarm mode

---

agent.go
controller.go

Avoid by reinitializing the channel immediately after closing the
channel within a lock. Also change the wait code to cache the channel in
stack be retrieving it from controller and wait on the stack copy of the
channel.

Avoid double close of agentInitDone

---

drivers/overlay/ov_network.go

In the case of swarm services this will result in task failure giving a chance for the user to notice it in the `service ps`

Propage the vxlan device creation error in driver to libnetwork

---

controller.go
service_linux.go
service_unsupported.go

Services with published port on different networks should be able to access each other's service from a given host. Currently this gets blocked by the ICC filter on docker_gwbridge.
Also, an unmanaged container on a local bridge network should be able to access a published service on the local host. This gets blocked by the inter-bridge isolation rule in DOCKER-ISOLATION chain.
Fix is to insert a specific rule at the beginning of the FORWARD chain to allow the published ports. This will be hit before the two rules mentioned earlier and thus giving the desired behavior.
related to [docker #25463] (https://github.com/docker/docker/issues/25463)

Allow reachability across services on the same host

---

support.sh

This script gathers some basic information from a system that might
be useful to help troubleshoot problems.  If added into an image
including the proper binaries, running looks something like this:
docker run --rm \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /var/run/docker/netns:/var/run/docker/netns \
--privileged --net=host nwsupport /bin/support

Simple support script to gather libnetwork info

---

sandbox.go

When the libnetwork controller is not in distributed control mode avoid
retaining stale sandboxes when the network cannot be retrieved from
store. This ratining logic is only applicable for an independent k/v
store which manages libnetwork state. In such case the k/v store may be
temporarily unavailable so there is a need to retain the sandbox so that
the resource cleanup happens properly.

Do not hold sandbox if not in distributed control

---

drivers/overlay/overlay.go

- if failure happened during restore endpoint phase
Related to https://github.com/docker/docker/issues/25215

Allow reattempt of overlay network sbox join

---

drivers/bridge/bridge.go
drivers/bridge/interface.go
drivers/bridge/interface_test.go

If someone creates a network with `-o com.docker.network.bridge.name=xxx` but "xxx" is not a bridge interface, we should show an error and let it fail.

make sure the user-provided bridge interface is a bridge

---

endpoint.go

Currently the endpoint count is being decremented before the driver
cleanup and more importantly before releasing the ip address. This is
racy as it creates a time window where we already have decremented the
endpoint count and so the network can be deleted now. But we haven't
released the IP address yet and the pool is already gone. Although there
is no harm done since the pool is already gone. it generates unnecessary
error message about not able to release the address. Also if the driver
cleanup fails we really should not decrement endpoint count.

Decrement epCnt only after all cleanup

---

drivers/bridge/bridge.go
drivers/bridge/bridge_store.go
drivers/bridge/bridge_test.go
drivers/bridge/network_test.go
drivers/bridge/port_mapping_test.go
drivers/bridge/setup_verify.go

Given that I have a bridge interface named br0, when I run `docker network create -d bridge -o com.docker.network.bridge.name=br0 mybr` and then run `docker network rm mybr`, the br0 interface on my host will be removed. 
I think in such case the pre-configured bridge interface should not be delete by docker.
Signed-off-by: Shijiang Wei <mountkin@gmail.com>

don't delete the bridge interface if it was not created by libnetwork

---

endpoint.go
libnetwork_test.go
networkdb/networkdb.go
sandbox.go

Added a new sandbox API to add a task to the load balancer and service discovery. This can be used by the engine to make the task available only if the health check status is ok. It can also be used potentially by the swarm agent to gracefully pull a task from the backends and allow a grace period to drain the existing connections in the upgrade case.
This doesn't affect the driver plumbing. And the container can still discover other services in the network so that health check with dependency on other services can be supported.

Add sandbox method for task insertion to service LB and service disovery

---

resolver.go
sandbox.go
sandbox_dns_unix.go

Related to [docker #26039](https://github.com/docker/docker/issues/26039)
PR #1435 addresses this issue by passing the user provided ndots value to the resolv.conf. [One concern](https://github.com/docker/libnetwork/pull/1435#issuecomment-245988800) with this approach is that it results in inconsistent UX. This PR addresses the issue differently; if the user passes a `ndots` option unqualified queries will not be forwarded in the root domain. This would allow the client resolver to try with the search domains attached.

Drop queries in root domain when ndots is set

---

Godeps/Godeps.json
Godeps/_workspace/src/github.com/docker/docker/pkg/locker/README.md
Godeps/_workspace/src/github.com/docker/docker/pkg/locker/locker.go
controller.go

When dynamic networks are created and there is a race in creation of the
same network from two different tasks then one of them will fail while
the other will succeed. For service tasks this is not a big problem
because they will be rescheduled again. But for attachment tasks this
can be a problem since they won't get recreated and making the whole
connection fail. Fixed it by serializing network creation for the
network with the same id and trying to see if the id is present after
coming out of wait.

Serialize dynamic network creation

---

portmapper/mapper.go

split out of https://github.com/docker/docker/pull/20315
in order to fix https://github.com/docker/docker/issues/11518
Signed-off-by: Michael Stapelberg <stapelberg@google.com>

portmapper: touch iptables only for IPv4

---

endpoint.go
libnetwork_test.go
networkdb/networkdb.go
sandbox.go

This reverts commit 2fb2fd20c7aea931a388d61c4994fc76c581957a.
This change was to support container health aware LB and graceful rolling upgrade. Without the docker and swarmkit changes for these features libnetwork can't be vendored in. Hence reverting it now and will be included when the docker/swarmkit changes are complete. cc @dongluochen

Revert "Add sandbox API for task insertion to service LB and service discovery"

---

bitseq/sequence.go
bitseq/sequence_test.go

- Size 1 range is a valid input
- Validation check was incorrect anyway given unsigned operands
Related to https://github.com/docker/docker/issues/23980
This allows:
```
$ docker network create --subnet=2.2.2.0/24 --gateway=2.2.2.254 --ip-range=2.2.2.100/32 abcd
d65e374fe18a88e1693aaca243f58682a8d160c853df7b54ab54ee284e8bd181
$ docker run --rm --network abcd busybox ifconfig eth0
eth0      Link encap:Ethernet  HWaddr 02:42:02:02:02:64  
inet addr:2.2.2.100  Bcast:0.0.0.0  Mask:255.255.255.0
inet6 addr: fe80::42:2ff:fe02:264/64 Scope:Link
UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
RX packets:2 errors:0 dropped:0 overruns:0 frame:0
TX packets:1 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:0 
RX bytes:180 (180.0 B)  TX bytes:90 (90.0 B)
$ 
```

Fix bitseq.SetAnyInRange

---

controller.go

Related to https://github.com/docker/docker/issues/26075
Fix reservePool logic to be cover the case where a restored network was created with a IPv6 subnet specified but no `--ipv6`.

Check if IPv6 is enabled before restoring the network pools

---

drivers/overlay/peerdb.go
osl/neigh_linux.go
osl/sandbox.go

When stale delete notifications are received, we still need to make sure
to purge sandbox neighbor cache because these stale deletes are most
typically out of order delete notifications and if an add for the
peermac was received before the delete of the old peermac,vtep pair then
we process that and replace the kernel state but the old neighbor state
in the sandbox cache remains. That needs to be purged when we finally
get the out of order delete notification.

Ensure purging neighbor cache for stale deletes

---

agent.go

Conflicting names in the cluster can lead to silent failures in the service discovery, routing mesh etc. When joining the cluster make sure the nodenames are unique.

Make nodenames unique in Gossip cluster

---

drivers/overlay/encryption.go
drivers/overlay/overlay.go

Overlay driver needs to reset the encrypion keys and any neigh map when libnetwork core sets the key.
Current logic would cause issues in case a node leaves a cluster and joins the cluster back after the key rotation has happened, for example.
Related to https://github.com/docker/docker/issues/25608

In overlay driver reset any state on setkey()

---

controller.go

For ease of debugging the ingress sandbox should have a fixed name that doesn't change.
This PR sets it explicitly in libnetwork. An alternative would be to use the container id `ingress-sandbox` which is passed to the sandbox creation. But the presence of `-` is currently interpreted as overlay network sandbox.

Name the ingress sandbox explicitly

---

agent.go

Related to https://github.com/docker/docker/issues/25848

Lock agent access in addDriverWatches

---

sandbox.go
sandbox_dns_unix.go

Related to [docker #26356] (https://github.com/docker/docker/issues/26356)
Panic was in ServeDNS(), in this dereference extConn.LocalAddr().String()
```
log.Debugf("Query %s[%d] from %s, forwarding to %s:%s", name, query.Question[0].Qtype,
extConn.LocalAddr().String(), proto, extDNS.ipStr)
```
It can happen only if the `execFunc` failed for some reason. #1412 already added a check for the execFunc failure. But the error from InvokeFunc was being ignored. Fixed that and also added error checks for other calls to InvokeFunc()
There is a 2nd panic mentioned in the same issue. Its a different decode. We can ask the submitter to open a different issue after collecting the required info to root cause it.

Check for ExecFunc failure

---

service_linux.go

Currently, a reference counting scheme is used to reference count all
individual port configs that need to be plumbed in the ingress to make
sure that in situations where a service with the same set of port
configs is getting added or removed doesn't accidentally remove the port
config plumbing if the add/remove notifications come out of order. This
same reference counting scheme is also used for plumbing the port-based
marking rules. But marking rules should not be plumbed based on that
because marks are always different for different instantiations of the
same service. So fixed the code to plumb port-based mark rules based on
the complete set of port configs, while plumbing pure port rules and
proxies based on a filter set of port configs based on the reference
count.
Signed-off-by: …

Use complete port configs when plumbing mark rules
